Repository ita-social-projects/SpaceToStudy-Client, pull requests merged in 2022-06, with the labels that each got.

#60 Create first section of guest home page
  src/assets/img/guest-home-page/desktopBg.svg
  src/assets/img/guest-home-page/titleMd.svg
  src/assets/img/guest-home-page/titleSm.svg
  src/assets/img/guest-home-page/titleXs.svg
  src/constants/translations/en/guest-home-page.json
  src/constants/translations/en/guestHomePage.json
  src/constants/translations/en/index.js
  src/constants/translations/ua/index.js
  src/containers/guest-home-page/WelcomeBlock.js
  src/containers/guest-home-page/styles/welcomeBlockStyles.js
  src/hooks/use-breakpoints.js
  src/pages/guest-home-page/GuestHome.js
  src/styles/app-theme/app.pallete.js
  src/styles/app-theme/app.shadows.js
  src/styles/app-theme/app.typography.js
  src/styles/app-theme/custom-mui.styles.js
  src/styles/index.css
Labels: Frontend part, feature

#63 Feature/61/connect-redux
  src/components/confirm-dialog/ConfirmDialog.js
  src/components/loader/Loader.js
  src/constants/request.js
  src/containers/layout/AppMain.js
  src/containers/layout/GuestLayout.js
  src/containers/layout/MentorLayout.js
  src/containers/layout/StudentLayout.js
  src/context/confirm-context.js
  src/hooks/use-confirm.js
  src/index.js
  src/pages/mentor-home/MentorHome.js
  src/pages/student-home/StudentHome.js
  src/redux/action-creators.js
  src/redux/reducer.js
  src/redux/store.js
  src/services/user-service.js
  src/utils/helper-functions.js
Labels: Frontend part, feature

#55 Feature/54/create login popup
  src/assets/img/login-dialog/google.svg
  src/assets/img/login-dialog/login.svg
  src/constants/translations/en/index.js
  src/constants/translations/en/login.json
  src/constants/translations/ua/index.js
  src/constants/translations/ua/login.json
  src/constants/validation/login.js
  src/containers/guest-home-page/google-login/GoogleLogin.js
  src/containers/guest-home-page/google-login/google-login.style.js
  src/containers/guest-home-page/login-dialog/LoginDialog.js
  src/containers/guest-home-page/login-dialog/login-dialog.style.js
  src/containers/guest-home-page/login-form/LoginForm.js
  src/containers/guest-home-page/login-form/login-form.style.js
  src/containers/layout/AppHeader.js
  src/containers/modal/Modal.js
  src/containers/navbar/NavBar.js
  src/hooks/use-form.js
  src/styles/app-theme/app.button.js
  src/styles/app-theme/app.pallete.js
  src/styles/app-theme/app.svgicon.js
  src/styles/app-theme/app.typography.js
  src/styles/app-theme/custom-mui.styles.js
Labels: Frontend part, feature, component

#67 tests/65/confirmDialog-modal-loader
  src/components/confirm-dialog/ConfirmDialog.js
  src/components/loader/Loader.js
  src/components/popup-dialog/PopupDialog.js
  src/components/test-confirm-component/testConfirm.js
  src/containers/guest-home-page/login-dialog/LoginDialog.js
  src/context/modal-context.js
  src/hooks/use-confirm.js
  src/hooks/use-prompt.js
  src/pages/guest-home-page/GuestHome.js
  tests/setup-tests.js
  tests/test-utils.js
  tests/unit/components/ConfirmDialog.spec.js
  tests/unit/components/Loader.spec.js
  tests/unit/components/PopupDialog.spec.js
  tests/unit/components/layout/AppHeader.spec.js
  tests/unit/components/layout/AppMain.spec.js
  tests/unit/hooks/use-confirm.spec.js
  tests/unit/pages/about/About.spec.js
Labels: test

#72 feature/54/login-popup-tests
  tests/unit/containers/guest-home-page/google-login/GoogleLogin.spec.js
  tests/unit/containers/guest-home-page/login-dialog/LoginDialog.spec.js
  tests/unit/containers/guest-home-page/login-form/LoginForm.spec.js
Labels: Frontend part, test

#74 hotfix/45/fix background on the first section of the guest page
  src/assets/img/guest-home-page/desktopBg.svg
  src/assets/img/guest-home-page/welcomeBgMd.svg
  src/assets/img/guest-home-page/welcomeBgSm.svg
  src/assets/img/guest-home-page/welcomeBgXs.svg
  src/containers/guest-home-page/WelcomeBlock.js
  src/containers/guest-home-page/styles/welcome.styles.js
  src/containers/guest-home-page/styles/welcomeBlockStyles.js
Labels: Frontend part

#71 feature/68/sidebar
  src/App.js
  src/constants/routes.js
  src/containers/layout/AppHeader.js
  src/containers/navbar/NavBar.js
  src/containers/navbar/navbar.style.js
  src/containers/sidebar/Sidebar.js
  src/containers/sidebar/sidebar.style.js
  src/hooks/use-hash-scroll.js
  tests/unit/containers/navbar/NavBar.spec.js
  tests/unit/containers/sidebar/Sidebar.spec.js
  tests/unit/hooks/use-hash-scroll.spec.js
Labels: Frontend part, feature, component

#89 feature/54/useForm-test
  tests/unit/hooks/use-form.spec.js
Labels: Frontend part, test

#92 bug/91/fix position of close icon in popup
  src/components/popup-dialog/PopupDialog.js
  src/components/popup-dialog/popup-dialog.style.js
  src/containers/guest-home-page/login-dialog/login-dialog.style.js
  src/containers/guest-home-page/signup-dialog/signup-dialog.style.js
  src/containers/guest-home-page/signup-form/signup-form.style.js
Labels: bug, Frontend part

#94 Feature/93/tests for redux, modalContext, AppMain
  src/components/confirm-dialog/ConfirmDialog.js
  src/components/loader/Loader.js
  src/components/popup-dialog/PopupDialog.js
  src/containers/guest-home-page/login-form/LoginForm.js
  src/containers/layout/AppHeader.js
  src/pages/guest-home-page/GuestHome.js
  src/pages/mentor-home/MentorHome.js
  src/pages/student-home/StudentHome.js
  tests/test-utils.js
  tests/unit/components/Loader.spec.js
  tests/unit/components/PopupDialog.spec.js
  tests/unit/components/layout/AppHeader.spec.js
  tests/unit/components/layout/AppMain.spec.js
  tests/unit/containers/guest-home-page/signup-dialog/SignupDialog.spec.js
  tests/unit/containers/guest-home-page/signup-form/SignupForm.spec.js
  tests/unit/containers/navbar/NavBar.spec.js
  tests/unit/containers/sidebar/Sidebar.spec.js
  tests/unit/context/modal-context.spec.js
  tests/unit/redux/redux.spec.js
  tests/unit/redux/redux.variables.js
Labels: test
