Repository ita-social-projects/SpaceToStudy-Client, pull requests merged in 2022-09, with the labels that each got.

#276 Add a scrollbar to a signup form
  src/components/img-title-description/ImgTitleDescription.js
  src/components/popup-dialog/PopupDialog.js
  src/components/popup-dialog/PopupDialog.style.js
  src/containers/email-confirm-modal/EmailConfirmModal.js
  src/containers/email-confirm-modal/EmailConfirmModal.style.js
  src/containers/guest-home-page/forgot-password/ForgotPassword.js
  src/containers/guest-home-page/forgot-password/ForgotPassword.style.js
  src/containers/guest-home-page/login-dialog/LoginDialog.js
  src/containers/guest-home-page/login-dialog/LoginDialog.style.js
  src/containers/guest-home-page/login-dialog/login-dialog.style.js
  src/containers/guest-home-page/login-form/LoginForm.js
  src/containers/guest-home-page/login-form/LoginForm.style.js
  src/containers/guest-home-page/signup-dialog/SignupDialog.js
  src/containers/guest-home-page/signup-dialog/SignupDialog.style.js
  src/containers/guest-home-page/signup-dialog/signup-dialog.style.js
  src/containers/guest-home-page/signup-form/SignupForm.js
  src/containers/guest-home-page/signup-form/SignupForm.style.js
Labels: Frontend part

#295 Feature/294/close modal after delay
  src/components/popup-dialog/PopupDialog.js
  src/containers/guest-home-page/forgot-password/ForgotPassword.js
  src/containers/guest-home-page/signup-dialog/SignupDialog.js
  src/context/modal-context.js
  tests/unit/components/popup-dialog/PopupDialog.spec.js
Labels: Frontend part, feature

#289 Feature/282/create custom scrollbar
  src/containers/guest-home-page/login-dialog/LoginDialog.style.js
  src/containers/guest-home-page/signup-dialog/SignupDialog.style.js
  src/styles/app-theme/app.textfield.js
  src/styles/app-theme/custom-scrollbar.js
  src/styles/index.css
Labels: Frontend part, feature

#292 refactor useBreakpoints hook
  src/components/popup-dialog/PopupDialog.js
  src/containers/guest-home-page/FeatureBlock.js
  src/containers/guest-home-page/Welcome.js
  src/containers/student-home-page/find-mentor-block/FindMentorBlock.js
  src/containers/student-home-page/popular-categories/PopularCategories.js
  src/hooks/use-breakpoints.js
  src/pages/error/BadRequest.js
  src/pages/error/NotFound.js
  tests/unit/containers/guest-home-page/FeatureBlock.spec.js
  tests/unit/containers/student-home-page/FindMentorBlock.spec.js
  tests/unit/hooks/use-breakpoints.spec.js
Labels: enhancement, Frontend part

#296 Feature/155/forgot password send email
  src/constants/request.js
  src/containers/guest-home-page/forgot-password/ForgotPassword.js
  src/services/auth-service.js
  tests/unit/containers/guest-home-page/forgot-password/ForgotPassword.spec.js
  tests/unit/containers/guest-home-page/login-form/LoginForm.spec.js
Labels: Frontend part, feature

#300 fix console error in Welcome component test
  src/containers/guest-home-page/Welcome.js
Labels: hotfix

#297 feature/239/reset-password
  src/constants/request.js
  src/constants/translations/en/errors.json
  src/constants/translations/en/login.json
  src/containers/guest-home-page/reset-password/ResetPassword.js
  src/context/snackbar-context.js
  src/hooks/use-axios.js
  src/pages/guest-home-page/GuestHome.js
  src/services/auth-service.js
  tests/unit/containers/guest-home-page/reset-password/ResetPassword.spec.js
Labels: Frontend part, feature, component

#308 Hotfix/282/change scrollbar styles
  src/styles/app-theme/custom-scrollbar.js
Labels: Frontend part

#315 Feature/314/refactor error routes
  src/constants/routes.js
  src/router/AppRouter.js
  src/router/helpers/PrivateRoute.js
  src/router/routes/ErrorRoutes.js
  src/router/routes/GuestRoutes.js
  src/router/routes/MentorRoutes.js
  src/router/routes/StudentRoutes.js
Labels: Frontend part

#307 Add language header to axios interceptor
  src/services/auth-service.js
  src/services/setup-interceptors.js
  tests/unit/containers/guest-home-page/forgot-password/ForgotPassword.spec.js
Labels: Frontend part, feature

#275 Added loader on button on signup modal and login modal
  src/components/app-button/AppButton.js
  src/components/loader/Loader.js
  src/containers/guest-home-page/forgot-password/ForgotPassword.js
  src/containers/guest-home-page/login-form/LoginForm.js
  src/containers/guest-home-page/signup-form/SignupForm.js
  src/stories/AppButton.stories.js
  tests/unit/containers/guest-home-page/WhatCanYouDo.spec.js
  tests/unit/containers/guest-home-page/cards-with-button/CardsWithButton.spec.js
  tests/unit/containers/guest-home-page/login-dialog/LoginDialog.spec.js
  tests/unit/containers/guest-home-page/login-form/LoginForm.spec.js
  tests/unit/containers/guest-home-page/signup-dialog/SignupDialog.spec.js
  tests/unit/containers/guest-home-page/signup-form/SignupForm.spec.js
  tests/unit/containers/navigation-icons/NavigationIcons.spec.js
  tests/unit/context/snackbar-context.spec.js
Labels: Frontend part

#328 Feature/324/added check for status code in interceptors
  src/services/setup-interceptors.js
Labels: Frontend part, feature

#327 Feature/325/added translations for step labels
  src/components/step-wrapper/StepWrapper.js
  src/constants/translations/en/become-tutor.json
  src/containers/mentor-home-page/become-a-tutor/BecomeATutor.js
  src/containers/mentor-home-page/constants.js
Labels: Frontend part, feature

#272 Created photo page for stepper
  src/components/file-uploader/FileUploader.js
  src/components/file-uploader/FileUploader.styles.js
  src/components/popup-dialog/PopupDialog.js
  src/components/popup-dialog/PopupDialog.styles.js
  src/components/step-wrapper/StepWrapper.styles.js
  src/constants/translations/en/become-tutor.json
  src/containers/mentor-home-page/add-photo/AddPhoto.js
  src/containers/mentor-home-page/add-photo/AddPhoto.style.js
  src/containers/mentor-home-page/add-photo/constants.js
  src/containers/mentor-home-page/become-a-tutor/BecomeATutor.js
  src/containers/mentor-home-page/constants.js
  src/hooks/use-form.js
  src/hooks/use-upload.js
  src/utils/image-resize.js
  tests/unit/components/file-uploader/FileUploader.spec.js
  tests/unit/containers/mentor-home-page/add-documents/AddDocuments.spec.js
  tests/unit/containers/mentor-home-page/add-photo/AddPhoto.spec.js
  tests/unit/containers/mentor-home-page/become-a-tutor/BecomeATutor.spec.js
  tests/unit/hooks/use-upload.spec.js
  tests/unit/utils/image-resize.spec.js
Labels: Frontend part, feature

#341 splitted constants/routes.js into separate files
  src/constants/routes.js
  src/containers/guest-home-page/Welcome.js
  src/containers/guest-home-page/WhatCanYouDo.js
  src/containers/guest-home-page/google-login/GoogleLogin.js
  src/containers/guest-home-page/how-it-works/HowItWorks.js
  src/containers/guest-home-page/signup-form/SignupForm.js
  src/containers/guest-home-page/who-we-are/WhoWeAre.js
  src/containers/layout/footer/Footer.js
  src/containers/layout/navbar/NavBar.js
  src/containers/student-home-page/faq/Faq.js
  src/containers/student-home-page/find-mentor-block/FindMentorBlock.js
  src/containers/student-home-page/popular-categories/PopularCategories.js
  src/containers/student-home-page/student-how-it-works/StudentHowItWorks.js
  src/pages/error/AuthPolicy.js
  src/pages/error/BadRequest.js
  src/pages/error/InternalServerError.js
  src/pages/error/NotFound.js
  src/router/AppRouter.js
  src/router/constants/errorRoutes.js
  src/router/constants/guestRoutes.js
  src/router/constants/studentRoutes.js
  src/router/helpers/GuestRoute.js
  src/router/helpers/PrivateRoute.js
  src/router/routes/ErrorRoutes.js
  src/router/routes/MentorRoutes.js
  src/router/routes/StudentRoutes.js
Labels: Frontend part, feature

#340 Bug/336/fix isDirty bug in use-form custom hook
  src/hooks/use-form.js
  src/utils/isEqual.js
Labels: bug, Frontend part

#337 Feature/239/sucsess reset password modal
  src/constants/translations/en/login.json
  src/containers/guest-home-page/reset-password/ResetPassword.js
  src/containers/guest-home-page/reset-password/ResetPassword.styles.js
  src/pages/guest-home-page/GuestHome.js
  tests/unit/containers/guest-home-page/reset-password/ResetPassword.spec.js
Labels: Frontend part, feature

#329 Feature/226/logout
  src/constants/translations/en/header.json
  src/containers/layout/navbar/NavBar.js
  src/containers/navigation-icons/NavigationIcons.styles.js
  src/containers/navigation-icons/student-icons/StudentIcons.js
  src/pages/logout/Logout.js
  src/router/AppRouter.js
  src/router/constants/studentRoutes.js
  src/styles/app-theme/app.menu-item.js
  src/styles/app-theme/app.menu-list.js
  src/styles/app-theme/custom-mui.styles.js
  tests/unit/containers/navigation-icons/student-icons/Studenticons.spec.js
  tests/unit/pages/logout/Logout.spec.js
Labels: Frontend part, feature

#336 Feature/316/added admin routes
  src/constants/index.js
  src/pages/admin-home/AdminHome.js
  src/router/AppRouter.js
  src/router/constants/adminRoutes.js
  src/router/constants/guestRoutes.js
  src/router/routes/AdminRoutes.js
  tests/unit/components/layout/AppMain.spec.js
Labels: Frontend part, feature

#342 Feature/310/scroll to top
  src/components/scroll-to-top-button/ScrollToTopButton.js
  src/components/scroll-to-top-button/ScrollToTopButton.styles.js
  src/components/scroll-to-top/ScrollToTop.js
  src/containers/app-content/AppContent.js
  tests/unit/components/scroll-to-top-button/ScrollToTopButton.spec.js
  tests/unit/components/scroll-to-top/ScrollToTop.spec.js
  tests/unit/containers/app-content/AppContent.spec.js
Labels: Frontend part, feature
