Repository ita-social-projects/SpaceToStudy-Client, pull requests merged in 2022-07, with the labels that each got.

#109 Feature/100/footer
  src/components/accordion-with-image/AccordionWithImage.js
  src/components/footer/Footer.js
  src/components/footer/footer.styles.js
  src/constants/routes.js
  src/constants/translations/en/common.json
  src/containers/guest-home-page/WelcomeBlock.js
  src/containers/guest-home-page/styles/welcome.styles.js
  src/pages/guest-home-page/GuestHome.js
  src/styles/index.css
  tests/unit/components/confirm-dialog/ConfirmDialog.spec.js
  tests/unit/components/footer/Footer.spec.js
  tests/unit/components/loader/Loader.spec.js
  tests/unit/components/popup-dialog/PopupDialog.spec.js
Labels: Frontend part, feature, component

#75 Feature/64/create what you can do section
  package-lock.json
  src/assets/img/guest-home-page/learnImg.png
  src/assets/img/guest-home-page/teachImg.png
  src/components/info-card/InfoCard.js
  src/components/info-card/info-card.styles.js
  src/components/title-with-description/TitleWithDescription.js
  src/components/title-with-description/title-with-description.styles.js
  src/constants/translations/en/guest-home-page.json
  src/containers/guest-home-page/Welcome.js
  src/containers/guest-home-page/WhatCanYouDo.js
  src/containers/guest-home-page/styles/welcome.styles.js
  src/containers/guest-home-page/styles/what-can-you-do.styles.js
  src/pages/guest-home-page/GuestHome.js
  tests/unit/components/info-card/InfoCard.spec.js
  tests/unit/components/title-with-description/TitleWithDescription.spec.js
  tests/unit/containers/guest-home-page/Welcome.spec.js
Labels: Frontend part, feature

#113 Write tests for useBreakpoints custom hook
  package-lock.json
  package.json
  tests/unit/hooks/use-breakpoints.spec.js
Labels: Frontend part, test

#117 hotfix/54/fix console warning
  tests/unit/hooks/use-form.spec.js
Labels: Frontend part

#115 Feature/96/find-mentor-block
  src/assets/img/student-home/bag.png
  src/constants/routes.js
  src/constants/translations/en/common.json
  src/constants/translations/en/footer.json
  src/constants/translations/en/index.js
  src/constants/translations/en/student-home-page.json
  src/containers/footer/Footer.js
  src/containers/footer/footer.styles.js
  src/containers/layout/StudentLayout.js
  src/containers/student-home-page/find-mentor-block/FindMentorBlock.js
  src/containers/student-home-page/find-mentor-block/find-mentor-block.styles.js
  src/pages/find-mentor/FindMentor.js
  src/pages/guest-home-page/GuestHome.js
  src/pages/student-home/StudentHome.js
  src/styles/app-theme/app.button.js
  src/styles/app-theme/app.pallete.js
  src/styles/app-theme/app.typography.js
  src/styles/index.css
  tests/unit/containers/footer/Footer.spec.js
  tests/unit/containers/student-home-page/FindMentorBlock.spec.js
Labels: Frontend part, feature, component

#119 Add new favicon.
  public/favicon.ico
  public/logo192.png
  public/logo512.png
Labels: feature

#112 Feature/83/create who we are section
  src/assets/img/guest-home-page/title-bar.png
  src/assets/img/guest-home-page/videoImg.png
  src/components/info-card/InfoCard.js
  src/components/info-card/info-card.styles.js
  src/components/title-with-description/title-with-description.styles.js
  src/components/video-box/VideoBox.js
  src/components/video-box/video-box.styles.js
  src/constants/translations/en/guest-home-page.json
  src/containers/guest-home-page/FeatureBlock.js
  src/containers/guest-home-page/WhatCanYouDo.js
  src/containers/guest-home-page/who-we-are/WhoWeAre.js
  src/pages/guest-home-page/GuestHome.js
  src/styles/app-theme/app.pallete.js
  tests/unit/components/layout/AppMain.spec.js
  tests/unit/components/video-box/VideoBox.spec.js
  tests/unit/containers/guest-home-page/FeatureBlock.spec.js
  tests/unit/containers/guest-home-page/WhatCanYouDo.spec.js
Labels: Frontend part, feature

#125 Add logout instead of throwing an error in axios interceptor
  src/plugins/axiosClient.js
Labels: Frontend part, hotfix

#116 Feature/99/Create "Frequently Asked Questions" block
  src/components/accordion-with-image/AccordionWithImage.js
  src/components/accordion-with-image/accordion-with-image.style.js
  src/components/accordion/Accordions.js
  src/components/accordion/accordion.styles.js
  src/constants/translations/en/student-home-page.json
  src/containers/student-home-page/faq/Faq.js
  src/containers/student-home-page/faq/accordionItems.js
  src/pages/student-home/StudentHome.js
  src/styles/app-theme/app.pallete.js
  src/styles/app-theme/custom-shadows.js
  tests/unit/components/accordion/Accordions.spec.js
  tests/unit/containers/student-home-page/faq/Faq.spec.js
Labels: Frontend part, feature

#136 Feature/22/bad-request-error-page
  src/assets/img/error-page/400.svg
  src/constants/routes.js
  src/constants/translations/en/errorPage.json
  src/containers/layout/GuestLayout.js
  src/containers/layout/MentorLayout.js
  src/containers/layout/StudentLayout.js
  src/pages/error/BadRequest.js
  src/pages/error/styles/bad-request.styles.js
  tests/unit/pages/error/BadRequest.spec.js
Labels: Frontend part, feature

#132 Feature/129/scroll to top button
  src/App.js
  src/components/scroll-to-top/ScrollToTop.js
  src/components/scroll-to-top/scroll-to-top.style.js
  src/pages/guest-home-page/GuestHome.js
  src/pages/student-home/StudentHome.js
  tests/unit/components/scroll-to-top/ScrollToTop.spec.js
Labels: Frontend part, feature

#141 Added test for confirm password visibility icon
  tests/unit/containers/guest-home-page/signup-form/SignupForm.spec.js
Labels: Frontend part, test

#139 Feature/129/Scroll to top
  src/App.js
  src/components/scroll-to-top/ScrollToTop.js
  src/components/scroll-to-top/scroll-to-top.style.js
  src/containers/student-home-page/faq/Faq.js
  src/pages/guest-home-page/GuestHome.js
  src/pages/student-home/StudentHome.js
  tests/unit/components/scroll-to-top/ScrollToTop.spec.js
Labels: Frontend part, feature

#144 Feature/124/Fix regex according to error message
  src/constants/translations/en/common.json
  src/constants/translations/ua/login.json
  src/constants/validation/common.js
  src/constants/validation/login.js
  src/containers/guest-home-page/signup-form/SignupForm.js
Labels: Frontend part

#149 Feature/142/added husky
  .husky/pre-commit
  .husky/pre-push
  package-lock.json
  package.json
  src/stories/Header.jsx
  src/stories/Header.stories.jsx
  src/stories/header.css
Labels: Frontend part, feature

#114 Create popular categories block
  src/assets/img/student-home-page/service_icon.png
  src/components/clickable-card/ClickableCard.js
  src/components/clickable-card/clickable-card.styles.js
  src/components/info-card/InfoCard.js
  src/components/title-with-description/TitleWithDescription.js
  src/constants/translations/en/student-home-page.json
  src/containers/guest-home-page/WhatCanYouDo.js
  src/containers/guest-home-page/who-we-are/WhoWeAre.js
  src/containers/student-home-page/faq/Faq.js
  src/containers/student-home-page/popular-categories/PopularCategories.js
  src/containers/student-home-page/popular-categories/categories-list-mock.js
  src/containers/student-home-page/popular-categories/popular-categories.styles.js
  src/hooks/use-breakpoints.js
  src/hooks/use-show-more.js
  src/pages/error/BadRequest.js
  src/pages/student-home/StudentHome.js
  src/stories/TitleWithDescription.stories.js
  src/styles/app-theme/custom-shadows.js
  tests/unit/components/clickable-card/ClickableCard.spec.js
  tests/unit/containers/student-home-page/popular-categories/PopularCategories.spec.js
  tests/unit/hooks/mock-categories.js
  tests/unit/hooks/use-show-more.spec.js
Labels: Frontend part, feature

#134 Feature/23/error 404 page
  src/assets/img/error-page/404-man.svg
  src/assets/img/error-page/404-plant.svg
  src/constants/translations/en/errorPage.json
  src/containers/layout/GuestLayout.js
  src/containers/layout/MentorLayout.js
  src/containers/layout/StudentLayout.js
  src/pages/error/NotFound.js
  src/pages/error/styles/bad-request.styles.js
  src/pages/error/styles/internal-server-error.styles.js
  src/pages/error/styles/not-found.style.js
  tests/unit/pages/error/NotFound.spec.js
Labels: Frontend part, feature

#184 Hotfix/95/fix header icons loader
  src/containers/navigation-icons/NavigationIcons.js
Labels: Frontend part, feature

#178 Added Accordion component to storybook
  src/stories/Accordion.stories.js
Labels: documentation, Frontend part

#181 Feature/155/forgot passsword
  src/assets/img/guest-home-page/info.svg
  src/constants/translations/en/login.json
  src/containers/guest-home-page/forgot-password/ForgotPassword.js
  src/containers/guest-home-page/forgot-password/forgot-password.style.js
  src/containers/guest-home-page/login-form/LoginForm.js
  src/containers/guest-home-page/login-form/login-form.style.js
  src/containers/guest-home-page/reset-password-success/ResetPasswordSuccess.js
  tests/unit/containers/guest-home-page/forgot-password/ForgotPassword.spec.js
  tests/unit/containers/guest-home-page/login-form/LoginForm.spec.js
  tests/unit/containers/guest-home-page/reset-password-success/ResetPasswordInfo.spec.js
Labels: Frontend part, feature

#187 Feature/174/popup-dialog-story-book
  .gitignore
  sonar-project.properties
  src/stories/PopupDialog.stories.js
Labels: feature

#180 Add VideoBox component to storybook
  src/stories/VideoBox.stories.js
Labels: Frontend part, feature

#182 Feature/159/created step wrapper
  src/assets/img/step-wrapper/backArrow.svg
  src/assets/img/step-wrapper/nextArrow.svg
  src/components/popup-dialog/PopupDialog.js
  src/components/step-wrapper/StepWrapper.js
  src/components/step-wrapper/step-wrapper.styles.js
  src/constants/translations/en/common.json
  src/containers/mentor-home-page/become-a-tutor/BecomeATutor.js
  src/context/modal-context.js
  src/hooks/use-confirm.js
  src/pages/mentor-home/MentorHome.js
  src/styles/app-theme/app.button.js
  src/styles/app-theme/app.typography.js
  tests/unit/components/layout/AppMain.spec.js
  tests/unit/components/popup-dialog/PopupDialog.spec.js
  tests/unit/components/step-wrapper/StepWrapper.spec.js
  tests/unit/containers/guest-home-page/login-form/LoginForm.spec.js
  tests/unit/containers/mentor-home-page/become-a-tutor/BecomeATutor.spec.js
  tests/unit/context/modal-context.spec.js
Labels: Frontend part, feature

#189 feature/159/refactor-general-step-wrapper
  src/assets/img/step-wrapper/backArrow.svg
  src/assets/img/step-wrapper/nextArrow.svg
  src/components/step-wrapper/StepWrapper.js
  src/components/step-wrapper/step-wrapper.styles.js
  src/styles/app-theme/app.button.js
Labels: Frontend part, feature, component
