Repository ita-social-projects/SpaceToStudy-Client, pull requests merged in 2022-05, with the labels that each got.

#48 Feature/47/confirm-dialog
  .eslintrc.json
  public/index.html
  src/App.js
  src/components/ConfirmDialog/ConfirmDialog.js
  src/components/testConfirmComponent/testConfirm.js
  src/constants/translations/en/common.json
  src/constants/translations/ua/common.json
  src/containers/modal/Modal.js
  src/context/confirm-context.js
  src/context/modal-context.js
  src/hooks/use-confirm.js
  src/pages/guest-home-page/GuestHomePage.js
Labels: Frontend part, feature, component

#52 refactor routes and header
  src/constants/routes.js
  src/constants/translations/en/header.json
  src/constants/translations/ua/header.json
  src/containers/layout/AppHeader.js
  src/containers/layout/AppMain.js
  src/containers/navbar/NavBar.js
  src/pages/home/Home.css
Labels: Frontend part, feature

#58 Feature/57/prompt
  src/components/testConfirmComponent/testConfirm.js
  src/context/confirm-context.js
  src/hooks/use-prompt.js
Labels: Frontend part, feature, component

#59 Feature/47/styled confirm dialog
  src/components/ConfirmDialog/ConfirmDialog.js
  src/constants/translations/en/index.js
  src/constants/translations/en/questions.json
  src/constants/translations/en/titles.json
  src/constants/translations/index.js
  src/constants/translations/ua/index.js
  src/constants/translations/ua/questions.json
  src/constants/translations/ua/titles.json
  src/containers/modal/Modal.js
  src/context/confirm-context.js
  src/hooks/use-confirm.js
  src/plugins/i18n.js
  src/styles/app-theme/app.button.js
  src/styles/app-theme/app.typography.js
  src/styles/index.css
Labels: Frontend part
