Repository ita-social-projects/SpaceToStudy-Client, pull requests merged in 2022-08, with the labels that each got.

#191 Feature/172/add InfoCard to Storybook
  src/stories/InfoCard.stories.js
Labels: documentation, Frontend part

#190 Feature/127/app-text-field-storybook
  src/stories/AppTextField.stories.jsx
Labels: feature

#195 Feature/194/pass btnsbox from StepWrapper to child
  src/components/step-wrapper/StepWrapper.js
  src/containers/mentor-home-page/become-a-tutor/BecomeATutor.js
  src/containers/mentor-home-page/become-a-tutor/TempComponent.js
  tests/unit/components/step-wrapper/StepWrapper.spec.js
Labels: enhancement, Frontend part

#198 Bugfix/197/change password and email regex
  src/constants/translations/en/common.json
  src/constants/validation/login.js
Labels: Frontend part

#200 add storybook workflow
  .github/workflows/storybook.yaml
Labels: enhancement

#196 Feature/160/general info step for became a tutor
  src/assets/img/mentor-home-page/become-tutor/general-info.png
  src/components/step-wrapper/StepWrapper.js
  src/components/step-wrapper/step-wrapper.styles.js
  src/constants/translations/en/becomeTutor.json
  src/constants/translations/en/common.json
  src/constants/translations/en/index.js
  src/containers/mentor-home-page/become-a-tutor/BecomeATutor.js
  src/containers/mentor-home-page/constants.js
  src/containers/mentor-home-page/general-info/GeneralInfo.js
  src/containers/mentor-home-page/general-info/general-info.styles.js
  tests/unit/containers/mentor-home-page/become-a-tutor/BecomeATutor.spec.js
Labels: Frontend part, feature, component

#203 Bugfix/197/Fix password regex
  src/constants/validation/login.js
Labels: bug, Frontend part

#204 Added AccordionWithImage to storybook
  .storybook/preview.js
  src/stories/AccordionWithImage.stories.js
Labels: documentation, Frontend part

#179 Rewrite 401 error page
  src/App.js
  src/assets/img/error-page/401.svg
  src/constants/translations/en/errorPage.json
  src/containers/app-content/AppContent.js
  src/containers/layout/MentorLayout.js
  src/containers/layout/StudentLayout.js
  src/pages/error/AuthPolicy.js
  src/pages/error/styles/auth-policy.styles.js
  src/pages/error/styles/bad-request.styles.js
  src/pages/error/styles/internal-server-error.styles.js
  src/pages/error/styles/not-found.style.js
  tests/unit/containers/app-content/AppContent.spec.js
  tests/unit/pages/error/AuthPolicy.spec.js
Labels: Frontend part, feature

#193 Feature/157/create cookie policy page
  src/constants/translations/en/cookie-policy-page.json
  src/constants/translations/en/index.js
  src/containers/layout/GuestLayout.js
  src/containers/layout/MentorLayout.js
  src/containers/layout/StudentLayout.js
  src/pages/cookie-policy/CookiePolicy.js
  src/pages/cookie-policy/cookie-policy.constants.js
  src/pages/cookie-policy/cookie-policy.styles.js
  tests/unit/pages/cookie-policy/cookiePolicy.spec.js
Labels: Frontend part, feature

#212 Bug/211/fix loader
  src/components/loader/Loader.js
  src/containers/navigation-icons/NavigationIcons.js
Labels: bug, Frontend part

#214 feature/213/Change textfield in login and forgot password to custom
  src/containers/guest-home-page/forgot-password/ForgotPassword.js
  src/containers/guest-home-page/login-form/LoginForm.js
Labels: Frontend part, feature

#216 alpine Dockerfile
  Dockerfile
Labels: enhancement

#208 Feature/202/First login popup
  src/pages/mentor-home/MentorHome.js
  src/redux/reducer.js
  tests/unit/pages/mentor-home/MentorHome.spec.js
  tests/unit/redux/redux.variables.js
Labels: Frontend part, feature

#242 Feature/241/fix blinking page
  src/containers/layout/AppMain.js
Labels: Frontend part

#222 Feature/221/update prettier and eslint
  .eslintrc.json
  .prettierrc
  .vscode/settings.json
  package.json
Labels: Frontend part

#223 feature/153/create-confirm-email-notification-modal
  src/components/img-title-description/ImgTitleDescription.js
  src/constants/translations/en/signup.json
  src/containers/guest-home-page/forgot-password/ForgotPassword.js
  src/containers/guest-home-page/reset-password-success/ResetPasswordSuccess.js
  src/containers/guest-home-page/signup-dialog/SignupDialog.js
  tests/unit/components/img-title-description/ImgTitleDescription.spec.js
  tests/unit/containers/guest-home-page/reset-password-success/ResetPasswordInfo.spec.js
Labels: Frontend part, feature, component

#219 Added way to open modal with link, added tests
  src/pages/guest-home-page/GuestHome.js
  tests/test-utils.js
  tests/unit/pages/guest-home/GuestHome.spec.js
Labels: Frontend part, feature

#224 add student how it works block
  src/constants/translations/en/student-home-page.json
  src/containers/student-home-page/student-how-it-works/HowItWorksCards.js
  src/containers/student-home-page/student-how-it-works/StudentHowItWorks.js
  src/containers/student-home-page/student-how-it-works/student-how-it-works.styles.js
  src/pages/student-home/StudentHome.js
  tests/unit/containers/student-home-page/student-how-it-works/StudentHowItWorks.spec.js
Labels: Frontend part

#199 Feature/164/Add documents
  .storybook/preview.js
  src/assets/img/mentor-home-page/become-tutor/add-documents.png
  src/components/file-uploader/FileUploader.js
  src/components/file-uploader/file-uploader.style.js
  src/constants/translations/en/becomeTutor.json
  src/containers/mentor-home-page/add-documents/AddDocuments.js
  src/containers/mentor-home-page/add-documents/add-documents.style.js
  src/containers/mentor-home-page/become-a-tutor/BecomeATutor.js
  src/hooks/use-upload.js
  src/pages/guest-home-page/GuestHome.js
  src/stories/FileUploader.stories.js
  src/utils/validations/files.js
  tests/unit/components/file-uploader/FileUploader.spec.js
  tests/unit/containers/mentor-home-page/add-documents/AddDocuments.spec.js
  tests/unit/containers/mentor-home-page/become-a-tutor/BecomeATutor.spec.js
  tests/unit/hooks/use-upload.spec.js
Labels: Frontend part, feature

#207 Add the Experience step for become a tutor
  src/assets/img/mentor-home-page/become-tutor/experience.png
  src/components/step-wrapper/StepWrapper.js
  src/constants/translations/en/becomeTutor.json
  src/constants/translations/en/common.json
  src/containers/guest-home-page/forgot-password/ForgotPassword.js
  src/containers/guest-home-page/login-dialog/LoginDialog.js
  src/containers/guest-home-page/signup-dialog/SignupDialog.js
  src/containers/mentor-home-page/add-documents/AddDocuments.js
  src/containers/mentor-home-page/become-a-tutor/BecomeATutor.js
  src/containers/mentor-home-page/constants.js
  src/containers/mentor-home-page/experience-step/ExperienceStep.js
  src/containers/mentor-home-page/experience-step/experience-step.styles.js
  src/containers/mentor-home-page/general-info/GeneralInfo.js
  src/utils/validations/common.js
  src/utils/validations/login.js
  tests/unit/components/step-wrapper/StepWrapper.spec.js
  tests/unit/containers/mentor-home-page/add-documents/AddDocuments.spec.js
  tests/unit/containers/mentor-home-page/become-a-tutor/experience-step/ExperienceStep.spec.js
Labels: Frontend part

#243 Fixed the size of Signup with google button
  src/containers/guest-home-page/google-login/google-login.style.js
  src/pages/guest-home-page/GuestHome.js
Labels: Frontend part

#205 Add confirmdialog to storybook
  src/stories/ConfirmDialog.stories.js
Labels: documentation, Frontend part

#271 HotFix/signup-test
  tests/unit/containers/guest-home-page/signup-dialog/SignupDialog.spec.js
Labels: hotfix

#269 Bugfix/249/Remove special symbols validation
  src/constants/translations/en/common.json
  src/utils/validations/login.js
Labels: bug, Frontend part

#263 Feature/258/change the position of the content in the footer
  src/containers/footer/footer.styles.js
Labels: Frontend part, feature

#273 Add min-width for confirmation modal
  src/components/confirm-dialog/ConfirmDialog.js
  src/components/confirm-dialog/confirm-dialog.style.js
Labels: Frontend part

#274 add tooltips for header
  src/constants/translations/en/iconsTooltip.json
  src/constants/translations/en/index.js
  src/containers/navigation-icons/guest-icons/GuestIcons.js
  src/containers/navigation-icons/navigation-icons.style.js
  src/containers/navigation-icons/student-icons/StudentIcons.js
  src/styles/app-theme/app.tooltip.js
  src/styles/app-theme/custom-mui.styles.js
  tests/unit/containers/navigation-icons/guest-icons/GuestIcons.spec.js
  tests/unit/containers/navigation-icons/student-icons/Studenticons.spec.js
Labels: Frontend part, feature

#266 Feature/255/add stepper animation
  src/components/step-wrapper/step-wrapper.styles.js
  src/containers/mentor-home-page/add-documents/add-documents.style.js
  src/containers/mentor-home-page/experience-step/experience-step.styles.js
  src/containers/mentor-home-page/general-info/general-info.styles.js
  src/styles/app-theme/custom-animations.js
Labels: enhancement, Frontend part, feature

#280 Feature/261/how it works animation
  package-lock.json
  package.json
  src/containers/guest-home-page/cards-with-button/CardsWithButton.js
  src/containers/guest-home-page/cards-with-button/cards-with-button.style.js
  src/containers/guest-home-page/how-it-works/HowItWorks.js
  src/styles/app-theme/custom-animations.js
Labels: Frontend part, feature

#278 Feature/244/error handling
  src/App.js
  src/constants/index.js
  src/constants/translations/en/errors.json
  src/constants/translations/en/index.js
  src/containers/guest-home-page/login-dialog/LoginDialog.js
  src/containers/guest-home-page/signup-dialog/SignupDialog.js
  src/context/snackbar-context.js
  src/redux/reducer.js
  tests/unit/containers/guest-home-page/WhatCanYouDo.spec.js
  tests/unit/containers/guest-home-page/cards-with-button/CardsWithButton.spec.js
  tests/unit/containers/guest-home-page/forgot-password/ForgotPassword.spec.js
  tests/unit/containers/guest-home-page/login-dialog/LoginDialog.spec.js
  tests/unit/containers/guest-home-page/signup-dialog/SignupDialog.spec.js
  tests/unit/containers/navbar/NavBar.spec.js
  tests/unit/containers/navigation-icons/NavigationIcons.spec.js
  tests/unit/context/modal-context.spec.js
  tests/unit/context/snackbar-context.spec.js
  tests/unit/redux/redux.spec.js
  tests/unit/redux/redux.variables.js
Labels: Frontend part, feature

#270 Feature/150/create custom hash link
  .eslintrc.json
  src/App.js
  src/components/hash-link/HashLink.js
  src/containers/guest-home-page/Welcome.js
  src/containers/navbar/NavBar.js
  src/containers/sidebar/Sidebar.js
  src/containers/student-home-page/popular-categories/PopularCategories.js
  src/hooks/use-hash-scroll.js
  tests/unit/hooks/use-hash-scroll.spec.js
Labels: Frontend part, feature, component

#279 Added links in login and signup
  src/containers/guest-home-page/google-login/GoogleLogin.js
  src/containers/guest-home-page/google-login/google-login.style.js
  src/containers/guest-home-page/signup-dialog/SignupDialog.js
  src/containers/guest-home-page/signup-form/SignupForm.js
  tests/unit/containers/guest-home-page/google-login/GoogleLogin.spec.js
  tests/unit/containers/guest-home-page/signup-form/SignupForm.spec.js
Labels: Frontend part, feature

#268 Feature/238/avaliable signup after agree terms
  src/containers/guest-home-page/signup-form/SignupForm.js
  tests/unit/containers/guest-home-page/signup-dialog/SignupDialog.spec.js
  tests/unit/containers/guest-home-page/signup-form/SignupForm.spec.js
Labels: Frontend part, feature

#288 Feature/286/Remove loader in the Navbar
  src/containers/layout/AppHeader.js
  src/containers/navbar/NavBar.js
  src/containers/navbar/NavBar.styles.js
  src/containers/navigation-icons/NavigationIcons.js
  src/containers/navigation-icons/NavigationIcons.styles.js
  src/containers/navigation-icons/guest-icons/GuestIcons.js
  src/containers/navigation-icons/student-icons/StudentIcons.js
  src/containers/sidebar/Sidebar.js
  src/containers/sidebar/Sidebar.styles.js
  tests/unit/containers/navigation-icons/NavigationIcons.spec.js
Labels: enhancement, Frontend part
