Repository ita-social-projects/SpaceToStudy-Client, pull requests merged in 2023-11, with the labels that each got.

#1349 implemented edit question in quiz page functionality
  src/components/question-editor/QuestionEditor.styles.ts
  src/components/question-editor/QuestionEditor.tsx
  src/components/question/Question.tsx
  src/constants/request.ts
  src/constants/translations/en/my-resources-page.json
  src/constants/translations/ua/my-resources-page.json
  src/containers/my-quizzes/create-or-edit-quiz-question/CreateOrEditQuizQuestion.constants.ts
  src/containers/my-quizzes/create-or-edit-quiz-question/CreateOrEditQuizQuestion.tsx
  src/containers/my-quizzes/edit-quiz-container/EditQuizContainer.constants.ts
  src/containers/my-quizzes/edit-quiz-container/EditQuizContainer.tsx
  src/containers/my-resources/create-or-edit-question-modal/CreateOrEditQuestionModal.tsx
  src/containers/questions-list/QuestionsList.tsx
  src/services/resource-service.ts
  src/types/questions/interfaces/questions.interface.ts
  src/types/quizzes/interfaces/quizzes.interface.ts
  tests/unit/components/question-editor/QuestionEditor.spec.jsx
  tests/unit/components/question/Question.spec.jsx
  tests/unit/containers/my-quizzes/CreateOrEditQuizQuestion.spec.jsx
  tests/unit/containers/my-resources/CreateOrEditQuestionModal.spec.jsx
Labels: Frontend part, feature

#1332 Created constant.json ua translation
  src/components/file-uploader/FileUploader.tsx
  src/components/not-found-results/NotFoundResults.tsx
  src/constants/translations/en/error-messages.json
  src/constants/translations/en/index.ts
  src/constants/translations/ua/error-messages.json
  src/constants/translations/ua/index.ts
  src/pages/categories/Categories.tsx
  src/pages/subjects/Subjects.tsx
  tests/unit/components/not-found-results/NotFoundResults.spec.jsx
  tests/unit/pages/categories/Categories.spec.jsx
Labels: Frontend part

#1357 Created section for new category
  src/constants/translations/en/course.json
  src/constants/translations/en/index.ts
  src/constants/translations/ua/course.json
  src/constants/translations/ua/index.ts
  src/containers/course-section/CourseSectionContainer.constants.tsx
  src/containers/course-section/CourseSectionContainer.styles.ts
  src/containers/course-section/CourseSectionContainer.tsx
  src/containers/course-sections-list/CourseSectionsList.styles.ts
  src/containers/course-sections-list/CourseSectionsList.tsx
  src/pages/create-course/CreateCourse.constants.tsx
  src/pages/create-course/CreateCourse.styles.ts
  src/pages/create-course/CreateCourse.tsx
  src/types/course/course.index.ts
  src/types/course/interfaces/course.interface.ts
  src/types/index.ts
  tests/unit/containers/course-section/CourseSectionContainer.spec.jsx
  tests/unit/pages/create-course/CreateCourse.spec.jsx
Labels: Frontend part, feature

#1369 Implemented chat deletion
  src/constants/request.ts
  src/constants/translations/en/chat.json
  src/constants/translations/ua/chat.json
  src/containers/chat/chat-header/ChatHeader.tsx
  src/containers/layout/chat-menu/ChatMenu.styles.ts
  src/containers/layout/chat-menu/ChatMenu.tsx
  src/containers/offer-page/chat-dialog-window/ChatDialogWindow.styles.ts
  src/containers/offer-page/chat-dialog-window/ChatDialogWindow.tsx
  src/pages/chat/Chat.constants.ts
  src/pages/chat/Chat.styles.ts
  src/pages/chat/Chat.tsx
  src/services/chat-service.ts
  src/services/message-service.ts
  src/styles/app-theme/app.pallete.ts
  src/types/chat/interfaces/chat.interfaces.ts
  src/types/common/enums/common.enums.ts
  tests/unit/containers/layout/chat-menu/ChatMenu.spec.jsx
Labels: Frontend part, feature

#1388 Implemented save logic in create quiz
  src/constants/request.ts
  src/constants/translations/en/my-resources-page.json
  src/constants/translations/ua/my-resources-page.json
  src/containers/my-quizzes/QuizzesContainer.tsx
  src/containers/my-quizzes/create-or-edit-quiz-container/CreateOrEditQuizContainer.constants.ts
  src/containers/my-quizzes/create-or-edit-quiz-container/CreateOrEditQuizContainer.styles.ts
  src/containers/my-quizzes/create-or-edit-quiz-container/CreateOrEditQuizContainer.tsx
  src/pages/new-quiz/NewQuiz.constants.tsx
  src/pages/new-quiz/NewQuiz.tsx
  src/services/quiz-service.ts
  src/services/resource-service.ts
  src/types/quizzes/interfaces/quizzes.interface.ts
  tests/unit/containers/my-quizzes/CreateOrEditQuizContainer.spec.jsx
Labels: Frontend part, feature, Tutor

#1391 Add none property to resources
  src/components/filter-selector/FilterSelector.tsx
  src/containers/my-resources/add-resource-with-input/AddResourceWithInput.tsx
  src/containers/my-resources/categories-container/CategoriesContainer.tsx
Labels: Frontend part, feature

#1374 fetched resource categories and add create new category modal for new quiz page
  src/components/app-auto-complete/AppAutoComplete.jsx
  src/containers/my-resources/add-categories-modal/AddCategories.styles.ts
  src/pages/create-or-edit-question/CreateOrEditQuestion.tsx
  tests/unit/containers/find-offer/offer-search-toolbar/offerSearchToolbar.spec.jsx
  tests/unit/pages/create-or-edit-question/CreateOrEditQuestion.spec.jsx
Labels: Frontend part, feature

#1392 Created new view for quiz page
  src/containers/my-quizzes/quiz-question/QuizQuestion.styles.ts
  src/containers/my-quizzes/quiz-question/QuizQuestion.tsx
  src/containers/my-quizzes/scroll-question-quiz-view/ScrollQuestionsQuizView.styles.ts
  src/containers/my-quizzes/scroll-question-quiz-view/ScrollQuestionsQuizView.tsx
  src/containers/my-quizzes/selectable-question-quiz-view/SelectableQuestion.styles.ts
  src/containers/my-quizzes/selectable-question-quiz-view/SelectableQuestionQuizView.tsx
  src/containers/my-quizzes/view-quiz-container/ViewQuizContainer.tsx
  tests/unit/pages/my-quizzes/QuizQuestion.spec.jsx
  tests/unit/pages/my-quizzes/ScrollQuestionsQuizView.spec.jsx
Labels: Frontend part, feature

#1416 Refactored description shows popups on every page
  src/components/icon-extension-with-title/IconExtensionWithTitle.tsx
  src/components/title-with-description/TitleWithDescription.tsx
Labels: bug, Frontend part

#1411 Implemented clear history functionality
  src/constants/request.ts
  src/constants/translations/en/chat.json
  src/constants/translations/en/errors.json
  src/constants/translations/ua/chat.json
  src/constants/translations/ua/errors.json
  src/containers/chat/chat-header/ChatHeader.tsx
  src/containers/layout/chat-menu/ChatMenu.tsx
  src/pages/chat/Chat.tsx
  src/services/message-service.ts
  tests/unit/containers/layout/chat-menu/ChatMenu.spec.jsx
Labels: Frontend part, feature

#1414 Implemented find offers modal for tutor navBar
  src/constants/translations/en/header.json
  src/constants/translations/ua/header.json
  src/containers/layout/navbar/NavBar.styles.ts
  src/containers/layout/navbar/NavBar.tsx
  src/hooks/use-menu.jsx
  src/router/constants/tutorRoutes.ts
Labels: Frontend part, feature

#1415 Added previous values for content and attachments on edit lesson
  src/components/file-editor/FileEditor.tsx
  src/pages/create-or-edit-lesson/CreateOrEditLesson.constants.tsx
  src/pages/create-or-edit-lesson/CreateOrEditLesson.tsx
  src/services/resource-service.ts
  src/types/lesson/interfaces/lesson.interfaces.ts
Labels: Frontend part, feature

#1417 Change edit to rename
  src/containers/my-resources/my-resources-table/MyResourcesTable.tsx
Labels: Frontend part, feature

#1412 Added course component
  src/components/course-card/CourseCard.styles.ts
  src/components/course-card/CourseCard.tsx
  src/constants/translations/en/course.json
  src/constants/translations/ua/course.json
  src/types/course/interfaces/course.interface.ts
  tests/unit/components/course-card/CourseCard.spec.jsx
Labels: Frontend part, feature

#1409 removed access token from local storage
  src/constants/index.ts
  src/containers/my-quizzes/QuizzesContainer.tsx
  src/redux/reducer.ts
  src/services/setup-interceptors.ts
  src/types/user/user-interfaces/user.interfaces.ts
  tests/unit/components/layout/AppMain.spec.jsx
  tests/unit/containers/my-quizzes/QuizzesContainer.spec.jsx
  tests/unit/services/local-storage-service.spec.js
Labels: Frontend part, feature

#1386 Add resources to course section
  src/components/icon-extension-with-title/IconExtensionWithTitle.styles.ts
  src/components/icon-extension-with-title/IconExtensionWithTitle.tsx
  src/constants/translations/en/my-resources-page.json
  src/constants/translations/ua/my-resources-page.json
  src/containers/add-attachments/AddAttachments.constants.tsx
  src/containers/add-attachments/AddAttachments.tsx
  src/containers/add-resources/AddAttachments.constants.tsx
  src/containers/add-resources/AddLessons.constants.tsx
  src/containers/add-resources/AddQuestions.constants.tsx
  src/containers/add-resources/AddQuizzes.constants.tsx
  src/containers/add-resources/AddResources.constants.tsx
  src/containers/add-resources/AddResources.styles.ts
  src/containers/add-resources/AddResources.tsx
  src/containers/course-section/CourseSectionContainer.constants.tsx
  src/containers/course-section/CourseSectionContainer.styles.ts
  src/containers/course-section/CourseSectionContainer.tsx
  src/containers/course-section/resource-item/ResourceItem.styles.ts
  src/containers/course-section/resource-item/ResourceItem.tsx
  src/containers/course-section/resources-list/ResourcesList.styles.ts
  src/containers/course-section/resources-list/ResourcesList.tsx
  src/containers/course-sections-list/CourseSectionsList.styles.ts
  src/containers/my-quizzes/create-or-edit-quiz-container/CreateOrEditQuizContainer.tsx
  src/containers/my-resources/add-questions/AddQuestions.tsx
  src/pages/create-or-edit-lesson/CreateOrEditLesson.tsx
  src/types/attachment/interfaces/attachment.interface.ts
  src/types/course/interfaces/course.interface.ts
  src/types/my-resources/interfaces/myResources.interface.ts
  src/types/quizzes/interfaces/quizzes.interface.ts
  tests/unit/containers/add-attachments/AddAttachments.spec.jsx
  tests/unit/containers/add-resources/add-attachments/AddAttachments.spec.jsx
  tests/unit/containers/add-resources/add-lessons/AddLessons.spec.jsx
  tests/unit/containers/add-resources/add-questions/AddQuestions.spec.jsx
  tests/unit/containers/add-resources/add-quizzes/AddQuizzes.spec.jsx
  tests/unit/containers/course-section/CourseSectionContainer.spec.jsx
  tests/unit/containers/course-section/resource-item/ResourceItem.spec.jsx
  tests/unit/containers/course-section/resources-list/ResourcesList.spec.jsx
  tests/unit/pages/create-or-edit-lesson/CreateOrEditLesson.spec.jsx
Labels: Frontend part, feature

#1384 Implemented settings tab for Quiz
  src/components/setting-item/SettingItem.styles.ts
  src/components/setting-item/SettingItem.tsx
  src/constants/translations/en/common.json
  src/constants/translations/en/my-resources-page.json
  src/constants/translations/ua/common.json
  src/constants/translations/ua/my-resources-page.json
  src/containers/my-quizzes/quiz-settings-container/QuizSettingsContainer.styles.ts
  src/containers/my-quizzes/quiz-settings-container/QuizSettingsContainer.tsx
  src/styles/app-theme/app.pallete.ts
  tests/unit/containers/my-quizzes/QuizSettingsContainer.spec.jsx
Labels: Frontend part, feature, Tutor, on Hold

#1356 Created filters with title and description for new course
  src/constants/translations/en/filters.json
  src/constants/translations/en/my-courses-page.json
  src/constants/translations/ua/filters.json
  src/constants/translations/ua/my-courses-page.json
  src/containers/my-courses/course-search-tool-bar/CourseSearchToolbar.style.ts
  src/containers/my-courses/course-search-tool-bar/CourseSearchToolbar.tsx
  src/pages/create-course/CreateCourse.tsx
Labels: Frontend part, feature

#1410 Added previous value to the quiz editor
  src/constants/request.ts
  src/constants/translations/en/breadcrumbs.json
  src/constants/translations/en/my-resources-page.json
  src/constants/translations/ua/breadcrumbs.json
  src/constants/translations/ua/my-resources-page.json
  src/containers/my-quizzes/QuizzesContainer.tsx
  src/containers/my-quizzes/create-or-edit-quiz-container/CreateOrEditQuizContainer.tsx
  src/pages/new-quiz/NewQuiz.constants.tsx
  src/pages/new-quiz/NewQuiz.tsx
  src/router/constants/authRoutes.ts
  src/router/constants/crumbs.ts
  src/router/routes/authRouter.tsx
  src/services/resource-service.ts
  src/types/quizzes/interfaces/quizzes.interface.ts
  tests/unit/containers/my-quizzes/CreateOrEditQuizContainer.spec.jsx
Labels: Frontend part, feature

#1420 Added category autocomplete to the lesson page
  src/constants/translations/en/my-resources-page.json
  src/containers/category-dropdown/CategoryDropdown.styles.tsx
  src/containers/category-dropdown/CategoryDropdown.tsx
  src/pages/create-or-edit-lesson/CreateOrEditLesson.constants.tsx
  src/pages/create-or-edit-lesson/CreateOrEditLesson.styles.ts
  src/pages/create-or-edit-lesson/CreateOrEditLesson.tsx
  src/pages/create-or-edit-question/CreateOrEditQuestion.tsx
  src/types/lesson/interfaces/lesson.interfaces.ts
  tests/unit/containers/category-dropdown/CategoryDropdown.spec.jsx
  tests/unit/pages/create-or-edit-lesson/CreateOrEditLesson.spec.jsx
  tests/unit/pages/create-or-edit-question/CreateOrEditQuestion.spec.jsx
Labels: Frontend part, feature, Tutor

#1389 Added chose category dropdown for new quiz
  src/components/async-autocomlete/AsyncAutocomplete.tsx
  src/containers/my-quizzes/create-or-edit-quiz-container/CreateOrEditQuizContainer.styles.ts
  src/containers/my-quizzes/create-or-edit-quiz-container/CreateOrEditQuizContainer.tsx
Labels: Frontend part, feature

#1422 Rewrited auth mutation endpoints using RTK Query
  src/containers/guest-home-page/google-button/GoogleButton.jsx
  src/containers/guest-home-page/login-dialog/LoginDialog.jsx
  src/containers/guest-home-page/signup-dialog/SignupDialog.jsx
  src/containers/my-resources/categories-container/CategoriesContainer.tsx
  src/pages/logout/Logout.tsx
  src/redux/apiSlice.ts
  src/redux/reducer.ts
  src/redux/store.ts
  src/services/auth-service.ts
  src/services/resource-service.ts
  src/services/setup-interceptors.ts
  src/types/common/enums/common.enums.ts
  src/types/user/user-interfaces/user.interfaces.ts
  tests/unit/containers/guest-home-page/login-dialog/LoginDialog.spec.jsx
  tests/unit/containers/guest-home-page/signup-dialog/SignupDialog.spec.jsx
  tests/unit/context/snackbar-context.spec.jsx
  tests/unit/pages/logout/Logout.spec.jsx
  tests/unit/redux/redux.spec.js
Labels: Frontend part, feature

#1424 added use form hook to create course page
  src/containers/course-section/CourseSectionContainer.tsx
  src/containers/course-sections-list/CourseSectionsList.tsx
  src/containers/my-courses/course-search-tool-bar/CourseSearchToolbar.tsx
  src/containers/my-courses/course-toolbar/CourseToolbar.style.ts
  src/containers/my-courses/course-toolbar/CourseToolbar.tsx
  src/pages/create-course/CreateCourse.constants.tsx
  src/pages/create-course/CreateCourse.tsx
  src/types/course/interfaces/course.interface.ts
  tests/unit/containers/course-section/CourseSectionContainer.spec.jsx
Labels: Frontend part, feature

#1451 Fixed title and description in quiz view
  src/constants/translations/en/my-resources-page.json
  src/constants/translations/ua/my-resources-page.json
  src/containers/my-quizzes/scroll-question-quiz-view/ScrollQuestionsQuizView.tsx
  src/containers/my-quizzes/view-quiz-container/ViewQuizContainer.tsx
  src/pages/create-or-edit-lesson/CreateOrEditLesson.styles.ts
  tests/unit/containers/my-quizzes/ViewQuizContainer.spec.jsx
  tests/unit/pages/my-quizzes/ScrollQuestionsQuizView.spec.jsx
Labels: Frontend part, feature

#1423 Added categories button to attachment table
  src/components/enhanced-table/enhanced-table-row/EnhancedTableRow.styles.ts
  src/constants/translations/en/my-resources-page.json
  src/constants/translations/ua/my-resources-page.json
  src/containers/my-resources/add-attachment-category-modal/AddAttachmentCategoryModal.constants.tsx
  src/containers/my-resources/add-attachment-category-modal/AddAttachmentCategoryModal.styles.ts
  src/containers/my-resources/add-attachment-category-modal/AddAttachmentCategoryModal.tsx
  src/containers/my-resources/attachments-container/AttachmentsContainer.constants.tsx
  src/containers/my-resources/attachments-container/AttachmentsContainer.styles.ts
  src/containers/my-resources/attachments-container/AttachmentsContainer.tsx
  src/containers/my-resources/edit-attachment-modal/EditAttachmentModal.tsx
  src/types/attachment/interfaces/attachment.interface.ts
  tests/unit/containers/my-resources/AddAttachmentCategoryModal.spec.jsx
Labels: Frontend part, feature

#1446 Created courses table and pagination
  src/components/course-card/CourseCard.styles.ts
  src/constants/request.ts
  src/constants/translations/en/my-courses-page.json
  src/constants/translations/ua/my-courses-page.json
  src/containers/my-courses/my-courses-container/MyCorsesCardsList.styles.ts
  src/containers/my-courses/my-courses-container/MyCorsesCardsList.tsx
  src/pages/my-courses/MyCourses.constants.tsx
  src/pages/my-courses/MyCourses.styles.ts
  src/pages/my-courses/MyCourses.tsx
  src/services/course-service.ts
  src/types/course/course.index.ts
  src/types/course/interfaces/course.interface.ts
  src/types/course/types/course.types.ts
  tests/unit/containers/my-courses/my-courses-container/MyCoursesContainer.spec.jsx
  tests/unit/pages/my-courses/MyCourses.spec.constans.js
  tests/unit/pages/my-courses/MyCourses.spec.jsx
Labels: Frontend part, feature
