Repository ita-social-projects/SpaceToStudy-Client, pull requests merged in 2023-10, with the labels that each got.

#1212 changed description text in What can you do section at guest-home-page
  src/constants/translations/en/guest-home-page.json
  src/constants/translations/ua/guest-home-page.json
Labels: bug, Frontend part

#1213 Changed placeholder input text on the home page
  src/constants/translations/en/student-home-page.json
  src/constants/translations/ua/student-home-page.json
Labels: bug, Frontend part

#1209 Changed description on home page welcoming block
  src/constants/translations/en/guest-home-page.json
Labels: bug, Frontend part

#1211 Changed howItWorks description content
  src/constants/translations/en/guest-home-page.json
  src/constants/translations/ua/guest-home-page.json
Labels: bug, Frontend part

#1214 Changed description in the list of phrases on the welcoming block
  src/constants/translations/en/guest-home-page.json
  src/constants/translations/ua/guest-home-page.json
Labels: bug, Frontend part

#1128 Added functionality for create question page
  src/components/question-editor/QuestionEditor.constants.tsx
  src/components/question-editor/QuestionEditor.styles.ts
  src/components/question-editor/QuestionEditor.tsx
  src/constants/translations/en/common.json
  src/constants/translations/en/question-page.json
  src/constants/translations/ua/common.json
  src/constants/translations/ua/question-page.json
  src/containers/my-resources/questions-container/QuestionsContainer.tsx
  src/pages/create-or-edit-question/CreateOrEditQuestion.tsx
  src/services/resource-service.ts
  src/types/questions/interfaces/questions.interface.ts
Labels: Frontend part, feature

#1109 Added redirect from dialog to chat
  src/constants/request.ts
  src/constants/translations/en/chat.json
  src/constants/translations/ua/chat.json
  src/containers/chat/chat-item/ChatItem.tsx
  src/containers/chat/list-of-users-with-search/ListOfUsersWithSearch.constants.ts
  src/containers/offer-page/chat-dialog-window/ChatDialogWindow.styles.ts
  src/containers/offer-page/chat-dialog-window/ChatDialogWindow.tsx
  src/pages/chat/Chat.tsx
  src/services/chat-service.ts
  src/types/chat/interfaces/chat.interfaces.ts
  tests/unit/containers/chat/chat-item/ChatItem.spec.jsx
  tests/unit/pages/chat/Chat.spec.jsx
Labels: Frontend part, feature

#1215 Changed description text on home page in 'Who we are' block
  src/constants/translations/en/guest-home-page.json
  src/constants/translations/ua/guest-home-page.json
Labels: bug, UI/Usability, priority: low, severity: trivial

#1245 Added unit tests for ProfileContainerMobile in ProfileInfo
  tests/unit/containers/tutor-profile/ProfileInfo.spec.jsx
Labels: Frontend part, test

#1229 Created unit test for EditProfile
  tests/unit/pages/edit-profile/EditProfile.spec.jsx
Labels: Frontend part, test

#1230 Unit tests for AdminPortal container
  tests/unit/containers/admin-portal/AdminPortal.spec.jsx
Labels: Frontend part, test

#1231 Added tests for CategoriesContainer
  tests/unit/containers/my-resources/CategoriesContainer.spec.jsx
Labels: Frontend part, test

#1233 Implemented Edit Attachment modal
  src/components/filter-selector/FilterSelector.tsx
  src/components/icon-extension-with-title/IconExtensionWithTitle.styles.ts
  src/components/icon-extension-with-title/IconExtensionWithTitle.tsx
  src/constants/translations/en/my-resources-page.json
  src/constants/translations/ua/my-resources-page.json
  src/containers/my-resources/add-resource-modal/AddResourceModal.tsx
  src/containers/my-resources/attachments-container/AttachmentsContainer.constants.tsx
  src/containers/my-resources/attachments-container/AttachmentsContainer.styles.ts
  src/containers/my-resources/attachments-container/AttachmentsContainer.tsx
  src/containers/my-resources/edit-attachment-modal/EditAttachmentModal.constants.ts
  src/containers/my-resources/edit-attachment-modal/EditAttachmentModal.styles.ts
  src/containers/my-resources/edit-attachment-modal/EditAttachmentModal.tsx
  src/services/resource-service.ts
  src/types/attachment/interfaces/attachment.interface.ts
  tests/unit/containers/my-resources/EditAttachmentModal.spec.jsx
Labels: Frontend part, feature

#1239 Added message sending to the backend in chat dialog
  src/constants/translations/en/chat.json
  src/constants/translations/ua/chat.json
  src/containers/find-offer/offer-container/OfferContainer.tsx
  src/containers/offer-page/chat-dialog-window/ChatDialogWindow.tsx
  src/pages/find-offers/FindOffers.tsx
  src/services/chat-service.ts
  src/types/chat/types/chat.types.ts
  src/types/offer/interfaces/offer.interfaces.ts
Labels: Frontend part, feature

#1248 Changed description text on the home page welcoming block at tutor-home-page.
  src/constants/translations/en/tutor-home-page.json
  src/constants/translations/ua/tutor-home-page.json
Labels: bug, Frontend part

#1251 Changed wrong content on the student's home page FAQ
  src/constants/translations/en/student-home-page.json
  src/constants/translations/ua/student-home-page.json
  src/containers/student-home-page/faq/accordionItems.ts
  tests/unit/containers/student-home-page/faq/Faq.spec.jsx
Labels: bug, Frontend part

#1253 implemented rename functionality for resource category
  src/constants/request.ts
  src/containers/my-resources/categories-container/CategoriesContainer.constansts.tsx
  src/containers/my-resources/categories-container/CategoriesContainer.tsx
  src/containers/my-resources/rename-input/RenameInput.styles.ts
  src/containers/my-resources/rename-input/RenameInput.tsx
  src/services/resource-service.ts
  src/types/my-resources/interfaces/myResources.interface.ts
  tests/unit/containers/my-resources/RenameInput.spec.jsx
Labels: Frontend part, feature

#1254 Added test for CreateOrEditQuestion
  tests/unit/pages/create-or-edit-question/CreateOrEditQuestion.spec.jsx
Labels: Frontend part, test

#1258 Optimized OfferDetails.spec.jsx
  tests/unit/pages/offer-details/OfferDetails.spec.jsx
Labels: bug, Frontend part, test

#1290 Fixed the placeholder on tutor’s home page. Text was not corresponded to the mockup in the search input field
  src/constants/translations/en/tutor-home-page.json
  src/constants/translations/ua/tutor-home-page.json
Labels: bug, Frontend part, UI/Usability

#1257 Implemented tooltip for attachments description in attachment table
  src/components/icon-extension-with-title/IconExtensionWithTitle.styles.ts
  src/components/icon-extension-with-title/IconExtensionWithTitle.tsx
  src/components/title-with-description/TitleWithDescription.tsx
  src/constants/translations/en/my-resources-page.json
  src/constants/translations/ua/my-resources-page.json
  src/containers/my-resources/add-questions/AddQuestions.constants.tsx
  src/containers/my-resources/add-resource-modal/AddResourceModal.tsx
  src/containers/my-resources/attachments-container/AttachmentsContainer.constants.tsx
  src/containers/my-resources/attachments-container/AttachmentsContainer.styles.ts
  src/containers/my-resources/edit-attachment-modal/EditAttachmentModal.tsx
  src/containers/my-resources/questions-container/QuestionsContainer.constants.tsx
  tests/unit/containers/AttachmentsContainer/AttachmentsContainer.spec.jsx
Labels: Frontend part, feature

#1291 Test for FilterSelector
  tests/unit/components/filter-selector/FilterSelector.spec.jsx
Labels: Frontend part, test

#1274 Changed description text on the student home page welcoming block
  src/constants/translations/en/student-home-page.json
  src/constants/translations/ua/student-home-page.json
Labels: bug, Frontend part

#1287 Fixed incorrect title display on Category deletion modal (My resources page)
  src/constants/translations/en/my-resources-page.json
  src/constants/translations/ua/my-resources-page.json
Labels: bug, Frontend part, UI/Usability

#1288 Added description for popular categories
  src/constants/translations/en/tutor-home-page.json
  src/constants/translations/ua/tutor-home-page.json
  src/pages/tutor-home/TutorHome.tsx
Labels: bug, Frontend part

#1289 Changed the description text on the student's home page How it works block
  src/constants/translations/en/student-home-page.json
  src/constants/translations/ua/student-home-page.json
Labels: bug, Frontend part

#1292 Changed description in popular categories block on the student's home page
  src/constants/translations/en/student-home-page.json
  src/constants/translations/ua/student-home-page.json
Labels: bug, Frontend part

#1294 Fixed Find Offers search request
  src/components/find-block/FindBlock.jsx
Labels: bug, Frontend part

#1296 Changed "test" to "it" in some folders
  tests/unit/components/app-auto-complete/AppAutoComplete.spec.jsx
  tests/unit/components/app-range/AppRange.spec.jsx
  tests/unit/components/appPopover/AppPopover.spec.jsx
  tests/unit/components/clickable-image/ClickableImage.spec.jsx
  tests/unit/components/file-component/FileComponent.spec.jsx
  tests/unit/components/link-component/LinkComponent.spec.jsx
  tests/unit/components/not-found-results/NotFoundResults.spec.jsx
  tests/unit/components/sidebar-content-box/SidebarContentBox.spec.jsx
  tests/unit/components/sidebar-image-grid/SidebarImageGrid.spec.jsx
  tests/unit/containers/about-chat-sidebar/AboutChatSidebar.spec.jsx
Labels: Frontend part, test

#1301 Duplicated search request data to Find Offers input
  src/components/search-filter-input/SearchFilterInput.tsx
Labels: bug, Frontend part

#1298 implemented creating question in new quiz page
  src/components/question-editor/QuestionEditor.constants.tsx
  src/components/question-editor/QuestionEditor.styles.ts
  src/components/question-editor/QuestionEditor.tsx
  src/components/question/Question.styles.ts
  src/components/question/Question.tsx
  src/containers/my-quizzes/edit-quiz-container/EditQuizContainer.constants.ts
  src/containers/my-quizzes/edit-quiz-container/EditQuizContainer.styles.ts
  src/containers/my-quizzes/edit-quiz-container/EditQuizContainer.tsx
  src/containers/my-resources/add-questions/AddQuestions.constants.tsx
  src/containers/my-resources/add-questions/AddQuestions.tsx
  src/containers/my-resources/create-or-edit-question-modal/CreateOrEditQuestionModal.styles.ts
  src/containers/my-resources/create-or-edit-question-modal/CreateOrEditQuestionModal.tsx
  src/containers/my-resources/questions-container/QuestionsContainer.constants.tsx
  src/containers/my-resources/questions-container/QuestionsContainer.tsx
  src/hooks/use-form.tsx
  src/pages/create-or-edit-question/CreateOrEditQuestion.styles.ts
  src/pages/create-or-edit-question/CreateOrEditQuestion.tsx
  src/services/resource-service.ts
  src/types/questions/interfaces/questions.interface.ts
  src/types/quizzes/interfaces/quizzes.interface.ts
  tests/unit/components/question-editor/QuestionEditor.spec.jsx
  tests/unit/containers/my-resources/CreateOrEditQuestionModal.spec.jsx
Labels: Frontend part, feature

#1293 Implemented category adding functionality
  src/constants/request.ts
  src/constants/translations/en/common.json
  src/constants/translations/en/my-resources-page.json
  src/constants/translations/ua/common.json
  src/constants/translations/ua/my-resources-page.json
  src/containers/my-resources/add-categories-modal/AddCategories.styles.ts
  src/containers/my-resources/add-categories-modal/AddCategoriesModal.constants.ts
  src/containers/my-resources/add-categories-modal/AddCategoriesModal.tsx
  src/containers/my-resources/categories-container/CategoriesContainer.style.ts
  src/containers/my-resources/categories-container/CategoriesContainer.tsx
  src/pages/create-or-edit-question/CreateOrEditQuestion.styles.ts
  src/pages/create-or-edit-question/CreateOrEditQuestion.tsx
  src/services/resource-service.ts
  src/types/categories/interfaces/categories.interfaces.ts
  src/types/common/enums/common.enums.ts
  tests/unit/containers/my-resources/CreateAttachmentModal.spec.jsx
Labels: Frontend part, feature

#1210 Add categories for resources
  src/containers/my-quizzes/QuizzesContainer.tsx
  src/containers/my-resources/add-resource-with-input/AddResourceWithInput.styles.ts
  src/containers/my-resources/add-resource-with-input/AddResourceWithInput.tsx
  src/containers/my-resources/attachments-container/AttachmentsContainer.tsx
  src/containers/my-resources/categories-container/CategoriesContainer.tsx
  src/containers/my-resources/lessons-container/LessonsContainer.tsx
  src/containers/my-resources/questions-container/QuestionsContainer.tsx
  tests/unit/containers/my-resources/AddResourceWithInput.spec.jsx
Labels: Frontend part, feature

#1302 Added category field for all resources tabs
  src/containers/my-quizzes/QuizzesContainer.constants.tsx
  src/containers/my-quizzes/QuizzesContainer.styles.ts
  src/containers/my-resources/lessons-container/LessonsContainer.constants.tsx
  src/containers/my-resources/lessons-container/LessonsContainer.styles.ts
  src/containers/my-resources/questions-container/QuestionsContainer.constants.tsx
  src/containers/my-resources/questions-container/QuestionsContainer.styles.ts
  src/pages/lesson-details/LessonDetails.constants.tsx
  src/types/my-resources/interfaces/myResources.interface.ts
  src/types/quizzes/interfaces/quizzes.interface.ts
  tests/unit/containers/AttachmentsContainer/AttachmentsContainer.spec.jsx
  tests/unit/containers/my-quizzes/QuizzesContainer.spec.jsx
  tests/unit/containers/my-resources/LessonsContainer.spec.jsx
  tests/unit/containers/my-resources/QuestionsContainer.spec.jsx
Labels: Frontend part, feature

#1316 Added new-course route
  src/constants/translations/en/breadcrumbs.json
  src/constants/translations/ua/breadcrumbs.json
  src/pages/create-course/CreateCourse.tsx
  src/router/constants/authRoutes.ts
  src/router/constants/crumbs.ts
  src/router/routes/authRouter.tsx
  tests/unit/pages/create-course/CreateCourse.spec.jsx
Labels: Frontend part, feature, component, Tutor

#1313 Fixed attachments duplication on upload
  src/containers/add-documents/AddDocuments.tsx
  src/containers/my-resources/attachments-container/AttachmentsContainer.tsx
Labels: bug, Frontend part

#1317 Fixed overlapped email input field on the forgot password form
  src/containers/guest-home-page/forgot-password/ForgotPassword.jsx
  src/containers/guest-home-page/forgot-password/ForgotPassword.styles.js
Labels: bug, Frontend part

#1327 Added table.json to ua
  src/constants/translations/ua/index.ts
  src/constants/translations/ua/table.json
Labels: bug, Frontend part

#1328 Created cookie-policy-page.json for ua translation
  src/constants/translations/ua/cookie-policy-page.json
  src/constants/translations/ua/index.ts
Labels: bug, Frontend part

#1329 Created translation for signup
  src/constants/translations/ua/index.ts
  src/constants/translations/ua/signup.json
Labels: bug, Frontend part

#1331 Created errors.json ua translation
  src/constants/translations/ua/errors.json
  src/constants/translations/ua/index.ts
Labels: Frontend part

#1333 Created admin.json ua translation
  src/constants/translations/ua/admin.json
  src/constants/translations/ua/index.ts
Labels: Frontend part, admin

#1336 Added ua translation for user-table
  src/constants/translations/ua/index.ts
  src/constants/translations/ua/user-table.json
Labels: bug, Frontend part

#1337 Created ua translation to step.json
  src/constants/translations/ua/index.ts
  src/constants/translations/ua/step.json
Labels: bug, Frontend part

#1342 implemented components for quiz view page
  src/components/tab-navigation/TabNavigation.style.ts
  src/components/tab-navigation/TabNavigation.tsx
  src/components/tab/Tab.tsx
  src/containers/my-quizzes/edit-quiz-container/EditQuizContainer.tsx
  src/containers/my-quizzes/selectable-question-quiz-view/SelectableQuestion.styles.ts
  src/containers/my-quizzes/selectable-question-quiz-view/SelectableQuestionQuizView.tsx
  src/containers/my-quizzes/selectable-question/SelectableQuestion.styles.ts
  src/containers/my-quizzes/selectable-question/SelectableQuestion.tsx
  src/containers/my-quizzes/view-quiz-container/ViewQuizContainer.styles.ts
  src/containers/my-quizzes/view-quiz-container/ViewQuizContainer.tsx
  src/containers/my-resources/create-or-edit-question-modal/CreateOrEditQuestionModal.tsx
  src/pages/new-quiz/NewQuiz.constants.tsx
  src/pages/new-quiz/NewQuiz.tsx
  tests/unit/pages/my-quizzes/SelectableQuestion.spec.jsx
  tests/unit/pages/my-quizzes/SelectableQuestionQuizView.spec.jsx
Labels: Frontend part, feature

#1343 Added new course btn, filter, sort by and search
  src/constants/translations/en/my-courses-page.json
  src/constants/translations/ua/my-courses-page.json
  src/containers/find-course/courses-filter-bar/CoursesFilterBar.styles.ts
  src/containers/find-course/courses-filter-bar/CoursesFilterBar.tsx
  src/containers/find-course/courses-filter-block/CoursesFilterBlock.constants.ts
  src/containers/my-courses/add-course-with-input/AddCourseWithInput.styles.ts
  src/containers/my-courses/add-course-with-input/AddCourseWithInput.tsx
  src/pages/find-offers/FindOffers.tsx
  src/pages/my-courses/MyCourses.styles.ts
  src/pages/my-courses/MyCourses.tsx
  src/services/offer-service.ts
  src/types/findOffers/interfaces/findOffers.interfaces.ts
  tests/unit/containers/find-course/courses-filter-bar/CoursesFilterBar.spec.jsx
  tests/unit/containers/my-courses/add-course-with-input/AddCourseWithInput.spec.jsx
Labels: Frontend part, feature

#1345 Implemented buttons for new page route
  src/pages/create-course/CreateCourse.styles.ts
  src/pages/create-course/CreateCourse.tsx
  tests/unit/pages/create-course/CreateCourse.spec.jsx
Labels: Frontend part, feature

#1347 Fixed unlimited renders in Edit Lesson page
  src/pages/create-or-edit-lesson/CreateOrEditLesson.constants.tsx
  src/pages/create-or-edit-lesson/CreateOrEditLesson.tsx
Labels: bug

#1348 Added banner functionality for newCourse
  src/assets/img/tutor-my-courses/add-image-icon.svg
  src/assets/img/tutor-my-courses/banner-pattern.png
  src/constants/translations/en/my-courses-page.json
  src/constants/translations/ua/my-courses-page.json
  src/containers/add-course-banner/AddCourseBanner.constants.tsx
  src/containers/add-course-banner/AddCourseBanner.styles.ts
  src/containers/add-course-banner/AddCourseBanner.tsx
  src/pages/create-course/CreateCourse.tsx
  tests/unit/containers/add-course-banner/AddCourseBanner.spec.jsx
Labels: Frontend part, feature, Tutor

#1354 Added next and back buttons on questions view in quiz
  src/constants/translations/ua/common.json
  src/containers/my-quizzes/selectable-question-quiz-view/SelectableQuestion.styles.ts
  src/containers/my-quizzes/selectable-question-quiz-view/SelectableQuestionQuizView.tsx
  tests/unit/pages/my-quizzes/SelectableQuestionQuizView.spec.jsx
Labels: Frontend part, feature

#1355 Fixed style breadcrumb last element position
  src/containers/layout/app-breadcrumbs/AppBreadCrumbs.styles.ts
Labels: bug, Frontend part

#1353 Added successDeletion fields to translations
  src/constants/translations/en/my-resources-page.json
  src/constants/translations/ua/my-resources-page.json
Labels: bug, Frontend part

#1351 Fixed crumbs for new course
  src/router/routes/authRouter.tsx
Labels: Frontend part, hotfix

#1360 added contributing files for client
  CONTRIBUTING.md
  CONTRIBUTING_UA.md
Labels: documentation

#1344 Categorization to all resources
  src/components/filter-selector/FilterSelector.tsx
  src/containers/my-quizzes/QuizzesContainer.tsx
  src/containers/my-resources/add-resource-with-input/AddResourceWithInput.tsx
  src/containers/my-resources/attachments-container/AttachmentsContainer.tsx
  src/containers/my-resources/lessons-container/LessonsContainer.tsx
  src/types/services/types/services.types.ts
Labels: Frontend part, feature
