Repository ita-social-projects/SpaceToStudy-Client, pull requests merged in 2023-12, with the labels that each got.

#1431 Added edit question on create or edit question page
  src/components/question-editor/QuestionEditor.tsx
  src/constants/translations/en/breadcrumbs.json
  src/constants/translations/en/my-resources-page.json
  src/constants/translations/ua/breadcrumbs.json
  src/constants/translations/ua/my-resources-page.json
  src/containers/my-quizzes/create-or-edit-quiz-container/CreateOrEditQuizContainer.tsx
  src/containers/my-quizzes/create-or-edit-quiz-question/CreateOrEditQuizQuestion.tsx
  src/containers/my-resources/questions-container/QuestionsContainer.constants.tsx
  src/containers/my-resources/questions-container/QuestionsContainer.tsx
  src/hooks/use-form.tsx
  src/pages/create-or-edit-question/CreateOrEditQuestion.constants.tsx
  src/pages/create-or-edit-question/CreateOrEditQuestion.tsx
  src/router/constants/authRoutes.ts
  src/router/constants/crumbs.ts
  src/router/routes/authRouter.tsx
  src/services/resource-service.ts
  src/types/questions/interfaces/questions.interface.ts
  tests/unit/components/question-editor/QuestionEditor.spec.jsx
Labels: Frontend part, feature

#1465 Created save logic for course
  src/constants/request.ts
  src/constants/translations/en/my-courses-page.json
  src/constants/translations/ua/my-courses-page.json
  src/containers/course-section/CourseSectionContainer.tsx
  src/pages/create-course/CreateCourse.constants.tsx
  src/pages/create-course/CreateCourse.tsx
  src/services/course-service.ts
  src/services/resource-service.ts
  src/types/course/interfaces/course.interface.ts
  tests/unit/containers/course-section/CourseSectionContainer.spec.jsx
  tests/unit/pages/create-course/CreateCourse.spec.jsx
Labels: Frontend part, feature

#1464 Course dropdown menu and delete
  src/components/course-card/CourseCard.styles.ts
  src/components/course-card/CourseCard.tsx
  src/constants/request.ts
  src/constants/translations/en/my-courses-page.json
  src/constants/translations/ua/my-courses-page.json
  src/containers/my-courses/my-courses-container/MyCorsesCardsList.tsx
  src/pages/my-courses/MyCourses.tsx
  src/services/course-service.ts
  tests/unit/components/course-card/CourseCard.spec.jsx
Labels: Frontend part, feature

#1456 Disable enroll user for offer if user is already enrolled
  src/containers/my-cooperations/accept-cooperation-modal/AcceptCooperationModal.tsx
  src/containers/offer-details/enroll-offer/EnrollOffer.tsx
  src/pages/offer-details/OfferDetails.constants.ts
  src/pages/offer-details/OfferDetails.tsx
  src/services/offer-service.ts
  src/types/cooperation/interfaces/cooperation.interface.ts
  src/types/findOffers/interfaces/findOffers.interfaces.ts
  src/types/offer/interfaces/offer.interfaces.ts
  tests/unit/containers/my-cooperations/accept-cooperation-modal/AcceptCooperationModal.spec.jsx
  tests/unit/containers/offer-details/enroll-offer/EnrollOffer.spec.jsx
  tests/unit/pages/offer-details/OfferDetails.spec.constants.js
  tests/unit/pages/offer-details/OfferDetails.spec.jsx
Labels: Frontend part, feature

#1457 Implemented courses drawer with filters
  src/constants/translations/en/my-courses-page.json
  src/constants/translations/ua/my-courses-page.json
  src/containers/my-courses/add-course-with-input/AddCourseWithInput.tsx
  src/containers/my-courses/courses-filters-drawer/CoursesFiltersDrawer.styles.ts
  src/containers/my-courses/courses-filters-drawer/CoursesFiltersDrawer.tsx
  src/services/course-service.ts
  src/styles/app-theme/app.pallete.ts
  src/types/course/interfaces/course.interface.ts
Labels: Frontend part, feature, component

#1462 Removed course banner
  src/containers/add-course-banner/AddCourseBanner.constants.tsx
  src/containers/add-course-banner/AddCourseBanner.styles.ts
  src/containers/add-course-banner/AddCourseBanner.tsx
  src/pages/create-course/CreateCourse.tsx
  tests/unit/containers/add-course-banner/AddCourseBanner.spec.jsx
Labels: Frontend part, component, Tutor

#1459 Fixed quiz setting item
  src/constants/translations/en/my-resources-page.json
  src/constants/translations/ua/my-resources-page.json
  src/containers/my-quizzes/quiz-settings-container/QuizSettingsContainer.tsx
Labels: bug, Frontend part, Tutor

#1480 Implemented course card duplication
  src/components/course-card/CourseCard.tsx
  src/components/subject-level-chips/SubjectLevelChips.tsx
  src/constants/translations/en/my-courses-page.json
  src/constants/translations/ua/my-courses-page.json
  src/containers/my-courses/my-courses-container/MyCorsesCardsList.tsx
  src/pages/my-courses/MyCourses.tsx
  src/types/course/interfaces/course.interface.ts
  tests/unit/components/course-card/CourseCard.spec.jsx
  tests/unit/pages/my-courses/MyCourses.spec.jsx
Labels: Frontend part, feature

#1471 Disabled sending messages from me to my offer and moving closed offer to draft
  src/containers/find-offer/offer-container/OfferContainer.tsx
  src/containers/offer-page/create-or-edit-offer/CreateOrEditOffer.tsx
Labels: bug, Frontend part

#1484 Fixed the title and description on new or edit lesson page
  src/pages/create-or-edit-lesson/CreateOrEditLesson.styles.ts
  src/pages/create-or-edit-lesson/CreateOrEditLesson.tsx
Labels: bug, Frontend part, Tutor

#1483 Fixed required fields not marked with "*" character in create offer/request modal
  src/constants/translations/en/offer-page.json
  src/constants/translations/ua/offer-page.json
  src/containers/offer-page/specialization-block/SpecializationBlock.tsx
  src/containers/offer-page/teaching-block/TeachingBlock.tsx
  tests/unit/containers/offer-page/create-offer/CreateOffer.spec.jsx
  tests/unit/containers/offer-page/edit-offer/EditOffer.spec.jsx
Labels: bug, Frontend part, feature

#1466 Fixed the send button is shifted to the bottom
  src/containers/chat/chat-text-area/ChatTextArea.styles.ts
Labels: bug, Frontend part, UI/Usability, severity: minor, priority: low

#1461 Fixed counter of matches is active when hovering in the 'search in chat' block
  src/components/icons-with-counter/IconsWithCounter.style.ts
Labels: bug, Frontend part, severity: minor, Functional, priority: low

#1460 Fixed color of selected message bubble with corresponding search request
  src/components/message/Message.styles.ts
  src/components/message/Message.tsx
Labels: bug, Frontend part, UI/Usability, priority: low, severity: trivial

#1468 fixed reopen modal after close by close button
  src/containers/my-quizzes/create-or-edit-quiz-container/CreateOrEditQuizContainer.tsx
  src/containers/my-quizzes/create-or-edit-quiz-question/CreateOrEditQuizQuestion.tsx
  src/context/modal-context.tsx
Labels: bug, Frontend part

#1454 Fixed question description and added util for icons
  src/containers/my-resources/questions-container/QuestionsContainer.constants.tsx
  src/utils/check-icons.tsx
Labels: Frontend part, feature

#1503 Fixed test SearchAutocomplete
  src/containers/offer-page/faq-block/FaqBlock.tsx
  tests/test-utils.jsx
  tests/unit/components/search-autocomplete/SearchAutocomplete.spec.jsx
  tests/unit/containers/my-quizzes/ViewQuizContainer.spec.jsx
  tests/unit/pages/my-courses/MyCourses.spec.jsx
  tests/unit/pages/my-quizzes/ScrollQuestionsQuizView.spec.jsx
Labels: test

#1487 Implemented course card edit button
  src/components/course-card/CourseCard.tsx
  src/constants/request.ts
  src/constants/translations/en/breadcrumbs.json
  src/constants/translations/en/my-courses-page.json
  src/constants/translations/ua/breadcrumbs.json
  src/constants/translations/ua/my-courses-page.json
  src/containers/course-section/CourseSectionContainer.tsx
  src/containers/course-sections-list/CourseSectionsList.tsx
  src/pages/create-course/CreateCourse.constants.tsx
  src/pages/create-course/CreateCourse.tsx
  src/router/constants/authRoutes.ts
  src/router/constants/crumbs.ts
  src/router/routes/authRouter.tsx
  src/services/course-service.ts
  src/types/course/interfaces/course.interface.ts
  tests/unit/components/course-card/CourseCard.spec.jsx
Labels: Frontend part, feature

#1511 Update README.md
  README.md
Labels: documentation

#1486 Fixed price range
  src/containers/find-offer/offer-filter-block/OfferFilterBlock.tsx
  src/containers/find-offer/offer-filter-block/offer-filter-list/OfferFilterList.tsx
  src/pages/find-offers/FindOffers.tsx
  src/types/findOffers/interfaces/findOffers.interfaces.ts
  tests/unit/containers/find-offer/offer-filter-block/OfferFilterBlock.spec.jsx
Labels: bug, Frontend part

#1507 Created divider in my resources page
  src/components/tab-navigation/TabNavigation.styles.ts
  src/components/tab-navigation/TabNavigation.tsx
  src/pages/my-resources/MyResources.constants.tsx
  src/pages/my-resources/MyResources.styles.ts
  src/pages/my-resources/MyResources.tsx
Labels: Frontend part

#1485 Added add category button to dropdown
  src/components/dropdown-add-btn/DropdownButton.styles.ts
  src/components/dropdown-add-btn/DropdownButton.tsx
  src/containers/category-dropdown/CategoryDropdown.styles.tsx
  src/containers/category-dropdown/CategoryDropdown.tsx
Labels: Frontend part, feature

#1506 Changed course and lesson error messages
  src/constants/translations/en/errors.json
  src/constants/translations/ua/errors.json
  src/containers/my-quizzes/create-or-edit-quiz-container/CreateOrEditQuizContainer.tsx
  src/containers/my-quizzes/create-or-edit-quiz-question/CreateOrEditQuizQuestion.tsx
  src/context/snackbar-context.tsx
  src/pages/create-course/CreateCourse.tsx
  src/pages/create-or-edit-lesson/CreateOrEditLesson.tsx
  src/pages/create-or-edit-question/CreateOrEditQuestion.tsx
  src/utils/error-with-message.tsx
  tests/unit/utils/error-with-message.spec.jsx
Labels: bug, Frontend part

#1508 By click on quiz or question redirected on edit page
  src/containers/my-quizzes/QuizzesContainer.constants.tsx
  src/containers/my-resources/questions-container/QuestionsContainer.constants.tsx
  src/containers/my-resources/questions-container/QuestionsContainer.styles.ts
Labels: Frontend part, feature

#1501 removed last updates field on mobile for resources table
  src/containers/my-quizzes/QuizzesContainer.constants.tsx
  src/containers/my-resources/attachments-container/AttachmentsContainer.constants.tsx
  src/containers/my-resources/categories-container/CategoriesContainer.constansts.tsx
  src/containers/my-resources/categories-container/CategoriesContainer.style.ts
  src/containers/my-resources/lessons-container/LessonsContainer.constants.tsx
Labels: Frontend part

#1504 Feature/1498/create responsivity for my resources tabs
  src/components/tab-navigation/TabNavigation.styles.ts
  src/components/tab-navigation/TabNavigation.tsx
  src/components/tab/Tab.styles.ts
  src/components/tab/Tab.tsx
  src/pages/my-resources/MyResources.styles.ts
  src/pages/my-resources/MyResources.tsx
Labels: Frontend part, feature

#1510 Implemented courses search logic
  src/containers/my-courses/add-course-with-input/AddCourseWithInput.tsx
  src/pages/my-courses/MyCourses.tsx
  src/services/course-service.ts
  src/types/course/interfaces/course.interface.ts
Labels: Frontend part, feature
