Repository ita-social-projects/SpaceToStudy-Client, pull requests merged in 2023-01, with the labels that each got.

#381 added loader to storybook
  package.json
  src/stories/Loader.stories.js
Labels: good first issue, Frontend part, feature

#392 deleted experience and add documents steps
  src/components/step-wrapper/StepWrapper.js
  src/components/step-wrapper/StepWrapper.styles.js
  src/constants/translations/en/become-tutor.json
  src/containers/tutor-home-page/become-a-tutor/BecomeATutor.js
  src/containers/tutor-home-page/constants.js
  src/containers/tutor-home-page/experience-step/ExperienceStep.js
  src/containers/tutor-home-page/experience-step/experience-step.styles.js
  src/containers/tutor-home-page/general-info/GeneralInfo.js
  tests/unit/containers/mentor-home-page/become-a-tutor/BecomeATutor.spec.js
  tests/unit/containers/mentor-home-page/become-a-tutor/experience-step/ExperienceStep.spec.js
Labels: bug

#395 added my profile button
  src/constants/translations/en/header.json
  src/router/constants/studentRoutes.js
Labels: good first issue, Frontend part, feature

#397 Modified header, added header for tutor
  src/constants/translations/en/header.json
  src/constants/translations/ua/header.json
  src/containers/layout/navbar/NavBar.js
  src/containers/navigation-icons/NavigationIcons.js
  src/containers/navigation-icons/user-icons/UserIcons.js
  src/router/constants/tutorRoutes.js
  tests/unit/containers/navigation-icons/user-icons/UserIcons.spec.js
Labels: Frontend part, feature

#400 Change steper data storing to context
  src/components/step-wrapper/StepWrapper.js
  src/containers/tutor-home-page/add-photo/AddPhoto.js
  src/containers/tutor-home-page/become-a-tutor/BecomeATutor.js
  src/containers/tutor-home-page/constants.js
  src/containers/tutor-home-page/general-info/GeneralInfo.js
  src/context/step-context.js
  src/hooks/use-steps.js
  tests/unit/components/step-wrapper/StepWrapper.spec.js
  tests/unit/containers/mentor-home-page/add-photo/AddPhoto.spec.js
  tests/unit/containers/mentor-home-page/become-a-tutor/BecomeATutor.spec.js
Labels: Frontend part

#384 Signup and signin with google
  public/index.html
  src/components/hash-link/HashLink.js
  src/constants/request.js
  src/constants/translations/en/errors.json
  src/containers/guest-home-page/forgot-password/ForgotPassword.styles.js
  src/containers/guest-home-page/google-button/GoogleButton.js
  src/containers/guest-home-page/google-button/GoogleButton.styles.js
  src/containers/guest-home-page/google-login/GoogleLogin.js
  src/containers/guest-home-page/google-login/GoogleLogin.styles.js
  src/containers/guest-home-page/login-dialog/LoginDialog.js
  src/containers/guest-home-page/login-dialog/LoginDialog.styles.js
  src/containers/guest-home-page/login-form/LoginForm.styles.js
  src/containers/guest-home-page/signup-dialog/SignupDialog.js
  src/containers/guest-home-page/signup-dialog/SignupDialog.styles.js
  src/containers/guest-home-page/signup-form/SignupForm.styles.js
  src/redux/reducer.js
  src/services/auth-service.js
  src/styles/app-theme/app.textfield.js
  src/utils/hash-scroll.js
  tests/unit/containers/guest-home-page/WhatCanYouDo.spec.js
  tests/unit/containers/guest-home-page/cards-with-button/CardsWithButton.spec.js
  tests/unit/containers/guest-home-page/forgot-password/ForgotPassword.spec.js
  tests/unit/containers/guest-home-page/google-login/GoogleLogin.spec.js
  tests/unit/containers/guest-home-page/login-dialog/LoginDialog.spec.js
  tests/unit/containers/guest-home-page/signup-dialog/SignupDialog.spec.js
  tests/unit/containers/navbar/NavBar.spec.js
  tests/unit/containers/navigation-icons/NavigationIcons.spec.js
  tests/unit/context/modal-context.spec.js
  tests/unit/context/snackbar-context.spec.js
Labels: Frontend part, feature

#398 Changed images for Login, Signup student and tutor.
  src/assets/img/login-dialog/login.png
  src/assets/img/login-dialog/login.svg
  src/assets/img/signup-dialog/student.png
  src/assets/img/signup-dialog/student.svg
  src/assets/img/signup-dialog/tutor.png
  src/assets/img/signup-dialog/tutor.svg
  src/containers/guest-home-page/login-dialog/LoginDialog.js
  src/containers/guest-home-page/login-dialog/LoginDialog.styles.js
  src/containers/guest-home-page/signup-dialog/SignupDialog.js
  src/containers/guest-home-page/signup-dialog/SignupDialog.styles.js
Labels: Frontend part, feature

#403 Create "Subjects" page for stepper
  src/assets/img/tutor-home-page/become-tutor/study-category.svg
  src/components/app-chip/AppChip.js
  src/components/app-chips-list/AppChipList.js
  src/components/app-chips-list/AppChipsList-styles.js
  src/components/autocoplete/Autocomplete.js
  src/components/step-wrapper/StepWrapper.styles.js
  src/constants/translations/en/become-tutor.json
  src/containers/tutor-home-page/become-a-tutor/BecomeATutor.js
  src/containers/tutor-home-page/subjects/Subjects.js
  src/containers/tutor-home-page/subjects/Subjects.styles.js
  src/containers/tutor-home-page/subjects/constants.js
  src/context/step-context.js
  src/pages/tutor-home/TutorHome.js
  tests/unit/components/app-chips/AppChipsList.spec.js
  tests/unit/components/autocoplete/Autocomplete.spec.js
  tests/unit/containers/mentor-home-page/become-a-tutor/BecomeATutor.spec.js
  tests/unit/containers/mentor-home-page/become-a-tutor/subjects/Subjects.spec.js
Labels: Frontend part, feature

#402 added an empty page for a student profile, fixed routes
  src/pages/find-tutor/FindTutor.js
  src/pages/student-profile/StudentProfile.js
  src/router/constants/studentRoutes.js
  src/router/routes/StudentRoutes.js
Labels: good first issue, Frontend part, feature
