Repository ita-social-projects/SpaceToStudy-Client, pull requests merged in 2023-08, with the labels that each got.

#949 Implemented left side of chat
  package-lock.json
  package.json
  src/components/app-drawer/AppDrawer.styles.ts
  src/components/app-text-field/AppTextField.tsx
  src/components/user-profile-info/UserProfileInfo.tsx
  src/constants/request.ts
  src/constants/translations/en/chat.json
  src/constants/translations/en/index.ts
  src/constants/translations/ua/chat.json
  src/constants/translations/ua/index.ts
  src/containers/chat/chat-item/ChatItem.styles.ts
  src/containers/chat/chat-item/ChatItem.tsx
  src/containers/chat/list-of-users-with-search/ListOfUsersWithSearch.constants.ts
  src/containers/chat/list-of-users-with-search/ListOfUsersWithSearch.styles.ts
  src/containers/chat/list-of-users-with-search/ListOfUsersWithSearch.tsx
  src/containers/my-cooperations/cooperations-container/CooperationContainer.constants.tsx
  src/containers/my-offers/my-offers-container/MyOffersContainer.constants.tsx
  src/pages/chat/Chat.styles.ts
  src/pages/chat/Chat.tsx
  src/services/chat-service.ts
  src/styles/app-theme/app.pallete.ts
  src/types/chat/chat.index.ts
  src/types/chat/interfaces/chat.interfaces.ts
  src/types/index.ts
  src/types/utils/utils-interfaces/utils.interface.ts
  src/types/utils/utils.index.ts
  src/utils/helper-functions.tsx
  tests/unit/components/message/Message.spec.jsx
  tests/unit/containers/chat/chat-item/ChatItem.spec.jsx
  tests/unit/containers/chat/list-of-users-with-search/ListOfUsersWithSearch.spec.jsx
  tests/unit/containers/chat/list-of-users-with-search/MockChat.spec.constants.js
  tests/unit/pages/chat/Chat.spec.jsx
Labels: Frontend part, feature

#977 Test for MyOffersCard container
  tests/unit/containers/my-offers/my-offers-card/MyOffersCard.spec.jsx
Labels: Frontend part, feature, test

#976 Implemented lessons list on the page "My resources"
  src/components/confirm-dialog/ConfirmDialog.tsx
  src/components/enhanced-table/EnhancedTable.tsx
  src/components/enhanced-table/enhanced-table-row/EnhancedTableRow.jsx
  src/components/user-profile-info/UserProfileInfo.tsx
  src/constants/request.ts
  src/constants/translations/en/breadcrumbs.json
  src/constants/translations/en/common.json
  src/constants/translations/en/my-resources-page.json
  src/constants/translations/ua/breadcrumbs.json
  src/constants/translations/ua/common.json
  src/constants/translations/ua/my-resources-page.json
  src/containers/chat/chat-item/ChatItem.tsx
  src/containers/my-cooperations/cooperation-offer-toolbar/CooperationOfferToolbar.tsx
  src/containers/my-cooperations/cooperations-container/CooperationContainer.constants.tsx
  src/containers/my-cooperations/cooperations-container/CooperationContainer.tsx
  src/containers/my-offers/my-offers-container/MyOffersContainer.constants.tsx
  src/containers/my-offers/my-offers-container/MyOffersContainer.tsx
  src/containers/my-resources/lessons-container/LessonsContainer.constants.tsx
  src/containers/my-resources/lessons-container/LessonsContainer.styles.ts
  src/containers/my-resources/lessons-container/LessonsContainer.tsx
  src/hooks/use-axios.tsx
  src/pages/guest-home-page/GuestHome.tsx
  src/pages/my-lesson/MyLesson.tsx
  src/pages/my-offers/MyOffers.tsx
  src/pages/my-resources/MyResources.constants.tsx
  src/pages/my-resources/MyResources.styles.ts
  src/pages/my-resources/MyResources.tsx
  src/pages/new-lesson/NewLesson.tsx
  src/router/constants/authRoutes.ts
  src/router/constants/crumbs.ts
  src/router/constants/tutorRoutes.ts
  src/router/routes/authRouter.tsx
  src/services/resource-service.ts
  src/types/components/enhanced-table/enhancedTable.interface.ts
  src/types/index.ts
  src/types/my-cooperations/interfaces/myCooperations.interfaces.ts
  src/types/my-resources/interfaces/myResources.interface.ts
  src/types/my-resources/myResources.index.ts
  src/utils/helper-functions.tsx
  tests/unit/components/enhanced-table/EnhancedTable.spec.jsx
  tests/unit/components/enhanced-table/enhanced-table-head/EnhancedTableHead.spec.jsx
  tests/unit/components/enhanced-table/enhanced-table-row/EnhancedTableRow.spec.jsx
  tests/unit/components/message/Message.spec.jsx
  tests/unit/components/user-table/UserTable.spec.jsx
  tests/unit/containers/my-resources/LessonsContainer.spec.jsx
  tests/unit/pages/admin-table/AdminTable.spec.jsx
  tests/unit/pages/student-table/StudentTable.spec.jsx
  tests/unit/pages/tutor-table/TutorTable.spec.jsx
Labels: Frontend part, feature

#1016 Added unit test for PrivateRoute
  tests/unit/router/helpers/PrivateRoute.spec.jsx
Labels: Frontend part, test

#994 Added unit test for HomeRoute
  tests/unit/router/helpers/HomeRoute.spec.jsx
Labels: Frontend part, test

#1017 (SP:1) Implement Icon with extention and title component
  src/components/icon-extention-with-title/IconExtentionWithTitle.styles.ts
  src/components/icon-extention-with-title/IconExtentionWithTitle.tsx
  src/constants/translations/en/common.json
  src/constants/translations/ua/common.json
  src/styles/app-theme/app.pallete.ts
  tests/unit/components/icon-extention-with-title/IconExtentionWithTitle.spec.jsx
Labels: Frontend part, feature

#1018 implemented chat messages list with input
  src/components/app-card/AppCard.styles.ts
  src/components/app-card/AppCard.tsx
  src/components/app-text-area/AppTextArea.styles.ts
  src/components/app-text-area/AppTextArea.tsx
  src/components/app-text-field/AppTextField.tsx
  src/components/message/Message.styles.ts
  src/components/message/Message.tsx
  src/constants/request.ts
  src/constants/translations/en/chat.json
  src/constants/translations/ua/chat.json
  src/containers/chat/chat-date/ChatDate.styles.ts
  src/containers/chat/chat-date/ChatDate.tsx
  src/containers/chat/chat-header/ChatHeader.styles.ts
  src/containers/chat/chat-header/ChatHeader.tsx
  src/containers/chat/chat-item/ChatItem.tsx
  src/containers/chat/chat-text-area/ChatTextArea.styles.ts
  src/containers/chat/chat-text-area/ChatTextArea.tsx
  src/containers/chat/list-of-users-with-search/ListOfUsersWithSearch.tsx
  src/pages/chat/Chat.styles.ts
  src/pages/chat/Chat.tsx
  src/services/message-service.ts
  src/types/chat/message/interfaces/message.interface.ts
  src/types/common/enums/common.enums.ts
  src/utils/helper-functions.tsx
  tests/unit/components/message/Message.spec.jsx
  tests/unit/containers/chat/chat-item/ChatItem.spec.jsx
  tests/unit/containers/chat/list-of-users-with-search/ListOfUsersWithSearch.spec.jsx
  tests/unit/containers/chat/list-of-users-with-search/MockChat.spec.constants.js
  tests/unit/pages/chat/Chat.spec.jsx
Labels: Frontend part, feature

#1015 Implemented unit test for FindOffers component
  tests/unit/pages/find-offers/FindOffers.constants.js
  tests/unit/pages/find-offers/FindOffers.spec.jsx
Labels: Frontend part, test

#978 Created chat sidebar component
  src/components/all-content-modal/AllContentModal.styles.ts
  src/components/all-content-modal/AllContentModal.tsx
  src/components/clickable-image/ClickableImage.styles.ts
  src/components/clickable-image/ClickableImage.tsx
  src/components/file-component/FileComponent.constants.ts
  src/components/file-component/FileComponent.styles.ts
  src/components/file-component/FileComponent.tsx
  src/components/link-component/LinkComponent.styles.ts
  src/components/link-component/LinkComponent.tsx
  src/components/sidebar-content-box/SidebarContentBox.constants.ts
  src/components/sidebar-content-box/SidebarContentBox.styles.ts
  src/components/sidebar-content-box/SidebarContentBox.tsx
  src/components/sidebar-image-grid/SidebarImageGrid.styles.ts
  src/components/sidebar-image-grid/SidebarImageGrid.tsx
  src/components/user-profile-info/UserProfileInfo.tsx
  src/constants/translations/en/chat.json
  src/constants/translations/en/index.ts
  src/constants/translations/ua/chat.json
  src/constants/translations/ua/index.ts
  src/containers/about-chat-sidebar/AboutChatSidebar.styles.ts
  src/containers/about-chat-sidebar/AboutChatSidebar.tsx
  src/containers/chat/chat-item/ChatItem.tsx
  src/styles/app-theme/app.pallete.ts
  src/types/chat/file/file.index.ts
  src/types/chat/file/interfaces/file.interface.ts
  src/types/chat/link/interfaces/link.interface.ts
  src/types/chat/link/link.index.ts
  src/types/chat/media/interface/media.interface.ts
  src/types/chat/media/media.index.ts
  src/types/index.ts
  src/types/utils/utils-interfaces/utils.interface.ts
  src/utils/helper-functions.tsx
  tests/unit/components/all-content-modal/AllContentModal.spec.jsx
  tests/unit/components/clickable-image/ClickableImage.spec.jsx
  tests/unit/components/file-component/FileComponent.spec.jsx
  tests/unit/components/link-component/LinkComponent.spec.jsx
  tests/unit/components/sidebar-content-box/SidebarContentBox.spec.jsx
  tests/unit/components/sidebar-image-grid/SidebarImageGrid.spec.jsx
  tests/unit/containers/about-chat-sidebar/AboutChatSidebar.spec.jsx
  tests/unit/containers/chat/chat-item/ChatItem.spec.jsx
Labels: Frontend part, feature

#1022 Added send message functionality to the chat
  src/constants/request.ts
  src/constants/translations/en/chat.json
  src/constants/translations/ua/chat.json
  src/containers/chat/chat-text-area/ChatTextArea.tsx
  src/pages/chat/Chat.styles.ts
  src/pages/chat/Chat.tsx
  src/services/message-service.ts
  src/types/chat/message/interfaces/message.interface.ts
  tests/unit/pages/chat/Chat.spec.jsx
Labels: Frontend part, feature

#1023 Add list of attachments to resource page
  src/components/icon-extention-with-title/IconExtentionWithTitle.tsx
  src/constants/request.ts
  src/constants/translations/en/common.json
  src/constants/translations/en/my-resources-page.json
  src/constants/translations/ua/my-resources-page.json
  src/containers/my-resources/attachments-container/AttachmentsContainer.constants.tsx
  src/containers/my-resources/attachments-container/AttachmentsContainer.styles.ts
  src/containers/my-resources/attachments-container/AttachmentsContainer.tsx
  src/pages/my-resources/MyResources.constants.tsx
  src/services/resource-service.ts
  src/types/attachment/attachment.index.ts
  src/types/attachment/interfaces/attachment.interface.ts
  src/types/index.ts
  src/types/my-cooperations/interfaces/myCooperations.interfaces.ts
  src/utils/helper-functions.tsx
  tests/unit/containers/AttachmentsContainer/AttachmentsContainer.spec.jsx
Labels: Frontend part, feature

#1024 Created modal window for add attachments to new lesson
  src/components/icon-extention-with-title/IconExtentionWithTitle.styles.ts
  src/components/icon-extention-with-title/IconExtentionWithTitle.tsx
  src/constants/translations/en/common.json
  src/constants/translations/en/my-resources-page.json
  src/constants/translations/ua/common.json
  src/constants/translations/ua/my-resources-page.json
  src/containers/add-attachments/AddAttachments.constants.tsx
  src/containers/add-attachments/AddAttachments.styles.ts
  src/containers/add-attachments/AddAttachments.tsx
  src/containers/my-resources/attachments-container/AttachmentsContainer.constants.tsx
  src/services/attachment-service.ts
  src/types/attachment/interfaces/attachment.interface.ts
  src/types/index.ts
  src/types/my-attachments/interfaces/myAttachments.interfaces.ts
  src/types/my-attachments/myAttachments.index.ts
  src/types/my-cooperations/interfaces/myCooperations.interfaces.ts
  src/types/utils/utils-interfaces/utils.interface.ts
  src/utils/helper-functions.tsx
  tests/unit/components/icon-extention-with-title/IconExtentionWithTitle.spec.jsx
  tests/unit/containers/AttachmentsContainer/AttachmentsContainer.spec.jsx
  tests/unit/containers/add-attachments/AddAttachments.spec.jsx
Labels: Frontend part

#1020 Added table of quizzes to resource page
  src/constants/request.ts
  src/constants/translations/en/my-resources-page.json
  src/constants/translations/ua/my-resources-page.json
  src/containers/my-cooperations/cooperations-container/CooperationContainer.styles.ts
  src/containers/my-quizzes/QuizzesContainer.constants.tsx
  src/containers/my-quizzes/QuizzesContainer.styles.ts
  src/containers/my-quizzes/QuizzesContainer.tsx
  src/containers/my-resources/attachments-container/AttachmentsContainer.styles.ts
  src/containers/my-resources/attachments-container/AttachmentsContainer.tsx
  src/containers/my-resources/lessons-container/LessonsContainer.styles.ts
  src/containers/my-resources/lessons-container/LessonsContainer.tsx
  src/pages/my-resources/MyResources.constants.tsx
  src/pages/my-resources/MyResources.styles.ts
  src/pages/my-resources/MyResources.tsx
  src/services/quiz-service.ts
  src/types/index.ts
  src/types/my-cooperations/interfaces/myCooperations.interfaces.ts
  src/types/quizzes/interfaces/quizzes.interface.ts
  src/types/quizzes/quizzes.index.ts
  src/utils/helper-functions.tsx
  tests/unit/containers/my-quizzes/QuizzesContainer.spec.jsx
  tests/unit/pages/find-offers/FindOffers.spec.jsx
  tests/unit/pages/my-resources/MyResources.spec.jsx
Labels: Frontend part, feature

#1019 Implemented "New lesson" page
  package-lock.json
  package.json
  src/components/file-editor/FileEditor.constants.ts
  src/components/file-editor/FileEditor.tsx
  src/constants/request.ts
  src/constants/translations/en/breadcrumbs.json
  src/constants/translations/en/button.json
  src/constants/translations/en/common.json
  src/constants/translations/en/index.ts
  src/constants/translations/en/new-lesson.json
  src/constants/translations/ua/breadcrumbs.json
  src/constants/translations/ua/button.json
  src/constants/translations/ua/common.json
  src/constants/translations/ua/index.ts
  src/constants/translations/ua/new-lesson.json
  src/containers/my-resources/lessons-container/LessonsContainer.styles.ts
  src/containers/my-resources/lessons-container/LessonsContainer.tsx
  src/pages/new-lesson/NewLesson.constants.tsx
  src/pages/new-lesson/NewLesson.styles.ts
  src/pages/new-lesson/NewLesson.tsx
  src/router/routes/authRouter.tsx
  src/services/resource-service.ts
  src/types/index.ts
  src/types/lesson/interfaces/lesson.interfaces.ts
  src/types/lesson/lesson.index.ts
  src/vite-env.d.ts
  tests/unit/pages/new-lesson/NewLesson.spec.jsx
Labels: Frontend part, feature

#993 TutorProfile test
  tests/unit/pages/tutor-profile/TutorProfile.spec.jsx
Labels: test

#1028 Changed the type of cursor
  src/components/app-chips-list/AppChipsList-styles.ts
Labels: Frontend part, feature

#1040 Changed chat on chatPage
  src/components/file-component/FileComponent.tsx
  src/components/sidebar-content-box/SidebarContentBox.tsx
  src/components/sidebar-image-grid/SidebarImageGrid.tsx
  src/components/user-profile-info/UserProfileInfo.tsx
  src/containers/about-chat-sidebar/AboutChatSidebar.tsx
  src/containers/chat/chat-item/ChatItem.tsx
  tests/unit/components/file-component/FileComponent.spec.jsx
  tests/unit/containers/about-chat-sidebar/AboutChatSidebar.spec.jsx
  tests/unit/containers/chat/chat-item/ChatItem.spec.jsx
Labels: bug, Frontend part

#1035 Implemented quiz deletion for my cooperation page
  src/constants/request.ts
  src/constants/translations/en/my-resources-page.json
  src/containers/my-quizzes/QuizzesContainer.tsx
  src/containers/my-resources/lessons-container/LessonsContainer.tsx
  src/services/quiz-service.ts
Labels: Frontend part, feature

#1025 Search by message
  src/components/icons-with-counter/IconsWithCounter.style.ts
  src/components/icons-with-counter/IconsWithCounter.tsx
  src/components/search-by-message/SearchByMessage.styles.ts
  src/components/search-by-message/SearchByMessage.tsx
  src/constants/translations/en/common.json
  src/constants/translations/ua/common.json
  tests/unit/components/icons-with-counter/IconsWithCounter.spec.jsx
  tests/unit/components/search-by-message/SearchByMessage.spec.jsx
Labels: Frontend part, feature

#1034 implemented search for table of quizzes
  src/constants/translations/en/my-resources-page.json
  src/constants/translations/ua/my-resources-page.json
  src/containers/my-quizzes/QuizzesContainer.constants.tsx
  src/containers/my-quizzes/QuizzesContainer.tsx
  src/containers/my-resources/add-resource-with-input/AddResourceWithInput.styles.ts
  src/containers/my-resources/add-resource-with-input/AddResourceWithInput.tsx
  src/containers/my-resources/lessons-container/LessonsContainer.styles.ts
  src/containers/my-resources/lessons-container/LessonsContainer.tsx
  tests/unit/containers/my-resources/AddResourceWithInput.spec.jsx
Labels: Frontend part, feature

#1055 Fixed TinyMCE warnings with packages and key
  src/components/file-editor/FileEditor.tsx
Labels: Frontend part

#1032 Separate messages by date and hide avatar for same author
  src/components/message/Message.styles.ts
  src/components/message/Message.tsx
  src/containers/chat/chat-date/ChatDate.tsx
  src/pages/chat/Chat.styles.ts
  src/pages/chat/Chat.tsx
  src/types/chat/message/interfaces/message.interface.ts
  src/utils/helper-functions.tsx
Labels: Frontend part, feature

#1042 implemented selection attachments
  src/components/enhanced-table/EnhancedTable.tsx
  src/components/enhanced-table/enhanced-table-row/EnhancedTableRow.jsx
  src/components/enhanced-table/enhanced-table-row/EnhancedTableRow.styles.ts
  src/containers/add-attachments/AddAttachments.tsx
  src/pages/new-lesson/NewLesson.tsx
  src/services/attachment-service.ts
  tests/unit/containers/add-attachments/AddAttachments.spec.jsx
Labels: Frontend part, feature

#1056 Implemented pagination for attachments tab
  src/containers/my-resources/attachments-container/AttachmentsContainer.tsx
  tests/unit/containers/AttachmentsContainer/AttachmentsContainer.spec.jsx
Labels: Frontend part, feature

#1057 Added filter for attachment modal window
  src/containers/add-attachments/AddAttachments.constants.tsx
  src/containers/add-attachments/AddAttachments.tsx
  tests/unit/containers/add-attachments/AddAttachments.spec.jsx
Labels: Frontend part, feature

#1043 Added sorting to quizzes tab
  src/containers/my-quizzes/QuizzesContainer.constants.tsx
  src/containers/my-quizzes/QuizzesContainer.tsx
  src/pages/my-resources/MyResources.constants.tsx
Labels: Frontend part

#1059 Add sort to attachments on myResources
  src/containers/my-resources/attachments-container/AttachmentsContainer.tsx
Labels: Frontend part, feature

#1026 implemented search with functionality
  src/constants/translations/ua/my-resources-page.json
  src/containers/my-quizzes/QuizzesContainer.tsx
  src/containers/my-resources/attachments-container/AttachmentsContainer.styles.ts
  src/containers/my-resources/attachments-container/AttachmentsContainer.tsx
  src/pages/my-resources/MyResources.constants.tsx
  src/services/resource-service.ts
  src/types/my-attachments/interfaces/myAttachments.interfaces.ts
Labels: Frontend part, feature

#1064 Implemented attachments list to "New lesson"
  src/components/icon-extension-with-title/IconExtensionWithTitle.styles.ts
  src/components/icon-extension-with-title/IconExtensionWithTitle.tsx
  src/containers/add-attachments/AddAttachments.constants.tsx
  src/containers/my-resources/attachments-container/AttachmentsContainer.constants.tsx
  src/pages/new-lesson/NewLesson.styles.ts
  src/pages/new-lesson/NewLesson.tsx
  tests/unit/components/icon-extention-with-title/IconExtentionWithTitle.spec.jsx
Labels: Frontend part, feature
