Repository ita-social-projects/SpaceToStudy-Client, pull requests merged in 2023-06, with the labels that each got.

#799 Added cards from response to coop page
  src/components/popular-categories/PopularCategories.constants.ts
  src/components/popular-categories/PopularCategories.tsx
  src/constants/index.ts
  src/containers/my-cooperations/cooperation-card/CooperationCard.styles.ts
  src/containers/my-cooperations/cooperation-card/CooperationCard.tsx
  src/containers/my-cooperations/cooperation-toolbar/CooperationToolbar.tsx
  src/containers/my-cooperations/cooperations-container/CooperationContainer.styles.ts
  src/pages/categories/Categories.tsx
  src/pages/my-cooperations/MyCooperations.constants.ts
  src/pages/my-cooperations/MyCooperations.tsx
  src/pages/subjects/Subjects.tsx
  src/types/common/interfaces/common.interfaces.ts
  src/types/cooperation/interfaces/cooperation.interface.ts
  src/types/my-cooperations/interfaces/myCooperations.interfaces.ts
  src/utils/helper-functions.tsx
  tests/unit/containers/my-cooperations/cooperation-card/CooperationCard.spec.jsx
  tests/unit/containers/my-cooperations/cooperation-container/CooperationContainer.spec.jsx
  tests/unit/pages/my-cooperations/MyCooperations.spec.jsx
Labels: Frontend part, feature

#785 disable closing window outside popup
  src/components/popup-dialog/PopupDialog.tsx
Labels: bug, severity: minor, Functional, priority: low

#798 The item descriptions are bold in the home page “How it works” block fixed
  src/containers/guest-home-page/cards-with-button/CardsWithButton.styles.js
Labels: bug, UI/Usability, severity: minor, priority: medium

#802 [Tutor stepper] The study category placeholder text is not corresponded to the mockup.
  src/constants/translations/en/become-tutor.json
Labels: bug, UI/Usability, priority: low, severity: trivial

#803 The “Send a Request” item in the home page “How it works” block is not corresponded to the mockup fixed
  src/containers/guest-home-page/cards-with-button/CardsWithButton.styles.js
Labels: bug, UI/Usability, severity: minor, priority: medium

#805 [Home page] The label item from the right of the world map is not corresponded to the mockup.
  src/constants/translations/en/guest-home-page.json
Labels: bug, UI/Usability, severity: minor, priority: medium

#807 [Home page] The slash separator between home page buttons is not corresponded to the mockup
  src/containers/layout/navbar/NavBar.styles.js
Labels: bug, UI/Usability, severity: minor, priority: medium

#809 Added unit test for page wrapper
  tests/unit/components/page-wrapper/PageWrapper.spec.jsx
Labels: Frontend part, test

#811 Fixed spelling in block
  src/constants/translations/en/guest-home-page.json
  src/constants/translations/en/student-home-page.json
Labels: bug, UI/Usability, severity: minor, priority: low

#812 Implemented unit test for AppCarousel component
  tests/unit/components/app-carousel/AppCarousel.spec.jsx
Labels: Frontend part, test

#824 Fix page loading and login dialog
  src/components/app-carousel/AppCarousel.tsx
  src/components/scroll-to-top/ScrollToTop.jsx
  src/components/scroll-to-top/ScrollToTop.tsx
  src/containers/guest-home-page/login-dialog/LoginDialog.jsx
  src/containers/layout/app-main/AppMain.tsx
  src/containers/tutor-profile/comments-block/CommentBlock.tsx
  src/redux/reducer.ts
  tests/unit/components/layout/AppMain.spec.jsx
  tests/unit/components/scroll-to-top/ScrollToTop.spec.jsx
  tests/unit/context/modal-context.spec.jsx
  tests/unit/redux/redux.variables.js
Labels: bug, Frontend part, feature

#837 Fixed requests to onFocus
  src/components/async-autocomlete/AsyncAutocomplete.tsx
  src/components/search-autocomplete/SearchAutocomplete.tsx
  src/components/user-steps-wrapper/UserStepsWrapper.tsx
  src/constants/translations/en/header.json
  src/containers/find-offer/create-new-subject/CreateNewSubject.tsx
  src/containers/offer-page/create-offer/CreateOffer.tsx
  src/containers/offer-page/create-offer/specialization-block/SpecializationBlock.tsx
  src/containers/offer-page/create-offer/teaching-block/TeachingBlock.tsx
  src/pages/categories/Categories.tsx
  src/pages/tutor-home/TutorHome.styles.ts
  src/pages/tutor-home/TutorHome.tsx
  src/redux/reducer.ts
  tests/unit/containers/find-offer/create-new-subject/CreateNewSubject.spec.jsx
Labels: bug, Frontend part

#835 Added clear stepper fields in subject step
  src/containers/tutor-home-page/subjects-step/SubjectsStep.jsx
  tests/unit/containers/mentor-home-page/subjects-step/SubjectsStep.spec.jsx
Labels: Frontend part, feature

#823 Created coop table
  src/components/enhanced-table/EnhancedTable.jsx
  src/components/enhanced-table/EnhancedTable.styles.js
  src/components/enhanced-table/enhanced-table-head/EnhancedTableHead.jsx
  src/components/enhanced-table/enhanced-table-header-cell/EnhancedTableHeaderCell.jsx
  src/components/enhanced-table/enhanced-table-row/EnhancedTableRow.jsx
  src/components/enhanced-table/filter-row/FilterRow.jsx
  src/components/enhanced-table/filter-row/filter-cell/FilterCell.jsx
  src/constants/translations/en/cooperations-page.json
  src/constants/translations/ua/cooperations-page.json
  src/containers/guest-home-page/login-form/LoginForm.styles.js
  src/containers/my-cooperations/cooperation-toolbar/CooperationToolbar.styles.ts
  src/containers/my-cooperations/cooperation-toolbar/CooperationToolbar.tsx
  src/containers/my-cooperations/cooperations-container/CooperationContainer.constants.tsx
  src/containers/my-cooperations/cooperations-container/CooperationContainer.styles.ts
  src/containers/my-cooperations/cooperations-container/CooperationContainer.tsx
  src/hooks/table/use-sort.jsx
  src/hooks/table/use-sort.tsx
  src/pages/my-cooperations/MyCooperations.constants.ts
  src/pages/my-cooperations/MyCooperations.tsx
  src/types/my-cooperations/interfaces/myCooperations.interfaces.ts
  src/utils/helper-functions.tsx
  tests/unit/components/enhanced-table/enhanced-table-row/EnhancedTableRow.spec.jsx
  tests/unit/containers/my-cooperations/cooperation-toolbar/CooperationToolbar.spec.jsx
  tests/unit/hooks/table/use-sort.spec.jsx
Labels: Frontend part, feature

#779 The “What can you do” button is not highlighted after clicking it, fixed.
  src/containers/layout/navbar/NavBar.styles.js
Labels: bug, good first issue, UI/Usability, severity: minor, priority: medium

#806 The “Space2Study” logo button does not return to the home page welcoming block after clicking it fixed
  src/containers/guest-home-page/Welcome.jsx
  src/containers/layout/navbar/NavBar.jsx
  src/router/constants/guestRoutes.ts
Labels: bug, severity: minor, priority: medium, Functional

#821 Added proper route to tutor categories page
  src/router/constants/tutorRoutes.ts
Labels: Frontend part, feature

#831 Added unit test for FilterBarMenu component
  src/containers/find-offer/filter-bar-menu/FilterBarMenu.tsx
  tests/unit/containers/find-offer/filter-bar-menu/FilterBarMenu.spec.jsx
Labels: Frontend part, test

#836 Changed view of footer and its position
  src/constants/translations/en/find-offer-page.json
  src/containers/layout/footer/Footer.styles.ts
  src/containers/layout/footer/Footer.tsx
  src/containers/layout/footer/footer-by-role/FooterByRole.styles.ts
  src/containers/layout/footer/user-footer/UserFooter.styles.ts
  src/containers/layout/footer/user-footer/UserFooter.tsx
  src/pages/tutor-home/TutorHome.tsx
Labels: Frontend part, feature

#832 Disabled all buttons/links that are not working right now
  src/containers/navigation-icons/guest-icons/GuestIcons.jsx
  src/containers/navigation-icons/user-icons/UserIcons.jsx
  src/containers/tutor-profile/profile-info/ProfileInfo.jsx
  src/router/constants/guestRoutes.ts
Labels: good first issue, Frontend part

#810 (SP: 1) Write unit test for tab
  tests/unit/components/tab/Tab.spec.jsx
Labels: Frontend part, test

#843 Created subject level component
  src/components/offer-banner/OfferBanner.styles.ts
  src/components/offer-banner/OfferBanner.tsx
  src/components/offer-card/OfferCard.tsx
  src/components/offer-card/offer-details/OfferDetails.jsx
  src/components/offer-card/offer-details/OfferDetails.styles.js
  src/components/page-wrapper/PageWrapper.tsx
  src/components/status-chip/StatusChip.styles.ts
  src/components/subject-level-chips/SubjectLevelChips.styles.ts
  src/components/subject-level-chips/SubjectLevelChips.tsx
  src/components/tab/Tab.styles.ts
  src/components/tab/Tab.tsx
  src/components/user-table/UserTable.jsx
  src/constants/translations/en/cooperations-page.json
  src/constants/translations/ua/cooperations-page.json
  src/containers/find-offer/offer-card-square/OfferCardSquare.styles.ts
  src/containers/find-offer/offer-card-square/OfferCardSquare.tsx
  src/containers/layout/app-breadcrumbs/AppBreadCrumbs.jsx
  src/containers/my-cooperations/cooperation-card/CooperationCard.styles.ts
  src/containers/my-cooperations/cooperation-card/CooperationCard.tsx
  src/containers/my-cooperations/cooperation-toolbar/CooperationToolbar.tsx
  src/containers/my-cooperations/cooperations-container/CooperationContainer.constants.tsx
  src/containers/my-cooperations/cooperations-container/CooperationContainer.styles.ts
  src/containers/offer-page/create-offer/CreateOffer.constants.ts
  src/containers/offer-page/create-offer/CreateOffer.tsx
  src/containers/offer-page/create-offer/faq-block/FaqBlock.tsx
  src/containers/tutor-profile/profile-info/ProfileInfo.constants.jsx
  src/pages/my-cooperations/MyCooperations.constants.ts
  src/pages/my-cooperations/MyCooperations.styles.ts
  src/pages/my-cooperations/MyCooperations.tsx
  src/styles/app-theme/app.pallete.ts
  src/types/common/interfaces/common.interfaces.ts
  src/types/cooperation/interfaces/cooperation.interface.ts
  src/types/findOffers/interfaces/findOffers.interfaces.ts
  src/types/my-cooperations/interfaces/myCooperations.interfaces.ts
  src/types/offer/interfaces/offer.interfaces.ts
  src/types/user/user-interfaces/user.interfaces.ts
  src/utils/helper-functions.tsx
  tests/unit/components/offer-banner/OfferBanner.spec.jsx
  tests/unit/components/tab/Tab.spec.jsx
  tests/unit/containers/find-offer/offer-card-square/OfferCardSquare.spec.jsx
  tests/unit/containers/find-offer/offer-container/OfferContainer.spec.jsx
  tests/unit/containers/my-cooperations/cooperation-card/CooperationCard.spec.jsx
  tests/unit/containers/my-cooperations/cooperation-container/CooperationContainer.spec.jsx
  tests/unit/containers/offer-details/enroll-offer/EnrollOffer.spec.jsx
  tests/unit/containers/offer-details/offer-carousel/OfferCarousel.spec.jsx
  tests/unit/pages/offer-details/OfferDetails.spec.constants.js
  tests/unit/pages/offer-details/OfferDetails.spec.jsx
Labels: Frontend part, feature

#840 Changed amount of offers by role
  src/components/app-rating-mobile/AppRatingMobile.tsx
  src/components/popular-categories/PopularCategories.tsx
  src/containers/find-offer/offer-card-square/OfferCardSquare.tsx
  src/pages/categories/Categories.tsx
  src/pages/subjects/Subjects.tsx
  src/types/common/interfaces/common.interfaces.ts
  src/types/user/user-interfaces/user.interfaces.ts
  src/utils/helper-functions.tsx
Labels: Frontend part, feature

#842 (SP: 0.5) Fix student home page #797
  src/components/input-with-icon/InputWithIcon.styles.ts
  src/components/input-with-icon/InputWithIcon.tsx
  src/components/popular-categories/PopularCategories.styles.ts
  src/components/title-block/TitleBlock.styles.ts
  src/components/title-block/TitleBlock.tsx
  src/constants/translations/en/student-home-page.json
  src/constants/translations/ua/student-home-page.json
  src/containers/student-home-page/find-tutor-block/FindTutorBlock.jsx
  src/containers/student-home-page/find-tutor-block/find-tutor-block.styles.js
  src/containers/student-home-page/popular-categories/PopularCategories.styles.js
  tests/unit/containers/student-home-page/FindTutorBlock.spec.jsx
Labels: bug, Frontend part

#846 Feature/827/fix filter block view
  src/containers/find-offer/filter-bar-menu/FilterBarMenu.tsx
  src/containers/find-offer/offer-container/OfferContainer.tsx
  src/pages/find-offers/FindOffers.tsx
  src/types/common/enums/common.enums.ts
  src/types/components/accordions/accordions.enum.ts
  src/types/components/components.index.ts
  tests/unit/containers/find-offer/filter-bar-menu/FilterBarMenu.spec.jsx
Labels: Frontend part, feature

#838 fixed the text under the button Sign Up with Google
  src/constants/translations/en/signup.json
Labels: bug, good first issue, UI/Usability, priority: low, severity: trivial

#834 Added unit test for EnhancedTable component and rewrite to TS
  src/components/enhanced-table/EnhancedTable.styles.ts
  src/components/enhanced-table/EnhancedTable.tsx
  src/components/enhanced-table/enhanced-table-row/EnhancedTableRow.jsx
  src/types/components/components.index.ts
  src/types/components/enhanced-table/enhancedTable.interface.ts
  src/types/components/enhanced-table/enhancedTable.types.ts
  src/types/components/user-profile-info/userProfileInfo.interface.ts
  tests/unit/components/enhanced-table/EnhancedTable.spec.jsx
  tsconfig.json
Labels: Frontend part, feature, test, TypeScript

#870 Feature/787/change functionality of use-load-more hook
  src/components/popular-categories/PopularCategories.tsx
  src/constants/index.ts
  src/hooks/use-load-more.tsx
  src/pages/categories/Categories.tsx
  src/services/category-service.ts
  src/services/subject-service.ts
  src/types/common/interfaces/common.interfaces.ts
  tests/unit/components/popular-categories/PopularCategories.spec.jsx
  tests/unit/hooks/use-load-more.spec.jsx
Labels: Frontend part

#868 Added EditProfile page
  src/constants/index.ts
  src/constants/translations/en/breadcrumbs.json
  src/constants/translations/ua/breadcrumbs.json
  src/containers/tutor-profile/profile-info/ProfileInfo.jsx
  src/pages/edit-profile/EditProfile.tsx
  src/router/constants/crumbs.ts
  src/router/constants/studentRoutes.ts
  src/router/constants/tutorRoutes.ts
  src/router/routes/studentRouter.tsx
  src/router/routes/tutorRouter.tsx
Labels: Frontend part, feature

#869 Created link to profile
  src/components/app-text-area/AppTextArea.styles.ts
  src/components/app-text-area/AppTextArea.tsx
  src/components/comment/Comment.tsx
  src/components/offer-banner/OfferBanner.tsx
  src/components/offer-card/OfferCard.tsx
  src/components/user-profile-info/UserProfileInfo.styles.ts
  src/components/user-profile-info/UserProfileInfo.tsx
  src/containers/find-offer/offer-card-square/OfferCardSquare.tsx
  src/containers/find-offer/offer-container/OfferContainer.tsx
  src/containers/layout/app-breadcrumbs/AppBreadCrumbs.styles.js
  src/containers/layout/app-breadcrumbs/AppBreadCrumbs.styles.ts
  src/containers/layout/app-breadcrumbs/AppBreadCrumbs.tsx
  src/containers/my-cooperations/cooperation-card/CooperationCard.tsx
  src/containers/my-cooperations/cooperations-container/CooperationContainer.constants.tsx
  src/containers/offer-details/enroll-offer/EnrollOffer.tsx
  src/containers/offer-details/offer-carousel/OfferCarousel.tsx
  src/containers/offer-page/create-offer/CreateOffer.tsx
  src/containers/tutor-profile/profile-info/ProfileInfo.styles.js
  src/pages/find-offers/FindOffers.tsx
  src/pages/my-cooperations/MyCooperations.styles.ts
  src/pages/my-cooperations/MyCooperations.tsx
  src/router/constants/authRoutes.ts
  src/router/constants/crumbs.ts
  src/router/constants/loaders.ts
  src/router/routes/authRouter.tsx
  src/services/auth-service.ts
  src/services/location-service.ts
  src/services/offer-service.ts
  src/services/subject-service.ts
  src/services/user-service.tsx
  src/types/common/interfaces/common.interfaces.ts
  src/types/components/app-breadcrumbs/appBreadcrumbs.interfaces.ts
  src/types/components/app-breadcrumbs/appBreadcrumbs.types.ts
  src/types/components/components.index.ts
  src/types/cooperation/interfaces/cooperation.interface.ts
  src/types/offer-details/interfaces/offerDetails.interfaces.ts
  src/utils/helper-functions.tsx
  tests/unit/containers/my-cooperations/cooperation-card/CooperationCard.spec.jsx
  tests/unit/containers/my-cooperations/cooperation-container/CooperationContainer.spec.jsx
  tests/unit/containers/tutor-profile/comments-block/ComentsBlock.spec.jsx
Labels: Frontend part, feature

#845 Subjects names fetching on input focus
  src/containers/navigation-icons/guest-icons/GuestIcons.jsx
  src/containers/navigation-icons/user-icons/UserIcons.jsx
  src/pages/subjects/Subjects.tsx
Labels: Frontend part, feature

#875 (Student/tutor stepper) subjects names fetching on input focus
  src/components/async-autocomlete/AsyncAutocomplete.tsx
  src/containers/tutor-home-page/subjects-step/SubjectsStep.jsx
  tests/unit/containers/mentor-home-page/subjects-step/SubjectsStep.spec.jsx
Labels: Frontend part, feature

#872 (Tutor home) Implemented Find Student block
  src/components/find-block/FindBlock.jsx
  src/components/find-block/find-block.styles.js
  src/components/find-block/find-student-constants.js
  src/components/find-block/find-tutor-constants.js
  src/constants/translations/en/index.ts
  src/constants/translations/en/tutor-home-page.json
  src/constants/translations/ua/index.ts
  src/constants/translations/ua/tutor-home-page.json
  src/pages/student-home/StudentHome.tsx
  src/pages/tutor-home/TutorHome.tsx
  tests/unit/components/find-block/FindBlock.spec.jsx
Labels: Frontend part, feature

#853 Fixed view of title, updated data retrival
  src/components/offer-card/OfferCard.styles.ts
  src/components/offer-card/offer-details/OfferDetails.styles.js
Labels: Frontend part, feature

#871 (Tutor home) Added popular categories
  src/pages/tutor-home/TutorHome.tsx
Labels: Frontend part, feature

#909 Сreated acceptCooperation modal
  src/components/app-card/AppCard.tsx
  src/components/enhanced-table/EnhancedTable.tsx
  src/components/enhanced-table/enhanced-table-row/EnhancedTableRow.jsx
  src/components/loader/Loader.styles.ts
  src/components/loader/Loader.tsx
  src/components/page-wrapper/PageWrapper.tsx
  src/components/popular-categories/PopularCategories.tsx
  src/components/slider-with-input/SliderWithInput.styles.ts
  src/components/slider-with-input/SliderWithInput.tsx
  src/components/status-chip/StatusChip.styles.ts
  src/components/subject-level-chips/SubjectLevelChips.styles.ts
  src/components/user-profile-info/UserProfileInfo.styles.ts
  src/components/user-profile-info/UserProfileInfo.tsx
  src/constants/request.ts
  src/constants/translations/en/cooperations-page.json
  src/constants/translations/en/header.json
  src/constants/translations/ua/cooperations-page.json
  src/constants/translations/ua/header.json
  src/containers/find-offer/create-new-subject/CreateNewSubject.tsx
  src/containers/guest-home-page/cards-with-button/CardsWithButton.tsx
  src/containers/layout/admin-portal/AdminPortal.jsx
  src/containers/layout/app-breadcrumbs/AppBreadCrumbs.tsx
  src/containers/layout/app-main/AppMain.tsx
  src/containers/my-cooperations/accept-cooperation-modal/AcceptCooperation.styles.ts
  src/containers/my-cooperations/accept-cooperation-modal/AcceptCooperationModal.tsx
  src/containers/my-cooperations/cooperation-card/CooperationCard.styles.ts
  src/containers/my-cooperations/cooperation-card/CooperationCard.tsx
  src/containers/my-cooperations/cooperations-container/CooperationContainer.constants.tsx
  src/containers/my-cooperations/cooperations-container/CooperationContainer.tsx
  src/containers/offer-details/enroll-offer/EnrollOffer.styles.ts
  src/containers/offer-details/enroll-offer/EnrollOffer.tsx
  src/containers/offer-page/create-offer/CreateOffer.styles.ts
  src/containers/offer-page/create-offer/CreateOffer.tsx
  src/containers/tutor-home-page/general-info-step/GeneralInfoStep.jsx
  src/containers/tutor-profile/comments-with-rating-block/CommentsWithRaitngBlock.tsx
  src/hooks/use-confirm.tsx
  src/pages/find-offers/FindOffers.tsx
  src/pages/my-cooperations/MyCooperations.constants.ts
  src/pages/my-cooperations/MyCooperations.tsx
  src/pages/offer-details/OfferDetails.tsx
  src/router/constants/loaders.ts
  src/router/constants/tutorRoutes.ts
  src/services/cooperation-service.ts
  src/types/common/enums/common.enums.ts
  src/types/components/enhanced-table/enhancedTable.interface.ts
  src/types/cooperation/cooperation.index.ts
  src/types/cooperation/interfaces/cooperation.interface.ts
  src/types/cooperation/types/cooperation.types.ts
  src/types/offer-details/interfaces/offerDetails.interfaces.ts
  tests/unit/components/loader/Loader.spec.jsx
  tests/unit/components/page-wrapper/PageWrapper.spec.jsx
  tests/unit/containers/my-cooperations/MyCooperations.spec.constants.js
  tests/unit/containers/my-cooperations/accept-cooperation-modal/AcceptCooperationModal.spec.jsx
  tests/unit/containers/my-cooperations/cooperation-card/CooperationCard.spec.jsx
  tests/unit/containers/my-cooperations/cooperation-container/CooperationContainer.spec.jsx
  tests/unit/pages/guest-home/GuestHome.spec.jsx
Labels: Frontend part, feature

#854 (SP: 1) Move items from account menu to burger on mobile
  src/containers/layout/navbar/NavBar.jsx
  src/containers/layout/sidebar/Sidebar.tsx
  src/containers/navigation-icons/user-icons/UserIcons.jsx
  src/types/common/interfaces/common.interfaces.ts
Labels: Frontend part, feature

#911 add fetched data to faq block
  src/pages/offer-details/OfferDetails.tsx
  src/pages/offer-details/constants.ts
Labels: Frontend part, feature

#906 Made the following pages wider: categories, subjects, find offer, offer details.
  src/components/cards-list/CardsList.styles.ts
  src/components/hash-link/HashLink.tsx
  src/components/offer-banner/OfferBanner.tsx
  src/components/page-wrapper/PageWrapper.styles.ts
  src/components/page-wrapper/PageWrapper.tsx
  src/components/popular-categories/PopularCategories.constants.ts
  src/components/popular-categories/PopularCategories.tsx
  src/constants/index.ts
  src/containers/find-offer/filter-bar-menu/FilterBarMenu.tsx
  src/containers/find-offer/offer-container/OfferContainer.styles.ts
  src/containers/find-offer/offer-container/OfferContainer.tsx
  src/containers/find-offer/offer-filter-block/OfferFilterBlock.tsx
  src/containers/find-offer/offer-search-toolbar/OfferSearchToolbar.tsx
  src/containers/guest-home-page/Welcome.tsx
  src/containers/guest-home-page/google-button/GoogleButton.jsx
  src/containers/layout/app-breadcrumbs/AppBreadCrumbs.styles.ts
  src/containers/layout/app-breadcrumbs/AppBreadCrumbs.tsx
  src/containers/offer-details/enroll-offer/EnrollOffer.tsx
  src/containers/offer-details/offer-carousel/OfferCarousel.constants.ts
  src/containers/offer-details/offer-carousel/OfferCarousel.styles.ts
  src/containers/offer-details/offer-carousel/OfferCarousel.tsx
  src/containers/tutor-home-page/add-photo-step/AddPhotoStep.jsx
  src/containers/tutor-home-page/general-info-step/GeneralInfoStep.jsx
  src/containers/tutor-home-page/language-step/LanguageStep.jsx
  src/containers/tutor-home-page/subjects-step/SubjectsStep.jsx
  src/containers/tutor-profile/profile-info/ProfileContainerDesktop.jsx
  src/containers/tutor-profile/profile-info/ProfileInfo.jsx
  src/containers/tutor-profile/profile-info/ProfileInfo.styles.js
  src/hooks/use-breakpoints.tsx
  src/hooks/use-load-more.tsx
  src/pages/categories/Categories.styles.ts
  src/pages/categories/Categories.tsx
  src/pages/find-offers/FindOffers.constants.ts
  src/pages/find-offers/FindOffers.styles.ts
  src/pages/find-offers/FindOffers.tsx
  src/pages/offer-details/OfferDetails.styles.ts
  src/pages/offer-details/OfferDetails.tsx
  src/pages/subjects/Subjects.styles.ts
  src/pages/subjects/Subjects.tsx
  src/types/common/interfaces/common.interfaces.ts
  src/types/my-cooperations/interfaces/myCooperations.interfaces.ts
  src/utils/helper-functions.tsx
  tests/unit/components/find-block/FindBlock.spec.jsx
  tests/unit/components/offer-banner/OfferBanner.spec.jsx
  tests/unit/components/user-steps-wrapper/UserStepsWrapper.spec.jsx
  tests/unit/containers/find-offer/filter-bar-menu/FilterBarMenu.spec.jsx
  tests/unit/containers/find-offer/offer-container/OfferContainer.spec.jsx
  tests/unit/containers/guest-home-page/FeatureBlock.spec.jsx
  tests/unit/containers/mentor-home-page/add-photo-step/AddPhotoStep.spec.jsx
  tests/unit/hooks/use-breakpoints.spec.jsx
  tests/unit/pages/offer-details/OfferDetails.spec.jsx
Labels: Frontend part, feature

#847 Feature/take data for my profile page
  src/components/app-rating-mobile/AppRatingMobile.styles.ts
  src/components/app-rating-mobile/AppRatingMobile.tsx
  src/components/complete-profile/CompleteProfileBlock.styles.js
  src/constants/translations/en/tutor-profile-page.json
  src/constants/translations/ua/tutor-profile-page.json
  src/containers/tutor-profile/profile-info/ProfileContainerDesktop.jsx
  src/containers/tutor-profile/profile-info/ProfileContainerMobile.jsx
  src/containers/tutor-profile/profile-info/ProfileInfo.constants.jsx
  src/containers/tutor-profile/profile-info/ProfileInfo.jsx
  src/containers/tutor-profile/profile-info/ProfileInfo.styles.js
  src/pages/tutor-profile/TutorProfile.jsx
  src/utils/helper-functions.tsx
  tests/unit/containers/tutor-profile/ProfileInfo.spec.jsx
Labels: enhancement, Frontend part

#919 Fix/location and image tutor profile
  src/containers/tutor-profile/profile-info/ProfileInfo.jsx
  src/containers/tutor-profile/profile-info/ProfileInfo.styles.js
  tests/unit/containers/tutor-profile/ProfileInfo.spec.jsx
Labels: bug, Frontend part

#916 Fixed role popular categories
  src/components/popular-categories/PopularCategories.tsx
Labels: bug, Frontend part

#920 Сreated page for chat
  src/components/input-with-icon/InputWithIcon.styles.ts
  src/components/slider-with-input/SliderWithInput.tsx
  src/constants/translations/en/breadcrumbs.json
  src/constants/translations/ua/breadcrumbs.json
  src/containers/find-offer/filter-bar-menu/FilterBarMenu.tsx
  src/containers/find-offer/offer-filter-block/OfferFilterBlock.tsx
  src/containers/find-offer/offer-search-toolbar/OfferSearchToolbar.tsx
  src/containers/layout/app-main/AppMain.tsx
  src/containers/navigation-icons/user-icons/UserIcons.jsx
  src/hooks/table/use-pagination.tsx
  src/pages/chat/Chat.tsx
  src/pages/find-offers/FindOffers.styles.ts
  src/pages/find-offers/FindOffers.tsx
  src/router/constants/authRoutes.ts
  src/router/constants/crumbs.ts
  src/router/routes/authRouter.tsx
  src/types/findOffers/interfaces/findOffers.interfaces.ts
  tests/unit/components/layout/AppMain.spec.jsx
  tests/unit/containers/app-content/AppContent.spec.jsx
  tests/unit/containers/find-offer/filter-bar-menu/FilterBarMenu.spec.jsx
  tests/unit/containers/find-offer/offer-filter-block/OfferFilterBlock.spec.jsx
  tests/unit/hooks/table/use-pagination.spec.jsx
Labels: Frontend part, feature

#934 Created notifications menu
  src/components/app-menu/AppMenu.styles.ts
  src/components/app-menu/AppMenu.tsx
  src/components/complete-profile/CompleteProfileBlock.jsx
  src/components/navigation-icon/NavigationIcon.tsx
  src/constants/index.ts
  src/constants/translations/en/header.json
  src/constants/translations/ua/breadcrumbs.json
  src/constants/translations/ua/header.json
  src/containers/app-content/AppContent.styles.ts
  src/containers/layout/account-menu/AccountMenu.styles.ts
  src/containers/layout/account-menu/AccountMenu.tsx
  src/containers/layout/navbar/NavBar.styles.ts
  src/containers/layout/navbar/NavBar.tsx
  src/containers/layout/notifications-menu/NotificationsMenu.constants.ts
  src/containers/layout/notifications-menu/NotificationsMenu.styles.ts
  src/containers/layout/notifications-menu/NotificationsMenu.tsx
  src/containers/layout/sidebar/Sidebar.styles.ts
  src/containers/layout/sidebar/Sidebar.tsx
  src/containers/navigation-icons/NavigationIcons.constants.tsx
  src/containers/navigation-icons/NavigationIcons.jsx
  src/containers/navigation-icons/NavigationIcons.styles.js
  src/containers/navigation-icons/NavigationIcons.styles.ts
  src/containers/navigation-icons/NavigationIcons.tsx
  src/containers/navigation-icons/admin-icons/AdminIcons.jsx
  src/containers/navigation-icons/guest-icons/GuestIcons.jsx
  src/containers/navigation-icons/guest-icons/GuestIcons.tsx
  src/containers/navigation-icons/user-icons/UserIcons.jsx
  src/containers/navigation-icons/user-icons/UserIcons.tsx
  src/containers/tutor-profile/profile-info/ProfileInfo.jsx
  src/pages/my-cooperations/MyCooperations.tsx
  src/router/constants/authRoutes.ts
  src/router/constants/crumbs.ts
  src/router/constants/studentRoutes.ts
  src/router/constants/tutorRoutes.ts
  src/router/router.tsx
  src/router/routes/authRouter.tsx
  src/router/routes/studentRouter.tsx
  src/router/routes/tutorRouter.tsx
  src/styles/index.css
  src/types/common/enums/common.enums.ts
  src/types/index.ts
  src/types/notification/enums/notification.enums.ts
  src/types/notification/interfaces/notification.interfaces.ts
  src/types/notification/notification.index.ts
  src/utils/helper-functions.tsx
  tests/unit/containers/navigation-icons/NavigationIcons.spec.jsx
  tests/unit/containers/navigation-icons/guest-icons/GuestIcons.spec.jsx
  tests/unit/containers/sidebar/Sidebar.spec.jsx
Labels: Frontend part, feature

#932 Implemented adding an offer to draft
  src/components/multi-accordion-with-title/MultiAccordionWIthTitle.tsx
  src/components/offer-card/offer-actions/OfferActions.styles.ts
  src/constants/translations/en/common.json
  src/constants/translations/ua/common.json
  src/containers/offer-details/offer-carousel/OfferCarousel.tsx
  src/containers/offer-page/create-offer/CreateOffer.constants.ts
  src/containers/offer-page/create-offer/CreateOffer.tsx
  src/pages/find-offers/FindOffers.tsx
  src/pages/offer-details/OfferDetails.constants.ts
  src/pages/offer-details/OfferDetails.styles.ts
  src/pages/offer-details/OfferDetails.tsx
  src/services/offer-service.ts
  src/types/components/multi-accordion-with-title/multiAccordionWithTitle.interface.ts
  src/types/findOffers/interfaces/findOffers.interfaces.ts
Labels: Frontend part, feature
