Repository ita-social-projects/SpaceToStudy-Client, pull requests merged in 2023-03, with the labels that each got.

#496 added test for DateFilter Component
  src/components/enhanced-table/date-filter/DateFilter.jsx
  tests/unit/components/date-filter/DateFilter.spec.jsx
Labels: Frontend part, feature, test

#454 fix password validation bug -now validation works fine
  src/containers/guest-home-page/signup-form/SignupForm.jsx
  src/utils/validations/common.js
  src/utils/validations/login.js
Labels: bug, Frontend part

#446 Modify page scrolling#319
  src/components/scroll-to-top-button/ScrollToTopButton.jsx
  src/containers/app-content/AppContent.jsx
  src/pages/guest-home-page/GuestHome.jsx
  src/pages/student-home/StudentHome.jsx
  src/stories/AppChip.stories.js
  tests/unit/components/scroll-to-top-button/ScrollToTopButton.spec.jsx
  tests/unit/components/title-with-description/TitleWithDescription.spec.jsx
Labels: Frontend part, feature

#491 429/Implemented unit test for filter checkbox component
  src/components/enhanced-table/filter-checkbox/FilterCheckbox.jsx
  tests/unit/components/enhanced-table/filter-checkbox/FilterCheckbox.spec.jsx
Labels: Frontend part, test

#510 Added test for EnhancedTableToolbar component
  src/components/enhanced-table/enhanced-table-toolbar/EnhancedTableToolbar.jsx
  tests/unit/components/enhanced-table/enhanced-table-toolbar/EnhancedTableToolbar.spec.jsx
Labels: Frontend part, test

#505 Changed view of menu on stepper
  src/components/step-wrapper/StepWrapper.jsx
  src/components/step-wrapper/StepWrapper.styles.js
Labels: Frontend part, feature

#504 Adaptability added to 2nd step
  src/containers/tutor-home-page/subjects-step/SubjectsStep.jsx
  src/pages/guest-home-page/GuestHome.jsx
Labels: Frontend part, feature

#501 Fixed name on the admin table
  src/pages/admin-table/constants.jsx
Labels: bug, admin

#498 Removed 'Remember me' checkbox
  src/constants/translations/en/login.json
  src/constants/translations/ua/login.json
  src/containers/guest-home-page/login-form/LoginForm.jsx
  src/containers/guest-home-page/login-form/LoginForm.styles.js
  tests/unit/containers/guest-home-page/login-form/LoginForm.spec.jsx
Labels: Frontend part, feature

#495 Updated popups and add buttons to modals
  src/constants/translations/en/button.json
  src/constants/translations/en/common.json
  src/containers/email-confirm-modal/EmailConfirmModal.jsx
  src/containers/guest-home-page/cards-with-button/CardsWithButton.jsx
  src/containers/guest-home-page/forgot-password/ForgotPassword.jsx
  src/containers/guest-home-page/signup-dialog/SignupDialog.jsx
  tests/unit/containers/email-confirm-modal/EmailConfirmModal.spec.jsx
Labels: Frontend part, feature

#511 feature/430/unit-test-enenchanced-table/filter-row
  src/components/enhanced-table/filter-row/FilterRow.jsx
  src/components/enhanced-table/filter-row/filter-cell/FilterCell.jsx
  tests/unit/components/enhanced-table/filter-row/FilterRow.spec.jsx
Labels: Frontend part, test

#503 472/Implemented offers view switcher
  src/components/view-switcher/ViewSwitcher.jsx
  src/components/view-switcher/ViewSwitcher.styles.js
  src/constants/index.js
  src/stories/ViewSwitcher.stories.jsx
  tests/unit/components/view-switcher/ViewSwitcher.spec.jsx
Labels: Frontend part, feature

#527 Implemented unit tests for SearchInput component
  src/components/search-input/SearchInput.jsx
  tests/unit/components/search-input/SearchInput.spec.jsx
Labels: Frontend part, test

#526 Added tests for enhanced table head component
  tests/unit/components/enhanced-table/enhanced-table-head/EnhancedTableHead.spec.jsx
Labels: Frontend part, feature

#519 Added test for EhancedTablePagination component
  src/components/enhanced-table/enhanced-table-pagination/EnhancedTablePagination.jsx
  tests/unit/components/enhanced-table/enhanced-table-pagination/EnhancedTablePagination.spec.jsx
Labels: feature, test

#515 Feature/431/unit tests enhanced table row
  src/components/enhanced-table/enhanced-table-row/EnhancedTableRow.jsx
  tests/unit/components/enhanced-table/enhanced-table-row/EnhancedTableRow.spec.jsx
Labels: Frontend part, test

#509 Feature/434/unit tests for EnumFilter component
  src/components/enhanced-table/enum-filter/EnumFilter.jsx
  tests/unit/components/enhanced-table/enum-filter/EnumFilter.spec.jsx
Labels: Frontend part, test

#530 Resolved conflicts in tests
  tests/unit/components/app-select/AppSelect.spec.jsx
  tests/unit/containers/admin-portal/admin-nav-bar/AdminNavBar.spec.jsx
  tests/unit/containers/guest-home-page/signup-form/SignupForm.spec.jsx
  tests/unit/containers/student-home-page/student-how-it-works/StudentHowItWorks.spec.jsx
  tests/unit/pages/guest-home/GuestHome.spec.jsx
  tests/unit/pages/logout/Logout.spec.jsx
Labels: Frontend part, test

#522 add routes for pages
  src/constants/translations/en/breadcrumbs.json
  src/containers/student-home-page/find-tutor-block/FindTutorBlock.jsx
  src/containers/student-home-page/student-how-it-works/StudentHowItWorks.jsx
  src/pages/categories/Categories.jsx
  src/pages/find-offers/FindOffers.jsx
  src/pages/subjects/Subjects.jsx
  src/pages/tutor-home/TutorHome.jsx
  src/router/constants/guestRoutes.js
  src/router/constants/studentRoutes.js
  src/router/routes/guestRouter.jsx
  src/router/routes/studentRouter.jsx
Labels: Frontend part, feature

#525 Implemented Pagination component and added this component to Storybook
  src/components/app-pagination/AppPagination.jsx
  src/components/app-pagination/AppPagination.styles.js
  src/pages/find-offers/FindOffers.jsx
  src/stories/AppPagination.stories.jsx
  tests/unit/components/app-pagination/AppPagination.spec.jsx
Labels: Frontend part, feature

#524 Feature/Implemented block with reviews
  .storybook/preview.js
  src/components/app-button/AppButton.tsx
  src/components/app-rating-large/AppRatingLarge.styles.ts
  src/components/app-rating-large/AppRatingLarge.tsx
  src/components/app-rating-mobile/AppRatingMobile.styles.ts
  src/components/app-rating-mobile/AppRatingMobile.tsx
  src/components/app-rating/AppRating.styles.ts
  src/components/app-rating/AppRating.tsx
  src/components/comment/Comment.styles.ts
  src/components/comment/Comment.tsx
  src/constants/request.js
  src/constants/translations/en/tutor-profile-page.json
  src/constants/translations/ua/tutor-profile-page.json
  src/containers/tutor-profile/coments-block/ComentsBlock.styles.ts
  src/containers/tutor-profile/coments-block/ComentsBlock.tsx
  src/containers/tutor-profile/coments-block/constants.ts
  src/containers/tutor-profile/coments-block/rating-block/RatingBlock.styles.ts
  src/containers/tutor-profile/coments-block/rating-block/RatingBlock.tsx
  src/hooks/use-breakpoints.tsx
  src/pages/tutor-profile/TutorProfile.jsx
  src/pages/tutor-profile/constants.js
  src/stories/AppRating.stories.jsx
  src/stories/AppRatingLarge.stories.jsx
  src/stories/AppRatingMobile.stories.jsx
  src/types/common/interfaces/common.interfaces.ts
  src/types/tutorProfile/types/tutorProfile.types.ts
  tests/unit/components/app-rating-mobile/AppRatingMobile.spec.jsx
  tests/unit/components/app-rating/AppRating.spec.jsx
  tests/unit/containers/tutor-profile/comments-block/ComentsBlock.spec.jsx
Labels: Frontend part, feature

#536 Feature/534/checkbox list component
  src/components/app-select/AppSelect.styles.js
  src/components/app-select/AppSelect.styles.ts
  src/components/app-select/AppSelect.tsx
  src/components/checkbox-list/CheckboxList.styles.ts
  src/components/checkbox-list/CheckboxList.tsx
  src/components/checkbox-list/CheckboxList.types.ts
  src/constants/translations/en/filters.json
  src/constants/translations/ua/filters.json
  src/stories/CheckboxList.stories.jsx
  src/types/app/appSelect.types.ts
  tests/unit/components/app-select/AppSelect.spec.jsx
  tests/unit/components/checkbox-list/CheckboxList.spec.jsx
Labels: Frontend part, feature

#532 Refactored styles
  src/components/step-wrapper/StepWrapper.jsx
  src/components/step-wrapper/StepWrapper.styles.js
  src/containers/tutor-home-page/add-photo-step/AddPhotoStep.style.js
  src/containers/tutor-home-page/general-info-step/GeneralInfoStep.styles.js
  src/containers/tutor-home-page/subjects-step/SubjectsStep.jsx
  src/containers/tutor-home-page/subjects-step/SubjectsStep.styles.js
Labels: enhancement, Frontend part

#560 Added structure for TypeScript
  src/components/comment/Comment.tsx
  src/containers/tutor-profile/coments-block/ComentsBlock.tsx
  src/containers/tutor-profile/coments-block/rating-block/RatingBlock.tsx
  src/types/common/common.index.ts
  src/types/common/enums/common.enums.ts
  src/types/common/interfaces/common.interfaces.ts
  src/types/common/types/common.types.ts
  src/types/index.ts
  src/types/tutorProfile/tutorProfile.index.ts
Labels: feature, TypeScript

#557 Added unit tests for enhanced-table-header-cell component
  src/components/enhanced-table/enhanced-table-header-cell/EnhancedTableHeaderCell.jsx
  tests/unit/components/enhanced-table/enhanced-table-header-cell/EnhancedTableHeaderCell.spec.jsx
Labels: Frontend part, test

#549 Fixed checkbox agreement
  src/containers/guest-home-page/signup-form/SignupForm.jsx
  tests/unit/containers/guest-home-page/signup-form/SignupForm.spec.jsx
Labels: bug, Frontend part

#561 Checkbox list component test fix
  src/components/checkbox-list/CheckboxList.tsx
  tests/unit/components/checkbox-list/CheckboxList.spec.jsx
Labels: Frontend part, test

#554 Fix SonarCloud client side
  .github/workflows/main.yaml
  package-lock.json
  package.json
  sonar-project.properties
  vitest.config.ts
Labels: bug, Frontend part, devOps

#572 implement categories with search block
  src/components/app-auto-complete/AppAutoComplete.jsx
  src/components/clickable-card-list/ClickableCardList.jsx
  src/components/clickable-card-list/ClickableCardList.styles.js
  src/components/clickable-card/ClickableCard.jsx
  src/components/clickable-card/ClickableCard.styles.js
  src/components/search-with-filters/SearchWithFilters.jsx
  src/components/search-with-filters/SearchWithFilters.styles.js
  src/constants/translations/en/categories-page.json
  src/constants/translations/en/index.js
  src/constants/translations/en/student-home-page.json
  src/constants/translations/ua/breadcrumbs.json
  src/constants/translations/ua/categories-page.json
  src/constants/translations/ua/index.js
  src/containers/categories-page/explore-categories/ExploreCategories.jsx
  src/containers/categories-page/explore-categories/ExploreCategories.styles.js
  src/containers/student-home-page/popular-categories/PopularCategories.jsx
  src/containers/student-home-page/popular-categories/categories-list-mock.js
  src/pages/categories/Categories.jsx
Labels: Frontend part, feature

#553 feature/552/convert-app-chip-list-to-ts
  src/components/app-chips-list/AppChipList.tsx
Labels: Frontend part, feature, TypeScript

#556 Feature/541/Added types to ViewSwitcher component
  src/components/view-switcher/ViewSwitcher.styles.ts
  src/components/view-switcher/ViewSwitcher.tsx
  src/types/findOffers/enums/viewSwitcher.enums.ts
  src/types/findOffers/findOffers.index.ts
  src/types/findOffers/types/viewSwitcher.types.ts
  src/types/index.ts
Labels: Frontend part, feature, TypeScript

#575 Feature/567/Implemented filter bar menu
  src/components/app-content-switcher/AppContentSwitcher.jsx
  src/components/app-select/AppSelect.styles.ts
  src/components/app-select/AppSelect.tsx
  src/components/filters-toggle/FiltersToggle.styles.ts
  src/components/filters-toggle/FiltersToggle.tsx
  src/constants/translations/en/filters.json
  src/constants/translations/ua/filters.json
  src/containers/find-offer/filter-bar-menu/FilterBarMenu.constants.ts
  src/containers/find-offer/filter-bar-menu/FilterBarMenu.styles.ts
  src/containers/find-offer/filter-bar-menu/FilterBarMenu.tsx
  src/stories/FiltersToggle.stories.jsx
  src/types/findOffers/findOffers.index.ts
  src/types/findOffers/interfaces/filterBarMenu.interfaces.ts
  tests/unit/components/filters-toggle/FiltersToggle.spec.jsx
Labels: Frontend part, feature

#497 Added the OfferCard component
  src/components/app-card/AppCard.jsx
  src/components/app-card/AppCard.styles.js
  src/components/app-chip/AppChip.tsx
  src/components/app-rating/AppRating.styles.ts
  src/components/offer-card/OfferCard.jsx
  src/components/offer-card/offer-actions/OfferActions.jsx
  src/components/offer-card/offer-actions/OfferActions.styles.js
  src/components/offer-card/offer-avatar-and-rating/OfferAvatarAndRating.jsx
  src/components/offer-card/offer-avatar-and-rating/OfferAvatarAndRating.styles.js
  src/components/offer-card/offer-details/OfferDetails.jsx
  src/components/offer-card/offer-details/OfferDetails.styles.js
  src/constants/translations/en/common.json
  src/constants/translations/ua/common.json
  src/pages/find-offers/FindOffers.jsx
  src/pages/find-tutor/FindTutor.jsx
  src/styles/app-theme/app.pallete.js
Labels: Frontend part, feature, component

#550 Fix StoryBook deploy
  .github/workflows/storybook.yaml
  .gitignore
  build-story/0.24de2727.iframe.bundle.js
  build-story/0.24de2727.iframe.bundle.js.LICENSE.txt
  build-story/0.24de2727.iframe.bundle.js.map
  build-story/0.28cd50944631c825303f.manager.bundle.js
  build-story/0.28cd50944631c825303f.manager.bundle.js.LICENSE.txt
  build-story/1.b1d473f7.iframe.bundle.js
  build-story/1.b1d473f7.iframe.bundle.js.LICENSE.txt
  build-story/1.b1d473f7.iframe.bundle.js.map
  build-story/1.d517ce94f2498f9bd05c.manager.bundle.js
  build-story/10.cca49323.iframe.bundle.js
  build-story/10.cca49323.iframe.bundle.js.LICENSE.txt
  build-story/10.cca49323.iframe.bundle.js.map
  build-story/2.40c8cf42.iframe.bundle.js
  build-story/3.9e2fe1eb.iframe.bundle.js
  build-story/5.c5158154ffab4dd73c1b.manager.bundle.js
  build-story/5.c5158154ffab4dd73c1b.manager.bundle.js.LICENSE.txt
  build-story/6.c61dff26f99db3dbb49a.manager.bundle.js
  build-story/7.48de1ff5d754a6811933.manager.bundle.js
  build-story/7.578820bc.iframe.bundle.js
  build-story/7.578820bc.iframe.bundle.js.LICENSE.txt
  build-story/7.578820bc.iframe.bundle.js.map
  build-story/8.03e70751d8e5665418dd.manager.bundle.js
  build-story/8.03e70751d8e5665418dd.manager.bundle.js.LICENSE.txt
  build-story/8.f9b8fc55.iframe.bundle.js
  build-story/9.bf3d19e4.iframe.bundle.js
  build-story/9.d690e81cdf33ce539bf1.manager.bundle.js
  build-story/asset-manifest.json
  build-story/favicon.ico
  build-story/iframe.html
  build-story/index.html
  build-story/main.0fb6315b.iframe.bundle.js
  build-story/main.de2da9b033d13c93dbb4.manager.bundle.js
  build-story/project.json
  build-story/runtime~main.0721d2c1.iframe.bundle.js
  build-story/runtime~main.64aef461fed9006e5359.manager.bundle.js
  build-story/static/css/main.b50ddf43.chunk.css
  build-story/static/css/main.b50ddf43.chunk.css.map
  build-story/static/media/logo.78fc6355.svg
  build-story/static/media/map.6a478a0e.svg
  build-story/static/media/videoImg.54b775eb.png
  build-story/vendors~main.4ce6dde4.iframe.bundle.js
  build-story/vendors~main.4ce6dde4.iframe.bundle.js.LICENSE.txt
  build-story/vendors~main.4ce6dde4.iframe.bundle.js.map
  build-story/vendors~main.6b3db865421470fbc7b5.manager.bundle.js
  build-story/vendors~main.6b3db865421470fbc7b5.manager.bundle.js.LICENSE.txt
  package.json
Labels: bug, Frontend part, devOps

#586 Test fix
  .husky/pre-commit
  .husky/pre-push
  src/stories/ViewSwitcher.stories.jsx
  tests/unit/components/view-switcher/ViewSwitcher.spec.jsx
Labels: Frontend part, hotfix
