Repository ita-social-projects/SpaceToStudy-Client, pull requests merged in 2023-02, with the labels that each got.

#393 Feature/387/change first step according to figma
  src/assets/img/tutor-home-page/become-tutor/general-info.png
  src/assets/img/tutor-home-page/become-tutor/general-info.svg
  src/components/app-auto-complete/AppAutoComplete.js
  src/components/step-wrapper/StepWrapper.styles.js
  src/constants/request.js
  src/constants/translations/en/become-tutor.json
  src/containers/tutor-home-page/become-a-tutor/BecomeATutor.js
  src/containers/tutor-home-page/constants.js
  src/containers/tutor-home-page/general-info/GeneralInfo.js
  src/containers/tutor-home-page/general-info/general-info.styles.js
  src/context/step-context.js
  src/hooks/use-axios.js
  src/hooks/use-form.js
  src/services/location-service.js
  src/styles/app-theme/app.textfield.js
  tests/unit/components/app-auto-complete/AppAutoComplete.spec.js
  tests/unit/containers/mentor-home-page/become-a-tutor/general-info/GeneralInfo.spec.js
  tests/unit/services/location-service.spec.js
Labels: Frontend part, feature

#420 added tutor profile route and placeholder
  src/pages/tutor-profile/TutorProfile.js
  src/router/routes/studentRouter.js
  src/router/routes/tutorRouter.js
Labels: good first issue, Frontend part, feature

#441 Feature/313/remove unused links from student navbar
  src/containers/student-home-page/find-tutor-block/FindTutorBlock.js
  src/containers/student-home-page/student-how-it-works/StudentHowItWorks.js
  src/router/constants/studentRoutes.js
  src/router/routes/studentRouter.js
  tests/unit/containers/navbar/NavBar.spec.js
  tests/unit/router/router.spec.js
Labels: enhancement, Frontend part, feature

#440 Changed routin to use nested routes properly
  src/router/router.js
  src/router/routes/studentRouter.js
  src/router/routes/tutorRouter.js
Labels: Frontend part

#426 Implement block with progress bar and adaptivity
  src/components/app-progress-bar-line/AppProgressBarLine.js
  src/components/app-progress-bar-line/AppProgressBarLine.styles.js
  src/components/complete-profile/CompleteProfileBlock.js
  src/components/complete-profile/CompleteProfileBlock.styles.js
  src/components/profile-item/ProfileItem.js
  src/components/profile-item/ProfileItem.styles.js
  src/components/profile-item/complete-profile.constants.js
  src/constants/translations/en/complete-profile.json
  src/constants/translations/en/index.js
  src/constants/translations/ua/complete-profile.json
  src/constants/translations/ua/index.js
  src/pages/tutor-profile/TutorProfile.js
  src/styles/app-theme/app.pallete.js
  src/styles/app-theme/app.typography.js
  tests/unit/components/complete-profile/CompleteProfileBlock.spec.js
  tests/unit/pages/tutor-home/TutorHome.spec.js
Labels: Frontend part, feature

#482 Refactored 'get user' in admin grid
  src/components/tab/Tab.jsx
  src/hooks/table/use-pagination.jsx
  src/pages/student-table/StudentTable.jsx
  src/pages/student-table/constants.jsx
  src/services/user-service.js
Labels: bug, Frontend part

#461 Feature/445/Add AppChip to storybook
  src/stories/AppChip.stories.js
Labels: feature

#462 Implemented languages step for stepper with adaptivity
  src/assets/img/tutor-home-page/become-tutor/languages.svg
  src/components/step-wrapper/StepWrapper.jsx
  src/components/step-wrapper/StepWrapper.styles.js
  src/constants/translations/en/become-tutor.json
  src/constants/translations/ua/become-tutor.json
  src/containers/tutor-home-page/become-a-tutor/BecomeATutor.jsx
  src/containers/tutor-home-page/constants.js
  src/containers/tutor-home-page/language-step/LanguageStep.jsx
  src/containers/tutor-home-page/language-step/LanguageStep.styles.js
  src/containers/tutor-home-page/language-step/constants.js
  src/context/step-context.jsx
  src/hooks/use-steps.js
  tests/unit/containers/mentor-home-page/become-a-tutor/language/LanguageStep.spec.jsx
Labels: Frontend part, feature

#443 Changed duration of animation "How it works" block to 0.3s
  src/styles/app-theme/custom-animations.js
Labels: Frontend part, feature

#490 filled firstName and lastName fields from user data
  src/containers/tutor-home-page/become-a-tutor/BecomeATutor.jsx
  src/containers/tutor-home-page/general-info/GeneralInfo.jsx
  src/services/user-service.js
  tests/unit/containers/mentor-home-page/become-a-tutor/BecomeATutor.spec.jsx
  tests/unit/containers/mentor-home-page/become-a-tutor/general-info/GeneralInfo.spec.jsx
  tests/unit/pages/tutor-home/TutorHome.spec.jsx
Labels: Frontend part, feature

#487 Refactor style for stepper (px must be same in each step), rename files for steppers and change autocomplete in subjects step.
  src/components/autocoplete/Autocomplete.jsx
  src/containers/tutor-home-page/add-photo-step/AddPhotoStep.jsx
  src/containers/tutor-home-page/add-photo-step/AddPhotoStep.style.js
  src/containers/tutor-home-page/add-photo-step/constants.js
  src/containers/tutor-home-page/become-a-tutor/BecomeATutor.jsx
  src/containers/tutor-home-page/general-info-step/GeneralInfoStep.jsx
  src/containers/tutor-home-page/general-info-step/GeneralInfoStep.styles.js
  src/containers/tutor-home-page/language-step/LanguageStep.jsx
  src/containers/tutor-home-page/subjects-step/SubjectsStep.jsx
  src/containers/tutor-home-page/subjects-step/SubjectsStep.styles.js
  src/containers/tutor-home-page/subjects-step/constants.js
  tests/unit/components/autocoplete/Autocomplete.spec.jsx
  tests/unit/containers/mentor-home-page/add-photo-step/AddPhotoStep.spec.jsx
  tests/unit/containers/mentor-home-page/general-info-step/GeneralInfoStep.spec.jsx
  tests/unit/containers/mentor-home-page/language-step/LanguageStep.spec.jsx
  tests/unit/containers/mentor-home-page/subjects-step/SubjectsStep.spec.jsx
Labels: Frontend part, feature

#453 implement tutor main info block
  src/assets/img/tutor-profile-page/avatar.png
  src/components/app-chip/AppChip.jsx
  src/components/app-chips-list/AppChipList.jsx
  src/components/app-chips-list/AppChipsList-styles.js
  src/components/app-popover/AppPopover.jsx
  src/components/icon-with-text-list/ProfileDoneItemsList.jsx
  src/components/icon-with-text-list/ProfileDoneItemsList.style.js
  src/constants/index.js
  src/constants/translations/en/index.js
  src/constants/translations/en/tutor-profile-page.json
  src/constants/translations/ua/tutor-profile-page.json
  src/containers/tutor-home-page/subjects-step/SubjectsStep.jsx
  src/containers/tutor-profile/profile-info/ProfileContainerDesktop.jsx
  src/containers/tutor-profile/profile-info/ProfileContainerMobile.jsx
  src/containers/tutor-profile/profile-info/ProfileInfo.constants.jsx
  src/containers/tutor-profile/profile-info/ProfileInfo.jsx
  src/containers/tutor-profile/profile-info/ProfileInfo.styles.js
  src/context/snackbar-context.jsx
  src/pages/tutor-profile/TutorProfile.jsx
  src/styles/app-theme/app.button.js
  src/styles/app-theme/app.pallete.js
  tests/unit/components/app-chips/AppChipsList.spec.jsx
  tests/unit/components/appPopover/AppPopover.spec.jsx
  tests/unit/containers/guest-home-page/login-form/LoginForm.spec.jsx
  tests/unit/containers/tutor-profile/ProfileInfo.spec.jsx
Labels: feature

#485 Create admins page on admin
  src/components/enhanced-table/EnhancedTable.jsx
  src/constants/translations/en/admin-table.json
  src/constants/translations/en/index.js
  src/pages/admin-table/AdminTable.jsx
  src/pages/admin-table/AdminTable.styles.js
  src/pages/admin-table/constants.jsx
  src/router/routes/adminRouter.jsx
Labels: feature, admin

#483 Added new storybook component - AppAutoComplete
  jsconfig.json
  src/stories/AppAutoComplete.stories.jsx
Labels: feature

#492 Feature/410/Implemented mock presentation block on tutor profile page
  src/assets/img/tutor-profile-page/presentationVideoImg.png
  src/components/video-box/VideoBox.jsx
  src/components/video-box/VideoBox.styles.js
  src/constants/translations/en/tutor-profile-page.json
  src/constants/translations/ua/tutor-profile-page.json
  src/containers/tutor-profile/video-presentation/VideoPresentation.jsx
  src/pages/tutor-profile/TutorProfile.jsx
  tests/unit/containers/tutor-profile/video-presentation/VideoPresentation.spec.jsx
Labels: good first issue, Frontend part, feature
