Repository ita-social-projects/SpaceToStudy-Client, pull requests merged in 2023-04, with the labels that each got.

#590 Changed routes and icon, added translations
  src/constants/translations/en/breadcrumbs.json
  src/constants/translations/en/icons-tooltip.json
  src/constants/translations/ua/breadcrumbs.json
  src/constants/translations/ua/icons-tooltip.json
  src/constants/translations/ua/index.js
  src/constants/translations/ua/login.json
  src/containers/categories-page/explore-categories/ExploreCategories.jsx
  src/containers/navigation-icons/user-icons/UserIcons.jsx
  src/containers/student-home-page/find-tutor-block/FindTutorBlock.jsx
  src/router/constants/studentRoutes.js
Labels: bug, Frontend part, feature

#592 created appDrawer component
  src/components/app-drawer/AppDrawer.styles.ts
  src/components/app-drawer/AppDrawer.tsx
  src/components/filters-toggle/FiltersToggle.styles.ts
  src/components/filters-toggle/FiltersToggle.tsx
  src/containers/find-offer/offer-filter-block/OfferFilterBlock.styles.ts
  src/containers/find-offer/offer-filter-block/OfferFilterBlock.tsx
  src/containers/layout/sidebar/Sidebar.jsx
  src/containers/layout/sidebar/Sidebar.styles.js
  src/containers/layout/sidebar/Sidebar.styles.ts
  src/containers/layout/sidebar/Sidebar.tsx
  src/hooks/use-filter-query.tsx
  src/pages/find-offers/FindOffers.constants.ts
  src/pages/find-offers/FindOffers.jsx
  src/stories/AppDrawer.stories.jsx
  src/stories/AppRange.stories.jsx
  src/stories/CheckboxList.stories.jsx
  src/utils/helper-functions.ts
  tests/unit/containers/navbar/NavBar.spec.jsx
  tests/unit/containers/sidebar/Sidebar.spec.jsx
Labels: Frontend part, feature

#594 Refactored user-service.js file
  src/constants/request.ts
  src/containers/tutor-home-page/general-info-step/GeneralInfoStep.jsx
  src/plugins/axiosClient.js
  src/plugins/axiosClient.ts
  src/services/user-service.js
  src/services/user-service.tsx
  src/types/common/interfaces/common.interfaces.ts
  src/types/index.ts
  src/types/services/services.types.ts
  src/types/types/common.types.ts
  tests/unit/containers/mentor-home-page/become-a-tutor/BecomeATutor.spec.jsx
  tests/unit/containers/mentor-home-page/general-info-step/GeneralInfoStep.spec.jsx
  tests/unit/pages/tutor-home/TutorHome.spec.jsx
  tests/unit/services/user-service.spec.jsx
Labels: Frontend part, feature, test, TypeScript

#574 Added popular categories
  src/components/app-card/AppCard.jsx
  src/components/app-card/AppCard.styles.js
  src/components/app-card/AppCard.styles.ts
  src/components/app-card/AppCard.tsx
  src/components/clickable-card-list/ClickableCardList.jsx
  src/components/clickable-card-list/ClickableCardList.styles.js
  src/components/clickable-card-list/ClickableCardList.styles.ts
  src/components/clickable-card/ClickableCard.jsx
  src/components/clickable-card/ClickableCard.styles.ts
  src/components/clickable-card/ClickableCard.tsx
  src/components/popular-categories/PopularCategories.styles.ts
  src/components/popular-categories/PopularCategories.tsx
  src/constants/translations/en/common.json
  src/constants/translations/ua/common.json
  src/containers/student-home-page/popular-categories/PopularCategories.jsx
  src/containers/student-home-page/popular-categories/categories-list-mock.js
  src/hooks/use-categories-names.tsx
  src/pages/find-offers/FindOffers.jsx
  src/pages/student-home/StudentHome.jsx
  src/pages/student-home/StudentHome.tsx
  src/pages/subjects/Subjects.tsx
  src/types/services/services.types.ts
  tests/unit/components/popular-categories/PopularCategories.spec.jsx
  tests/unit/containers/student-home-page/popular-categories/PopularCategories.spec.jsx
  tests/unit/hooks/use-categories-names.spec.jsx
  tests/unit/pages/student-home/StudentHome.spec.jsx
Labels: Frontend part, feature

#595 Feature/474/offer card block square
  src/components/app-card/AppCard.tsx
  src/components/app-chip/AppChip.tsx
  src/components/img-title-description/ImgTitleDescription.styles.ts
  src/components/img-title-description/ImgTitleDescription.tsx
  src/components/title-with-description/TitleWithDescription.jsx
  src/constants/translations/en/common.json
  src/containers/find-offer/offer-card-square/OfferCardSquare.styles.ts
  src/containers/find-offer/offer-card-square/OfferCardSquare.tsx
  src/pages/find-offers/FindOffers.constants.ts
  src/types/common/common.index.ts
  src/types/common/enums/common.enums.ts
  src/types/common/interfaces/common.interfaces.ts
  src/types/index.ts
  src/types/offer/interfaces/offer.interfaces.ts
  src/types/offer/offer.index.ts
  src/types/offer/types/offer.types.ts
Labels: Frontend part, feature

#610 Converted AppPagination to TS
  src/components/app-pagination/AppPagination.jsx
  src/components/app-pagination/AppPagination.styles.ts
  src/components/app-pagination/AppPagination.tsx
  src/pages/find-offers/FindOffers.jsx
  src/stories/AppPagination.stories.jsx
  src/types/common/common.index.ts
  src/types/common/enums/common.enums.ts
  tests/unit/components/app-pagination/AppPagination.spec.jsx
Labels: Frontend part, TypeScript

#626 Fixed unauthorized error after reloading page
  .eslintrc.js
  src/containers/layout/app-main/AppMain.tsx
  src/containers/offer-page/create-offer/CreateOffer.tsx
  src/containers/offer-page/create-offer/specialization-block/SpecializationBlock.tsx
  src/containers/offer-page/create-offer/teaching-block/TeachingBlock.tsx
  src/hooks/use-redux.tsx
  src/pages/logout/Logout.tsx
  src/redux/reducer.ts
  src/redux/store.ts
  src/router/constants/guestRoutes.ts
  src/services/auth-service.js
  src/services/auth-service.ts
  src/services/local-storage-service.js
  src/services/local-storage-service.ts
  src/services/user-service.tsx
  src/types/common/common.index.ts
  src/types/index.ts
  src/types/services/services.types.ts
  src/types/user/user-enums/user.enums.ts
  src/types/user/user-interfaces/user.interfaces.ts
  src/types/user/user-types/user.types.ts
  src/types/user/user.index.ts
  src/utils/helper-functions.tsx
  tests/unit/components/layout/AppMain.spec.jsx
  tests/unit/pages/logout/Logout.spec.jsx
  tests/unit/redux/redux.spec.js
  tests/unit/redux/redux.variables.js
Labels: bug, Frontend part

#623 Added route for ofer details
  src/constants/translations/en/breadcrumbs.json
  src/constants/translations/ua/breadcrumbs.json
  src/pages/offer-details/OfferDetails.tsx
  src/router/constants/authRoutes.ts
  src/router/constants/crumbs.ts
  src/router/routes/authRouter.tsx
  tests/unit/components/layout/AppHeader.spec.jsx
Labels: Frontend part, feature

#648 Feature/602/convert title with description component to ts
  src/components/clickable-card/ClickableCard.styles.ts
  src/components/clickable-card/ClickableCard.tsx
  src/components/icon-with-text-list/ProfileDoneItemsList.jsx
  src/components/icon-with-text-list/ProfileDoneItemsList.style.js
  src/components/img-title-description/ImgTitleDescription.styles.ts
  src/components/img-title-description/ImgTitleDescription.tsx
  src/components/info-card/InfoCard.jsx
  src/components/info-card/InfoCard.styles.js
  src/components/popular-categories/PopularCategories.styles.ts
  src/components/popular-categories/PopularCategories.tsx
  src/components/title-block/TitleBlock.styles.ts
  src/components/title-block/TitleBlock.tsx
  src/components/title-with-description/TitleWithDescription.jsx
  src/components/title-with-description/TitleWithDescription.styles.ts
  src/components/title-with-description/TitleWithDescription.tsx
  src/containers/categories-page/explore-categories/ExploreCategories.jsx
  src/containers/categories-page/explore-categories/ExploreCategories.styles.js
  src/containers/email-confirm-modal/EmailConfirmModal.jsx
  src/containers/email-confirm-modal/EmailConfirmModal.styles.js
  src/containers/guest-home-page/WhatCanYouDo.jsx
  src/containers/guest-home-page/cards-with-button/CardsWithButton.jsx
  src/containers/guest-home-page/cards-with-button/CardsWithButton.styles.js
  src/containers/guest-home-page/forgot-password/ForgotPassword.jsx
  src/containers/guest-home-page/forgot-password/ForgotPassword.styles.js
  src/containers/guest-home-page/reset-password/ResetPassword.jsx
  src/containers/guest-home-page/reset-password/ResetPassword.styles.js
  src/containers/guest-home-page/styles/WhatCanYouDo.styles.js
  src/containers/guest-home-page/who-we-are/WhoWeAre.jsx
  src/containers/guest-home-page/who-we-are/WhoWeAre.styles.js
  src/containers/student-home-page/faq/Faq.jsx
  src/containers/student-home-page/faq/Faq.styles.js
  src/containers/student-home-page/popular-categories/PopularCategories.styles.js
  src/containers/student-home-page/student-how-it-works/StudentHowItWorks.jsx
  src/containers/student-home-page/student-how-it-works/student-how-it-works.styles.js
  src/containers/tutor-profile/profile-info/ProfileContainerDesktop.jsx
  src/containers/tutor-profile/profile-info/ProfileContainerMobile.jsx
  src/containers/tutor-profile/profile-info/ProfileInfo.jsx
  src/containers/tutor-profile/profile-info/ProfileInfo.styles.js
  src/pages/error/AuthPolicy.jsx
  src/pages/error/BadRequest.jsx
  src/pages/error/NotFound.jsx
  src/pages/error/styles/AuthPolicy.styles.js
  src/pages/error/styles/BadRequest.styles.js
  src/pages/error/styles/NotFound.styles.js
  src/pages/subjects/Subjects.styles.ts
  src/pages/subjects/Subjects.tsx
  src/stories/TitleWithDescription.stories.jsx
  tests/unit/components/title-with-description/TitleWithDescription.spec.jsx
Labels: Frontend part, feature

#649 Added wrapper and cart to offerDetails
  src/components/app-button/AppButton.tsx
  src/components/app-card/AppCard.tsx
  src/components/app-rating-mobile/AppRatingMobile.tsx
  src/components/img-title-description/ImgTitleDescription.tsx
  src/components/offer-card/OfferCard.jsx
  src/components/offer-card/OfferCard.styles.ts
  src/components/offer-card/OfferCard.tsx
  src/components/offer-card/offer-actions/OfferActions.styles.ts
  src/components/offer-card/offer-actions/OfferActions.tsx
  src/components/offer-card/offer-avatar-and-rating/OfferAvatarAndRating.styles.js
  src/components/offer-card/offer-details/OfferDetails.jsx
  src/components/title-with-description/TitleWithDescription.tsx
  src/constants/request.ts
  src/constants/translations/en/common.json
  src/containers/find-offer/offer-card-square/OfferCardSquare.styles.ts
  src/containers/find-offer/offer-card-square/OfferCardSquare.tsx
  src/containers/find-offer/offer-container/OfferContainer.tsx
  src/pages/find-offers/FindOffers.constants.ts
  src/pages/find-offers/FindOffers.jsx
  src/pages/offer-details/OfferDetails.styles.ts
  src/pages/offer-details/OfferDetails.tsx
  src/pages/offer-details/constants.ts
  src/services/offer-service.ts
  src/types/common/enums/common.enums.ts
  src/types/common/interfaces/common.interfaces.ts
  src/types/offer/interfaces/offer.interfaces.ts
  src/types/offer/offer.index.ts
  src/types/offer/types/offer.types.ts
  src/types/user/user-interfaces/user.interfaces.ts
  tests/unit/components/app-rating-mobile/AppRatingMobile.spec.jsx
  tests/unit/components/offer-card/offer-actions/OfferActions.spec.jsx
  tests/unit/containers/find-offer/offer-container/OfferContainer.spec.jsx
  tests/unit/pages/offer-details/OfferDetails.spec.jsx
Labels: Frontend part, feature

#654 Feature/566/Create search component
  src/components/search-filter-input/SearchFilterInput.styles.tsx
  src/components/search-filter-input/SearchFilterInput.tsx
  src/constants/translations/en/find-offer-page.json
  src/containers/find-offer/offer-search-toolbar/OfferSearchToolbar.styles.ts
  src/containers/find-offer/offer-search-toolbar/OfferSearchToolbar.tsx
  src/pages/find-offers/FindOffers.constants.ts
  src/pages/find-offers/FindOffers.styles.ts
  src/pages/find-offers/FindOffers.tsx
  src/types/findOffers/interfaces/findOffers.interfaces.ts
  tests/unit/components/search-filter-input/SearchFilterInput.spec.jsx
Labels: Frontend part, feature

#651 Added filters from filterbar to filters on offer page
  src/components/app-pagination/AppPagination.tsx
  src/components/app-range/AppRange.styles.ts
  src/components/app-range/AppRange.tsx
  src/components/app-select/AppSelect.styles.ts
  src/components/app-text-area/AppTextArea.tsx
  src/components/filter-input/FilterInput.tsx
  src/components/view-switcher/ViewSwitcher.tsx
  src/constants/index.ts
  src/constants/request.ts
  src/containers/find-offer/filter-bar-menu/FilterBarMenu.constants.ts
  src/containers/find-offer/filter-bar-menu/FilterBarMenu.tsx
  src/containers/find-offer/offer-container/OfferContainer.tsx
  src/containers/find-offer/offer-filter-block/OfferFilterBlock.tsx
  src/containers/find-offer/offer-filter-block/offer-filter-list/OfferFilterList.constants.ts
  src/containers/find-offer/offer-filter-block/offer-filter-list/OfferFilterList.tsx
  src/containers/find-offer/offer-search-toolbar/OfferSearchToolbar.tsx
  src/containers/offer-page/create-offer/specialization-block/SpecializationBlock.tsx
  src/containers/offer-page/create-offer/teaching-block/TeachingBlock.tsx
  src/hooks/use-filter-query.tsx
  src/hooks/use-form.tsx
  src/pages/find-offers/FindOffers.constants.ts
  src/pages/find-offers/FindOffers.tsx
  src/router/helpers/HomeRoute.tsx
  src/router/helpers/PrivateRoute.tsx
  src/services/offer-service.ts
  src/styles/app-theme/app.select.ts
  src/styles/app-theme/custom-mui.styles.js
  src/types/common/enums/common.enums.ts
  src/types/findOffers/enums/findOffers.enums.ts
  src/types/findOffers/interfaces/findOffers.interfaces.ts
  src/types/findOffers/types/findOffers.types.ts
  src/types/offer/interfaces/offer.interfaces.ts
  src/utils/count-active-filters.tsx
  src/utils/helper-functions.tsx
  src/utils/range-filter.tsx
  tests/unit/components/app-select/AppSelect.spec.jsx
  tests/unit/components/filter-input/FilterInput.spec.jsx
  tests/unit/components/view-switcher/ViewSwitcher.spec.jsx
  tests/unit/containers/find-offer/offer-filter-block/OfferFilterBlock.spec.jsx
  tests/unit/containers/offer-page/create-offer/CreateOffer.spec.jsx
Labels: Frontend part, feature
