Repository ita-social-projects/SpaceToStudy-Client, pull requests merged in 2023-07, with the labels that each got.

#933 Change container size
  src/components/input-with-icon/InputWithIcon.styles.ts
Labels: bug

#921 Feature/912/change view confirm modal
  src/components/app-drawer/AppDrawer.tsx
  src/components/confirm-dialog/ConfirmDialog.styles.ts
  src/components/confirm-dialog/ConfirmDialog.tsx
  src/constants/translations/en/common.json
  src/constants/translations/en/questions.json
  src/constants/translations/en/titles.json
  src/constants/translations/ua/common.json
  src/context/confirm-context.tsx
  src/hooks/use-confirm.tsx
Labels: Frontend part, feature

#913 fixed loader in myCooperations page
  src/components/app-button/AppButton.tsx
  src/components/loader/Loader.tsx
  src/containers/layout/footer/Footer.tsx
  src/pages/my-cooperations/MyCooperations.tsx
  src/pages/offer-details/OfferDetails.tsx
  src/redux/reducer.ts
  tests/unit/redux/redux.variables.js
Labels: Frontend part

#942 Implemented closing an offer and adding actions to the offer table
  src/components/enhanced-table/EnhancedTable.tsx
  src/components/enhanced-table/enhanced-table-head/EnhancedTableHead.jsx
  src/components/enhanced-table/enhanced-table-row/EnhancedTableRow.jsx
  src/constants/translations/en/common.json
  src/constants/translations/en/offer-details-page.json
  src/constants/translations/ua/common.json
  src/constants/translations/ua/offer-details-page.json
  src/containers/my-offers/my-offers-container/MyOffersContainer.tsx
  src/pages/offer-details/OfferDetails.constants.ts
  src/pages/offer-details/OfferDetails.tsx
  src/types/components/enhanced-table/enhancedTable.types.ts
  tests/unit/components/enhanced-table/enhanced-table-head/EnhancedTableHead.spec.jsx
  tests/unit/pages/offer-details/OfferDetails.spec.constants.js
  tests/unit/pages/offer-details/OfferDetails.spec.jsx
Labels: Frontend part, feature

#943 Write unit test for offerSearchToolbar component
  tests/unit/containers/find-offer/offer-search-toolbar/offerSearchToolbar.spec.jsx
Labels: Frontend part, test

#948 Added spaces between description blocks
  src/components/carousel-with-image/CarouselWithImage.styles.ts
Labels: good first issue, Frontend part, feature

#947 Change button's text according to the user roadmap
  src/containers/guest-home-page/cards-with-button/CardsWithButton.tsx
  src/containers/guest-home-page/how-it-works/HowItWorks.tsx
  tests/unit/containers/how-it-works/HowItWorks.spec.jsx
Labels: good first issue, Frontend part

#952 (SP:2) Create page My Resources
  src/constants/translations/en/breadcrumbs.json
  src/constants/translations/en/header.json
  src/constants/translations/en/index.ts
  src/constants/translations/en/my-resources-page.json
  src/constants/translations/ua/breadcrumbs.json
  src/constants/translations/ua/header.json
  src/constants/translations/ua/index.ts
  src/constants/translations/ua/my-resources-page.json
  src/pages/my-resources/MyResources.constants.tsx
  src/pages/my-resources/MyResources.styles.ts
  src/pages/my-resources/MyResources.tsx
  src/router/constants/authRoutes.ts
  src/router/constants/crumbs.ts
  src/router/constants/tutorRoutes.ts
  src/router/routes/authRouter.tsx
  tests/unit/pages/my-resources/MyResources.spec.jsx
Labels: Frontend part, feature
