Repository ita-social-projects/SpaceToStudy-Client, pull requests merged in 2023-05, with the labels that each got.

#666 Fixed names for a body in endpoints CreateOffer component
  src/containers/offer-page/create-offer/CreateOffer.constants.ts
  src/containers/offer-page/create-offer/CreateOffer.tsx
  src/containers/offer-page/create-offer/specialization-block/SpecializationBlock.tsx
Labels: bug, Frontend part

#663 Implemented No Found Result block
  src/assets/img/find-offer/search_icon.svg
  src/components/img-title-description/ImgTitleDescription.tsx
  src/components/not-found-results/NotFoundResults.styles.ts
  src/components/not-found-results/NotFoundResults.tsx
  src/constants/translations/en/constant.json
  src/pages/categories/Categories.tsx
  tests/unit/components/not-found-results/NotFoundResults.spec.jsx
  tests/unit/pages/categories/Categories.spec.jsx
Labels: Frontend part, feature

#661 Fixed footer and scroll for all pages
  src/assets/logo-light.svg
  src/components/scroll-to-top-button/ScrollToTopButton.jsx
  src/components/scroll-to-top-button/ScrollToTopButton.styles.ts
  src/components/scroll-to-top-button/ScrollToTopButton.tsx
  src/constants/translations/en/footer.json
  src/containers/app-content/AppContent.jsx
  src/containers/app-content/AppContent.styles.ts
  src/containers/app-content/AppContent.tsx
  src/containers/guest-home-page/styles/WhatCanYouDo.styles.js
  src/containers/layout/app-main/AppMain.tsx
  src/containers/layout/footer/Footer.jsx
  src/containers/layout/footer/Footer.styles.ts
  src/containers/layout/footer/Footer.tsx
  src/containers/layout/footer/footer-by-role/FooterByRole.styles.ts
  src/containers/layout/footer/footer-by-role/FooterByRole.tsx
  src/containers/layout/footer/guest-footer/GuestFooter.tsx
  src/containers/logo/Logo.jsx
  src/containers/logo/Logo.tsx
  src/pages/guest-home-page/GuestHome.tsx
  src/pages/student-home/StudentHome.tsx
  src/styles/index.css
  src/types/common/enums/common.enums.ts
  tests/unit/components/scroll-to-top-button/ScrollToTopButton.spec.jsx
  tests/unit/containers/footer/Footer.spec.jsx
Labels: bug, Frontend part

#675 Added functionality for pagination
  src/components/app-pagination/AppPagination.tsx
  src/components/enhanced-table/EnhancedTable.jsx
  src/components/enhanced-table/enhanced-table-head/EnhancedTableHead.jsx
  src/components/enhanced-table/enhanced-table-pagination/EnhancedTablePagination.jsx
  src/context/table-context.jsx
  src/hooks/table/use-pagination.jsx
  src/hooks/table/use-pagination.tsx
  src/hooks/use-axios.tsx
  src/pages/find-offers/FindOffers.constants.ts
  src/pages/find-offers/FindOffers.tsx
  src/types/findOffers/interfaces/findOffers.interfaces.ts
  tests/unit/components/app-pagination/AppPagination.spec.jsx
  tests/unit/components/enhanced-table/enhanced-table-pagination/EnhancedTablePagination.spec.jsx
  tests/unit/hooks/table/use-pagination.spec.jsx
Labels: Frontend part, feature

#677 Fixed adaptivity and styles for categories and finOffer
  src/components/app-card/AppCard.styles.ts
  src/components/app-toolbar/AppToolbar.styles.ts
  src/components/card-with-link/CardWithLink.styles.ts
  src/components/cards-list/CardsList.styles.ts
  src/components/cards-list/CardsList.tsx
  src/components/direction-link/DirectionLink.styles.ts
  src/components/filters-toggle/FiltersToggle.styles.ts
  src/components/loader/Loader.styles.ts
  src/components/offer-card/OfferCard.styles.ts
  src/components/offer-card/OfferCard.tsx
  src/components/offer-card/offer-actions/OfferActions.styles.ts
  src/components/offer-card/offer-actions/OfferActions.tsx
  src/components/offer-card/offer-avatar-and-rating/OfferAvatarAndRating.styles.js
  src/components/offer-card/offer-details/OfferDetails.jsx
  src/components/offer-card/offer-details/OfferDetails.styles.js
  src/components/ordered-list-item/OrderedListItem.styles.ts
  src/components/title-with-description/TitleWithDescription.tsx
  src/containers/find-offer/offer-card-square/OfferCardSquare.styles.ts
  src/containers/find-offer/offer-container/OfferContainer.tsx
  src/containers/find-offer/offer-filter-block/OfferFilterBlock.styles.ts
  src/containers/find-offer/offer-filter-block/OfferFilterBlock.tsx
  src/containers/offer-page/create-offer/CreateOffer.styles.ts
  src/pages/categories/Categories.tsx
  src/pages/find-offers/FindOffers.tsx
Labels: bug, Frontend part

#676 Added card for subjects
  src/pages/categories/Categories.styles.ts
  src/pages/subjects/Subjects.styles.ts
  src/pages/subjects/Subjects.tsx
  src/services/subject-service.ts
Labels: Frontend part, feature

#672 Fixed adaptivity for find-offer page
  src/components/search-filter-input/SearchFilterInput.styles.tsx
  src/components/search-filter-input/SearchFilterInput.tsx
  src/components/title-block/TitleBlock.styles.ts
  src/components/title-block/TitleBlock.tsx
  src/constants/translations/en/find-offer-page.json
  src/constants/translations/ua/find-offer-page.json
  src/containers/find-offer/offer-request-block/OfferRequestBlock.tsx
  src/containers/find-offer/offer-search-toolbar/OfferSearchToolbar.styles.ts
  src/containers/find-offer/offer-search-toolbar/OfferSearchToolbar.tsx
  src/pages/categories/Categories.tsx
  src/pages/find-offers/FindOffers.styles.ts
  src/pages/find-offers/FindOffers.tsx
  src/pages/subjects/Subjects.tsx
Labels: bug, Frontend part

#658 Accordion for FAQ
  src/components/accordion-with-image/AccordionWithImage.styles.ts
  src/components/accordion-with-image/AccordionWithImage.tsx
  src/components/accordion-with-image/accordion-with-image.constants.ts
  src/components/accordion/Accordion.styles.ts
  src/components/accordion/Accordions.jsx
  src/components/accordion/Accordions.tsx
  src/components/multi-accordion-with-title/MultiAccordionWIthTitle.tsx
  src/components/multi-accordion-with-title/MultiAccordionWithTitle.styles.ts
  src/containers/student-home-page/faq/Faq.styles.ts
  src/containers/student-home-page/faq/Faq.tsx
  src/containers/student-home-page/faq/accordionItems.ts
  src/stories/Accordion.stories.jsx
  src/stories/MultiAccordionWithTitle.stories.jsx
  src/types/common/enums/common.enums.ts
  src/types/common/types/common.types.ts
  src/types/components/accordion-with-image/accordionWithImage.interface.ts
  src/types/components/accordions/accordions.enum.ts
  src/types/components/accordions/accordions.interface.ts
  src/types/components/components.index.ts
  src/types/components/multi-accordion-with-title/multiAccordionWithTitle.interface.ts
  tests/unit/components/accordion/Accordions.spec.jsx
  tests/unit/components/multi-accordion-with-title/MultiAccordionWithTitle.spec.jsx
Labels: Frontend part, feature

#684 Fixed gap and added not found block to findOffer page
  src/components/direction-link/DirectionLink.styles.ts
  src/components/not-found-results/NotFoundResults.styles.ts
  src/components/not-found-results/NotFoundResults.tsx
  src/components/popular-categories/PopularCategories.styles.ts
  src/constants/translations/en/find-offer-page.json
  src/constants/translations/en/subjects-page.json
  src/constants/translations/ua/subjects-page.json
  src/containers/find-offer/offer-search-toolbar/OfferSearchToolbar.styles.ts
  src/pages/find-offers/FindOffers.styles.ts
  src/pages/find-offers/FindOffers.tsx
  src/pages/subjects/Subjects.styles.ts
Labels: bug

#713 created EnrollOffer component
  src/components/app-select/AppSelect.styles.ts
  src/components/app-select/AppSelect.tsx
  src/components/app-text-area/AppTextArea.styles.ts
  src/components/app-text-area/AppTextArea.tsx
  src/constants/request.ts
  src/constants/translations/en/button.json
  src/constants/translations/en/common.json
  src/constants/translations/en/index.js
  src/constants/translations/en/offer-details-page.json
  src/constants/translations/ua/button.json
  src/constants/translations/ua/index.js
  src/constants/translations/ua/offer-details-page.json
  src/containers/find-offer/offer-card-square/OfferCardSquare.styles.ts
  src/containers/find-offer/offer-card-square/OfferCardSquare.tsx
  src/containers/find-offer/offer-container/OfferContainer.tsx
  src/containers/offer-details/enroll-offer/EnrollOffer.styles.ts
  src/containers/offer-details/enroll-offer/EnrollOffer.tsx
  src/hooks/use-form.tsx
  src/pages/offer-details/OfferDetails.tsx
  src/pages/offer-details/constants.ts
  src/services/cooperation-service.ts
  src/types/components/appSelect/appSelect.types.ts
  src/types/index.ts
  src/types/offer-details/interfaces/offerDetails.interfaces.ts
  src/types/offer-details/offerDetails.index.ts
  src/types/offer/interfaces/offer.interfaces.ts
  tests/unit/containers/find-offer/offer-card-square/OfferCardSquare.spec.jsx
  tests/unit/containers/offer-details/enroll-offer/EnrollOffer.spec.jsx
  tests/unit/pages/offer-details/OfferDetails.spec.jsx
Labels: Frontend part, feature

#704 implemented student steppers
  src/components/file-uploader/FileUploader.styles.js
  src/components/step-wrapper/StepWrapper.jsx
  src/components/user-steps-wrapper/UserStepsWrapper.tsx
  src/components/user-steps-wrapper/constants.ts
  src/constants/translations/en/become-tutor.json
  src/constants/translations/en/index.js
  src/constants/translations/en/step.json
  src/containers/tutor-home-page/general-info-step/GeneralInfoStep.jsx
  src/containers/tutor-home-page/language-step/LanguageStep.jsx
  src/context/step-context.jsx
  src/pages/student-home/StudentHome.tsx
  src/pages/tutor-home/TutorHome.jsx
  tests/unit/components/step-wrapper/StepWrapper.spec.jsx
  tests/unit/components/step-wrapper/TempComponent.jsx
  tests/unit/components/user-steps-wrapper/UserStepsWrapper.spec.jsx
  tests/unit/containers/mentor-home-page/add-photo-step/AddPhotoStep.spec.jsx
  tests/unit/containers/mentor-home-page/general-info-step/GeneralInfoStep.spec.jsx
  tests/unit/containers/mentor-home-page/language-step/LanguageStep.spec.jsx
  tests/unit/containers/mentor-home-page/subjects-step/SubjectsStep.spec.jsx
  tests/unit/pages/student-home/StudentHome.spec.jsx
Labels: Frontend part, feature

#718 Added route for my cooperations
  src/constants/translations/en/breadcrumbs.json
  src/constants/translations/en/header.json
  src/constants/translations/ua/breadcrumbs.json
  src/constants/translations/ua/header.json
  src/pages/my-cooperations/MyCooperations.styles.ts
  src/pages/my-cooperations/MyCooperations.tsx
  src/router/constants/crumbs.ts
  src/router/constants/studentRoutes.ts
  src/router/constants/tutorRoutes.ts
  src/router/routes/studentRouter.tsx
  src/router/routes/tutorRouter.tsx
Labels: Frontend part, feature

#705 Implemented functionality for view details button
  src/components/offer-card/offer-actions/OfferActions.tsx
  src/containers/find-offer/offer-card-square/OfferCardSquare.styles.ts
  src/containers/find-offer/offer-card-square/OfferCardSquare.tsx
  src/containers/find-offer/offer-container/OfferContainer.tsx
  src/router/constants/authRoutes.ts
  src/types/offer/interfaces/offer.interfaces.ts
  tests/unit/containers/find-offer/offer-card-square/OfferCardSquare.spec.jsx
Labels: Frontend part, feature

#708 Implemented sending data to backEnd
  src/components/step-wrapper/StepWrapper.jsx
  src/components/user-steps-wrapper/constants.ts
  src/constants/request.ts
  src/constants/translations/en/become-tutor.json
  src/constants/translations/ua/become-tutor.json
  src/containers/tutor-home-page/general-info-step/GeneralInfoStep.jsx
  src/containers/tutor-home-page/language-step/LanguageStep.jsx
  src/hooks/use-steps.jsx
  src/services/user-service.tsx
  src/types/user/user-interfaces/user.interfaces.ts
  tests/unit/components/step-wrapper/StepWrapper.spec.jsx
  tests/unit/containers/mentor-home-page/general-info-step/GeneralInfoStep.spec.jsx
Labels: Frontend part, feature

#721 Added carousel library, created offerCarousel
  package-lock.json
  package.json
  src/components/app-carousel/AppCarousel.tsx
  src/components/checkbox-list/CheckboxList.tsx
  src/constants/translations/en/find-offer-page.json
  src/constants/translations/ua/find-offer-page.json
  src/containers/find-offer/offer-card-square/OfferCardSquare.styles.ts
  src/containers/find-offer/offer-card-square/OfferCardSquare.tsx
  src/containers/find-offer/offer-filter-block/offer-filter-list/OfferFilterList.tsx
  src/containers/offer-details/offer-carousel/OfferCarousel.styles.ts
  src/containers/offer-details/offer-carousel/OfferCarousel.tsx
  src/pages/find-offers/FindOffers.constants.ts
  src/pages/find-offers/FindOffers.tsx
  src/pages/offer-details/OfferDetails.tsx
  src/pages/offer-details/constants.ts
  src/types/findOffers/interfaces/findOffers.interfaces.ts
  src/types/offer/interfaces/offer.interfaces.ts
  tests/unit/containers/offer-details/offer-carousel/OfferCarousel.spec.jsx
Labels: Frontend part, feature

#725 added about offer block to offerDetails page
  src/components/show-more-collapse/ShowMoreCollapse.styles.ts
  src/components/show-more-collapse/ShowMoreCollapse.tsx
  src/constants/translations/en/common.json
  src/constants/translations/ua/common.json
  src/pages/offer-details/OfferDetails.styles.ts
  src/pages/offer-details/OfferDetails.tsx
  tests/unit/components/show-more-collapse/ShowMoreCollapse.spec.jsx
Labels: Frontend part, feature

#715 fix some modal styles and loader styles
  src/components/cards-list/CardsList.styles.ts
  src/components/cards-list/CardsList.tsx
  src/containers/email-confirm-modal/EmailConfirmModal.styles.js
Labels: Frontend part, feature

#727 Created CreateNewSubject component
  src/components/app-text-area/AppTextArea.styles.ts
  src/components/app-text-area/AppTextArea.tsx
  src/components/async-autocomlete/AsyncAutocomplete.tsx
  src/components/popup-dialog/PopupDialog.styles.ts
  src/components/popup-dialog/PopupDialog.tsx
  src/components/popup-dialog/popup-dialog.style.js
  src/constants/translations/en/button.json
  src/constants/translations/en/categories-page.json
  src/constants/translations/ua/button.json
  src/constants/translations/ua/categories-page.json
  src/containers/email-confirm-modal/EmailConfirmModal.jsx
  src/containers/find-offer/create-new-subject/CreateNewSubject.constants.ts
  src/containers/find-offer/create-new-subject/CreateNewSubject.styles.ts
  src/containers/find-offer/create-new-subject/CreateNewSubject.tsx
  src/containers/guest-home-page/WhatCanYouDo.jsx
  src/containers/guest-home-page/cards-with-button/CardsWithButton.jsx
  src/containers/guest-home-page/forgot-password/ForgotPassword.jsx
  src/containers/guest-home-page/google-button/GoogleButton.jsx
  src/containers/guest-home-page/google-login/GoogleLogin.jsx
  src/containers/guest-home-page/login-dialog/LoginDialog.jsx
  src/containers/guest-home-page/login-form/LoginForm.jsx
  src/containers/guest-home-page/signup-dialog/SignupDialog.jsx
  src/containers/navigation-icons/NavigationIcons.jsx
  src/containers/offer-details/enroll-offer/EnrollOffer.tsx
  src/containers/offer-page/create-offer/CreateOffer.tsx
  src/context/modal-context.jsx
  src/context/modal-context.tsx
  src/hooks/use-steps.jsx
  src/pages/categories/Categories.tsx
  src/pages/guest-home-page/GuestHome.tsx
  src/pages/offer-details/OfferDetails.tsx
  src/pages/student-home/StudentHome.tsx
  src/pages/subjects/Subjects.tsx
  src/pages/tutor-home/TutorHome.jsx
  src/stories/PopupDialog.stories.jsx
  tests/unit/containers/find-offer/create-new-subject/CreateNewSubject.spec.jsx
  tests/unit/containers/guest-home-page/google-login/GoogleLogin.spec.jsx
  tests/unit/pages/guest-home/GuestHome.spec.jsx
Labels: Frontend part, feature

#731 Added adaptivity for offerCard on offerDetails page
  src/components/app-chips-list/AppChipsList-styles.ts
  src/components/offer-card/OfferCard.tsx
  src/components/offer-card/offer-actions/OfferActions.tsx
  src/containers/find-offer/offer-card-square/OfferCardSquare.styles.ts
  src/containers/find-offer/offer-card-square/OfferCardSquare.tsx
  src/containers/find-offer/offer-container/OfferContainer.tsx
  src/pages/offer-details/OfferDetails.styles.ts
  src/pages/offer-details/OfferDetails.tsx
  src/types/offer/interfaces/offer.interfaces.ts
  tests/unit/containers/find-offer/offer-container/OfferContainer.spec.jsx
  tests/unit/pages/offer-details/OfferDetails.spec.jsx
Labels: Frontend part, feature

#744 Created faq block in Create Offer
  src/components/app-text-area/AppTextArea.styles.ts
  src/components/app-text-area/AppTextArea.tsx
  src/components/checkbox-list/CheckboxList.tsx
  src/components/ordered-list-item/OrderedListItem.styles.ts
  src/constants/translations/en/button.json
  src/constants/translations/en/offer-page.json
  src/constants/translations/ua/button.json
  src/constants/translations/ua/offer-page.json
  src/containers/offer-page/create-offer/CreateOffer.constants.ts
  src/containers/offer-page/create-offer/CreateOffer.styles.ts
  src/containers/offer-page/create-offer/CreateOffer.tsx
  src/containers/offer-page/create-offer/faq-block/FaqBlock.tsx
  src/containers/offer-page/create-offer/specialization-block/SpecializationBlock.tsx
  src/containers/offer-page/create-offer/teaching-block/TeachingBlock.tsx
  src/services/offer-service.ts
  src/types/common/interfaces/common.interfaces.ts
  src/types/findOffers/interfaces/findOffers.interfaces.ts
  src/types/offer/interfaces/offer.interfaces.ts
  src/utils/checkbox-list.tsx
  src/utils/helper-functions.tsx
Labels: Frontend part, feature

#726 Added title block to offer details
  src/assets/img/offer-details/top-block-icon.png
  src/components/title-block/TitleBlock.styles.ts
  src/components/title-block/TitleBlock.tsx
  src/constants/translations/en/offer-details-page.json
  src/constants/translations/ua/offer-details-page.json
  src/pages/offer-details/OfferDetails.tsx
Labels: Frontend part, feature

#733 Fixed card square
  src/components/img-title-description/ImgTitleDescription.tsx
  src/containers/find-offer/offer-card-square/OfferCardSquare.styles.ts
  src/containers/find-offer/offer-card-square/OfferCardSquare.tsx
Labels: bug, Frontend part

#738 feature/subject-stepper-implementation-2
  src/containers/tutor-home-page/subjects-step/SubjectsStep.jsx
  tests/unit/containers/mentor-home-page/subjects-step/SubjectsStep.spec.jsx
Labels: Frontend part, feature

#736 Сreate card for cooperations, and two smaller components for it
  src/components/comment/Comment.tsx
  src/components/languages-list-with-icon/LanguagesListWithIcon.styles.ts
  src/components/languages-list-with-icon/LanguagesListWithIcon.tsx
  src/components/offer-card/offer-details/OfferDetails.jsx
  src/components/offer-card/offer-details/OfferDetails.styles.js
  src/components/status-chip/StatusChip.styles.ts
  src/components/status-chip/StatusChip.tsx
  src/containers/find-offer/offer-card-square/OfferCardSquare.styles.ts
  src/containers/find-offer/offer-card-square/OfferCardSquare.tsx
  src/containers/my-cooperations/cooperation-card/CooperationCard.styles.ts
  src/containers/my-cooperations/cooperation-card/CooperationCard.tsx
  src/pages/my-cooperations/MyCooperations.tsx
  src/stories/LanguagesListWithIcon.stories.jsx
  src/stories/StatusChip.stories.jsx
  src/styles/app-theme/app.pallete.ts
  src/types/common/enums/common.enums.ts
  src/types/cooperation/cooperation.index.ts
  src/types/cooperation/interfaces/cooperation.interface.ts
  src/types/index.ts
  src/utils/helper-functions.tsx
  tests/unit/containers/my-cooperations/cooperation-card/CooperationCard.spec.jsx
Labels: Frontend part, feature

#732 Added faq block to offer details and made responsive mobile
  src/components/accordion/Accordion.styles.ts
  src/components/accordion/Accordions.tsx
  src/components/multi-accordion-with-title/MultiAccordionWIthTitle.tsx
  src/components/multi-accordion-with-title/MultiAccordionWithTitle.styles.ts
  src/constants/translations/en/offer-details-page.json
  src/constants/translations/ua/offer-details-page.json
  src/pages/offer-details/OfferDetails.styles.ts
  src/pages/offer-details/OfferDetails.tsx
  src/pages/offer-details/constants.ts
  src/stories/MultiAccordionWithTitle.stories.jsx
  src/types/components/accordions/accordions.interface.ts
  src/types/components/components.index.ts
Labels: Frontend part, feature

#737 added general info block to offer details page
  src/components/icon-title-description/IconTitleDescription.styles.ts
  src/components/icon-title-description/IconTitleDescription.tsx
  src/components/title-with-description/TitleWithDescription.tsx
  src/constants/translations/en/common.json
  src/constants/translations/en/offer-details-page.json
  src/constants/translations/ua/common.json
  src/constants/translations/ua/offer-details-page.json
  src/containers/find-offer/offer-card-square/OfferCardSquare.tsx
  src/containers/offer-details/offer-general-info/OfferGeneralInfo.styles.ts
  src/containers/offer-details/offer-general-info/OfferGeneralInfo.tsx
  src/pages/offer-details/OfferDetails.tsx
  src/stories/IconTitleDescription.stories.jsx
  src/types/common/enums/common.enums.ts
  tests/unit/components/icon-title-desxription/IconTitleDescription.spec.jsx
  tests/unit/containers/offer-details/offer-general-info/OfferGeneralInfo.spec.jsx
Labels: Frontend part, feature

#771 bugFix/624/description-text-change
  src/constants/translations/en/guest-home-page.json
Labels: bug, good first issue, UI/Usability, severity: minor, priority: low

#747 Added title to offer card
  src/components/offer-card/OfferCard.tsx
  src/components/offer-card/offer-avatar-and-rating/OfferAvatarAndRating.jsx
  src/components/offer-card/offer-avatar-and-rating/OfferAvatarAndRating.styles.js
  src/components/offer-card/offer-details/OfferDetails.jsx
  src/components/offer-card/offer-details/OfferDetails.styles.js
  src/containers/find-offer/offer-card-square/OfferCardSquare.styles.ts
  src/containers/find-offer/offer-card-square/OfferCardSquare.tsx
Labels: Frontend part, feature

#778 Fixed focus on google button and added focus on forgot password
  src/containers/guest-home-page/google-button/GoogleButton.jsx
  src/containers/guest-home-page/google-button/GoogleButton.styles.js
  src/containers/guest-home-page/login-form/LoginForm.jsx
  src/containers/guest-home-page/login-form/LoginForm.styles.js
Labels: bug

#750 Created blocks for cooperation page
  src/components/app-pagination/AppPagination.tsx
  src/components/input-with-icon/InputWithIcon.styles.ts
  src/components/input-with-icon/InputWithIcon.tsx
  src/components/page-wrapper/PageWrapper.styles.ts
  src/components/page-wrapper/PageWrapper.tsx
  src/components/search-filter-input/SearchFilterInput.styles.tsx
  src/components/search-filter-input/SearchFilterInput.tsx
  src/components/status-chip/StatusChip.styles.ts
  src/components/view-switcher/ViewSwitcher.styles.ts
  src/components/view-switcher/ViewSwitcher.tsx
  src/constants/translations/en/button.json
  src/constants/translations/en/cooperations-page.json
  src/constants/translations/en/index.js
  src/constants/translations/ua/button.json
  src/constants/translations/ua/cooperations-page.json
  src/constants/translations/ua/index.js
  src/containers/app-content/AppContent.styles.ts
  src/containers/find-offer/offer-search-toolbar/OfferSearchToolbar.tsx
  src/containers/my-cooperations/cooperation-card/CooperationCard.styles.ts
  src/containers/my-cooperations/cooperation-toolbar/CooperationToolbar.styles.ts
  src/containers/my-cooperations/cooperation-toolbar/CooperationToolbar.tsx
  src/containers/my-cooperations/cooperations-container/CooperationContainer.styles.ts
  src/containers/my-cooperations/cooperations-container/CooperationContainer.tsx
  src/pages/my-cooperations/MyCooperations.styles.ts
  src/pages/my-cooperations/MyCooperations.tsx
  src/stories/InputWithIcon.stories.jsx
  tests/unit/components/search-filter-input/SearchFilterInput.spec.jsx
  tests/unit/containers/my-cooperations/cooperation-container/CooperationContainer.spec.jsx
  tests/unit/containers/my-cooperations/cooperation-toolbar/CooperationToolbar.spec.jsx
Labels: Frontend part, feature

#764 Fixex amount of items for categories and subjects page. And added error handle for stepper.
  src/hooks/use-load-more.tsx
  src/hooks/use-steps.jsx
Labels: bug, feature

#754 Fixed width and height for all cards
  src/components/languages-list-with-icon/LanguagesListWithIcon.styles.ts
  src/containers/find-offer/offer-card-square/OfferCardSquare.styles.ts
  src/containers/find-offer/offer-container/OfferContainer.styles.ts
  src/containers/find-offer/offer-container/OfferContainer.tsx
  src/containers/offer-details/enroll-offer/EnrollOffer.styles.ts
  src/containers/offer-details/offer-carousel/OfferCarousel.styles.ts
Labels: bug, feature

#759 Fixed login button clickable on empty inputs
  src/containers/guest-home-page/login-form/LoginForm.jsx
Labels: bug, good first issue, Functional, priority: very low, severity: trivial

#784 fixed btn flashing
  src/components/popup-dialog/PopupDialog.tsx
Labels: bug, good first issue, severity: minor, Functional, priority: low

#776 renamed name field to search in offer filters
  src/containers/find-offer/offer-filter-block/offer-filter-list/OfferFilterList.tsx
  src/pages/find-offers/FindOffers.constants.ts
  src/types/findOffers/interfaces/findOffers.interfaces.ts
Labels: Frontend part

#760 642/mistake-in-popup-message
  src/constants/translations/en/login.json
Labels: bug, good first issue, UI/Usability, severity: minor, priority: low

#762 Fixed password confirmation bug
  src/constants/translations/en/common.json
  src/utils/validations/login.js
Labels: bug, good first issue, priority: medium, Functional, severity: major

#781 fixed bugs with input
  src/utils/validations/common.ts
Labels: bug, good first issue, severity: minor, priority: medium, Functional

#783 Changed some files to ts
  src/App.tsx
  src/constants/translations/en/index.ts
  src/constants/translations/index.ts
  src/constants/translations/ua/index.ts
  src/plugins/i18n.ts
  src/plugins/report-web-vitals.js
  src/plugins/report-web-vitals.ts
  src/redux/store.ts
  src/services/example-service.ts
  src/services/location-service.ts
  src/services/setup-interceptors.ts
  src/styles/app-theme/app.checkbox.ts
  src/styles/app-theme/app.menu-item.ts
  src/styles/app-theme/app.menu-list.ts
  src/styles/app-theme/app.select.ts
  src/styles/app-theme/app.svgicon.ts
  src/styles/app-theme/app.table.ts
  src/styles/app-theme/app.textfield.ts
  src/styles/app-theme/app.tooltip.ts
  src/styles/app-theme/app.typography.ts
  src/styles/app-theme/custom-animations.ts
  src/styles/app-theme/custom-mui.styles.ts
  src/styles/app-theme/custom-scrollbar.ts
  src/utils/hash-scroll.ts
  src/utils/image-resize.ts
  tests/unit/utils/image-resize.spec.jsx
Labels: Frontend part, feature

#786 Added tabs, hooks and request to cooperations page
  src/components/app-button/AppButton.tsx
  src/components/app-select/AppSelect.tsx
  src/components/enhanced-table/enhanced-table-pagination/EnhancedTablePagination.jsx
  src/components/enhanced-table/filter-row/FilterRow.jsx
  src/components/tab/Tab.jsx
  src/components/tab/Tab.styles.ts
  src/components/tab/Tab.tsx
  src/components/user-table/UserTable.jsx
  src/constants/request.ts
  src/constants/translations/en/cooperations-page.json
  src/constants/translations/en/find-offer-page.json
  src/constants/translations/ua/cooperations-page.json
  src/constants/translations/ua/find-offer-page.json
  src/containers/my-cooperations/cooperation-card/CooperationCard.tsx
  src/containers/my-cooperations/cooperation-toolbar/CooperationToolbar.tsx
  src/containers/offer-details/enroll-offer/EnrollOffer.tsx
  src/hooks/table/use-filter.jsx
  src/hooks/table/use-filter.tsx
  src/hooks/table/use-pagination.tsx
  src/hooks/use-filter-query.tsx
  src/pages/find-offers/FindOffers.tsx
  src/pages/my-cooperations/MyCooperations.constants.ts
  src/pages/my-cooperations/MyCooperations.styles.ts
  src/pages/my-cooperations/MyCooperations.tsx
  src/services/cooperation-service.ts
  src/types/components/components.index.ts
  src/types/components/tab/tab.types.ts
  src/types/index.ts
  src/types/my-cooperations/interfaces/myCooperations.interfaces.ts
  src/types/my-cooperations/myCooperations.index.ts
  src/types/offer-details/interfaces/offerDetails.interfaces.ts
  tests/unit/containers/my-cooperations/cooperation-container/CooperationContainer.spec.jsx
  tests/unit/containers/my-cooperations/cooperation-toolbar/CooperationToolbar.spec.jsx
  tests/unit/hooks/table/use-filter.spec.jsx
  tests/unit/hooks/table/use-pagination.spec.jsx
Labels: Frontend part, feature

#769 Fixed title text “Share your experience” is shown in two lines in the tutor registration block.
  src/components/info-card/InfoCard.styles.js
Labels: bug, good first issue, UI/Usability, severity: minor, priority: low

#782 Added ammount of reviews according to figma
  src/components/offer-card/OfferCard.tsx
  src/components/offer-card/offer-actions/OfferActions.tsx
  src/components/offer-card/offer-avatar-and-rating/OfferAvatarAndRating.jsx
  src/components/offer-card/offer-avatar-and-rating/OfferAvatarAndRating.styles.js
  src/types/offer/interfaces/offer.interfaces.ts
Labels: Frontend part
