Repository ita-social-projects/SpaceToStudy-Client, pull requests merged in 2024-07, with the labels that each got.

#1980 fix wrong rendering of svg
  src/assets/img/guest-home-page/map.svg
Labels: bug, Frontend part, severity: minor, hacktoberfest

#1990 Resolved interpolation issue of subject and category #1981
  src/constants/translations/en/categories-page.json
  src/constants/translations/en/subjects-page.json
  src/constants/translations/ua/categories-page.json
  src/constants/translations/ua/error-messages.json
  src/constants/translations/ua/subjects-page.json
  src/pages/categories/Categories.tsx
  src/pages/subjects/Subjects.tsx
  src/utils/get-translation-suffixes.tsx
  tests/unit/utils/get-translation-suffixes.spec.jsx
Labels: bug, Frontend part

#2000 Make CardWithLink component accept SVG icon and color
  src/components/card-with-link/CardWithLink.styles.ts
  src/components/card-with-link/CardWithLink.tsx
  src/components/popular-categories/PopularCategories.tsx
  src/pages/categories/Categories.tsx
  src/pages/subjects/Subjects.tsx
  src/services/category-icon-service.ts
  src/types/common/interfaces/common.interfaces.ts
  tests/unit/components/card-with-link/CardWithLink.spec.jsx
  tests/unit/components/popular-categories/PopularCategories.spec.jsx
  tests/unit/pages/categories/Categories.spec.jsx
  tests/unit/services/category-icon-service.spec.js
Labels: enhancement, Frontend part, feature

#2011 Added tests for AddProfessionalCategoryModal container
  tests/unit/containers/edit-profile/professional-info-tab/add-professional-category-modal/AddProfessionalCategoryModal.spec.jsx
Labels: Frontend part, test

#1975 Fixed translation of proficiency / preparation levels #1964
  src/components/checkbox-list/CheckboxList.tsx
  src/constants/labels.ts
  src/containers/offer-page/specialization-block/SpecializationBlock.tsx
  tests/unit/components/checkbox-list/CheckboxList.spec.jsx
  tests/unit/containers/offer-page/specialization-block/SpecializationBlock.spec.jsx
Labels: bug, Frontend part

#2002 Fixed "Login" pop-up scaling issue #1038
  src/containers/guest-home-page/login-dialog/LoginDialog.jsx
  src/containers/guest-home-page/login-dialog/LoginDialog.styles.js
Labels: bug, severity: minor, Functional, priority: low

#2043 Fix passwordAlphabeticAndNumeric regex
  src/utils/validations/validations.constants.ts
Labels: bug, Frontend part, severity: major, priority: high

#2047 Convert conditional to a boolean to avoid leaked value in UserTable.jsx
  src/components/user-table/UserTable.jsx
Labels: bug, Frontend part

#2013 Fixed translation on the Home Page and the input's width in the TitleBlock
  src/components/title-block/TitleBlock.styles.ts
  src/constants/translations/en/student-home-page.json
  src/constants/translations/en/tutor-home-page.json
  src/scss/src/atoms/Button.scss
Labels: bug, Frontend part

#2044 Made View more visible for Categories
  src/components/cards-list/CardsList.styles.ts
  src/components/cards-list/CardsList.tsx
  src/pages/categories/Categories.constants.tsx
  src/pages/categories/Categories.tsx
  tests/unit/components/cards-list/CardsList.spec.jsx
Labels: bug, Frontend part, feature

#2048 Fix AdminNavBar
  src/containers/layout/admin-portal/admin-nav-bar/AdminNavBar.jsx
Labels: bug, admin

#2032 Fixed typos in tests
  tests/unit/components/accordion/Accordions.spec.jsx
  tests/unit/components/app-range/AppRange.spec.jsx
  tests/unit/components/page-wrapper/PageWrapper.spec.jsx
  tests/unit/containers/app-breadcrumbs/AppBreadCrumbs.spec.jsx
  tests/unit/containers/course-section/resources-list/ResourcesList.spec.jsx
  tests/unit/containers/edit-profile/professional-info-tab/about-tutor-accordion/AboutTutorAccordion.spec.jsx
  tests/unit/containers/find-course/courses-filters/CoursesFilters.spec.jsx
  tests/unit/containers/find-offer/offer-container/OfferContainer.spec.jsx
  tests/unit/containers/guest-home-page/reset-password/ResetPassword.spec.jsx
  tests/unit/containers/offer-page/create-offer/CreateOffer.spec.jsx
  tests/unit/containers/student-home-page/faq/Faq.spec.jsx
  tests/unit/containers/tutor-home-page/language-step/LanguageStep.spec.jsx
  tests/unit/pages/guest-home/GuestHome.spec.jsx
  tests/unit/router/router.spec.jsx
  tests/unit/utils/image-resize.spec.jsx
Labels: bug, Frontend part, test

#2030 Implemented sorting categories in popular categories block
  src/components/popular-categories/PopularCategories.tsx
Labels: enhancement, Frontend part, feature

#2040 Redesign categories and subjects
  src/constants/translations/en/edit-profile.json
  src/constants/translations/ua/edit-profile.json
  src/containers/edit-profile/professional-info-tab/professional-category/ProfessionalCategory.styles.ts
  src/containers/edit-profile/professional-info-tab/professional-category/ProfessionalCategory.tsx
  src/types/edit-profile/interfaces/editProfile.interfaces.ts
  src/utils/get-validated-hex-color.tsx
  tests/unit/containers/edit-profile/professional-info-tab/professional-category/ProfessionalCategory.spec.jsx
  tests/unit/utils/get-validated-hex-color.spec.js
Labels: enhancement, Frontend part, Tutor, Student

#2054 Increased a CooperationActivitiesView.tsx coverage
  tests/unit/containers/cooperation-details/ CooperationActivitiesView.spec.jsx
Labels: Frontend part, test

#2045 Centered "View more" and "Go to categories" buttons
  src/scss/src/atoms/Button.scss
Labels: bug, Frontend part

#2049 Fixed icons for quiz options
  src/components/question-editor/QuestionEditor.constants.tsx
  src/containers/add-resources/AddQuestions.constants.tsx
  src/utils/check-icons.tsx
Labels: bug, Frontend part

#2052 Increase ProfessionalCategoryList.tsx coverage
  tests/unit/containers/edit-profile/professional-info-tab/professional-category-list/ProfessionalCategoryList.spec.jsx
Labels: Frontend part, test

#2051 Fixed lesson and quiz icons in edit and saved mode
  src/components/cooperation-section-view/CooperationSectionView.styles.ts
  src/components/cooperation-section-view/CooperationSectionView.tsx
  src/containers/course-section/CourseSectionContainer.tsx
  src/containers/course-section/resource-item/ResourceItem.tsx
  src/containers/course-section/resources-list/ResourcesList.styles.ts
  src/types/course/interfaces/course.interface.ts
Labels: bug, Frontend part

#2056 (SP: 0.5) Refactored spotted typescript errors
  src/components/cooperation-section-view/CooperationSectionView.styles.ts
  src/containers/cooperation-details/cooperetion-activities-view/CooperationActivitiesView.tsx
  src/types/course/interfaces/course.interface.ts
Labels: bug, Frontend part

#2068 Added new categories icons
  src/services/category-icon-service.ts
  tests/unit/services/category-icon-service.spec.js
Labels: Frontend part, feature, Tutor, Student

#2069 Fix EmptyCooperationActivities styles
  src/containers/my-cooperations/empty-cooperation-activities/EmptyCooperationActivities.styles.ts
  src/containers/my-cooperations/empty-cooperation-activities/EmptyCooperationTutorControls.tsx
Labels: bug, Frontend part, Tutor

#2077 Fixed Add and Cancel buttons on AddResourceModal
  src/containers/my-resources/add-resource-modal/AddResourceModal.styles.ts
  src/containers/my-resources/add-resource-modal/AddResourceModal.tsx
  src/pages/create-or-edit-lesson/CreateOrEditLesson.tsx
Labels: bug, Frontend part

#2079 Fixed quiz and lesson description
  src/containers/my-quizzes/create-or-edit-quiz-container/CreateOrEditQuizContainer.tsx
  src/pages/create-or-edit-lesson/CreateOrEditLesson.styles.ts
  src/pages/create-or-edit-lesson/CreateOrEditLesson.tsx
Labels: bug, Frontend part

#2009 Fixed "My resources" page to match with Figma
  src/components/app-button-menu/AppButtonMenu.styles.ts
  src/components/app-button-menu/AppButtonMenu.tsx
  src/components/enhanced-table/EnhancedTable.styles.ts
  src/constants/translations/en/my-resources-page.json
  src/containers/add-documents/AddDocuments.styles.ts
  src/containers/my-quizzes/QuizzesContainer.tsx
  src/containers/my-resources/add-resource-with-input/AddResourceWithInput.styles.ts
  src/containers/my-resources/add-resource-with-input/AddResourceWithInput.tsx
  src/containers/my-resources/attachments-container/AttachmentsContainer.tsx
  src/containers/my-resources/categories-container/CategoriesContainer.style.ts
  src/containers/my-resources/categories-container/CategoriesContainer.tsx
  src/containers/my-resources/lessons-container/LessonsContainer.tsx
  src/containers/my-resources/questions-container/QuestionsContainer.tsx
  tests/unit/containers/my-resources/AddResourceWithInput.spec.jsx
Labels: enhancement, Frontend part

#2060 Removed the js extension from imports in custom-mui file
  src/styles/app-theme/custom-mui.styles.ts
Labels: bug, Frontend part

#2097 Replaced 'ua' with 'uk' to ensure i18n detects the correct plural forms for Ukrainian language in the whole project
  src/constants/translations/index.ts
  src/constants/translations/uk/admin.json
  src/constants/translations/uk/become-tutor.json
  src/constants/translations/uk/breadcrumbs.json
  src/constants/translations/uk/button.json
  src/constants/translations/uk/categories-page.json
  src/constants/translations/uk/chat.json
  src/constants/translations/uk/common.json
  src/constants/translations/uk/complete-profile.json
  src/constants/translations/uk/cookie-consent-banner.json
  src/constants/translations/uk/cookie-policy-page.json
  src/constants/translations/uk/cooperation-details.json
  src/constants/translations/uk/cooperations-page.json
  src/constants/translations/uk/course.json
  src/constants/translations/uk/edit-profile.json
  src/constants/translations/uk/email-modals.json
  src/constants/translations/uk/error-messages.json
  src/constants/translations/uk/error-page.json
  src/constants/translations/uk/errors.json
  src/constants/translations/uk/filters.json
  src/constants/translations/uk/find-offer-page.json
  src/constants/translations/uk/footer.json
  src/constants/translations/uk/guest-home-page.json
  src/constants/translations/uk/header.json
  src/constants/translations/uk/icons-tooltip.json
  src/constants/translations/uk/index.ts
  src/constants/translations/uk/lesson.json
  src/constants/translations/uk/login.json
  src/constants/translations/uk/my-courses-page.json
  src/constants/translations/uk/my-offers-page.json
  src/constants/translations/uk/my-resources-page.json
  src/constants/translations/uk/offer-details-page.json
  src/constants/translations/uk/offer-page.json
  src/constants/translations/uk/question-page.json
  src/constants/translations/uk/questions.json
  src/constants/translations/uk/quiz.json
  src/constants/translations/uk/signup.json
  src/constants/translations/uk/step.json
  src/constants/translations/uk/student-home-page.json
  src/constants/translations/uk/subjects-page.json
  src/constants/translations/uk/table.json
  src/constants/translations/uk/titles.json
  src/constants/translations/uk/tutor-home-page.json
  src/constants/translations/uk/user-profile-page.json
  src/constants/translations/uk/user-table.json
  src/containers/layout/language-menu/LanguageMenu.constants.ts
  src/plugins/i18n.ts
  src/utils/get-translation-suffixes.tsx
  tests/unit/utils/get-translation-suffixes.spec.jsx
Labels: bug, Frontend part

#2082 Fixed a GoogleButton size and the text under when the website language is 'ua
  src/containers/guest-home-page/google-login/GoogleLogin.jsx
  src/containers/guest-home-page/google-login/GoogleLogin.styles.js
Labels: bug, Frontend part

#2101 Fixed translation on Home Page for tutor and student for 'ua' language
  src/constants/translations/uk/student-home-page.json
  src/constants/translations/uk/tutor-home-page.json
Labels: bug, Frontend part

#2104 Rewrite AppPopover to tsx format and fix the sonar issues
  src/components/app-popover/AppPopover.tsx
Labels: TypeScript, sonarFix

#2083 Rewrite profile edit
  src/containers/edit-profile/password-security-tab/PasswordSecurityTab.tsx
  src/containers/edit-profile/profile-tab/ProfileTab.tsx
  src/hooks/use-form.tsx
  src/pages/edit-profile/EditProfile.constants.tsx
  src/pages/edit-profile/EditProfile.tsx
  src/redux/features/editProfileSlice.ts
  src/types/edit-profile/interfaces/editProfile.interfaces.ts
  tests/test-utils.jsx
  tests/unit/containers/edit-profile/ProfileTab.spec.jsx
  tests/unit/hooks/use-form.spec.jsx
  tests/unit/pages/edit-profile/EditProfile.spec.jsx
  tests/unit/redux/editProfileSlice.spec.js
Labels: Frontend part, Tutor, Student

#2105 Rewrite EnhancedTableRow to tsx format and fix the sonar issues
  src/components/enhanced-table/enhanced-table-row/EnhancedTableRow.tsx
Labels: TypeScript, sonarFix

#2106 rewrote AppProgressBarLine to tsx format and fixed the sonar issues
  src/components/app-progress-bar-line/AppProgressBarLine.styles.ts
  src/components/app-progress-bar-line/AppProgressBarLine.tsx
  src/components/complete-profile/CompleteProfileBlock.jsx
Labels: TypeScript, sonarFix

#2108 Rewrote CompleteProfileBlock to tsx format and fix the sonar issues
  src/components/complete-profile/CompleteProfileBlock.styles.ts
  src/components/complete-profile/CompleteProfileBlock.tsx
  src/components/profile-item/complete-profile.constants.tsx
Labels: TypeScript, sonarFix

#2098 Rewrote NotificationTab with redux
  src/containers/edit-profile/notification-tab/NotificationTab.constants.tsx
  src/containers/edit-profile/notification-tab/NotificationTab.styles.ts
  src/containers/edit-profile/notification-tab/NotificationTab.tsx
  src/types/edit-profile/interfaces/editProfile.interfaces.ts
  tests/unit/containers/edit-profile/notification-tab/NotificationTab.spec.jsx
Labels: Frontend part, Tutor, Student

#2109 Rewrote DragAndDrop to tsx format and fix the sonar issues
  src/components/drag-and-drop/DragAndDrop.jsx
  src/components/drag-and-drop/DragAndDrop.tsx
  src/containers/tutor-home-page/add-photo-step/AddPhotoStep.style.js
Labels: TypeScript, sonarFix

#2110 Rewrote professional info tab using redux
  src/containers/edit-profile/professional-info-tab/ProfessionalInfoTab.tsx
  src/containers/edit-profile/professional-info-tab/about-tutor-accordion/AboutTutorAccordion.constants.tsx
  src/containers/edit-profile/professional-info-tab/add-professional-category-modal/AddProfessionalCategoryModal.tsx
  src/containers/edit-profile/professional-info-tab/professional-category/ProfessionalCategory.tsx
  src/pages/edit-profile/EditProfile.constants.tsx
  src/redux/features/editProfileSlice.ts
  src/types/edit-profile/types/editProfile.types.ts
  tests/unit/containers/edit-profile/professional-info-tab/ProfessionalInfoTab.spec.jsx
  tests/unit/containers/edit-profile/professional-info-tab/add-professional-category-modal/AddProfessionalCategoryModal.spec.jsx
  tests/unit/redux/editProfileSlice.spec.js
Labels: Frontend part, Tutor, Student

#2150 Fixed 'Cannot read property of undefined'
  src/redux/features/editProfileSlice.ts
Labels: bug, Frontend part

#2151 Deleted old data fetching implementation from EditProfile component
  src/containers/edit-profile/password-security-tab/PasswordSecurityTab.tsx
  src/pages/edit-profile/EditProfile.constants.tsx
  src/pages/edit-profile/EditProfile.tsx
  tests/unit/containers/edit-profile/password-security-tab/PasswordSecurityTab.spec.jsx
Labels: enhancement, Frontend part, feature

#2187 Expanded workflow triggers to include feature branches #2186
  .github/workflows/main.yaml
Labels: Frontend part, devOps

#2232 Deleted sonar.branch.name
  sonar-project.properties
Labels: bug, enhancement, Frontend part, devOps

#2155 Rewrite EnhancedTableHead to tsx
  src/components/enhanced-table/enhanced-table-head/EnhancedTableHead.styles.ts
  src/components/enhanced-table/enhanced-table-head/EnhancedTableHead.tsx
  src/types/components/enhanced-table/enhancedTable.interface.ts
Labels: TypeScript, sonarFix

#2156 Rewrite EnhancedTableHeaderCell to tsx format
  src/components/enhanced-table/enhanced-table-header-cell/EnhancedTableHeaderCell.styles.ts
  src/components/enhanced-table/enhanced-table-header-cell/EnhancedTableHeaderCell.tsx
Labels: TypeScript, sonarFix

#2159 Rewrite EnhancedTablePagination to tsx
  src/components/enhanced-table/enhanced-table-pagination/EnhancedTablePagination.styles.ts
  src/components/enhanced-table/enhanced-table-pagination/EnhancedTablePagination.tsx
  src/types/components/enhanced-table/enhancedTable.interface.ts
Labels: TypeScript, sonarFix

#2162 Rewrite EnhancedTableToolbar to typescript
  src/components/enhanced-table/enhanced-table-toolbar/EnhancedTableToolbar.styles.ts
  src/components/enhanced-table/enhanced-table-toolbar/EnhancedTableToolbar.tsx
  src/services/user-service.tsx
  src/types/components/enhanced-table/enhancedTable.types.ts
  tests/unit/components/enhanced-table/enhanced-table-toolbar/EnhancedTableToolbar.spec.jsx
Labels: TypeScript, sonarFix

#2161 Updated dependencies related to testing
  package.json
  vitest.config.mts
Labels: Frontend part, dependency

#2167 Updated Vite package
  package.json
  tsconfig.node.json
  vite.config.mts
Labels: Frontend part, dependency

#2196 Updated eslint package, migrated to the new eslint config system
  .eslintignore
  .eslintrc.js
  eslint.config.mjs
  package.json
  sonar-project.properties
  tsconfig.eslint.json
Labels: Frontend part, dependency

#2218 Updated husky package and husky hooks
  .husky/pre-commit
  .husky/pre-push
  package.json
Labels: Frontend part, dependency
