Repository ita-social-projects/SpaceToStudy-Client, pull requests merged in 2024-09, with the labels that each got.

#2414 Fixed error "cannot read properties of undefined student" when loading the Profile page for a student #2413
  src/redux/features/editProfileSlice.ts
Labels: bug, Frontend part

#2440 Fix translations of the level preparation on My Courses page
  src/constants/labels.ts
  src/constants/translations/en/common.json
  src/constants/translations/uk/common.json
  src/containers/my-courses/courses-filters-drawer/CoursesFiltersDrawer.tsx
  src/types/common/enums/common.enums.ts
  tests/unit/components/file-component/FileComponent.spec.jsx
  tests/unit/containers/my-courses/courses-filters-drawer/CoursesFiltersDrawer.spec.jsx
  tests/unit/pages/chat/messages-list/MessagesList.spec.jsx
Labels: bug, Frontend part

#2419 Configured Stylelint package
  .stylelintrc.json
  package-lock.json
  package.json
  src/scss/_mixins.scss
  src/scss/_reset.scss
  src/scss/_root.scss
  src/scss/_variables.scss
  src/scss/styles.scss
  src/stories/button.css
  src/styles/index.css
Labels: Frontend part, dependency

#2442 Photo step - TS bugfix
  src/containers/tutor-home-page/add-photo-step/AddPhotoStep.tsx
  src/context/step-context.tsx
  src/types/common/interfaces/common.interfaces.ts
Labels: bug, TypeScript

#2448 Fixed typescript error in OfferCardSquare.tsx
  src/containers/find-offer/offer-card-square/OfferCardSquare.tsx
Labels: bug, Frontend part

#2427 Fixed translation on the Offer details page
  src/constants/translations/en/offer-details-page.json
  src/constants/translations/uk/offer-details-page.json
Labels: bug, Tutor

#2434 (SP: 0.5 ) Fixed translation for tutor and student for a Reviews blog on the Offer Details page after clicking View details on the offer.
  src/pages/offer-details/OfferDetails.tsx
Labels: bug, Frontend part, Tutor, Student

#2435 ( SP: 0.5 )Fixed title on My offers page for UK translation.
  src/constants/translations/uk/my-offers-page.json
Labels: bug, Frontend part, Tutor

#2441 Fix text on the filter drawer on My Courses page
  src/constants/translations/uk/my-courses-page.json
Labels: bug, Frontend part

#2447 Added spacing utility classes
  src/components/app-button/AppButton.scss
  src/scss/_functions.scss
  src/scss/_mixins.scss
  src/scss/_root.scss
  src/scss/_variables.scss
  src/scss/styles.scss
  src/scss/utilities.scss
  src/scss/utilities/_index.scss
  src/scss/utilities/spacing.scss
Labels: Frontend part, design system, scss

#2451 ( SP: 1) Fixed toggling bookmark on OfferDetails
  src/containers/find-offer/offer-container/OfferContainer.tsx
  src/pages/offer-details/OfferDetails.tsx
  src/utils/toggle-bookmark.ts
  tests/unit/pages/offer-details/OfferDetails.spec.jsx
Labels: bug, Frontend part, Tutor, Student

#2474 Reverted changes and fixed translations of the level preparation
  src/constants/labels.ts
  src/constants/translations/en/common.json
  src/constants/translations/uk/common.json
  src/containers/my-courses/courses-filters-drawer/CoursesFiltersDrawer.tsx
  src/types/common/enums/common.enums.ts
Labels: bug, Frontend part

#2467 Added background color utility classes
  src/scss/utilities/_index.scss
  src/scss/utilities/background.scss
Labels: Frontend part, design system, scss

#2469 Fixed location bug in user profile
  src/components/icon-with-text-list/ProfileDoneItemsList.style.ts
  src/components/icon-with-text-list/ProfileDoneItemsList.tsx
Labels: bug, good first issue, Frontend part

#2470 Successfully verified email message( confirm email modal)
  src/containers/email-confirm-modal/EmailConfirmModal.tsx
  src/hooks/use-axios.tsx
Labels: bug

#2473 Apptextarea style for counter/2456
  src/components/app-text-area/AppTextArea.styles.ts
  src/components/app-text-area/AppTextArea.tsx
  src/containers/offer-page/teaching-block/TeachingBlock.tsx
Labels: bug, enhancement

#2465 Fix sorting functionality on student page (What tutors say)
  src/containers/user-profile/comments-with-rating-block/CommentsWithRatingBlock.constants.ts
  src/containers/user-profile/comments-with-rating-block/CommentsWithRatingBlock.tsx
Labels: bug, Frontend part, Student

#2476 Fixed all of the warnings during tests run
  src/components/app-select/AppSelect.tsx
  src/containers/edit-profile/professional-info-tab/professional-category/ProfessionalCategory.tsx
  src/containers/user-profile/comments-with-rating-block/CommentsWithRatingBlock.constants.ts
  src/pages/subjects/Subjects.tsx
  tests/unit/components/changing-confirm/ChangingConfirm.spec.jsx
  tests/unit/components/cooperation-section-view/CooperationSectionView.spec.jsx
  tests/unit/containers/course-section/resources-list/ResourcesList.spec.jsx
  tests/unit/containers/course-sections-list/CourseSectionsList.spec.jsx
  tests/unit/containers/edit-profile/professional-info-tab/add-professional-category-modal/AddProfessionalCategoryModal.spec.jsx
  tests/unit/containers/find-offer/offer-search-toolbar/offerSearchToolbar.spec.jsx
  tests/unit/containers/guest-home-page/signup-dialog/SignupDialog.spec.jsx
  tests/unit/containers/my-cooperations/cooperation-notes/create-or-edit-note/CreateOrEditNote.spec.jsx
  tests/unit/containers/my-courses/add-course-with-input/AddCourseWithInput.spec.jsx
  tests/unit/containers/my-courses/course-toolbar/CourseToolbar.spec.jsx
  tests/unit/containers/my-courses/courses-filters-drawer/CoursesFiltersDrawer.spec.jsx
  tests/unit/containers/navigation-icons/AccountIcon.spec.jsx
  tests/unit/containers/navigation-icons/NavigationIcons.spec.jsx
  tests/unit/containers/offer-page/faq-block/FaqBlock.spec.jsx
  tests/unit/containers/tutor-profile/ProfileInfo.spec.jsx
  tests/unit/pages/chat/Chat.spec.jsx
  tests/unit/pages/chat/messages-list/MessagesList.spec.jsx
  tests/unit/pages/create-course/CreateCourse.spec.jsx
  tests/unit/pages/my-courses/MyCourses.spec.jsx
  tests/unit/pages/subjects/Subjects.spec.jsx
  tests/unit/pages/tutor-profile/TutorProfile.spec.jsx
Labels: Frontend part, test

#2482 Added flexbox utility classes
  src/scss/_mixins.scss
  src/scss/utilities/_index.scss
  src/scss/utilities/flexbox.scss
  src/scss/utilities/spacing.scss
Labels: Frontend part, design system, scss

#2487 Added sizing utility classes
  src/scss/utilities/_index.scss
  src/scss/utilities/sizing.scss
Labels: Frontend part, design system, scss

#2500 Added shadow utility classes
  src/scss/utilities/_index.scss
  src/scss/utilities/shadow.scss
Labels: Frontend part, design system, scss

#2496 Added typography classes
  src/scss/_functions.scss
  src/scss/_typography.scss
  src/scss/styles.scss
Labels: Frontend part, design system, scss

#2449 (SP: 0.5) Fixed price overlapping the bookmark
  src/components/offer-card/offer-actions/OfferActions.styles.ts
  src/containers/find-offer/offer-card-square/OfferCardSquare.styles.ts
  src/containers/find-offer/offer-container/OfferContainer.styles.ts
Labels: bug, Frontend part, Tutor, Student

#2428 Refactored: Simplified React Components by Extracting Function #2418
  src/containers/course-section/resource-item/ResourceItem.constants.ts
  src/containers/course-section/resource-item/ResourceItem.tsx
  src/containers/my-cooperations/cooperation-activities-list/CooperationActivitiesList.tsx
  src/pages/create-course/CreateCourse.handlers.ts
  src/pages/create-course/CreateCourse.tsx
  src/types/common/events/enums/events.enums.ts
  src/types/common/events/events.index.ts
  src/types/common/events/interfaces/events.interfaces.ts
  src/types/common/events/types/events.types.ts
  src/types/common/interfaces/common.interfaces.ts
  src/types/course/interfaces/course.interface.ts
  src/types/index.ts
  tests/unit/pages/create-course/CreateCourse.handlers.spec.jsx
  vitest.config.ts
Labels: Frontend part

#2228 Fix incorrect translation of description
  src/constants/translations/en/offer-details-page.json
  src/constants/translations/uk/offer-details-page.json
Labels: bug, Frontend part

#2444 Add active students block
  src/components/active-students/ActiveStudent.styles.ts
  src/components/active-students/ActiveStudent.tsx
  src/components/active-students/ActiveStudentsBlock.styles.ts
  src/components/active-students/ActiveStudentsBlock.tsx
  src/constants/translations/en/active-students.json
  src/constants/translations/en/index.ts
  src/constants/translations/uk/active-students.json
  src/constants/translations/uk/index.ts
  src/pages/tutor-home/TutorHome.tsx
  tests/unit/components/active-students/ActiveStudent.spec.jsx
  tests/unit/components/active-students/ActiveStudentsBlock.spec.jsx
Labels: Frontend part, feature

#2445 Fix burger menu
  src/containers/layout/account-menu/AccountMenu.tsx
  src/containers/layout/navbar/NavBar.tsx
  src/router/constants/authRoutes.ts
Labels: bug, Frontend part

#2484 Add text color utility classes
  src/scss/utilities/_index.scss
  src/scss/utilities/colors.scss
Labels: Frontend part, design system, scss

#2502 Fix lastest message still visible after clearing chat
  src/containers/chat/chat-item/ChatItem.tsx
  src/containers/layout/chat-menu/ChatMenu.tsx
  src/types/chat/interfaces/chat.interfaces.ts
Labels: bug, Frontend part

#2495 Removed media and files from the chat sidebar
  src/components/sidebar-content-box/SidebarContentBox.tsx
  src/containers/about-chat-sidebar/AboutChatSidebar.tsx
  src/containers/chat/sidebar-grouped-content/SidebarGroupedContent.tsx
  src/pages/chat/Chat.tsx
  src/types/chat/enum/chat.enums.ts
  tests/unit/containers/about-chat-sidebar/AboutChatSidebar.spec.jsx
Labels: bug, Frontend part

#2501 Fixed input in the mini chat
  src/containers/chat/chat-text-area/ChatTextArea.tsx
  src/containers/offer-page/chat-dialog-window/ChatDialogWindow.styles.ts
  src/containers/offer-page/chat-dialog-window/ChatDialogWindow.tsx
  src/types/chat/enum/chat.enums.ts
Labels: bug, Frontend part

#2426 Refactor the bookmarks page
  src/constants/translations/en/bookmarked-offers-page.json
  src/constants/translations/uk/bookmarked-offers-page.json
  src/pages/bookmarked-offers/BookmarkedOffers.tsx
  tests/unit/pages/bookmarked-offers/BookmarkedOffers.spec.jsx
Labels: Frontend part, Tutor, Student

#2455 (SP: 0.5) Fixed videoLink deletion on the Edit Profile.
  src/pages/edit-profile/EditProfile.tsx
Labels: bug, Frontend part, Tutor, Student

#2499 Down-stepper and up-stepper icons should be inactive
  src/components/icons-with-counter/IconsWithCounter.tsx
  tests/unit/containers/chat/sidebar-grouped-content/SidebarGroupedContent.spec.jsx
Labels: bug, Frontend part

#2513 Fix cooperation details visual bugs
  src/components/subject-level-chips/SubjectLevelChips.styles.ts
  src/containers/my-cooperations/my-cooperations-details/MyCooperationsDetails.styles.ts
  src/containers/my-cooperations/my-cooperations-details/MyCooperationsDetails.tsx
Labels: bug, Frontend part

#2518 Implemented border utility
  src/scss/_variables.scss
  src/scss/utilities/_index.scss
  src/scss/utilities/borders.scss
Labels: Frontend part, feature

#2439 (SP: 0.5) Fixed button on policy banner
  src/components/app-button/AppButton.scss
  src/containers/cookie-consent-banner/CookieConsentBanner.styles.ts
  src/containers/cookie-consent-banner/CookieConsentBanner.tsx
Labels: bug, Frontend part

#2524 Fixed tests that fall sometimes
  src/components/active-students/ActiveStudent.tsx
  src/components/app-chip/AppChip.tsx
  tests/unit/pages/create-course/CreateCourse.spec.jsx
  tests/unit/pages/my-courses/MyCourses.spec.jsx
Labels: Frontend part, test

#2514 Feature/2486/add search by user name on the chat page
  src/components/filter-input/FilterInput.tsx
  src/containers/chat/chat-item/ChatItem.tsx
  src/containers/chat/list-of-users-with-search/ListOfUsersWithSearch.constants.ts
  src/containers/chat/list-of-users-with-search/ListOfUsersWithSearch.tsx
  tests/unit/components/filter-input/FilterInput.spec.jsx
  tests/unit/components/message/Message.spec.jsx
  tests/unit/containers/chat/list-of-users-with-search/ListOfUsersWithSearch.spec.jsx
  tests/unit/containers/chat/list-of-users-with-search/MockChat.constants.js
  tests/unit/containers/my-courses/courses-filters-drawer/CoursesFiltersDrawer.spec.jsx
  tests/unit/containers/offer-page/chat-dialog-window/ChatDialogWindow.spec.jsx
  tests/unit/pages/bookmarked-offers/BookmarkedOffers.spec.jsx
  tests/unit/pages/chat/Chat.spec.jsx
  tests/unit/pages/chat/ChatsMock.constants.js
Labels: feature

#2531 Fixed margin in the SubjectLevelChips component
  src/components/subject-level-chips/SubjectLevelChips.styles.ts
  src/containers/my-cooperations/my-cooperations-details/MyCooperationsDetails.styles.ts
  src/containers/my-cooperations/my-cooperations-details/MyCooperationsDetails.tsx
Labels: bug, Frontend part

#2532 Fixed the bookmark icon position on the offer details page
  src/pages/offer-details/OfferDetails.styles.ts
Labels: bug, Frontend part

#2519 Contacts should be listed in ascending order
  src/components/active-students/ActiveStudent.tsx
  src/components/app-button/AppButton.scss
  src/components/app-chip/AppChip.tsx
  src/components/cooperation-section-view/CooperationSectionView.tsx
  src/components/filter-input/FilterInput.tsx
  src/components/icons-with-counter/IconsWithCounter.tsx
  src/containers/chat/chat-item/ChatItem.tsx
  src/containers/chat/list-of-users-with-search/ListOfUsersWithSearch.constants.ts
  src/containers/chat/list-of-users-with-search/ListOfUsersWithSearch.tsx
  src/containers/cookie-consent-banner/CookieConsentBanner.styles.ts
  src/containers/cookie-consent-banner/CookieConsentBanner.tsx
  src/containers/course-section/CourseSectionContainer.tsx
  src/containers/course-section/resource-item/ResourceItem.tsx
  src/containers/course-section/resources-list/ResourcesList.tsx
  src/containers/my-cooperations/cooperation-activities-list/CooperationActivitiesList.tsx
  src/containers/my-cooperations/my-cooperations-details/MyCooperationsDetails.styles.ts
  src/containers/my-cooperations/my-cooperations-details/MyCooperationsDetails.tsx
  src/pages/edit-profile/EditProfile.tsx
  src/pages/offer-details/OfferDetails.styles.ts
  src/redux/features/cooperationsSlice.ts
  src/scss/_variables.scss
  src/scss/utilities/_index.scss
  src/scss/utilities/borders.scss
  src/types/common/events/enums/events.enums.ts
  src/types/common/events/interfaces/events.interfaces.ts
  src/types/common/events/types/events.types.ts
  src/types/course/interfaces/course.interface.ts
  src/types/my-resources/interfaces/myResources.interface.ts
  tests/unit/components/filter-input/FilterInput.spec.jsx
  tests/unit/components/message/Message.spec.jsx
  tests/unit/containers/chat/list-of-users-with-search/ListOfUsersWithSearch.spec.jsx
  tests/unit/containers/chat/list-of-users-with-search/MockChat.constants.js
  tests/unit/containers/chat/list-of-users-with-search/MockChat.spec.constants.js
  tests/unit/containers/chat/sidebar-grouped-content/SidebarGroupedContent.spec.jsx
  tests/unit/containers/course-section/CourseSectionContainer.spec.constants.js
  tests/unit/containers/course-section/CourseSectionContainer.spec.jsx
  tests/unit/containers/course-section/resource-item/ResourceItem.spec.constants.js
  tests/unit/containers/course-section/resource-item/ResourceItem.spec.jsx
  tests/unit/containers/course-section/resources-list/ResourcesList.spec.jsx
  tests/unit/containers/my-courses/courses-filters-drawer/CoursesFiltersDrawer.spec.jsx
  tests/unit/containers/offer-page/chat-dialog-window/ChatDialogWindow.spec.jsx
  tests/unit/pages/bookmarked-offers/BookmarkedOffers.spec.jsx
  tests/unit/pages/chat/Chat.spec.jsx
  tests/unit/pages/create-course/CreateCourse.spec.jsx
  tests/unit/pages/my-courses/MyCourses.spec.jsx
  tests/unit/redux/cooperationsSlice.spec.js
Labels: Frontend part, feature

#2517 Fix minichat messages order
  src/containers/offer-page/chat-dialog-window/ChatDialogWindow.tsx
Labels: enhancement, Frontend part

#2530 Create tests for videolink logic from EditProfile.tsx
  src/components/app-text-field/AppTextField.tsx
  src/containers/course-section/CourseSectionContainer.tsx
  tests/unit/pages/edit-profile/EditProfile.spec.jsx
Labels: Frontend part, test

#2544 Revert "implement function for sorting chats by date (#2519)"
  src/components/active-students/ActiveStudent.tsx
  src/components/app-button/AppButton.scss
  src/components/app-chip/AppChip.tsx
  src/components/cooperation-section-view/CooperationSectionView.tsx
  src/components/filter-input/FilterInput.tsx
  src/components/icons-with-counter/IconsWithCounter.tsx
  src/containers/chat/chat-item/ChatItem.tsx
  src/containers/chat/list-of-users-with-search/ListOfUsersWithSearch.constants.ts
  src/containers/chat/list-of-users-with-search/ListOfUsersWithSearch.tsx
  src/containers/cookie-consent-banner/CookieConsentBanner.styles.ts
  src/containers/cookie-consent-banner/CookieConsentBanner.tsx
  src/containers/course-section/CourseSectionContainer.tsx
  src/containers/course-section/resource-item/ResourceItem.tsx
  src/containers/course-section/resources-list/ResourcesList.tsx
  src/containers/my-cooperations/cooperation-activities-list/CooperationActivitiesList.tsx
  src/containers/my-cooperations/my-cooperations-details/MyCooperationsDetails.styles.ts
  src/containers/my-cooperations/my-cooperations-details/MyCooperationsDetails.tsx
  src/pages/edit-profile/EditProfile.tsx
  src/pages/offer-details/OfferDetails.styles.ts
  src/redux/features/cooperationsSlice.ts
  src/scss/_variables.scss
  src/scss/utilities/_index.scss
  src/scss/utilities/borders.scss
  src/types/common/events/enums/events.enums.ts
  src/types/common/events/interfaces/events.interfaces.ts
  src/types/common/events/types/events.types.ts
  src/types/course/interfaces/course.interface.ts
  src/types/my-resources/interfaces/myResources.interface.ts
  tests/unit/components/filter-input/FilterInput.spec.jsx
  tests/unit/components/message/Message.spec.jsx
  tests/unit/containers/chat/list-of-users-with-search/ListOfUsersWithSearch.spec.jsx
  tests/unit/containers/chat/list-of-users-with-search/MockChat.constants.js
  tests/unit/containers/chat/sidebar-grouped-content/SidebarGroupedContent.spec.jsx
  tests/unit/containers/course-section/CourseSectionContainer.spec.constants.js
  tests/unit/containers/course-section/CourseSectionContainer.spec.jsx
  tests/unit/containers/course-section/resource-item/ResourceItem.spec.constants.js
  tests/unit/containers/course-section/resource-item/ResourceItem.spec.jsx
  tests/unit/containers/course-section/resources-list/ResourcesList.spec.jsx
  tests/unit/containers/my-courses/courses-filters-drawer/CoursesFiltersDrawer.spec.jsx
  tests/unit/containers/offer-page/chat-dialog-window/ChatDialogWindow.spec.jsx
  tests/unit/pages/bookmarked-offers/BookmarkedOffers.spec.jsx
  tests/unit/pages/chat/Chat.spec.jsx
  tests/unit/pages/chat/ChatsMock.constants.js
  tests/unit/pages/create-course/CreateCourse.spec.jsx
  tests/unit/pages/my-courses/MyCourses.spec.jsx
  tests/unit/redux/cooperationsSlice.spec.js
Labels: bug, Frontend part, hotfix, priority: high

#2541 2510/feature/mini chat window and default open chat
  src/containers/offer-page/chat-dialog-window/ChatDialogWindow.tsx
  src/pages/chat/Chat.tsx
  tests/unit/pages/chat/Chat.spec.jsx
Labels: Frontend part, feature

#2534 Fixed search inputs on the find offer page
  src/components/search-filter-input/SearchFilterInput.styles.tsx
  src/constants/translations/en/find-offer-page.json
  src/constants/translations/uk/find-offer-page.json
  src/containers/find-offer/offer-filter-block/offer-filter-list/OfferFilterList.tsx
  src/containers/find-offer/offer-search-toolbar/OfferSearchToolbar.styles.ts
Labels: bug, Frontend part

#2545 Redirect on certain routes in Courses and Cooperation
  src/containers/course-section/CourseSectionContainer.tsx
  tests/unit/containers/course-section/CourseSectionContainer.spec.constants.js
Labels: Frontend part, feature

#2553 Rewrited ChangeConfirm component to use modal context
  src/components/changing-confirm/ChangeConfirm.tsx
  src/constants/translations/en/change-confirm.json
  src/constants/translations/uk/change-confirm.json
  src/containers/change-resource-confirm-modal/ChangeResourceConfirmModal.styles.ts
  src/containers/change-resource-confirm-modal/ChangeResourceConfirmModal.tsx
  src/containers/my-quizzes/create-or-edit-quiz-container/CreateOrEditQuizContainer.tsx
  src/hooks/use-change-confirm.tsx
  src/hooks/use-form.tsx
  src/pages/create-or-edit-lesson/CreateOrEditLesson.tsx
  tests/unit/components/changing-confirm/ChangingConfirm.spec.jsx
  tests/unit/containers/change-resource-confirm-modal/ChangeResourceConfirmModal.spec.jsx
  tests/unit/pages/create-or-edit-lesson/CreateOrEditLessonWithId.spec.jsx
Labels: enhancement, Frontend part, feature

#2250 Fix banners
  src/components/app-button/AppButton.tsx
  src/components/offer-banner/OfferBanner.styles.ts
  src/components/offer-banner/OfferBanner.tsx
Labels: bug, Frontend part

#2547 Changed length of chart search input
  src/components/search-by-message/SearchByMessage.tsx
Labels: Frontend part

#2265 Adjust Dialog Width
  src/containers/my-resources/add-resource-modal/AddResourceModal.styles.ts
Labels: bug, Frontend part

#2511 Fix accordion design
  src/containers/user-profile/about-tutor-block/AboutTutorBlock.styles.tsx
Labels: bug, Frontend part, Tutor

#2546 Contacts should be listed in ascending order
  src/containers/chat/list-of-users-with-search/ListOfUsersWithSearch.constants.ts
Labels: Frontend part, feature

#2535 Implemented possibility of adding new resources with same availability
  src/containers/course-section/resource-item/ResourceItem.tsx
  tests/unit/components/cooperation-section-view/CooperationSectionView.spec.jsx
Labels: bug, Frontend part

#2539 Fixed text according to figma
  src/constants/translations/en/chat.json
Labels: bug, Frontend part

#2550 Implemented validation for OpenFrom
  src/containers/cooperation-details/cooperation-activities/CooperationActivities.constants.tsx
  src/containers/cooperation-details/cooperation-activities/CooperationActivities.tsx
  tests/unit/containers/cooperation-details/cooperation-activities/CooperationActivities.spec.jsx
Labels: Frontend part, feature

#2555 Translate title on landing page into Ukrainian
  src/assets/img/guest-home-page/titleMdUk.svg
  src/assets/img/guest-home-page/titleSmUk.svg
  src/assets/img/guest-home-page/titleXsUk.svg
  src/containers/guest-home-page/Welcome.tsx
Labels: Frontend part, feature

#2538 Your schedule
  src/components/tutor-schedule/TutorSchedule.styles.ts
  src/components/tutor-schedule/TutorSchedule.tsx
  src/components/tutor-schedule/TutorScheduleCard.styles.tsx
  src/components/tutor-schedule/TutorScheduleCard.tsx
  src/components/tutor-schedule/types.ts
  src/pages/tutor-home/TutorHome.tsx
Labels: Frontend part, feature

#2554 Binded confirmation modal on resources edit
  src/containers/change-resource-confirm-modal/ChangeResourceConfirmModal.tsx
  src/containers/course-section/CourseSectionContainer.tsx
  src/containers/my-quizzes/QuizzesContainer.tsx
  src/containers/my-quizzes/create-or-edit-quiz-container/CreateOrEditQuizContainer.tsx
  src/containers/my-resources/attachments-container/AttachmentsContainer.tsx
  src/containers/my-resources/lessons-container/LessonsContainer.tsx
  src/pages/create-or-edit-lesson/CreateOrEditLesson.tsx
  src/pages/lesson-details/LessonDetails.tsx
  tests/unit/containers/AttachmentsContainer/AttachmentsContainer.spec.jsx
  tests/unit/containers/my-quizzes/QuizzesContainer.spec.jsx
  tests/unit/containers/my-resources/LessonsContainer.spec.jsx
  tests/unit/pages/create-or-edit-lesson/CreateOrEditLessonWithId.spec.jsx
  tests/unit/pages/lesson-details/LessonDetails.spec.jsx
Labels: Frontend part, feature, Tutor

#2551 Calendar block
  src/components/calendar/Calendar.styles.ts
  src/components/calendar/Calendar.tsx
  src/pages/tutor-home/TutorHome.tsx
Labels: Frontend part, feature

#2446 Centered the avatar on the offer card in list view
  src/components/offer-card/OfferCard.styles.ts
Labels: bug, Frontend part
