Repository ita-social-projects/SpaceToStudy-Client, pull requests merged in 2024-10, with the labels that each got.

#2564 Changed the position of the opening date input
  src/containers/course-section/resource-item/ResourceItem.styles.ts
  src/containers/course-section/resource-item/ResourceItem.tsx
Labels: Frontend part, feature

#2569 Setup socket connection on the client side
  docker/files/default.conf.template
  package-lock.json
  package.json
  src/pages/chat/Chat.tsx
  src/services/socket-service.ts
  vite.config.ts
Labels: Frontend part, feature, socket

#2406 Redirect when clicking on Complete Profile items
  src/components/complete-profile/CompleteProfileBlock.tsx
  src/components/profile-item/ProfileItem.styles.ts
  src/components/profile-item/ProfileItem.tsx
  src/components/profile-item/complete-profile.constants.tsx
  src/components/title-with-description/TitleWithDescription.styles.ts
  src/components/title-with-description/TitleWithDescription.tsx
  src/containers/edit-profile/common.styles.ts
  src/containers/edit-profile/professional-info-tab/ProfessionalInfoTab.tsx
  src/containers/edit-profile/profile-tab/ProfileTab.tsx
  src/containers/edit-profile/profile-tab/profile-tab-form/ProfileTabForm.tsx
  src/pages/edit-profile/EditProfile.tsx
  src/pages/user-profile/UserProfile.jsx
  src/redux/features/editProfileSlice.ts
  src/styles/app-theme/app.pallete.ts
  src/styles/index.css
  src/utils/hash-scroll.ts
  src/utils/scroll-and-highlight.tsx
  tests/unit/redux/editProfileSlice.spec.js
  tests/unit/utils/scroll-and-highlight.spec.jsx
Labels: Frontend part, feature, Tutor, Student, Functional

#2566 Added validation for local storage
  src/services/local-storage-service.ts
  tests/unit/services/local-storage-service.spec.js
Labels: bug, Frontend part

#2568 Bound confirm on resource delete
  src/containers/my-resources/my-resources-table/MyResourcesTable.tsx
  src/types/components/enhanced-table/enhancedTable.interface.ts
  tests/unit/containers/my-resources/MyResourcesTable.spec.jsx
Labels: Frontend part, feature, Tutor

#2587 added MIT license
  LICENSE
Labels: Frontend part

#2577 Fixed visual bug on the tutor home page
  src/components/calendar/Calendar.styles.ts
  src/components/tutor-schedule/TutorSchedule.styles.ts
  src/pages/tutor-home/TutorHome.styles.ts
  src/pages/tutor-home/TutorHome.tsx
Labels: bug, Frontend part, Tutor

#2567 Add redirect to resource details
  src/containers/course-section/resource-item/ResourceItem.tsx
  src/containers/guest-home-page/Welcome.tsx
  tests/unit/components/cooperation-section-view/CooperationSectionView.spec.jsx
Labels: enhancement, Frontend part, feature, Student

#2582 Replace class values for flex-grow and flex-shrink utility classes
  src/scss/utilities/flexbox.scss
Labels: bug, scss

#2578 Fix active students block with no active cooperations
  src/components/active-students/ActiveStudentsBlock.styles.ts
  src/components/active-students/ActiveStudentsBlock.tsx
  src/constants/translations/en/active-students.json
  src/constants/translations/uk/active-students.json
  tests/unit/components/active-students/ActiveStudentsBlock.spec.jsx
Labels: bug, Frontend part, Tutor

#2593 Optimized component re-renders caused by input change
  src/containers/course-section/CourseSectionContainer.styles.ts
  src/containers/course-section/CourseSectionContainer.tsx
  tests/unit/containers/course-section/CourseSectionContainer.spec.jsx
Labels: bug, Frontend part, performance optimization

#2589 Open a modal when clicking on offer profile item
  src/components/profile-item/ProfileItem.tsx
Labels: Frontend part, feature, Functional

#2600 Rewrite variables in camel case
  src/utils/helper-functions.tsx
Labels: enhancement, Frontend part

#2595 Fix render empty state for faqItems
  src/pages/offer-details/OfferDetails.tsx
Labels: bug, Frontend part

#2601 Fix students accessing unavailable cooperation resources
  src/containers/course-section/resource-item/ResourceItem.tsx
Labels: bug, Frontend part, Tutor, Student

#2596 Implement user online-offline status
  src/components/user-profile-info/UserProfileInfo.tsx
  src/constants/translations/en/chat.json
  src/constants/translations/uk/chat.json
  src/containers/chat/chat-header/ChatHeader.tsx
  src/containers/chat/chat-item/ChatItem.tsx
  src/containers/offer-page/chat-dialog-window/ChatDialogWindow.tsx
  src/pages/chat/Chat.tsx
  src/redux/features/socketSlice.ts
  src/redux/middleware/socket-middleware.ts
  src/redux/redux.constants.ts
  src/redux/selectors/socket-selectors.ts
  src/redux/socket-factory.ts
  src/redux/store.ts
  src/services/socket-service.ts
  src/utils/debounce.ts
  tests/test-utils.jsx
  tests/unit/components/offer-banner/OfferBanner.spec.jsx
  tests/unit/containers/chat/list-of-users-with-search/ListOfUsersWithSearch.spec.jsx
  tests/unit/containers/my-cooperations/cooperation-card/CooperationCard.spec.jsx
  tests/unit/containers/my-cooperations/cooperation-container/CooperationContainer.spec.jsx
  tests/unit/containers/tutor-profile/comments-block/ComentsBlock.spec.jsx
  tests/unit/redux/socketMiddleware.spec.js
  tests/unit/redux/socketSlice.spec.js
  tests/unit/utils/debounce.spec.js
Labels: Frontend part, feature, socket

#2612 Hide the attachments accordion on the lesson details page if no attachments are available
  src/pages/lesson-details/LessonDetails.tsx
  src/services/course-service.ts
  tests/unit/pages/lesson-details/LessonDetails.spec.jsx
Labels: enhancement, Frontend part

#2605 Redirect to CompleteProfileBlock after creating offer
  src/components/profile-item/ProfileItem.tsx
  src/components/profile-item/complete-profile.constants.tsx
  src/containers/offer-page/create-or-edit-offer/CreateOrEditOffer.tsx
Labels: Frontend part, feature, Functional

#2614 Use an couseCooperation service in the ChangeResourceConfirmModal
  src/constants/request.ts
  src/containers/change-resource-confirm-modal/ChangeResourceConfirmModal.tsx
  src/services/course-cooperation-service.ts
  src/types/common/interfaces/common.interfaces.ts
  tests/unit/containers/change-resource-confirm-modal/ChangeResourceConfirmModal.spec.jsx
Labels: Frontend part, feature

#2615 Changed resources icons
  src/components/icon-extension-with-title/IconExtensionWithTitle.tsx
  src/containers/add-resources/AddAttachments.constants.tsx
  src/containers/add-resources/AddLessons.constants.tsx
  src/containers/course-section/CourseSectionContainer.constants.tsx
  src/containers/course-section/resource-item/ResourceItem.constants.ts
  src/containers/my-resources/attachments-container/AttachmentsContainer.constants.tsx
  src/containers/my-resources/lessons-container/LessonsContainer.constants.tsx
  src/pages/my-resources/MyResources.constants.tsx
  tests/unit/components/icon-extention-with-title/IconExtentionWithTitle.spec.jsx
  tests/unit/containers/course-section/resource-item/ResourceItem.spec.jsx
Labels: Frontend part, feature

#2618 Implemented typing animation on the chat page
  package-lock.json
  package.json
  src/assets/lottiefiles/typingAnimation.json
  src/components/typing-block/TypingBlock.styles.ts
  src/components/typing-block/TypingBlock.tsx
  src/constants/translations/en/chat.json
  src/constants/translations/uk/chat.json
  src/containers/chat/chat-item/ChatItem.styles.ts
  src/containers/chat/chat-item/ChatItem.tsx
  src/pages/chat/Chat.tsx
  src/pages/chat/MessagesList.tsx
  src/redux/features/socketSlice.ts
  src/redux/middleware/socket-middleware.ts
  src/redux/selectors/socket-selectors.ts
  src/styles/app-theme/custom-animations.ts
  tests/unit/components/typing-block/TypingBlock.spec.jsx
  tests/unit/pages/chat/messages-list/MessagesList.spec.jsx
  tests/unit/redux/socketMiddleware.spec.js
  tests/unit/redux/socketSlice.spec.js
Labels: Frontend part, feature, socket

#2598 Added refreshing for an access token
  src/services/setup-interceptors.ts
  src/types/services/types/services.types.ts
  tests/unit/services/setup-interceptors.spec.js
Labels: bug, Frontend part

#2349 Added bookmark icon in Offer Cards within OfferCarousel
  src/containers/find-offer/offer-card-square/OfferCardSquare.styles.ts
  src/containers/offer-details/offer-carousel/OfferCarousel.tsx
  tests/unit/containers/offer-details/offer-carousel/OfferCarousel.spec.jsx
Labels: bug, Frontend part

#2620 Fixed chat input field
  src/containers/chat/chat-text-area/ChatTextArea.styles.ts
  src/containers/chat/chat-text-area/ChatTextArea.tsx
  src/containers/offer-page/chat-dialog-window/ChatDialogWindow.tsx
  src/pages/chat/Chat.styles.ts
Labels: bug, Frontend part

#2617 Button hot fix
  src/components/offer-banner/OfferBanner.styles.ts
Labels: bug, Frontend part, Tutor

#2459 Bugfix/2314/change offers to requests
  src/constants/translations/en/breadcrumbs.json
  src/constants/translations/en/button.json
  src/constants/translations/en/my-offers-page.json
  src/constants/translations/uk/breadcrumbs.json
  src/constants/translations/uk/button.json
  src/constants/translations/uk/my-offers-page.json
  src/containers/my-offers/my-offers-container/MyOffersContainer.tsx
  src/pages/my-cooperations/MyCooperations.tsx
  src/pages/my-offers/MyOffers.tsx
  src/router/constants/authRoutes.ts
  src/router/constants/crumbs.ts
  src/router/routes/authRouter.tsx
  src/router/routes/studentRouter.tsx
  src/router/routes/tutorRouter.tsx
  tests/unit/pages/my-offers/MyOffers.spec.jsx
Labels: bug, Frontend part, Student

#2639 Fix videopresentation count
  src/components/complete-profile/CompleteProfileBlock.tsx
  src/types/user/user-types/user.types.ts
  tests/unit/components/complete-profile/CompleteProfileBlock.spec.jsx
Labels: bug, Frontend part

#2630 Display active tab in URL on "My cooperations" and "My offers" pages
  src/components/tab-filter-list/TabFilterList.tsx
  src/pages/my-cooperations/MyCooperations.tsx
  src/pages/my-offers/MyOffers.tsx
  tests/unit/components/tab-filter-list/TabFilterList.spec.jsx
Labels: enhancement, Frontend part

#2592 Implemented edit of duplication lessons and quizes
  src/containers/course-section/CourseSectionContainer.tsx
  src/containers/course-section/resources-list/ResourcesList.tsx
  src/redux/features/cooperationsSlice.ts
  src/types/lesson/interfaces/lesson.interfaces.ts
  tests/unit/containers/course-section/CourseSectionContainer.handleAdd.spec.jsx
  tests/unit/containers/course-section/CourseSectionContainer.spec.constants.js
  tests/unit/containers/course-section/CourseSectionContainer.spec.jsx
  tests/unit/redux/cooperationsSlice.spec.js
Labels: Frontend part, feature
