Repository ita-social-projects/SpaceToStudy-Client, pull requests merged in 2024-06, with the labels that each got.

#1927 Created useAccordion hook
  src/components/accordion-with-image/AccordionWithImage.tsx
  src/components/multi-accordion-with-title/MultiAccordionWIthTitle.tsx
  src/containers/edit-profile/professional-info-tab/about-tutor-accordion/AboutTutorAccordion.tsx
  src/containers/student-home-page/faq/Faq.tsx
  src/containers/user-profile/about-tutor-block/AboutTutorBlock.tsx
  src/hooks/use-accordions.tsx
  src/pages/lesson-details/LessonDetails.tsx
  tests/unit/hooks/use-accordions.spec.js
Labels: enhancement, Frontend part

#1913 Feature/1894/professional block categories
  src/constants/translations/en/edit-profile.json
  src/constants/translations/ua/edit-profile.json
  src/containers/edit-profile/professional-info-tab/ProfessionalInfoTab.tsx
  src/containers/edit-profile/professional-info-tab/add-professional-category-modal/AddProfessionalCategoryModal.constants.ts
  src/containers/edit-profile/professional-info-tab/add-professional-category-modal/AddProfessionalCategoryModal.styles.ts
  src/containers/edit-profile/professional-info-tab/add-professional-category-modal/AddProfessionalCategoryModal.tsx
  src/containers/edit-profile/professional-info-tab/professional-category-list/ProfessionalCategoryList.tsx
  src/containers/edit-profile/professional-info-tab/professional-category/ProfessionalCategory.styles.ts
  src/containers/edit-profile/professional-info-tab/professional-category/ProfessionalCategory.tsx
  src/containers/edit-profile/profile-tab/ProfileTab.tsx
  src/containers/user-profile/profile-info/ProfileInfo.jsx
  src/hooks/use-form.tsx
  src/pages/edit-profile/EditProfile.constants.tsx
  src/pages/edit-profile/EditProfile.tsx
  src/services/user-service.tsx
  src/types/edit-profile/interfaces/editProfile.interfaces.ts
  src/types/edit-profile/types/editProfile.types.ts
  src/types/user/user-interfaces/user.interfaces.ts
  src/types/user/user-types/user.types.ts
  src/utils/get-profile-values.ts
  src/utils/helper-functions.tsx
  tests/test-utils.jsx
  tests/unit/containers/edit-profile/professional-info-tab/add-professional-category-modal/AddProfessionalCategoryModal.spec.jsx
  tests/unit/containers/edit-profile/professional-info-tab/professional-category/ProfessionalCategory.spec.jsx
  tests/unit/containers/tutor-profile/ProfileInfo.spec.jsx
  tests/unit/pages/edit-profile/EditProfile.spec.jsx
  tests/unit/pages/tutor-profile/TutorProfile.spec.jsx
Labels: Frontend part, feature

#1945 Fix AddProfessionalCategoryModal test
  src/containers/edit-profile/professional-info-tab/add-professional-category-modal/AddProfessionalCategoryModal.tsx
Labels: bug, Frontend part, test

#1941 Removed useEffect warning in ResourceItem
  src/containers/course-section/resource-item/ResourceItem.tsx
Labels: enhancement, Frontend part

#1942 Fixed active tab in SidebarMenu, located in edit profile page
  src/components/sidebar-menu/SidebarMenu.tsx
Labels: bug, enhancement, Frontend part

#1950 fixed styles for active tab
  src/components/tab/Tab.styles.ts
Labels: bug, enhancement, Frontend part

#1947 Fix styles for edit profile tab according to the mockup
  src/components/page-wrapper/PageWrapper.tsx
  src/containers/user-profile/profile-info/ProfileInfo.styles.js
Labels: bug, Frontend part

#1917 Feature/1865/add possibility to change password
  src/constants/request.ts
  src/constants/translations/en/common.json
  src/constants/translations/ua/common.json
  src/containers/edit-profile/password-security-tab/PasswordSecurityTab.constants.ts
  src/containers/edit-profile/password-security-tab/PasswordSecurityTab.styles.ts
  src/containers/edit-profile/password-security-tab/PasswordSecurityTab.tsx
  src/containers/edit-profile/profile-tab/ProfileTab.tsx
  src/hooks/use-change-user-status.tsx
  src/hooks/use-form.tsx
  src/pages/edit-profile/EditProfile.constants.tsx
  src/services/auth-service.ts
  src/types/common/enums/common.enums.ts
  src/types/edit-profile/interfaces/editProfile.interfaces.ts
  src/types/user/user-interfaces/user.interfaces.ts
  tests/unit/containers/edit-profile/password-security-tab/PasswordSecurityTab.spec.jsx
  tests/unit/services/auth-service.spec.jsx
Labels: Frontend part, feature

#1923 Added getting name and avatar of the current user while creating or editing note
  src/containers/my-cooperations/cooperation-notes/create-or-edit-note/CreateOrEditNote.styles.ts
  src/containers/my-cooperations/cooperation-notes/create-or-edit-note/CreateOrEditNote.tsx
  src/containers/my-cooperations/cooperation-notes/note-view/NoteView.styles.tsx
  src/containers/my-cooperations/cooperation-notes/note-view/NoteView.tsx
Labels: Frontend part, feature

#1953 Added helper function for initials
  src/utils/helper-functions.tsx
Labels: Frontend part

#1931 added tests for OfferFilterDrawer, OfferFilterList, fix type errors
  src/containers/find-offer/offer-filter-block/offer-filter-list/OfferFilterList.tsx
  tests/unit/containers/find-offer/offer-filter-block/offer-filter-list/OfferFilterList.spec.jsx
  tests/unit/containers/my-courses/courses-filters-drawer/CoursesFiltersDrawer.spec.jsx
Labels: Frontend part, test

#1986 Implemented redux for cooperations
  src/containers/cooperation-details/cooperation-activities/CooperationActivities.tsx
  src/containers/my-cooperations/cooperation-activities-list/CooperationActivitiesList.constants.ts
  src/containers/my-cooperations/cooperation-activities-list/CooperationActivitiesList.tsx
  src/redux/features/cooperationsSlice.ts
  src/types/cooperation/interfaces/cooperation.interface.ts
  src/types/course/interfaces/course.interface.ts
  src/types/course/types/course.types.ts
  tests/unit/containers/my-cooperations/cooperation-activities-list/CooperationActivitiesList.spec.jsx
Labels: Epic, Frontend part, feature

#1983 Fix CardList grid to match figma design
  src/components/cards-list/CardsList.styles.ts
Labels: bug, Frontend part

#1985 Fix OfferContainer grid to match figma design
  src/containers/find-offer/offer-container/OfferContainer.styles.ts
Labels: bug, Frontend part

#1971 Created cookie consent banner
  src/constants/translations/en/cookie-consent-banner.json
  src/constants/translations/en/index.ts
  src/constants/translations/ua/cookie-consent-banner.json
  src/constants/translations/ua/index.ts
  src/containers/app-content/AppContent.tsx
  src/containers/cookie-consent-banner/CookieConsentBanner.styles.ts
  src/containers/cookie-consent-banner/CookieConsentBanner.tsx
  src/router/constants/guestRoutes.ts
  src/types/user/user-interfaces/user.interfaces.ts
  tests/setup-tests.js
  tests/unit/containers/cookie-consent-banner/CookieConsentBanner.spec.jsx
Labels: Frontend part, feature, component

#1961 Fix styles when Ukrainian language is used
  src/components/app-select/AppSelect.styles.ts
Labels: enhancement, Frontend part, feature

#1970 Fixed overlapping "TurnedInNotIcon" and first & last name
  src/containers/find-offer/offer-card-square/OfferCardSquare.styles.ts
Labels: enhancement, Frontend part, feature

#1987 Added space between TitleBlock and a logo
  src/components/title-block/TitleBlock.styles.ts
  src/components/title-block/TitleBlock.tsx
Labels: enhancement, feature

#1998 Fixed styles for AppToolbar and CourseToolbar
  src/containers/my-courses/course-toolbar/CourseToolbar.style.ts
  src/containers/my-courses/course-toolbar/CourseToolbar.tsx
  src/containers/proficiency-level-select/ProficiencyLevelSelect.tsx
Labels: enhancement, Frontend part, feature

#2006 Fixed space between titleWithDescription and img in TitleBlock component
  src/components/title-block/TitleBlock.styles.ts
Labels: enhancement, Frontend part

#1962 Made submit button disabled when subject field is empty #1951
  src/containers/edit-profile/professional-info-tab/add-professional-category-modal/AddProfessionalCategoryModal.tsx
  src/utils/is-submit-disabled.tsx
  tests/unit/containers/edit-profile/professional-info-tab/add-professional-category-modal/AddProfessionalCategoryModal.spec.jsx
Labels: enhancement, Frontend part, feature

#1974 Fixed bug causing console warning when rendering the profile page #1933
  src/components/title-with-description/TitleWithDescription.tsx
  tests/unit/components/title-with-description/TitleWithDescription.spec.jsx
Labels: bug, enhancement, Frontend part

#2001 Fixed modal window button behavior when deleting a category
  src/containers/edit-profile/professional-info-tab/professional-category/ProfessionalCategory.tsx
Labels: bug, Frontend part

#1999 Implemented tests for useUpdateUser hook
  tests/unit/hooks/use-update-user.spec.jsx
Labels: Frontend part, test

#1967 Fixed the description text in offer request block
  src/components/title-block/TitleBlock.tsx
  src/constants/translations/en/find-offer-page.json
  src/constants/translations/ua/find-offer-page.json
  tests/unit/pages/find-offers/FindOffers.spec.jsx
Labels: bug, Student, UI/Usability, severity: minor, priority: low

#1959 Changed the message about successful creation of a quiz question to a clearer one
  src/containers/my-quizzes/create-or-edit-quiz-question/CreateOrEditQuizQuestion.tsx
Labels: bug, good first issue, Frontend part

#1997 Fixing translation in "Who we are" block on guest home page
  src/constants/translations/ua/guest-home-page.json
Labels: bug, Frontend part

#2010 Fixing missing translation for field on my profile page
  src/constants/translations/ua/user-profile-page.json
Labels: bug, Frontend part

#1989 Adjusted padding for AppButton
  src/components/app-button/AppButton.tsx
  src/components/cards-list/CardsList.tsx
  src/containers/student-home-page/student-how-it-works/StudentHowItWorks.jsx
  src/scss/src/atoms/Button.scss
  src/types/common/enums/common.enums.ts
Labels: enhancement, feature

#1965 Added spec for "CourseSectionsList" container #1665
  tests/unit/containers/course-sections-list/CourseSectionsList.spec.jsx
Labels: good first issue, Frontend part, test

#1969 Fixed popup message for user password reset #1968
  src/constants/translations/en/login.json
Labels: bug, Frontend part

#1977 Fixed translation for count of reviews into Ukrainian for the offer list #1976
  src/constants/translations/ua/user-profile-page.json
Labels: bug, Frontend part

#2007 Added 'Remember me' option to the login form #971
  src/constants/translations/en/login.json
  src/constants/translations/ua/login.json
  src/containers/guest-home-page/login-dialog/LoginDialog.jsx
  src/containers/guest-home-page/login-form/LoginForm.jsx
  src/containers/guest-home-page/login-form/LoginForm.styles.js
  tests/unit/containers/guest-home-page/login-form/LoginForm.spec.jsx
Labels: Frontend part, feature, test case
