Repository ita-social-projects/SpaceToStudy-Client, pull requests merged in 2024-12, with the labels that each got.

#2657 Add lastSeen
  src/types/user/user-interfaces/user.interfaces.ts
Labels: enhancement, Frontend part, Tutor, Student

#2847 Fix tutor homepage schedule localization
  src/components/tutor-schedule/TutorSchedule.tsx
  src/components/tutor-schedule/TutorScheduleCard.tsx
  src/constants/translations/en/common.json
  src/constants/translations/en/tutor-home-page.json
  src/constants/translations/uk/common.json
  src/constants/translations/uk/tutor-home-page.json
Labels: bug, Frontend part, Localization

#2905 added the visiblity icon back
  src/containers/edit-profile/password-security-tab/change-password-modal/ChangePasswordModal.tsx
Labels: bug, Frontend part

#2926 Fixed duplicate chat creation bug
  src/containers/offer-page/chat-dialog-window/ChatDialogWindow.tsx
Labels: bug, Frontend part

#2901 (SP:5) Create Chip component
  src/design-system/components/chip/Chip.scss
  src/design-system/components/chip/Chip.tsx
  src/design-system/components/chip/ChipTypes.tsx
  src/design-system/stories/Chip.stories.tsx
  tests/unit/design-system/components/Chip.spec.jsx
Labels: Frontend part, feature, component, test, design system

#2818 Created reusable link button component
  src/design-system/components/link-button/LinkButton.scss
  src/design-system/components/link-button/LinkButton.tsx
  src/design-system/stories/LinkButton.stories.tsx
  src/types/common/enums/common.enums.ts
  tests/unit/design-system/components/LinkButton/LinkButton.spec.jsx
Labels: Frontend part, component, design system

#2918 Fixed invalid additionalInfo validation in enroll offer modal
  src/components/app-text-area/AppTextArea.tsx
  src/constants/translations/en/offer-details-page.json
  src/constants/translations/uk/offer-details-page.json
  src/containers/offer-details/enroll-offer/EnrollOffer.styles.ts
  src/containers/offer-details/enroll-offer/EnrollOffer.tsx
  tests/unit/containers/offer-details/enroll-offer/EnrollOffer.spec.jsx
Labels: bug, Frontend part

#2924 Verified ability to save a 'First name' containing allowed special characters
  tests/unit/containers/edit-profile/ProfileTab.spec.jsx
  tests/unit/pages/edit-profile/EditProfile.spec.jsx
  tests/unit/utils/common.spec.jsx
Labels: Tutor, Student, priority: medium, test case, my-profile, Edit

#2920 Replaced InputWithIcon with InputField throughout the project
  src/components/app-menu-button/AppMenuButton.styles.ts
  src/components/app-menu-button/AppMenuButton.tsx
  src/components/find-block/FindBlock.tsx
  src/components/find-block/find-block.styles.ts
  src/components/search-by-message/SearchByMessage.tsx
  src/components/search-filter-input/SearchFilterInput.tsx
  src/containers/cooperation-details/add-course-modal-modal/AddCourseTemplateModal.tsx
  src/containers/my-cooperations/cooperation-offer-toolbar/CooperationOfferToolbar.styles.ts
  src/containers/my-cooperations/cooperation-offer-toolbar/CooperationOfferToolbar.tsx
  src/containers/my-courses/add-course-with-input/AddCourseWithInput.styles.ts
  src/containers/my-courses/add-course-with-input/AddCourseWithInput.tsx
  src/containers/my-resources/add-resource-modal/AddResourceModal.styles.ts
  src/containers/my-resources/add-resource-modal/AddResourceModal.tsx
  src/containers/my-resources/add-resource-with-input/AddResourceWithInput.styles.ts
  src/containers/my-resources/add-resource-with-input/AddResourceWithInput.tsx
  src/containers/my-resources/resources-toolbar-drawer/ResourceToolbarDrawer.styles.ts
  src/containers/my-resources/resources-toolbar-drawer/ResourcesToolbarDrawer.tsx
  src/design-system/components/input-field/InputField.tsx
  tests/unit/containers/my-courses/add-course-with-input/AddCourseWithInput.spec.jsx
Labels: Frontend part, feature, component, design system

#2928 Fixed switch component styles
  src/design-system/components/switch/Switch.scss
  src/design-system/components/switch/Switch.tsx
  tests/unit/design-system/components/Switch/Switch.spec.jsx
Labels: bug, Frontend part, component, design system

#2929 Verified ability to save a 'Last name' containing allowed special characters
  tests/unit/containers/edit-profile/ProfileTab.spec.jsx
  tests/unit/pages/edit-profile/EditProfile.spec.jsx
  tests/unit/utils/common.spec.jsx
Labels: Tutor, Student, priority: medium, Functional, test case, my-profile, Edit

#2919 create badge component
  src/design-system/components/badge/Badge.scss
  src/design-system/components/badge/Badge.tsx
  src/design-system/stories/Badge.stories.tsx
  tests/unit/design-system/components/Badge/Badge.spec.jsx
Labels: design system

#2635 Add snackbar after creating an offer in CompleteProfileBlock
  src/constants/translations/en/offer-page.json
  src/constants/translations/uk/offer-page.json
  src/containers/layout/app-snackbar/AppSnackbar.styles.ts
  src/containers/layout/app-snackbar/AppSnackbar.tsx
  src/containers/offer-page/create-or-edit-offer/CreateOrEditOffer.constants.ts
  src/containers/offer-page/create-or-edit-offer/CreateOrEditOffer.tsx
  src/redux/features/snackbarSlice.ts
  tests/unit/containers/layout/app-snackbar/AppSnackbarExtended.spec.jsx
  tests/unit/containers/offer-page/create-or-edit-offer/CreateOrEditOffer.spec.jsx
Labels: Frontend part, feature

#2900 close cooperation process
  src/components/status-chip/StatusChip.styles.ts
  src/constants/translations/en/cooperation-details.json
  src/constants/translations/en/cooperations-page.json
  src/constants/translations/en/titles.json
  src/constants/translations/uk/cooperation-details.json
  src/constants/translations/uk/cooperations-page.json
  src/constants/translations/uk/titles.json
  src/containers/my-cooperations/accept-cooperation-close/AcceptCooperationClosing.styles.ts
  src/containers/my-cooperations/accept-cooperation-close/AcceptCooperationClosing.tsx
  src/containers/my-cooperations/cooperation-completion/CooperationCompletion.tsx
  src/containers/my-cooperations/cooperation-details/CooperationDetails.tsx
  src/containers/my-cooperations/cooperations-container/CooperationContainer.tsx
  src/containers/my-cooperations/my-cooperations-details/MyCooperationsDetails.tsx
  src/redux/features/cooperationsSlice.ts
  src/styles/app-theme/app.pallete.ts
  src/types/common/enums/common.enums.ts
  src/types/cooperation/interfaces/cooperation.interface.ts
  src/types/cooperation/types/cooperation.types.ts
  tests/unit/containers/my-cooperations/accept-cooperation-close/AcceptCooperationClosing.spec.jsx
  tests/unit/containers/my-cooperations/cooperation-completion/CooperationCompletion.spec.jsx
  tests/unit/containers/my-cooperations/cooperation-container/CooperationContainer.spec.jsx
Labels: Frontend part, feature

#2898 Create a UserAvatar component
  src/design-system/components/user-avatar/UserAvatar.scss
  src/design-system/components/user-avatar/UserAvatar.tsx
  src/design-system/stories/UserAvatar.stories.tsx
  tests/unit/design-system/components/user-avatar/UserAvatar.spec.jsx
Labels: Frontend part, feature, component, design system

#2931 Wrote test cases for accident when user can clear the "Main study category field" in the "Your professional category" pop-up.
  tests/unit/containers/edit-profile/professional-info-tab/add-professional-category-modal/AddProfessionalCategoryModal.spec.jsx
Labels: Tutor, Student, UI/Usability, priority: low, test case

#2933 Fixed duplicate name `enrolledUsers` in `CreateOrEditOffer.constants.ts`
  src/containers/offer-page/create-or-edit-offer/CreateOrEditOffer.constants.ts
Labels: bug, Frontend part, sonarFix

#2965 incorrect description of Badge maxContent prop in storybook
  src/design-system/stories/Badge.stories.tsx
Labels: bug, design system

#2953 Fixed invalid route for student in snackbar
  src/containers/offer-page/create-or-edit-offer/CreateOrEditOffer.tsx
Labels: bug, Frontend part, Student

#2973 Fixed incorrect bookmark height on bigger screens
  src/containers/find-offer/offer-container/OfferContainer.styles.ts
Labels: bug, Frontend part

#2971 Create reusable CooperationActionBanner component
  src/containers/my-cooperations/accept-cooperation-close/AcceptCooperationClosing.styles.ts
  src/containers/my-cooperations/accept-cooperation-close/AcceptCooperationClosing.tsx
  src/containers/my-cooperations/cooperation-action-banner/CooperationActionBanner.styles.ts
  src/containers/my-cooperations/cooperation-action-banner/CooperationActionBanner.tsx
  tests/unit/containers/my-cooperations/cooperation-action-banner/CooperationActionBanner.spec.jsx
Labels: Frontend part, feature

#2974 Made checkbox controlled
  src/design-system/components/checkbox/CheckBox.tsx
  src/design-system/stories/CheckBox.stories.tsx
Labels: design system

#2951 Replaced Alert throughout the project
  src/constants/index.ts
  src/containers/layout/app-snackbar/AppSnackbar.styles.ts
  src/containers/layout/app-snackbar/AppSnackbar.tsx
  src/design-system/components/alert/Alert.scss
  src/design-system/components/alert/Alert.tsx
  src/design-system/stories/Alert.stories.tsx
  src/redux/features/snackbarSlice.ts
  tests/unit/design-system/components/Alert/Alert.spec.jsx
Labels: Frontend part, feature, component, design system

#2976 replaced all of the switch elements and adujested the switch component
  src/components/app-content-switcher/AppContentSwitcher.tsx
  src/containers/edit-profile/notification-tab/NotificationTab.tsx
  src/containers/my-quizzes/quiz-settings-container/QuizSettingsContainer.tsx
  src/design-system/components/switch/Switch.scss
  src/design-system/components/switch/Switch.tsx
  src/design-system/stories/Switch.stories.tsx
  tests/unit/design-system/components/Switch/Switch.spec.jsx
Labels: enhancement, Frontend part, feature, design system

#2969 [Edit Tutor's Profile Password & Security]: Added error alert if current password is incorrect
  src/constants/translations/en/common.json
  src/constants/translations/uk/common.json
  src/containers/edit-profile/password-security-tab/change-password-modal/ChangePasswordModal.tsx
  src/hooks/use-axios.tsx
  src/services/auth-service.ts
  tests/unit/containers/edit-profile/password-security-tab/ChangePasswordModal.spec.jsx
Labels: bug, Frontend part, Tutor, my-profile

#3002 Fixed 'Content' description styles in 'Lesson details'
  src/pages/lesson-details/LessonsDetails.styles.ts
Labels: bug, Frontend part, UI/Usability

#2977 Replaced IconButton component through the project
  src/components/app-carousel/AppCarousel.tsx
  src/components/app-chip/AppChip.tsx
  src/components/app-drawer/AppDrawer.tsx
  src/components/app-icon-button/AppIconButton.tsx
  src/components/calendar/Calendar.tsx
  src/components/complete-profile/CompleteProfileBlock.tsx
  src/components/confirm-dialog/ConfirmDialog.tsx
  src/components/course-card/CourseCard.tsx
  src/components/enhanced-table/date-filter/DateFilter.tsx
  src/components/enhanced-table/enhanced-table-row/EnhancedTableRow.tsx
  src/components/enhanced-table/enhanced-table-toolbar/EnhancedTableToolbar.tsx
  src/components/enhanced-table/enum-filter/EnumFilter.tsx
  src/components/file-uploader/FileUploader.tsx
  src/components/filter-input/FilterInput.tsx
  src/components/header-text-with-dropdown/HeaderTextWithDropdown.tsx
  src/components/icons-with-counter/IconsWithCounter.tsx
  src/components/input-with-icon/InputWithIcon.tsx
  src/components/navigation-icon/NavigationIcon.tsx
  src/components/offer-card/offer-actions/OfferActions.tsx
  src/components/popup-dialog/PopupDialog.tsx
  src/components/question-editor/QuestionEditor.tsx
  src/components/question/Question.tsx
  src/components/scroll-to-top-button/ScrollToTopButton.tsx
  src/components/search-autocomplete/SearchAutocomplete.tsx
  src/components/search-input/SearchInput.tsx
  src/containers/about-chat-sidebar/AboutChatSidebar.tsx
  src/containers/bookmarked-offers/BookmarksToolbar.tsx
  src/containers/chat/chat-header/ChatHeader.tsx
  src/containers/chat/chat-text-area/ChatTextArea.tsx
  src/containers/cooperation-details/cooperation-activities-view/CooperationActivitiesView.tsx
  src/containers/course-section/resource-item/ResourceItem.tsx
  src/containers/edit-profile/professional-info-tab/add-professional-category-modal/AddProfessionalCategoryModal.tsx
  src/containers/edit-profile/professional-info-tab/professional-category/ProfessionalCategory.tsx
  src/containers/find-offer/offer-card-square/OfferCardSquare.tsx
  src/containers/layout/notifications-menu/NotificationsMenu.tsx
  src/containers/my-cooperations/cooperation-notes/note-view/NoteView.tsx
  src/containers/my-resources/rename-input/RenameInput.tsx
  src/containers/navigation-icons/NavigationIcons.constants.tsx
  src/containers/offer-page/chat-dialog-window/ChatDialogWindow.tsx
  src/containers/offer-page/faq-block/FaqBlock.tsx
  src/design-system/components/icon-button/IconButton.tsx
  src/design-system/stories/Badge.stories.tsx
  src/design-system/stories/IconButton.stories.tsx
  src/hooks/use-input-visibility.tsx
  src/hooks/use-menu.tsx
  src/pages/create-or-edit-lesson/CreateOrEditLesson.tsx
  tests/unit/containers/navigation-icons/guest-icons/GuestIcons.spec.jsx
  tests/unit/containers/navigation-icons/user-icons/UserIcons.spec.jsx
  tests/unit/design-system/components/Badge/Badge.spec.jsx
Labels: Frontend part, feature, component, design system

#2992 Created a wrapper over `useQuery` hook from react-query
  eslint.config.mjs
  package-lock.json
  package.json
  src/App.tsx
  src/QueryProvider.tsx
  src/hooks/use-query.tsx
  src/plugins/queryClient.ts
  tests/unit/hooks/use-query.spec.js
Labels: enhancement, Frontend part, feature

#2993 updated AcceptCooperationClosing
  src/constants/translations/en/cooperation-details.json
  src/constants/translations/uk/cooperation-details.json
  src/containers/my-cooperations/accept-cooperation-close/AcceptCooperationClosing.styles.ts
  src/containers/my-cooperations/accept-cooperation-close/AcceptCooperationClosing.tsx
  src/containers/my-cooperations/cooperation-details/CooperationDetails.tsx
  src/design-system/components/input-field/InputField.tsx
  tests/unit/containers/my-cooperations/accept-cooperation-close/AcceptCooperationClosing.spec.jsx
Labels: Frontend part

#3031 Added `QueryProvider` in `test-utils.jsx`
  tests/test-utils.jsx
Labels: bug, Frontend part, test, useQuery

#2975 replaced userAvatar throughout the project
  src/components/avatar-icon/AvatarIcon.tsx
  src/containers/navigation-icons/AccountIcon.tsx
  src/design-system/components/user-avatar/UserAvatar.tsx
  tests/unit/components/avatar-icon/AvatarIcon.spec.jsx
  tests/unit/containers/navigation-icons/AccountIcon.spec.jsx
Labels: Frontend part, design system

#3007 Fixed type incompatibility for size prop of AppButton in OfferActions Component
  src/components/app-button/AppButton.tsx
Labels: bug, Frontend part, component, design system

#3026 Create CooperationClosureDeclinedBanner
  src/constants/translations/en/cooperation-details.json
  src/constants/translations/en/titles.json
  src/constants/translations/uk/cooperation-details.json
  src/constants/translations/uk/titles.json
  src/containers/my-cooperations/accept-cooperation-close/AcceptCooperationClosing.styles.ts
  src/containers/my-cooperations/accept-cooperation-close/AcceptCooperationClosing.tsx
  src/containers/my-cooperations/cooperation-action-input/CooperationActionInput.styles.ts
  src/containers/my-cooperations/cooperation-action-input/CooperationActionInput.tsx
  src/containers/my-cooperations/cooperation-closure-declined-banner/CooperationClosureDeclinedBanner.styles.ts
  src/containers/my-cooperations/cooperation-closure-declined-banner/CooperationClosureDeclinedBanner.tsx
  src/containers/my-cooperations/cooperation-details/CooperationDetails.tsx
  tests/unit/containers/my-cooperations/accept-cooperation-close/AcceptCooperationClosing.spec.jsx
  tests/unit/containers/my-cooperations/cooperation-action-input/CooperationActionInput.spec.jsx
  tests/unit/containers/my-cooperations/cooperation-closure-declined-banner/CooperationClosureDeclinedBanner.spec.jsx
Labels: Frontend part, feature

#2966 Fix sonar issues іn utils, redux, context, hooks folders
  src/context/step-context.tsx
  src/hooks/use-axios.tsx
  src/hooks/use-filter-query.tsx
  src/hooks/use-form.tsx
  src/redux/reducer.ts
  src/utils/get-error-key.ts
  src/utils/get-profile-values.ts
Labels: sonarFix

#3040 Enhance useQuery hook
  src/exceptions/index.ts
  src/exceptions/response-error.ts
  src/hooks/use-query.tsx
  tests/unit/exceptions/response-error.spec.js
Labels: enhancement, Frontend part, TypeScript, useQuery

#3025 Update the Chip component
  src/design-system/components/chip/Chip.scss
  src/design-system/components/chip/Chip.tsx
  src/design-system/components/chip/ChipInternalComponents.tsx
  src/design-system/components/chip/ChipTypes.tsx
  src/design-system/components/chip/types.ts
  src/design-system/stories/Chip.stories.tsx
  tests/unit/design-system/components/Chip.spec.jsx
  tests/unit/design-system/components/chip/Chip.spec.jsx
Labels: enhancement, Frontend part, design system

#2996 Fixed type mismatch in FilterCell component
  src/components/enhanced-table/enum-filter/EnumFilter.tsx
  src/components/enhanced-table/filter-row/filter-cell/FilterCell.tsx
  src/types/components/enum-filter/enumFilter.interface.ts
Labels: bug, Frontend part, component, design system

#3019 Fixed type errors in QuizSettingsContainer
  src/containers/my-quizzes/quiz-settings-container/QuizSettingsContainer.tsx
Labels: bug, Frontend part, component

#3022 Created a wrapper over use mutation hook
  src/hooks/use-mutation.tsx
  tests/unit/hooks/use-mutation.spec.js
Labels: enhancement, Frontend part, feature

#3043 Create base service for all HTTP requests
  src/services/base-service.ts
  src/services/setup-interceptors.ts
  src/types/services/types/services.types.ts
  tests/unit/services/base-service.spec.js
Labels: enhancement, Frontend part, feature, TypeScript

#3047 Add getFullUrl helper function
  src/utils/helper-functions.tsx
  tests/unit/utils/get-full-url.spec.js
Labels: enhancement, Frontend part, feature
