Repository ita-social-projects/SpaceToStudy-Client, pull requests merged in 2024-04, with the labels that each got.

#1662 Created About Tutor block for my profile
  src/constants/translations/en/tutor-profile-page.json
  src/constants/translations/ua/tutor-profile-page.json
  src/containers/tutor-profile/about-tutor-block/AboutTutorBlock.constans.ts
  src/containers/tutor-profile/about-tutor-block/AboutTutorBlock.styles.tsx
  src/containers/tutor-profile/about-tutor-block/AboutTutorBlock.tsx
  src/pages/tutor-profile/TutorProfile.jsx
Labels: Frontend part, feature

#1697 Open Terms and Policies in new tab
  src/containers/guest-home-page/signup-dialog/SignupDialog.jsx
  src/containers/guest-home-page/signup-form/SignupForm.jsx
  tests/unit/containers/guest-home-page/signup-form/SignupForm.spec.jsx
Labels: enhancement, good first issue, Frontend part

#1699 Implement test for SidebarMenu component
  tests/unit/components/sidebar-menu/SidebarMenu.spec.jsx
Labels: good first issue, Frontend part, test

#1702 Fixed profile view
  src/pages/tutor-profile/TutorProfile.jsx
Labels: bug, Frontend part, Tutor, Student

#1684 Implemented Security block for Tutor profile edit
  src/components/confirm-dialog/ConfirmDialog.styles.ts
  src/components/confirm-dialog/ConfirmDialog.tsx
  src/constants/translations/en/edit-tutor-profile.json
  src/constants/translations/ua/edit-tutor-profile.json
  src/containers/tutor-profile/security-block/SecurityBlock.styles.js
  src/containers/tutor-profile/security-block/SecurityBlock.tsx
  src/pages/edit-profile/EditProfile.constants.tsx
  src/types/common/enums/common.enums.ts
  src/types/editTutorProfile/editTutorProfile.index.ts
  src/types/editTutorProfile/enums/editTutorProfile.enums.ts
  src/types/editTutorProfile/interfaces/securityBlockForm.interfaces.ts
Labels: Frontend part, feature, Tutor

#1683 Added notification tab to edit profile
  src/components/setting-item/SettingItem.tsx
  src/constants/translations/en/edit-tutor-profile.json
  src/constants/translations/ua/edit-tutor-profile.json
  src/containers/edit-profile/common.style.ts
  src/containers/edit-profile/notification-tab/NotificationContainer.constans.tsx
  src/containers/edit-profile/notification-tab/NotificationContainer.style.ts
  src/containers/edit-profile/notification-tab/NotificationContainer.tsx
  src/containers/edit-profile/profile-general-tab/ProfileGeneralTab.styles.ts
  src/containers/my-quizzes/quiz-settings-container/QuizSettingsContainer.styles.ts
  src/pages/edit-profile/EditProfile.constants.tsx
  src/pages/edit-profile/EditProfile.styles.ts
  src/pages/edit-profile/EditProfile.tsx
Labels: Frontend part, feature

#1708 Fixed add subject button label in stepper, that loads on first login
  src/constants/translations/en/become-tutor.json
  src/constants/translations/ua/become-tutor.json
Labels: enhancement, Frontend part, UI/Usability

#1704 Fix the bug when cooperation details cannot be opened
  src/containers/my-cooperations/cooperation-details/CooperationDetails.tsx
Labels: bug, good first issue, Frontend part, Tutor

#1698 Fixed styles of global network card on tutor and student home pages
  src/components/find-block/FindBlock.jsx
  src/components/find-block/find-block.styles.js
  src/components/title-block/TitleBlock.styles.ts
  src/constants/translations/en/student-home-page.json
  src/constants/translations/en/tutor-home-page.json
  src/constants/translations/ua/student-home-page.json
  src/constants/translations/ua/tutor-home-page.json
Labels: bug, good first issue, Frontend part, UI/Usability, severity: minor, priority: low

#1703 Fixed alignment and style of error message in add photo step of the stepper
  src/components/file-uploader/FileUploader.styles.ts
  src/components/file-uploader/FileUploader.tsx
Labels: bug, Frontend part

#1706 Bugfix/1695/attachment error
  src/constants/translations/en/become-tutor.json
  src/constants/translations/en/common.json
  src/constants/translations/ua/become-tutor.json
  src/constants/translations/ua/common.json
  src/containers/add-documents/AddDocuments.constants.ts
  src/containers/tutor-home-page/add-photo-step/constants.js
  src/hooks/use-upload.jsx
  src/types/common/interfaces/common.interfaces.ts
  src/utils/validations/files.js
  src/utils/validations/files.ts
  tests/unit/components/file-uploader/FileUploader.spec.jsx
  tests/unit/pages/edit-profile/EditProfile.spec.jsx
  tests/unit/utils/files.spec.jsx
Labels: bug, Frontend part

#1724 Fixed type in AppRatingMobile component
  src/components/app-rating-mobile/AppRatingMobile.tsx
Labels: enhancement, Frontend part, TypeScript

#1713 Fix tests for edit profile #1675
  tests/unit/pages/edit-profile/EditProfile.spec.jsx
Labels: good first issue, Frontend part, test

#1729 Feature/1710/app drawer types
  src/components/app-drawer/AppDrawer.tsx
Labels: enhancement, Frontend part, TypeScript

#1707 added redirect to user offers
  src/constants/translations/en/tutor-profile-page.json
  src/constants/translations/ua/tutor-profile-page.json
  src/containers/tutor-profile/profile-info/ProfileInfo.jsx
  src/pages/tutor-profile/TutorProfile.jsx
  tests/unit/containers/tutor-profile/ProfileInfo.spec.jsx
Labels: Frontend part, feature

#1730 Implement NotificationContainer tests
  tests/unit/containers/notification-tab/NotificationContainer.spec.jsx
Labels: Frontend part, test

#1722 Enabled message sending
  src/pages/offer-details/OfferDetails.constants.ts
  src/pages/offer-details/OfferDetails.tsx
Labels: Frontend part, Tutor, Student

#1726 Replaced mapped types with typescript Record utility type and splitte…
  src/containers/course-section/CourseSectionContainer.tsx
  src/containers/course-sections-list/CourseSectionsList.tsx
  src/containers/my-courses/course-toolbar/CourseToolbar.tsx
  src/hooks/use-form.tsx
  src/types/common/types/common.types.ts
  src/types/findOffers/interfaces/findOffers.interfaces.ts
  src/utils/helper-functions.tsx
Labels: enhancement, Frontend part, TypeScript

#1768 Deployment Proxy Fix
  .dockerignore
  .vscode/settings.json
  Dockerfile
  azure-pipeline.yaml
  compose.yml
  docker/Dockerfile.stage
  nginx.conf
Labels: enhancement, Frontend part, hotfix, devOps

#1769 added folder structure
  src/scss/src/atoms/.gitkeep
  src/scss/src/foundation/_all.scss
  src/scss/src/foundation/_colors.scss
  src/scss/src/foundation/_mixins.scss
  src/scss/src/foundation/_typography.scss
  src/scss/src/foundation/_variables.scss
  src/scss/src/global.scss
  src/scss/src/molecules/.gitkeep
  src/scss/src/organisms/.gitkeep
Labels: enhancement, design system

#1733 Fixed validation of signup form
  src/constants/translations/en/common.json
  src/utils/validations/common.ts
  src/utils/validations/validations.constants.ts
  tests/unit/utils/common.spec.jsx
Labels: bug, Frontend part

#1731 Implemented saving cooperation section as a copy
  src/containers/cooperation-details/cooperation-activities/CooperationActivities.tsx
  src/containers/my-cooperations/cooperation-activities-list/CooperationActivitiesList.tsx
  src/containers/my-cooperations/cooperation-details/CooperationDetails.tsx
  src/services/cooperation-service.ts
  src/types/cooperation/interfaces/cooperation.interface.ts
  src/types/cooperation/types/cooperation.types.ts
  tests/unit/containers/my-cooperations/cooperation-activities-list/CooperationActivitiesList.spec.jsx
Labels: Frontend part, feature

#1777 Feature/1751/design system colors
  src/scss/src/foundation/_colors.scss
  src/scss/src/foundation/_variables.scss
Labels: Frontend part, design system

#1774 Added sass package and configured script to compile it to css
  package-lock.json
  package.json
  src/scss/src/scripts/compile-scss.js
Labels: enhancement, Frontend part, design system

#1773 Fix and add tests for my cooperation details and cooperation details #1742
  tests/unit/containers/my-cooperations/cooperation-details/CooperationDetails.spec.jsx
  tests/unit/containers/my-cooperations/my-cooperations-details/MyCooperationsDetails.spec.jsx
Labels: Frontend part, test

#1776 Added redirection after user logs in on authorization error page
  src/containers/guest-home-page/login-dialog/LoginDialog.jsx
  src/router/helpers/PrivateRoute.tsx
  tests/unit/router/helpers/PrivateRoute.spec.jsx
Labels: Frontend part, feature

#1778 Fixed bug when find offer toolbar was not mapped correctly to search params
  src/components/search-filter-input/SearchFilterInput.tsx
  src/containers/cooperation-details/add-course-modal-modal/AddCourseTemplateModal.tsx
  src/containers/find-offer/filter-bar-menu/FilterBarMenu.tsx
  src/containers/find-offer/offer-filter-block/OfferFilterBlock.tsx
  src/containers/find-offer/offer-filter-block/offer-filter-list/OfferFilterList.tsx
  src/containers/find-offer/offer-search-toolbar/OfferSearchToolbar.tsx
  src/hooks/use-filter-query.tsx
  src/pages/find-offers/FindOffers.tsx
  src/types/findOffers/interfaces/findOffers.interfaces.ts
  src/types/findOffers/types/findOffers.types.ts
  tests/unit/containers/find-offer/filter-bar-menu/FilterBarMenu.spec.jsx
  tests/unit/containers/find-offer/offer-filter-block/OfferFilterBlock.spec.jsx
  tests/unit/containers/find-offer/offer-search-toolbar/offerSearchToolbar.spec.jsx
  tests/unit/pages/find-offers/FindOffers.spec.jsx
Labels: bug, Frontend part

#1780 Bugfix My Resources Content shifts
  src/pages/create-or-edit-lesson/CreateOrEditLesson.styles.ts
  src/pages/create-or-edit-lesson/CreateOrEditLesson.tsx
Labels: bug, Frontend part

#1783 Added typography variables to scss design system foundation
  src/scss/src/foundation/_typography.scss
  src/scss/src/foundation/_variables.scss
Labels: enhancement, Frontend part, design system

#1784 Created SecurityBlock tests
  src/containers/tutor-profile/security-block/SecurityBlock.tsx
  tests/unit/containers/tutor-profile/security-block/SecurityBlock.spec.jsx
Labels: Frontend part, test

#1779 Improved coverage of faq-block
  tests/unit/containers/offer-page/faq-block/FaqBlock.spec.jsx
Labels: Frontend part, test

#1794 Fix incorrect title for tutor home page
  src/constants/translations/en/tutor-home-page.json
Labels: bug, Frontend part

#1728 Converted useUpload hook to typescript
  src/components/file-uploader/FileUploader.tsx
  src/containers/add-documents/AddDocuments.tsx
  src/containers/tutor-home-page/add-photo-step/AddPhotoStep.jsx
  src/hooks/use-upload.jsx
  src/hooks/use-upload.tsx
  src/stories/FileUploader.stories.jsx
  src/types/attachment/types/attachment.types.ts
  tests/unit/components/file-uploader/FileUploader.spec.jsx
  tests/unit/hooks/use-upload.spec.js
Labels: enhancement, Frontend part, TypeScript

#1781 Improve coverage for the QuestionEditor component
  src/components/question-editor/QuestionEditor.tsx
  tests/unit/components/question-editor/QuestionEditor.spec.jsx
Labels: Frontend part, test

#1741 Converted step-context and use-steps hook to typescript
  src/components/step-wrapper/StepWrapper.jsx
  src/components/user-steps-wrapper/UserStepsWrapper.tsx
  src/components/user-steps-wrapper/constants.ts
  src/containers/tutor-home-page/add-photo-step/AddPhotoStep.jsx
  src/containers/tutor-home-page/general-info-step/GeneralInfoStep.jsx
  src/containers/tutor-home-page/language-step/LanguageStep.jsx
  src/containers/tutor-home-page/subjects-step/SubjectsStep.jsx
  src/context/step-context.jsx
  src/context/step-context.tsx
  src/hooks/use-steps.tsx
  src/types/common/enums/common.enums.ts
  src/types/common/interfaces/common.interfaces.ts
  src/types/common/types/common.types.ts
  src/types/user/user-interfaces/user.interfaces.ts
Labels: enhancement, Frontend part, TypeScript

#1788 Added breakpoints and spacings to design system variables
  src/scss/src/foundation/_variables.scss
Labels: enhancement, Frontend part, design system

#1791 Changed video presentation behaviour
  src/pages/tutor-profile/TutorProfile.jsx
  tests/unit/pages/tutor-profile/TutorProfile.spec.jsx
Labels: Frontend part, feature

#1792 Add coverage for cooperation notes and cooperation activities list
  tests/unit/containers/my-cooperations/cooperation-activities-list/CooperationActivitiesList.spec.jsx
  tests/unit/containers/my-cooperations/cooperation-notes/CooperationNotes.spec.jsx
Labels: Frontend part, test

#1793 Fix-incorrect-redirection-after-question-creation
  src/containers/my-quizzes/create-or-edit-quiz-container/CreateOrEditQuizContainer.tsx
  src/pages/create-or-edit-lesson/CreateOrEditLesson.tsx
  src/pages/create-or-edit-question/CreateOrEditQuestion.tsx
  src/pages/my-resources/MyResources.tsx
Labels: enhancement, Frontend part, feature, Tutor

#1795 Add profile general tab functionality
  src/components/file-uploader/FileUploader.tsx
  src/components/user-steps-wrapper/constants.ts
  src/constants/translations/en/common.json
  src/constants/translations/en/edit-profile.json
  src/constants/translations/ua/common.json
  src/constants/translations/ua/edit-profile.json
  src/containers/edit-profile/common.style.ts
  src/containers/edit-profile/profile-general-tab/ProfileGeneralTab.constants.ts
  src/containers/edit-profile/profile-tab/ProfileTab.tsx
  src/containers/edit-profile/profile-tab/profile-tab-inner-container/ProfileTabInnerContainer.styles.ts
  src/containers/edit-profile/profile-tab/profile-tab-inner-container/ProfileTabInnerContainer.tsx
  src/containers/edit-profile/profile-tab/profile-tabs/profile-general-tab/ProfileGeneralTab.styles.ts
  src/containers/edit-profile/profile-tab/profile-tabs/profile-general-tab/ProfileGeneralTab.tsx
  src/containers/tutor-home-page/add-photo-step/constants.js
  src/context/profile-context.tsx
  src/hooks/use-update-user.tsx
  src/pages/edit-profile/EditProfile.constants.tsx
  src/types/attachment/types/attachment.types.ts
  src/types/common/types/common.types.ts
  src/types/edit-profile/interfaces/editProfile.interfaces.ts
  src/types/services/types/services.types.ts
  src/types/user/user-interfaces/user.interfaces.ts
  src/utils/get-profile-context-initial-values.ts
  src/utils/validations/common.ts
  tests/unit/pages/edit-profile/EditProfile.spec.jsx
Labels: Frontend part, feature

#1787 Fix behavior of "Create new question" for quiz button
  src/containers/my-quizzes/create-or-edit-quiz-container/CreateOrEditQuizContainer.tsx
  src/containers/my-quizzes/create-or-edit-quiz-question/CreateOrEditQuizQuestion.tsx
  src/context/modal-context.tsx
Labels: bug, Frontend part

#1797 Feature/1772/design system global rules
  package-lock.json
  package.json
  src/scss/src/base/_reset.scss
  src/scss/src/base/_root.scss
  src/scss/src/global.scss
  src/scss/src/scripts/compile-scss.js
Labels: enhancement, Frontend part, design system

#1802 Converted use-input-visibility hook to typescript
  src/hooks/use-input-visibility.tsx
Labels: enhancement, Frontend part, TypeScript

#1798 Feature/1771/scss mixins
  src/scss/src/foundation/_mixins.scss
  src/scss/src/foundation/_typography.scss
  src/scss/src/foundation/_variables.scss
Labels: Frontend part, design system

#1806 Fixed authorized user redirection from home to 404 page
  src/router/helpers/HomeRoute.tsx
Labels: bug, enhancement, Frontend part

#1814 Сonvert use select hook into TS/1804
  src/components/enhanced-table/enhanced-table-row/EnhancedTableRow.jsx
  src/containers/add-resources/AddResources.tsx
  src/hooks/table/use-select.jsx
  src/hooks/table/use-select.tsx
  src/types/components/enhanced-table/enhancedTable.interface.ts
  tests/unit/hooks/table/use-select.spec.jsx
Labels: Frontend part, feature

#1813 Refactor FileUploader to emit action when the same file is added twice in a row
  src/components/file-uploader/FileUploader.tsx
Labels: bug, Frontend part

#1811 Implemented functionality for Courses Filters Drawer
  src/containers/cooperation-details/add-course-modal-modal/AddCourseTemplateModal.constants.tsx
  src/containers/find-offer/offer-filter-block/OfferFilterBlock.tsx
  src/containers/find-offer/offer-search-toolbar/OfferSearchToolbar.tsx
  src/containers/my-courses/add-course-with-input/AddCourseWithInput.tsx
  src/containers/my-courses/courses-filters-drawer/CoursesFiltersDrawer.tsx
  src/hooks/use-filter-query.tsx
  src/pages/my-courses/MyCourses.tsx
  src/types/common/interfaces/common.interfaces.ts
  src/types/course/interfaces/course.interface.ts
  src/types/findOffers/interfaces/findOffers.interfaces.ts
  src/utils/count-active-filters.tsx
  tests/unit/containers/my-courses/add-course-with-input/AddCourseWithInput.spec.jsx
Labels: Frontend part, feature, Tutor

#1836 Fixed translations on new course and new coopeation activities pages
  src/constants/translations/en/course.json
  src/constants/translations/ua/course.json
Labels: enhancement, Frontend part, UI/Usability

#1846 Implement lesson view for students
  package-lock.json
  package.json
  src/components/file-editor/FileEditor.constants.ts
  src/components/file-editor/FileEditor.tsx
  src/constants/translations/en/lesson.json
  src/constants/translations/ua/lesson.json
  src/containers/layout/app-breadcrumbs/AppBreadCrumbs.tsx
  src/pages/lesson-details/LessonDetails.tsx
  src/pages/lesson-details/LessonsDetails.styles.ts
  src/router/constants/authRoutes.ts
  src/router/routes/authRouter.tsx
  tests/unit/pages/lesson-details/LessonDetails.spec.jsx
Labels: Frontend part, feature

#1835 Fixed edit profile button
  src/components/app-icon-button/AppIconButton.tsx
  src/containers/tutor-profile/profile-info/ProfileInfo.jsx
  tests/unit/components/app-icon-button/AppIconButton.spec.jsx
Labels: bug, Frontend part

#1839 Fixed course template view
  src/components/course-card/CourseCard.styles.ts
  src/containers/cooperation-details/add-course-modal-modal/AddCourseTemplateModal.styles.ts
Labels: bug, Frontend part

#1843 Feature/1818/translation fuctionality
  package-lock.json
  src/components/popular-categories/PopularCategories.tsx
  src/constants/translations/en/common.json
  src/constants/translations/ua/common.json
  src/containers/layout/account-menu/AccountMenu.tsx
  src/containers/layout/language-menu/LanguageMenu.constants.ts
  src/containers/layout/language-menu/LanguageMenu.styles.tsx
  src/containers/layout/language-menu/LanguageMenu.tsx
  src/containers/layout/notifications-menu/NotificationsMenu.tsx
  src/containers/navigation-icons/NavigationIcons.constants.tsx
  src/containers/navigation-icons/user-icons/UserIcons.tsx
  src/plugins/i18n.ts
  src/types/user/user-interfaces/user.interfaces.ts
  tests/setup-tests.js
Labels: Frontend part, feature

#1840 added view for student & tests
  src/components/img-title-description/ImgTitleDescription.tsx
  src/components/title-with-description/TitleWithDescription.tsx
  src/constants/translations/en/cooperations-page.json
  src/constants/translations/ua/cooperations-page.json
  src/containers/my-cooperations/empty-cooperation-activities/EmptyCooperation.constants.ts
  src/containers/my-cooperations/empty-cooperation-activities/EmptyCooperationActivities.tsx
  src/containers/my-cooperations/empty-cooperation-activities/EmptyCooperationTutorControls.tsx
  tests/unit/components/img-title-description/ImgTitleDescription.spec.jsx
  tests/unit/containers/my-cooperations/empty-cooperation-activities/EmptyCooperationActivities.spec.jsx
Labels: Frontend part, feature, Student
