Repository ita-social-projects/SpaceToStudy-Client, pull requests merged in 2024-11, with the labels that each got.

#2631 Align cooperation details with new design
  src/components/app-text-field/AppTextField.tsx
  src/components/cooperation-section-view/CooperationSectionView.styles.ts
  src/components/cooperation-section-view/CooperationSectionView.tsx
  src/constants/translations/en/course.json
  src/constants/translations/uk/course.json
  src/containers/course-section/CourseSectionContainer.constants.tsx
  src/containers/course-section/resource-item/ResourceItem.constants.ts
  src/containers/course-section/resource-item/ResourceItem.styles.ts
  src/containers/course-section/resource-item/ResourceItem.tsx
  src/styles/app-theme/app.pallete.ts
  tests/unit/components/cooperation-section-view/CooperationSectionView.spec.jsx
  tests/unit/containers/course-section/resource-item/ResourceItem.spec.jsx
  tests/unit/containers/my-courses/courses-filters-drawer/CoursesFiltersDrawer.spec.jsx
Labels: enhancement, Frontend part, Tutor, Student

#2655 Fix the order of 'About tutor' block
  src/containers/user-profile/about-tutor-block/AboutTutorBlock.constants.ts
  src/containers/user-profile/about-tutor-block/AboutTutorBlock.tsx
Labels: bug, Frontend part

#2637 Implemented space for search
  src/pages/chat/Chat.styles.ts
  src/pages/chat/MessagesList.tsx
Labels: bug, Frontend part

#2652 Fixed the bookmarked offers page
  src/containers/bookmarked-offers/BookmarksToolbar.styles.tsx
  src/containers/bookmarked-offers/BookmarksToolbar.tsx
  src/pages/bookmarked-offers/BookmarkedOffers.tsx
  tests/unit/pages/bookmarked-offers/BookmarkedOffers.spec.jsx
Labels: bug, Frontend part

#2667 Add 'About the student' block
  src/constants/translations/en/user-profile-page.json
  src/constants/translations/uk/user-profile-page.json
  src/containers/user-profile/about-tutor-block/AboutTutorBlock.constants.ts
  src/containers/user-profile/about-user-block/AboutStudentBlock.tsx
  src/containers/user-profile/about-user-block/AboutTutorBlock.tsx
  src/containers/user-profile/about-user-block/AboutUserBlock.styles.tsx
  src/containers/user-profile/about-user-block/AboutUserBlock.tsx
  src/containers/user-profile/about-user-block/about-user-block.constants.ts
  src/pages/user-profile/UserProfile.jsx
  src/types/user/user-interfaces/user.interfaces.ts
  tests/unit/pages/tutor-profile/TutorProfile.spec.jsx
Labels: Frontend part, feature

#2616 Block with statistics by lessons quantity
  package-lock.json
  package.json
  src/components/quantity-lessons-card/QuantityLessonChart/QuantityLessonsChart.constants.ts
  src/components/quantity-lessons-card/QuantityLessonChart/QuantityLessonsChart.tsx
  src/components/quantity-lessons-card/QuantityLessons.constants.ts
  src/components/quantity-lessons-card/QuantityLessonsCard.styles.ts
  src/components/quantity-lessons-card/QuantityLessonsCard.tsx
  src/constants/translations/en/tutor-home-page.json
  src/constants/translations/uk/tutor-home-page.json
  src/pages/tutor-home/TutorHome.tsx
Labels: Frontend part, feature, Tutor

#2626 Block with statistics by students in categories
  src/components/students-in-categories/StudentsInCategories.constants.ts
  src/components/students-in-categories/StudentsInCategories.styles.ts
  src/components/students-in-categories/StudentsInCategories.tsx
  src/components/students-in-categories/StudentsInCategoriesChart.tsx
  src/constants/translations/en/tutor-home-page.json
  src/constants/translations/uk/tutor-home-page.json
  src/pages/tutor-home/TutorHome.tsx
Labels: Frontend part, feature, Tutor

#2686 fixed naming of the interface
  src/hooks/use-user-categories-and-subjects.tsx
Labels: Frontend part, sonarFix

#2689 Removed unnecessary non-null assertion in ProficiencyLevelSelect component
  src/containers/proficiency-level-select/ProficiencyLevelSelect.tsx
Labels: good first issue, Frontend part, sonarFix

#2685 Fixed using array index as key in lists
  src/containers/edit-profile/professional-info-tab/add-professional-category-modal/AddProfessionalCategoryModal.tsx
Labels: good first issue, Frontend part, sonarFix

#2659 Update Storybook to v8.2.6 and add initial AppButton story
  .gitignore
  .storybook/main.js
  .storybook/main.ts
  .storybook/preview-head.html
  .storybook/preview.js
  .storybook/preview.tsx
  eslint.config.mjs
  package-lock.json
  package.json
  src/stories/Accordion.stories.jsx
  src/stories/AccordionWithImage.stories.jsx
  src/stories/AppAutoComplete.stories.jsx
  src/stories/AppButton.stories.jsx
  src/stories/AppButton.stories.tsx
  src/stories/AppChip.stories.js
  src/stories/AppContentSwitcher.stories.jsx
  src/stories/AppDrawer.stories.jsx
  src/stories/AppPagination.stories.jsx
  src/stories/AppRange.stories.jsx
  src/stories/AppRating.stories.jsx
  src/stories/AppRatingLarge.stories.jsx
  src/stories/AppRatingMobile.stories.jsx
  src/stories/AppSelect.stories.jsx
  src/stories/AppTextField.stories.jsx
  src/stories/Button.jsx
  src/stories/Button.stories.jsx
  src/stories/CarouselWithImage.stories.jsx
  src/stories/CheckboxList.stories.jsx
  src/stories/ConfirmDialog.stories.jsx
  src/stories/FileUploader.stories.jsx
  src/stories/FiltersToggle.stories.jsx
  src/stories/Header.jsx
  src/stories/Header.stories.jsx
  src/stories/IconTitleDescription.stories.jsx
  src/stories/InfoCard.stories.jsx
  src/stories/InputWithIcon.stories.jsx
  src/stories/Introduction.stories.mdx
  src/stories/LanguagesListWithIcon.stories.jsx
  src/stories/Loader.stories.jsx
  src/stories/MultiAccordionWithTitle.stories.jsx
  src/stories/Page.jsx
  src/stories/Page.stories.jsx
  src/stories/PopupDialog.stories.jsx
  src/stories/RadioButtonInputs.stories.jsx
  src/stories/StatusChip.stories.jsx
  src/stories/TitleWithDescription.stories.jsx
  src/stories/VideoBox.stories.jsx
  src/stories/ViewSwitcher.stories.jsx
  src/stories/button.css
  src/stories/header.css
  src/stories/page.css
  src/styles/index.css
  tsconfig.eslint.json
Labels: Frontend part, dependency

#2690 Rewrite FilterCheckbox to tsx format and fix the sonar issues
  src/components/enhanced-table/filter-checkbox/FilterCheckbox.tsx
Labels: TypeScript, sonarFix

#2653 Fixed cooperation heading
  src/containers/my-cooperations/cooperation-details/CooperationDetails.styles.ts
  src/containers/my-cooperations/cooperation-details/CooperationDetails.tsx
Labels: Frontend part

#2683 Implemented Button from scss
  .storybook/preview.tsx
  sonar-project.properties
  src/components/app-button/AppButton.scss
  src/design-system/components/button/Button.scss
  src/design-system/components/button/Button.tsx
  src/design-system/scss/_functions.scss
  src/design-system/scss/_mixins.scss
  src/design-system/scss/_reset.scss
  src/design-system/scss/_root.scss
  src/design-system/scss/_typography.scss
  src/design-system/scss/_variables.scss
  src/design-system/scss/styles.scss
  src/design-system/scss/utilities.scss
  src/design-system/scss/utilities/_index.scss
  src/design-system/scss/utilities/background.scss
  src/design-system/scss/utilities/borders.scss
  src/design-system/scss/utilities/colors.scss
  src/design-system/scss/utilities/flexbox.scss
  src/design-system/scss/utilities/shadow.scss
  src/design-system/scss/utilities/sizing.scss
  src/design-system/scss/utilities/spacing.scss
  src/design-system/stories/Button.stories.tsx
  src/index.tsx
  tests/unit/design-system/components/Button/Button.spec.jsx
  tsconfig.json
  vite.config.mts
  vitest.config.mts
Labels: Frontend part, design system

#2801 Fix profile page accordion description text overflow
  src/components/accordion/Accordion.styles.ts
  src/containers/user-profile/about-user-block/AboutUserBlock.styles.tsx
  src/containers/user-profile/about-user-block/AboutUserBlock.tsx
Labels: bug, Frontend part, my-profile

#2687 Fixed the height of card when 1 bookmark selected
  src/containers/find-offer/offer-container/OfferContainer.styles.ts
Labels: bug, good first issue, Frontend part

#2758 Added relevant first questions for tutor in chat
  src/constants/translations/en/chat.json
  src/constants/translations/uk/chat.json
  src/containers/offer-page/chat-dialog-window/ChatDialogWindow.constants.ts
  src/containers/offer-page/chat-dialog-window/ChatDialogWindow.tsx
  tests/unit/containers/offer-page/chat-dialog-window/ChatDialogWindow.spec.jsx
Labels: enhancement, Frontend part, feature, Tutor

#2692 fixed the email input erroring
  src/containers/guest-home-page/login-form/LoginForm.tsx
Labels: bug, good first issue, Frontend part

#2688 converted ResetPassword component from jsx to tsx
  src/containers/guest-home-page/reset-password/ResetPassword.tsx
  src/services/auth-service.ts
  src/types/user/user-interfaces/user.interfaces.ts
Labels: good first issue, Frontend part, sonarFix

#2709 fixed the user description going out of the boundaries
  src/containers/user-profile/profile-info/ProfileInfo.styles.js
Labels: Frontend part, Tutor, Student, my-profile, Edit

#2786 Fix unintended horizontal scrolling issue on opening cooperation details
  src/containers/my-cooperations/cooperation-completion/CooperationCompletion.styles.ts
  src/containers/my-cooperations/my-cooperations-details/MyCooperationsDetails.styles.ts
Labels: bug, Frontend part, UI/Usability

#2809 Fix long names spilling outside container on profile page
  src/containers/user-profile/profile-info/ProfileInfo.styles.js
Labels: bug, Tutor, Student, UI/Usability, my-profile

#2830 Fixed irrelevant information in the categories
  src/constants/translations/en/edit-profile.json
  src/constants/translations/uk/edit-profile.json
  src/containers/edit-profile/professional-info-tab/ProfessionalInfoTab.tsx
Labels: bug, Student, my-profile, Edit

#2815 added save password disabling
  src/containers/edit-profile/password-security-tab/change-password-modal/ChangePasswordModal.tsx
Labels: bug, Frontend part, Edit

#2787 Remove unnecessary "Add to drafts" button
  src/containers/offer-page/create-or-edit-offer/CreateOrEditOffer.constants.ts
  src/containers/offer-page/create-or-edit-offer/CreateOrEditOffer.tsx
  tests/unit/containers/offer-page/edit-offer/EditOffer.spec.jsx
Labels: bug, Frontend part

#2793 Fix incorrect displaying of Edit button on MyOffersPage
  src/containers/my-offers/my-offers-container/MyOffersContainer.tsx
Labels: bug, Frontend part

#2691 Added Progress Bar for Cooperation Activities
  src/components/app-progress-bar-line/AppProgressBarLine.constans.tsx
  src/components/app-progress-bar-line/AppProgressBarLine.styles.ts
  src/components/app-progress-bar-line/AppProgressBarLine.tsx
  src/constants/translations/en/cooperation-details.json
  src/constants/translations/uk/cooperation-details.json
  src/containers/cooperation-details/cooperation-activities-view/CooperationActivitiesView.tsx
  src/containers/cooperation-details/cooperation-activities/CooperationActivities.tsx
  src/styles/app-theme/app.pallete.ts
Labels: good first issue, Frontend part, feature

#2697 Add AboutStudentAccordion in professional tab
  src/constants/translations/en/edit-profile.json
  src/constants/translations/uk/edit-profile.json
  src/containers/edit-profile/professional-info-tab/ProfessionalInfoTab.tsx
  src/containers/edit-profile/professional-info-tab/about-student-accordion/AboutStudentAccordion.tsx
  src/containers/edit-profile/professional-info-tab/about-tutor-accordion/AboutTutorAccordion.tsx
  src/containers/user-profile/about-user-block/about-user-block.constants.ts
  tests/unit/containers/edit-profile/professional-info-tab/ProfessionalInfoTab.spec.jsx
  tests/unit/containers/edit-profile/professional-info-tab/about-tutor-accordion/AboutTutorAccordion.spec.jsx
Labels: Frontend part, feature, Student

#2835 Fixed irrelevant information in the your professional categories
  src/constants/translations/en/edit-profile.json
  src/constants/translations/uk/edit-profile.json
  src/containers/edit-profile/professional-info-tab/ProfessionalInfoTab.tsx
Labels: bug, Tutor, Student, my-profile, Edit

#2754 Rewrote EnumFilter jsx to tsx and sonarfix
  src/components/enhanced-table/enum-filter/EnumFilter.tsx
Labels: bug, good first issue, TypeScript, sonarFix

#2855 Added active tab to URL params on the cooperation page
  src/containers/my-cooperations/cooperation-details/CooperationDetails.tsx
  src/containers/my-cooperations/cooperations-container/CooperationContainer.tsx
Labels: Frontend part, feature

#2895 Created Alert component aligned with design system
  src/design-system/components/alert/Alert.scss
  src/design-system/components/alert/Alert.tsx
  src/design-system/stories/Alert.stories.tsx
  tests/unit/design-system/components/Alert/Alert.spec.jsx
Labels: Frontend part, feature, component, design system

#2860 Added translation in Ukranian for categories and subjects
  src/components/popular-categories/PopularCategories.tsx
  src/constants/translations/en/categories.json
  src/constants/translations/en/index.ts
  src/constants/translations/en/subjects.json
  src/constants/translations/uk/categories.json
  src/constants/translations/uk/index.ts
  src/constants/translations/uk/subjects.json
  src/containers/edit-profile/professional-info-tab/add-professional-category-modal/AddProfessionalCategoryModal.tsx
  src/containers/edit-profile/professional-info-tab/professional-category/ProfessionalCategory.tsx
  src/pages/categories/Categories.tsx
  src/pages/subjects/Subjects.tsx
  src/types/common/interfaces/common.interfaces.ts
  src/utils/fetch-and-translate-category.tsx
  src/utils/title-to-camel-case.ts
  tests/unit/components/popular-categories/PopularCategories.spec.jsx
  tests/unit/containers/edit-profile/professional-info-tab/add-professional-category-modal/AddProfessionalCategoryModal.spec.jsx
  tests/unit/containers/edit-profile/professional-info-tab/professional-category/ProfessionalCategory.spec.jsx
  tests/unit/pages/categories/Categories.spec.jsx
  tests/unit/pages/subjects/Subjects.spec.jsx
Labels: bug, severity: minor, priority: low, Localization

#2842 Created RadioButton component
  src/design-system/components/radio-button/RadioButton.scss
  src/design-system/components/radio-button/RadioButton.tsx
  src/design-system/stories/RadioButton.stories.tsx
  tests/unit/design-system/components/radio-button/RadioButton.spec.jsx
Labels: Frontend part, feature, component, test, design system, scss

#2899 Add functionality to edit AboutStudentAccordion on the student profile edit page
  src/containers/edit-profile/professional-info-tab/ProfessionalInfoTab.tsx
  src/containers/edit-profile/professional-info-tab/about-student-accordion/AboutStudentAccordion.tsx
  src/containers/user-profile/about-user-block/AboutStudentBlock.tsx
  src/pages/edit-profile/EditProfile.tsx
  src/pages/user-profile/UserProfile.jsx
  src/redux/features/editProfileSlice.ts
  src/types/user/user-interfaces/user.interfaces.ts
  src/types/user/user-types/user.types.ts
  tests/unit/containers/edit-profile/professional-info-tab/ProfessionalInfoTab.spec.jsx
  tests/unit/pages/tutor-profile/TutorProfile.spec.jsx
  tests/unit/redux/editProfileSlice.spec.js
Labels: Frontend part, feature, Student, Functional

#2892 Added reusable switch component according to design systems
  src/design-system/components/switch/Switch.scss
  src/design-system/components/switch/Switch.tsx
  src/design-system/stories/Switch.stories.tsx
  tests/unit/design-system/components/Switch/Switch.spec.jsx
Labels: Frontend part, feature, component, design system

#2841 Create CheckBox component for design system
  src/design-system/components/checkbox/CheckBox.scss
  src/design-system/components/checkbox/CheckBox.tsx
  src/design-system/stories/CheckBox.stories.tsx
  tests/unit/design-system/components/Checkbox/Checkbox.spec.jsx
Labels: Frontend part, feature, component, design system

#2907 Fixed Bookmarks filter section
  src/constants/translations/en/bookmarked-offers-page.json
  src/constants/translations/uk/bookmarked-offers-page.json
  src/containers/bookmarked-offers/BookmarksToolbar.styles.tsx
Labels: bug, good first issue, Frontend part

#2840 Create input field component
  src/design-system/components/input-field/InputField.scss
  src/design-system/components/input-field/InputField.tsx
  src/design-system/stories/InputField.stories.tsx
  src/types/common/enums/common.enums.ts
  tests/unit/design-system/components/input-field/InputField.spec.jsx
Labels: Frontend part, feature, component, design needed

#2744 Rewrite FilterCell to tsx
  src/components/enhanced-table/filter-row/filter-cell/FilterCell.tsx
Labels: good first issue, TypeScript, sonarFix

#2858 Feature/2844/tooltip design system
  src/design-system/components/tooltip/Tooltip.scss
  src/design-system/components/tooltip/Tooltip.tsx
  src/design-system/stories/Tooltip.stories.tsx
  tests/unit/design-system/components/Tooltip/Tooltip.spec.jsx
Labels: Frontend part, design system

#2851 fixexd calendar height
  src/components/calendar/Calendar.styles.ts
  src/components/tutor-schedule/TutorScheduleCard.styles.tsx
Labels: bug, Frontend part

#2849 Prevent profile updates without changes
  src/containers/edit-profile/profile-tab/ProfileTab.tsx
  src/containers/edit-profile/profile-tab/profile-tab-form/ProfileTabForm.tsx
  src/containers/navigation-icons/AccountIcon.tsx
  src/pages/edit-profile/EditProfile.tsx
  src/redux/features/editProfileSlice.ts
  src/types/edit-profile/interfaces/editProfile.interfaces.ts
  src/types/edit-profile/types/editProfile.types.ts
  src/types/user/user-interfaces/user.interfaces.ts
  src/utils/are-all-values-empty-strings.ts
  src/utils/has-photo-changes.ts
  src/utils/is-updated-photo.ts
  tests/unit/containers/edit-profile/profile-tab/profile-tab-form/ProfileTabForm.spec.jsx
  tests/unit/pages/edit-profile/EditProfile.spec.jsx
  tests/unit/redux/editProfileSlice.spec.js
  tests/unit/utils/are-all-values-empty-strings.spec.js
  tests/unit/utils/has-photo-changes.spec.js
  tests/unit/utils/is-updated-photo.spec.js
Labels: bug, Tutor, Student, Functional, Edit

#2837 Fixed two identical items displaying
  src/containers/edit-profile/professional-info-tab/professional-category-list/ProfessionalCategoryList.tsx
Labels: bug, Frontend part, Functional, Edit

#2912 Replaced enums from all types to design system folder
  src/design-system/components/input-field/InputField.constants.ts
  src/design-system/components/input-field/InputField.tsx
  src/design-system/stories/InputField.stories.tsx
  src/types/common/enums/common.enums.ts
Labels: bug, component, priority: low, design system
