Repository ita-social-projects/SpaceToStudy-Client, pull requests merged in 2024-08, with the labels that each got.

#2255 Updated i18next and react-i18next packages
  package.json
Labels: Frontend part, dependency

#2257 Updated jsdom package
  package.json
  tests/unit/redux/redux.spec.js
Labels: Frontend part, dependency

#2226 Rewrote ProfileItem to tsx format
  src/components/profile-item/ProfileItem.styles.ts
  src/components/profile-item/ProfileItem.tsx
Labels: Frontend part, sonarFix

#2240 Rewrote DateFilter to tsx format and fixed sonar issues
  src/components/enhanced-table/date-filter/DateFilter.constants.ts
  src/components/enhanced-table/date-filter/DateFilter.styles.ts
  src/components/enhanced-table/date-filter/DateFilter.tsx
  src/components/enhanced-table/date-filter/constants.js
  src/types/mui/customTypes.index.ts
  src/types/mui/customTypes/customTypes.d.ts
  tests/unit/components/date-filter/DateFilter.spec.jsx
Labels: TypeScript, sonarFix

#2233 Rewrote SubjectsStep to tsx format
  src/containers/tutor-home-page/subjects-step/SubjectsStep.styles.ts
  src/containers/tutor-home-page/subjects-step/SubjectsStep.tsx
  src/containers/tutor-home-page/subjects-step/constants.ts
  src/types/common/interfaces/common.interfaces.ts
Labels: TypeScript, sonarFix

#2234 Rewrote FindBlock to tsx format
  src/components/find-block/FindBlock.tsx
  src/components/find-block/find-block.styles.ts
  src/components/find-block/find-student-constants.ts
  src/components/find-block/find-tutor-constants.ts
  tests/unit/components/find-block/FindBlock.spec.jsx
Labels: TypeScript, sonarFix

#2235 Rewrote ProfileDoneItemsList to tsx format
  src/components/icon-with-text-list/ProfileDoneItemsList.style.ts
  src/components/icon-with-text-list/ProfileDoneItemsList.tsx
  src/types/components/components.index.ts
  src/types/components/icon-with-text-list/profileDoneItemsList.interfaces.ts
Labels: TypeScript, sonarFix

#2153 Fixed privacy policy translation
  src/constants/translations/en/signup.json
  src/constants/translations/uk/signup.json
  src/containers/guest-home-page/signup-form/SignupForm.jsx
Labels: bug, good first issue, Frontend part

#2164 Add an error tooltip for User Profile
  src/components/sidebar-menu/SidebarMenu.styles.ts
  src/components/sidebar-menu/SidebarMenu.tsx
  src/constants/translations/en/edit-profile.json
  src/constants/translations/uk/edit-profile.json
  src/pages/edit-profile/EditProfile.tsx
Labels: Frontend part, feature, Tutor, Student

#2220 Rewrote ProfileContainerMobile to tsx
  src/containers/user-profile/profile-info/ProfileContainerMobile.tsx
Labels: TypeScript, sonarFix

#2223 Rewrote ProfileContainerDesktop to tsx
  src/containers/user-profile/profile-info/ProfileContainerDesktop.tsx
Labels: TypeScript, sonarFix

#2158 Bugfix/2113/change category name
  src/components/app-button-menu/AppButtonMenu.tsx
Labels: bug, good first issue, Frontend part

#2243 Rewrite GoogleLogin to tsx format and fix the sonar issues
  src/containers/guest-home-page/google-login/GoogleLogin.styles.ts
  src/containers/guest-home-page/google-login/GoogleLogin.tsx
Labels: TypeScript, sonarFix

#2245 Rewrite OfferDetails to tsx format and fix the sonar issues
  src/components/offer-card/offer-details/OfferDetails.tsx
Labels: TypeScript, sonarFix

#2210 Rewrote SearchInput to tsx
  src/components/search-input/SearchInput.tsx
Labels: TypeScript, sonarFix

#2212 Rewrote VideoPresentation to tsx
  src/containers/user-profile/video-presentation/VideoPresentation.tsx
Labels: TypeScript, sonarFix

#2244 Rewrote EmailConfirmModal to tsx
  src/containers/email-confirm-modal/EmailConfirmModal.tsx
  src/context/modal-context.tsx
Labels: TypeScript, sonarFix

#2237 Rewrote AdminNavBarItem to tsx
  src/containers/layout/admin-portal/admin-nav-bar-item/AdminNavBarItem.tsx
Labels: TypeScript, sonarFix

#2238 Rewrote SignupForm to tsx
  src/containers/guest-home-page/signup-form/SignupForm.tsx
Labels: TypeScript, sonarFix

#2252 Update date dependencies
  package.json
  src/components/enhanced-table/date-filter/DateFilter.jsx
  src/containers/course-section/resource-item/ResourceItem.tsx
  tests/unit/components/date-filter/DateFilter.spec.jsx
Labels: Frontend part, feature, dependency

#2247 Fixed visual discrepancy in 'My Courses' tab for UA translation
  src/containers/my-courses/add-course-with-input/AddCourseWithInput.styles.ts
Labels: bug, Frontend part

#2154 Fix translation in the placeholder when using Ukrainian interface on the My recourses page
  src/constants/translations/uk/my-resources-page.json
Labels: bug, Frontend part

#2188 Edit container for Change Password and create popup
  src/constants/translations/en/edit-profile.json
  src/constants/translations/uk/edit-profile.json
  src/containers/edit-profile/password-security-tab/PasswordSecurityTab.styles.ts
  src/containers/edit-profile/password-security-tab/PasswordSecurityTab.tsx
  src/containers/edit-profile/password-security-tab/change-password-modal/ChangePasswordModal.tsx
  src/containers/edit-profile/password-security-tab/password-security-item/PasswordSecurityItem.styles.ts
  src/containers/edit-profile/password-security-tab/password-security-item/PasswordSecurityItem.tsx
  tests/unit/containers/edit-profile/password-security-tab/ChangePasswordModal.spec.jsx
  tests/unit/containers/edit-profile/password-security-tab/PasswordSecurityTab.spec.jsx
Labels: enhancement, Frontend part

#2157 Fix login title position
  src/containers/guest-home-page/signup-dialog/SignupDialog.styles.js
Labels: bug, good first issue, Frontend part

#2165 Add feature student profile items
  src/components/complete-profile/CompleteProfileBlock.tsx
  src/components/profile-item/ProfileItem.tsx
  src/components/profile-item/complete-profile.constants.tsx
  src/constants/translations/en/complete-profile-student.json
  src/constants/translations/en/complete-profile-tutor.json
  src/constants/translations/en/index.ts
  src/constants/translations/uk/complete-profile-student.json
  src/constants/translations/uk/complete-profile-tutor.json
  src/constants/translations/uk/index.ts
  src/pages/user-profile/UserProfile.jsx
  tests/unit/components/complete-profile/CompleteProfileBlock.spec.jsx
Labels: Frontend part, feature, Student

#2241 Rework deactivate account
  src/constants/translations/en/edit-profile.json
  src/constants/translations/uk/edit-profile.json
  src/containers/edit-profile/password-security-tab/PasswordSecurityTab.styles.ts
  src/containers/edit-profile/password-security-tab/PasswordSecurityTab.tsx
  src/containers/edit-profile/password-security-tab/change-password-modal/ChangePasswordModal.tsx
  src/containers/edit-profile/password-security-tab/password-security-item/PasswordSecurityItem.styles.ts
  src/containers/edit-profile/password-security-tab/password-security-item/PasswordSecurityItem.tsx
  tests/unit/containers/edit-profile/password-security-tab/PasswordSecurityItem.spec.jsx
  tests/unit/containers/edit-profile/password-security-tab/PasswordSecurityTab.spec.jsx
Labels: Frontend part, Tutor, Student

#2292 Fix translation of proficiency levels
  src/containers/my-courses/course-toolbar/CourseToolbar.tsx
  src/containers/proficiency-level-select/ProficiencyLevelSelect.tsx
  tests/unit/containers/my-courses/course-toolbar/CourseToolbar.spec.jsx
Labels: bug, good first issue, Frontend part

#2264 Сreate tests for GoogleButton.jsx
  tests/unit/components/google-button/GoogleButton.spec.jsx
Labels: Frontend part, test

#2256 Prevented Description Text from Exceeding Container Bounds
  src/components/show-more-collapse/ShowMoreCollapse.styles.ts
  src/components/show-more-collapse/ShowMoreCollapse.tsx
  tests/unit/components/show-more-collapse/ShowMoreCollapse.spec.jsx
Labels: bug, Frontend part

#2271 Corrected pluralisation of offer counts
  src/components/popular-categories/PopularCategories.tsx
  src/constants/translations/en/categories-page.json
  src/constants/translations/en/common.json
  src/constants/translations/uk/categories-page.json
  src/constants/translations/uk/common.json
  src/pages/categories/Categories.tsx
  src/pages/subjects/Subjects.tsx
  tests/unit/components/popular-categories/PopularCategories.spec.jsx
  tests/unit/pages/categories/Categories.spec.jsx
  tests/unit/pages/subjects/Subjects.spec.jsx
Labels: bug, Frontend part

#2293 Corrected Count of Offers in 'Other offers' Carousel
  src/containers/offer-details/offer-carousel/OfferCarousel.constants.ts
Labels: bug, Frontend part

#2299 Bugfix/2276/set not visible button
  src/containers/cooperation-details/cooperetion-activities-view/CooperationActivitiesView.tsx
  tests/unit/containers/cooperation-details/ CooperationActivitiesView.spec.jsx
Labels: bug, Frontend part

#2303 Fixed date serialization and mask input issues in DatePicker component #2103
  src/containers/course-section/resource-item/ResourceItem.tsx
  src/types/course/types/course.types.ts
Labels: bug, Frontend part, priority: medium

#2263 Increase test coverage for CreateOrEditQuizQuestion.tsx
  tests/unit/containers/my-quizzes/CreateOrEditQuizQuestion.spec.jsx
Labels: Frontend part, test

#2272 Increased test coverafe for CreateOrEditLesson.tsx
  tests/unit/pages/create-or-edit-lesson/CreateOrEditLesson.spec.jsx
  tests/unit/pages/create-or-edit-lesson/CreateOrEditLessonWithId.spec.jsx
Labels: Frontend part, test

#2306 Fix ProfileItems count and make CompleteProfile visible only for owner
  src/components/complete-profile/CompleteProfileBlock.tsx
  src/components/profile-item/ProfileItem.tsx
  src/components/profile-item/complete-profile.constants.tsx
  src/constants/translations/en/complete-profile-student.json
  src/constants/translations/uk/complete-profile-student.json
  src/pages/user-profile/UserProfile.jsx
  src/types/services/types/services.types.ts
  src/types/user/user-interfaces/user.interfaces.ts
  tests/unit/components/complete-profile/CompleteProfileBlock.spec.jsx
Labels: bug, Frontend part, Tutor, Student

#2308 Rewrote AdminNavBar to tsx format and fix the sonar issues
  src/containers/layout/admin-portal/admin-nav-bar-item/AdminNavBarItem.tsx
  src/containers/layout/admin-portal/admin-nav-bar/AdminNavBar.tsx
Labels: TypeScript, sonarFix

#2242 Rewrite GoogleButton to tsx format and fix the sonar issues
  src/containers/guest-home-page/google-button/GoogleButton.jsx
  src/containers/guest-home-page/google-button/GoogleButton.styles.ts
  src/containers/guest-home-page/google-button/GoogleButton.tsx
Labels: TypeScript, sonarFix

#2305 Add "Sort by" and "Filter by" options in "What students say" block
  src/constants/labels.ts
  src/constants/translations/en/common.json
  src/constants/translations/en/user-profile-page.json
  src/constants/translations/uk/common.json
  src/constants/translations/uk/user-profile-page.json
  src/containers/user-profile/comments-block/CommentBlock.tsx
  src/containers/user-profile/comments-with-rating-block/CommentsWithRatingBlock.styles.ts
  src/containers/user-profile/comments-with-rating-block/CommentsWithRatingBlock.tsx
  src/pages/my-cooperations/MyCooperations.tsx
  src/pages/quiz/Quiz.tsx
  src/types/common/enums/common.enums.ts
  src/types/offer/interfaces/offer.interfaces.ts
  tests/unit/pages/quiz/Quiz.spec.jsx
Labels: Frontend part, feature

#2317 Rewrite UserTable to tsx format and fix the sonar issues
  src/components/user-table/UserTable.tsx
Labels: TypeScript, sonarFix

#2315 Fix coop details buttons
  src/containers/my-cooperations/my-cooperations-details/MyCooperationsDetails.styles.ts
  src/containers/my-cooperations/my-cooperations-details/MyCooperationsDetails.tsx
  tests/unit/hooks/use-load-more.spec.jsx
Labels: bug, good first issue, Frontend part, Tutor, Student

#2332 Add video ProfileItem for tutor
  src/components/app-progress-bar-line/AppProgressBarLine.tsx
  src/components/complete-profile/CompleteProfileBlock.tsx
  src/components/profile-item/ProfileItem.tsx
  src/components/profile-item/complete-profile.constants.tsx
  src/constants/translations/en/complete-profile-tutor.json
  src/constants/translations/uk/complete-profile-tutor.json
  src/pages/user-profile/UserProfile.jsx
  tests/unit/components/complete-profile/CompleteProfileBlock.spec.jsx
Labels: Frontend part, feature, Tutor

#2333 Created CheckboxWithTooltip component
  src/components/checkbox-with-tooltip/CheckboxWithTooltip.styles.ts
  src/components/checkbox-with-tooltip/CheckboxWithTooltip.tsx
  tests/unit/components/checkbox-with-tooltip/CheckboxWithTooltip.spec.jsx
Labels: Frontend part, feature

#2334 Added error message on saving section without title or description in cooperation #2327
  src/containers/cooperation-details/cooperation-activities/CooperationActivities.tsx
  tests/unit/containers/cooperation-details/CooperationActivities.spec.jsx
  tests/unit/containers/cooperation-details/add-course-modal-modal/AddCourseTemplateModal.spec.jsx
  tests/unit/containers/cooperation-details/cooperation-activities-view/ CooperationActivitiesView.spec.jsx
  tests/unit/containers/cooperation-details/cooperation-activities/CooperationActivities.spec.jsx
Labels: bug, Frontend part, Tutor, priority: high

#2341 Change video ProfileItem icon
  src/components/profile-item/complete-profile.constants.tsx
  tests/unit/containers/tutor-profile/ProfileInfo.spec.jsx
Labels: bug, good first issue, Frontend part

#2342 Increase indent before the 'What students say' block
  src/containers/user-profile/comments-with-rating-block/CommentsWithRatingBlock.styles.ts
Labels: bug, good first issue, Frontend part

#2350 Added alert for successful update user data
  package-lock.json
  package.json
  src/pages/edit-profile/EditProfile.tsx
Labels: enhancement, Frontend part

#2302 Rewrote StepWrapper to tsx
  src/components/step-wrapper/StepWrapper.tsx
Labels: TypeScript, sonarFix

#2282 Changed CooperationCompletion visibility for students
  src/containers/my-cooperations/my-cooperations-details/MyCooperationsDetails.tsx
Labels: Frontend part

#2229 Rewrote GeneralInfoStep to tsx
  src/containers/tutor-home-page/general-info-step/GeneralInfoStep.tsx
Labels: TypeScript, sonarFix

#2216 Rewrote ProfileInfo to tsx
  src/containers/user-profile/profile-info/ProfileInfo.tsx
Labels: TypeScript, sonarFix

#2320 Rewrote LanguageStep to tsx
  src/containers/tutor-home-page/language-step/LanguageStep.styles.js
  src/containers/tutor-home-page/language-step/LanguageStep.tsx
Labels: Frontend part, sonarFix

#2310 Deleted unused useUpdateUser hook
  src/hooks/use-update-user.tsx
  tests/unit/hooks/use-update-user.spec.jsx
Labels: Frontend part, feature

#2312 Deleted unused userProfileLoader
  src/router/constants/loaders.ts
  src/router/routes/authRouter.tsx
Labels: Frontend part, feature

#2230 Fix visual discrepancy
  src/components/setting-item/SettingItem.styles.ts
  src/containers/edit-profile/notification-tab/NotificationTab.styles.ts
  src/containers/edit-profile/notification-tab/NotificationTab.tsx
Labels: bug, Frontend part

#2269 Fix sonar issues in AddProfessionalCategoryModal component
  src/containers/edit-profile/professional-info-tab/add-professional-category-modal/AddProfessionalCategoryModal.tsx
Labels: TypeScript, sonarFix

#2289 Fixed toggle action
  src/containers/edit-profile/professional-info-tab/about-tutor-accordion/AboutTutorAccordion.tsx
Labels: bug, Frontend part

#2301 Fixed error in console
  src/components/title-with-description/TitleWithDescription.tsx
Labels: bug, Frontend part

#2300 Fixed: displaying student info for cooperation details (when logged in as a tutor)
  src/constants/translations/en/cooperation-details.json
  src/constants/translations/uk/cooperation-details.json
  src/containers/my-cooperations/my-cooperations-details/MyCooperationsDetails.tsx
  src/types/cooperation/interfaces/cooperation.interface.ts
  tests/unit/containers/my-cooperations/cooperation-details/CooperationDetails.spec.jsx
  tests/unit/containers/my-cooperations/my-cooperations-details/MyCooperationsDetails.spec.jsx
Labels: Frontend part

#2343 Created Lesson changing Confirm
  src/components/changing-confirm/ChangeConfirm.styles.ts
  src/components/changing-confirm/ChangeConfirm.tsx
  src/constants/translations/en/change-confirm.json
  src/constants/translations/en/index.ts
  src/constants/translations/uk/change-confirm.json
  src/constants/translations/uk/index.ts
  tests/unit/components/changing-confirm/ChangingConfirm.spec.jsx
Labels: Frontend part, feature

#2347 Reorganized scss package
  package.json
  src/components/app-button/AppButton.scss
  src/components/app-button/AppButton.tsx
  src/scss/base/_base.scss
  src/scss/base/_index.scss
  src/scss/base/_reset.scss
  src/scss/base/_root.scss
  src/scss/foundation/_colors.scss
  src/scss/foundation/_index.scss
  src/scss/foundation/_mixins.scss
  src/scss/foundation/_typography.scss
  src/scss/foundation/_variables.scss
  src/scss/src/foundation/_all.scss
  src/scss/src/molecules/.gitkeep
  src/scss/src/organisms/.gitkeep
  src/scss/src/scripts/compile-scss.js
  src/scss/styles.scss
Labels: design system

#2259 Created an Update button to save all data from ProfileEdit page and send it to backend
  src/constants/translations/en/edit-profile.json
  src/constants/translations/uk/edit-profile.json
  src/containers/edit-profile/notification-tab/NotificationTab.tsx
  src/containers/edit-profile/professional-info-tab/ProfessionalInfoTab.tsx
  src/containers/edit-profile/profile-tab/ProfileTab.tsx
  src/pages/edit-profile/EditProfile.styles.ts
  src/pages/edit-profile/EditProfile.tsx
  src/redux/features/editProfileSlice.ts
  src/types/user/user-interfaces/user.interfaces.ts
  src/types/user/user-types/user.types.ts
  tests/unit/containers/edit-profile/notification-tab/NotificationTab.spec.jsx
  tests/unit/containers/edit-profile/professional-info-tab/ProfessionalInfoTab.spec.jsx
  tests/unit/pages/edit-profile/EditProfile.spec.jsx
  tests/unit/redux/editProfileSlice.spec.js
Labels: enhancement, Frontend part, Tutor, Student

#2352 Created 'cn' utility for efficient class name management
  src/utils/cn.ts
  tests/unit/utils/cn.spec.js
  vitest.config.ts
Labels: Frontend part, feature, design system

#2346 Changed all avatar icons
  src/components/avatar-icon/AvatarIcon.styles.ts
  src/components/avatar-icon/AvatarIcon.tsx
  src/components/message/Message.tsx
  src/components/user-profile-info/UserProfileInfo.styles.ts
  src/components/user-profile-info/UserProfileInfo.tsx
  src/containers/about-chat-sidebar/AboutChatSidebar.styles.ts
  src/containers/about-chat-sidebar/AboutChatSidebar.tsx
  src/containers/chat/chat-item/ChatItem.tsx
  src/containers/edit-profile/profile-tab/profile-tab-form/ProfileTabForm.styles.ts
  src/containers/edit-profile/profile-tab/profile-tab-form/ProfileTabForm.tsx
  src/containers/my-cooperations/cooperation-notes/create-or-edit-note/CreateOrEditNote.tsx
  src/containers/my-cooperations/cooperation-notes/note-view/NoteView.tsx
  src/containers/my-cooperations/my-cooperations-details/MyCooperationsDetails.tsx
  src/containers/user-profile/profile-info/ProfileContainerDesktop.tsx
  src/containers/user-profile/profile-info/ProfileContainerMobile.tsx
  src/containers/user-profile/profile-info/ProfileInfo.styles.js
  src/types/chat/message/interfaces/message.interface.ts
  tests/unit/components/avatar-icon/AvatarIcon.spec.jsx
  tests/unit/containers/edit-profile/profile-tab/profile-tab-form/ProfileTabForm.spec.jsx
  tests/unit/containers/find-offer/offer-card-square/OfferCardSquare.spec.jsx
Labels: Frontend part, feature

#2354 The 'Save changes' button become disabled after changing main study category
  src/containers/edit-profile/professional-info-tab/add-professional-category-modal/AddProfessionalCategoryModal.tsx
  src/pages/find-offers/FindOffers.tsx
  tests/unit/containers/edit-profile/professional-info-tab/add-professional-category-modal/AddProfessionalCategoryModal.spec.jsx
  tests/unit/pages/find-offers/FindOffers.spec.jsx
Labels: bug, Frontend part, Functional

#2365 Added the possibility to add a resource to a Cooperation in two ways: by duplicating or linking
  src/components/checkbox-with-tooltip/CheckboxWithTooltip.tsx
  src/containers/add-resources/AddResources.tsx
  src/containers/course-section/CourseSectionContainer.tsx
  src/containers/my-cooperations/cooperation-activities-list/CooperationActivitiesList.tsx
  src/containers/my-resources/add-resource-modal/AddResourceModal.tsx
  src/hooks/table/use-select.tsx
  src/redux/features/cooperationsSlice.ts
  src/types/common/interfaces/common.interfaces.ts
  src/types/my-resources/interfaces/myResources.interface.ts
  tests/unit/components/checkbox-with-tooltip/CheckboxWithTooltip.spec.jsx
  tests/unit/containers/cooperation-details/cooperation-activities/CooperationActivities.spec.jsx
  tests/unit/containers/course-section/CourseSectionContainer.spec.constants.js
  tests/unit/containers/course-section/CourseSectionContainer.spec.jsx
  tests/unit/containers/my-cooperations/cooperation-activities-list/CooperationActivitiesList.spec.constants.js
  tests/unit/containers/my-cooperations/cooperation-activities-list/CooperationActivitiesList.spec.jsx
  tests/unit/redux/cooperationsSlice.spec.js
Labels: enhancement, Frontend part, feature, Tutor

#2368 Check photo types and ensured it is saved on backend
  src/containers/edit-profile/profile-tab/ProfileTab.tsx
  src/pages/edit-profile/EditProfile.tsx
  src/redux/features/editProfileSlice.ts
  tests/unit/containers/edit-profile/ProfileTab.spec.jsx
  tests/unit/pages/edit-profile/EditProfile.spec.jsx
  tests/unit/redux/editProfileSlice.spec.js
  vitest.config.ts
Labels: enhancement, Frontend part, Tutor, Student

#2383 Returned UserProfileLoader
  src/router/constants/loaders.ts
  src/router/routes/authRouter.tsx
Labels: bug, Frontend part

#2363 Fixed bug when user deletes all empty subjects
  src/containers/edit-profile/professional-info-tab/add-professional-category-modal/AddProfessionalCategoryModal.tsx
  src/utils/is-submit-disabled.tsx
Labels: bug, Frontend part, Functional

#2380 Changed header and menu design
  src/components/app-menu/AppMenu.styles.ts
  src/components/complete-profile/CompleteProfileBlock.tsx
  src/constants/translations/en/header.json
  src/constants/translations/uk/header.json
  src/containers/layout/account-menu/AccountMenu.styles.ts
  src/containers/layout/account-menu/AccountMenu.tsx
  src/containers/layout/navbar/NavBar.tsx
  src/containers/layout/notifications-menu/NotificationsMenu.constants.ts
  src/containers/student-home-page/faq/Faq.tsx
  src/containers/student-home-page/student-how-it-works/StudentHowItWorks.jsx
  src/containers/user-profile/profile-info/ProfileInfo.tsx
  src/pages/my-cooperations/MyCooperations.tsx
  src/pages/user-profile/UserProfile.jsx
  src/router/constants/authRoutes.ts
  src/router/constants/crumbs.ts
  src/router/constants/studentRoutes.ts
  src/router/constants/tutorRoutes.ts
  src/router/routes/authRouter.tsx
  tests/unit/containers/layout/account-menu/AccountMenu.spec.jsx
  tests/unit/containers/navbar/NavBar.spec.jsx
  tests/unit/containers/navigation-icons/user-icons/UserIcons.spec.jsx
Labels: Frontend part, feature, Tutor, Student

#2387 Added categories to dataToUpdate on EditProfile
  src/pages/edit-profile/EditProfile.tsx
Labels: enhancement, Frontend part

#2384 The button isn't centered in the pop-up window, after creating new student/tutor account and confirming new email
  src/containers/email-confirm-modal/EmailConfirmModal.styles.js
Labels: bug, UI/Usability, severity: minor, priority: medium

#2316 Replaced functionality of create course in order to use new handlers #2070
  src/containers/cooperation-details/cooperation-activities/CooperationActivities.tsx
  src/pages/create-course/CreateCourse.constants.tsx
  src/pages/create-course/CreateCourse.tsx
  src/types/common/interfaces/common.interfaces.ts
  tests/unit/containers/cooperation-details/CooperationActivities.spec.jsx
  tests/unit/containers/cooperation-details/add-course-modal-modal/AddCourseTemplateModal.spec.jsx
  tests/unit/containers/cooperation-details/cooperation-activities-view/ CooperationActivitiesView.spec.jsx
  tests/unit/containers/cooperation-details/cooperation-activities/CooperationActivities.spec.jsx
  tests/unit/containers/my-courses/course-toolbar/CourseToolbar.spec.jsx
  tests/unit/pages/create-course/CreateCourse.spec.constants.js
  tests/unit/pages/create-course/CreateCourse.spec.jsx
Labels: enhancement, Frontend part, feature, Tutor, priority: high

#2388 Fixed drag-and-drop functionality and unique ID generation
  src/components/cooperation-section-view/CooperationSectionView.tsx
  src/containers/cooperation-details/cooperation-activities-view/CooperationActivitiesView.tsx
  src/containers/course-sections-list/CourseSectionsList.tsx
  src/containers/my-cooperations/cooperation-activities-list/CooperationActivitiesList.tsx
  src/containers/my-cooperations/cooperation-details/CooperationDetails.tsx
  src/pages/create-course/CreateCourse.tsx
  src/redux/features/cooperationsSlice.ts
  tests/unit/containers/cooperation-details/cooperation-activities-view/ CooperationActivitiesView.spec.jsx
  tests/unit/containers/course-sections-list/CourseSectionsList.spec.jsx
  tests/unit/containers/my-cooperations/cooperation-activities-list/CooperationActivitiesList.spec.constants.js
  tests/unit/containers/my-cooperations/cooperation-activities-list/CooperationActivitiesList.spec.jsx
  tests/unit/redux/cooperationsSlice.spec.js
Labels: bug, Frontend part, Tutor, priority: high

#2379 Disabled already linked resources in Course/Cooperation in choose resources modals
  src/components/cooperation-section-view/CooperationSectionView.tsx
  src/components/enhanced-table/EnhancedTable.tsx
  src/components/enhanced-table/enhanced-table-row/EnhancedTableRow.styles.ts
  src/components/enhanced-table/enhanced-table-row/EnhancedTableRow.tsx
  src/containers/add-resources/AddResources.tsx
  src/containers/cooperation-details/cooperation-activities-view/CooperationActivitiesView.tsx
  src/containers/course-sections-list/CourseSectionsList.tsx
  src/containers/my-cooperations/cooperation-activities-list/CooperationActivitiesList.tsx
  src/containers/my-cooperations/cooperation-details/CooperationDetails.tsx
  src/containers/my-resources/add-resource-modal/AddResourceModal.tsx
  src/pages/create-course/CreateCourse.tsx
  src/redux/features/cooperationsSlice.ts
  tests/unit/containers/cooperation-details/cooperation-activities-view/ CooperationActivitiesView.spec.jsx
  tests/unit/containers/course-sections-list/CourseSectionsList.spec.jsx
  tests/unit/containers/my-cooperations/cooperation-activities-list/CooperationActivitiesList.spec.constants.js
  tests/unit/containers/my-cooperations/cooperation-activities-list/CooperationActivitiesList.spec.jsx
  tests/unit/redux/cooperationsSlice.spec.js
Labels: Frontend part, feature, Tutor

#2372 Updated icon display based on resource addition method (link vs copy)
  src/components/cooperation-section-view/CooperationSectionView.tsx
  src/components/enhanced-table/EnhancedTable.tsx
  src/components/enhanced-table/enhanced-table-row/EnhancedTableRow.styles.ts
  src/components/enhanced-table/enhanced-table-row/EnhancedTableRow.tsx
  src/containers/add-resources/AddResources.tsx
  src/containers/cooperation-details/cooperation-activities-view/CooperationActivitiesView.tsx
  src/containers/course-section/resource-item/ResourceItem.styles.ts
  src/containers/course-section/resource-item/ResourceItem.tsx
  src/containers/course-sections-list/CourseSectionsList.tsx
  src/containers/my-cooperations/cooperation-activities-list/CooperationActivitiesList.tsx
  src/containers/my-cooperations/cooperation-details/CooperationDetails.tsx
  src/containers/my-resources/add-resource-modal/AddResourceModal.tsx
  src/pages/create-course/CreateCourse.tsx
  src/redux/features/cooperationsSlice.ts
  tests/unit/containers/cooperation-details/cooperation-activities-view/ CooperationActivitiesView.spec.jsx
  tests/unit/containers/course-section/CourseSectionContainer.spec.constants.js
  tests/unit/containers/course-section/resource-item/ResourceItem.spec.constants.js
  tests/unit/containers/course-section/resource-item/ResourceItem.spec.jsx
  tests/unit/containers/course-sections-list/CourseSectionsList.spec.jsx
  tests/unit/containers/my-cooperations/cooperation-activities-list/CooperationActivitiesList.spec.constants.js
  tests/unit/containers/my-cooperations/cooperation-activities-list/CooperationActivitiesList.spec.jsx
  tests/unit/pages/create-course/CreateCourse.spec.constants.js
  tests/unit/pages/create-course/CreateCourse.spec.jsx
  tests/unit/pages/create-or-edit-lesson/CreateOrEditLesson.spec.jsx
  tests/unit/redux/cooperationsSlice.spec.js
Labels: Frontend part, feature, Tutor

#2391 Fix UserTable file
  src/components/user-table/UserTable.tsx
  src/hooks/table/use-sort.tsx
Labels: bug, Frontend part

#2369 Added the possibility to add a resource to a Course in two ways: by duplicating or linking
  src/components/cooperation-section-view/CooperationSectionView.tsx
  src/components/enhanced-table/EnhancedTable.tsx
  src/components/enhanced-table/enhanced-table-row/EnhancedTableRow.styles.ts
  src/components/enhanced-table/enhanced-table-row/EnhancedTableRow.tsx
  src/containers/add-resources/AddResources.tsx
  src/containers/cooperation-details/cooperation-activities-view/CooperationActivitiesView.tsx
  src/containers/course-section/resource-item/ResourceItem.styles.ts
  src/containers/course-section/resource-item/ResourceItem.tsx
  src/containers/course-sections-list/CourseSectionsList.tsx
  src/containers/my-cooperations/cooperation-activities-list/CooperationActivitiesList.tsx
  src/containers/my-cooperations/cooperation-details/CooperationDetails.tsx
  src/containers/my-resources/add-resource-modal/AddResourceModal.tsx
  src/pages/create-course/CreateCourse.tsx
  src/redux/features/cooperationsSlice.ts
  tests/unit/containers/cooperation-details/cooperation-activities-view/ CooperationActivitiesView.spec.jsx
  tests/unit/containers/course-section/CourseSectionContainer.spec.constants.js
  tests/unit/containers/course-section/resource-item/ResourceItem.spec.constants.js
  tests/unit/containers/course-section/resource-item/ResourceItem.spec.jsx
  tests/unit/containers/course-sections-list/CourseSectionsList.spec.jsx
  tests/unit/containers/my-cooperations/cooperation-activities-list/CooperationActivitiesList.spec.constants.js
  tests/unit/containers/my-cooperations/cooperation-activities-list/CooperationActivitiesList.spec.jsx
  tests/unit/pages/create-course/CreateCourse.spec.constants.js
  tests/unit/pages/create-course/CreateCourse.spec.jsx
  tests/unit/pages/create-or-edit-lesson/CreateOrEditLesson.spec.jsx
  tests/unit/redux/cooperationsSlice.spec.js
Labels: enhancement, Frontend part, feature, Tutor

#2366 Add 'What tutors say' block for students
  src/constants/translations/en/user-profile-page.json
  src/constants/translations/uk/user-profile-page.json
  src/containers/user-profile/comments-block/CommentBlock.tsx
  src/containers/user-profile/comments-with-rating-block/CommentsWithRatingBlock.constants.ts
  src/containers/user-profile/comments-with-rating-block/CommentsWithRatingBlock.tsx
  src/pages/user-profile/UserProfile.jsx
  tests/unit/containers/tutor-profile/comments-block/ComentsBlock.spec.jsx
Labels: bug, Frontend part, Student

#2328 Fixed icon for tutoring subject
  src/containers/my-cooperations/my-cooperations-details/MyCooperationsDetails.tsx
Labels: bug, Frontend part

#2325 Add functionality to bookmark icons
  src/components/offer-card/OfferCard.tsx
  src/components/offer-card/offer-details/OfferDetails.tsx
  src/constants/request.ts
  src/constants/translations/en/icons-tooltip.json
  src/constants/translations/uk/icons-tooltip.json
  src/containers/find-offer/offer-card-square/OfferCardSquare.tsx
  src/containers/find-offer/offer-container/OfferContainer.tsx
  src/pages/find-offers/FindOffers.tsx
  src/redux/features/editProfileSlice.ts
  src/services/user-service.tsx
  src/types/user/user-interfaces/user.interfaces.ts
  tests/unit/containers/find-offer/offer-container/OfferContainer.spec.jsx
  tests/unit/redux/editProfileSlice.spec.js
Labels: Frontend part

#2392 Resolved BSONTypeError when adding duplicate resources to Course/Cooperation
  src/components/cooperation-section-view/CooperationSectionView.tsx
  src/containers/cooperation-details/cooperation-activities-view/CooperationActivitiesView.tsx
  src/containers/course-section/CourseSectionContainer.tsx
  src/containers/course-section/resources-list/ResourcesList.tsx
  src/containers/course-sections-list/CourseSectionsList.tsx
  src/containers/my-cooperations/cooperation-activities-list/CooperationActivitiesList.constants.ts
  src/containers/my-cooperations/cooperation-activities-list/CooperationActivitiesList.tsx
  src/containers/my-cooperations/cooperation-details/CooperationDetails.tsx
  src/containers/my-cooperations/empty-cooperation-activities/EmptyCooperationTutorControls.tsx
  src/pages/create-course/CreateCourse.tsx
  src/redux/features/cooperationsSlice.ts
  src/types/my-resources/interfaces/myResources.interface.ts
  src/utils/validations/isValidUUID.js
  tests/unit/components/cooperation-section-view/CooperationSectionView.spec.jsx
  tests/unit/containers/cooperation-details/cooperation-activities-view/ CooperationActivitiesView.spec.jsx
  tests/unit/containers/course-section/CourseSectionContainer.spec.constants.js
  tests/unit/containers/course-section/CourseSectionContainer.spec.jsx
  tests/unit/containers/my-cooperations/cooperation-activities-list/CooperationActivitiesList.spec.constants.js
  tests/unit/containers/my-cooperations/cooperation-activities-list/CooperationActivitiesList.spec.jsx
  tests/unit/pages/create-course/CreateCourse.spec.constants.js
  tests/unit/pages/create-course/CreateCourse.spec.jsx
  tests/unit/redux/cooperationsSlice.spec.js
  tests/unit/utils/validations/isValidUUID.spec.js
  vitest.config.ts
Labels: bug, Frontend part, Tutor, Functional, severity: major, priority: high

#2358 Added the possibility to add a resource to a Cooperation / Course in two ways: by duplicating or linking
  src/components/checkbox-with-tooltip/CheckboxWithTooltip.tsx
  src/components/cooperation-section-view/CooperationSectionView.tsx
  src/components/enhanced-table/EnhancedTable.tsx
  src/components/enhanced-table/enhanced-table-row/EnhancedTableRow.styles.ts
  src/components/enhanced-table/enhanced-table-row/EnhancedTableRow.tsx
  src/constants/translations/en/my-resources-page.json
  src/constants/translations/uk/my-resources-page.json
  src/containers/add-resources/AddResources.tsx
  src/containers/cooperation-details/cooperation-activities-view/CooperationActivitiesView.tsx
  src/containers/course-section/CourseSectionContainer.tsx
  src/containers/course-section/resource-item/ResourceItem.styles.ts
  src/containers/course-section/resource-item/ResourceItem.tsx
  src/containers/course-section/resources-list/ResourcesList.tsx
  src/containers/course-sections-list/CourseSectionsList.tsx
  src/containers/my-cooperations/cooperation-activities-list/CooperationActivitiesList.constants.ts
  src/containers/my-cooperations/cooperation-activities-list/CooperationActivitiesList.tsx
  src/containers/my-cooperations/cooperation-details/CooperationDetails.tsx
  src/containers/my-cooperations/cooperations-container/CooperationContainer.constants.tsx
  src/containers/my-cooperations/cooperations-container/CooperationContainer.tsx
  src/containers/my-cooperations/empty-cooperation-activities/EmptyCooperationTutorControls.tsx
  src/containers/my-offers/my-offers-container/MyOffersContainer.tsx
  src/containers/my-quizzes/QuizzesContainer.tsx
  src/containers/my-resources/add-resource-modal/AddResourceModal.styles.ts
  src/containers/my-resources/add-resource-modal/AddResourceModal.tsx
  src/containers/my-resources/attachments-container/AttachmentsContainer.tsx
  src/containers/my-resources/categories-container/CategoriesContainer.tsx
  src/containers/my-resources/lessons-container/LessonsContainer.tsx
  src/containers/my-resources/questions-container/QuestionsContainer.tsx
  src/hooks/table/use-select.tsx
  src/pages/create-course/CreateCourse.tsx
  src/redux/features/cooperationsSlice.ts
  src/types/common/interfaces/common.interfaces.ts
  src/types/my-resources/interfaces/myResources.interface.ts
  src/utils/helper-functions.tsx
  src/utils/validations/isValidUUID.js
  tests/unit/components/checkbox-with-tooltip/CheckboxWithTooltip.spec.jsx
  tests/unit/components/cooperation-section-view/CooperationSectionView.spec.jsx
  tests/unit/containers/cooperation-details/cooperation-activities-view/ CooperationActivitiesView.spec.jsx
  tests/unit/containers/cooperation-details/cooperation-activities/CooperationActivities.spec.jsx
  tests/unit/containers/course-section/CourseSectionContainer.spec.constants.js
  tests/unit/containers/course-section/CourseSectionContainer.spec.jsx
  tests/unit/containers/course-section/resource-item/ResourceItem.spec.constants.js
  tests/unit/containers/course-section/resource-item/ResourceItem.spec.jsx
  tests/unit/containers/course-sections-list/CourseSectionsList.spec.jsx
  tests/unit/containers/my-cooperations/cooperation-activities-list/CooperationActivitiesList.spec.constants.js
  tests/unit/containers/my-cooperations/cooperation-activities-list/CooperationActivitiesList.spec.jsx
  tests/unit/pages/create-course/CreateCourse.spec.constants.js
  tests/unit/pages/create-course/CreateCourse.spec.jsx
  tests/unit/pages/create-or-edit-lesson/CreateOrEditLesson.spec.jsx
  tests/unit/redux/cooperationsSlice.spec.js
  tests/unit/utils/validations/isValidUUID.spec.js
  vitest.config.ts
Labels: enhancement, Frontend part, feature, predecessor

#2397 Fix pagination Find offers page
  src/pages/find-offers/FindOffers.tsx
  tests/unit/pages/find-offers/FindOffers.spec.jsx
Labels: bug, Frontend part

#2401 Fixed course template duplication issues in Cooperation #2395
  src/redux/features/cooperationsSlice.ts
  tests/unit/redux/cooperationsSlice.spec.js
Labels: bug, Frontend part, Tutor, Functional, priority: high

#2400 Fixed jumping footer on my offers page
  src/pages/my-offers/MyOffers.tsx
Labels: bug, Frontend part

#2393 Increased line height in course cards
  src/components/course-card/CourseCard.styles.ts
Labels: bug, Frontend part

#2377 Implement infinite scroll functionality
  src/containers/offer-page/chat-dialog-window/ChatDialogWindow.tsx
  src/pages/chat/Chat.styles.ts
  src/pages/chat/Chat.tsx
  src/pages/chat/MessagesList.tsx
  src/services/message-service.ts
  src/types/chat/message/interfaces/message.interface.ts
  tests/unit/components/message/Message.spec.jsx
  tests/unit/containers/chat/list-of-users-with-search/MockChat.spec.constants.js
  tests/unit/containers/offer-page/chat-dialog-window/ChatDialogWindow.spec.jsx
  tests/unit/pages/chat/Chat.spec.jsx
  tests/unit/pages/chat/messages-list/MessagesList.spec.jsx
Labels: Frontend part, feature

#2353 Made progress bar values correspond to reviews quantity
  src/pages/user-profile/UserProfile.jsx
  src/pages/user-profile/constants.js
Labels: bug, Frontend part, Functional

#2403 Fix buttons on language and photo step
  src/containers/tutor-home-page/add-photo-step/AddPhotoStep.tsx
  src/containers/tutor-home-page/language-step/LanguageStep.tsx
  tests/unit/containers/tutor-home-page/add-photo-step/AddPhotoStep.spec.jsx
Labels: bug

#2324 Misaligned Character Count in TextArea
  src/components/app-text-area/AppTextArea.styles.ts
  src/containers/edit-profile/professional-info-tab/ProfessionalInfoTab.tsx
  tests/unit/containers/edit-profile/professional-info-tab/ProfessionalInfoTab.spec.jsx
Labels: bug, Frontend part

#2408 Fixed bugs with description and title in create course block and create lesson block
  src/containers/my-courses/course-toolbar/CourseToolbar.tsx
  src/pages/create-or-edit-lesson/CreateOrEditLesson.tsx
  tests/unit/pages/create-course/CreateCourse.spec.jsx
  tests/unit/pages/create-or-edit-lesson/CreateOrEditLessonWithId.spec.jsx
Labels: bug, Frontend part

#2344 Corrected date translation in all possible places on the website
  src/utils/helper-functions.tsx
Labels: bug, Frontend part

#2410 Feature/2322/resource confirm
  src/components/changing-confirm/ChangeConfirm.styles.ts
  src/components/changing-confirm/ChangeConfirm.tsx
  src/containers/my-quizzes/create-or-edit-quiz-container/CreateOrEditQuizContainer.tsx
  src/hooks/use-change-confirm.tsx
  src/pages/create-or-edit-lesson/CreateOrEditLesson.tsx
  tests/unit/components/changing-confirm/ChangingConfirm.spec.jsx
Labels: Frontend part, feature, Tutor

#2412 Changed videolink type to string
  src/redux/features/editProfileSlice.ts
  tests/unit/redux/editProfileSlice.spec.js
Labels: bug, Frontend part
