Repository ita-social-projects/SpaceToStudy-Client, pull requests merged in 2024-01, with the labels that each got.

#1544 Implemented CooperationDetails Route
  src/constants/translations/en/breadcrumbs.json
  src/constants/translations/ua/breadcrumbs.json
  src/containers/my-cooperations/cooperation-details/CooperationDetails.styles.ts
  src/containers/my-cooperations/cooperation-details/CooperationDetails.tsx
  src/containers/my-cooperations/cooperations-container/CooperationContainer.tsx
  src/router/constants/authRoutes.ts
  src/router/constants/crumbs.ts
  src/router/routes/authRouter.tsx
  tests/unit/containers/my-cooperations/cooperation-details/CooperationDetails.spec.jsx
Labels: Frontend part, feature, Tutor

#1543 implemented add course template modal
  src/components/course-card/CourseCard.tsx
  src/components/loader/Loader.tsx
  src/components/not-found-results/NotFoundResults.tsx
  src/components/popup-dialog/PopupDialog.styles.ts
  src/constants/translations/en/cooperation-details.json
  src/constants/translations/en/index.ts
  src/constants/translations/en/my-courses-page.json
  src/constants/translations/ua/cooperation-details.json
  src/constants/translations/ua/index.ts
  src/constants/translations/ua/my-courses-page.json
  src/containers/cooperation-details/add-course-modal-modal/AddCourseTemplateModal.styles.ts
  src/containers/cooperation-details/add-course-modal-modal/AddCourseTemplateModal.tsx
  src/containers/find-course/courses-filter-bar/CoursesFilterBar.styles.ts
  src/containers/find-course/courses-filter-bar/CoursesFilterBar.tsx
  src/containers/find-course/courses-filter-block/CoursesFilterBlock.constants.ts
  src/containers/my-cooperations/cooperation-activities/CooperationActivities.tsx
  src/containers/my-courses/add-course-with-input/AddCourseWithInput.styles.ts
  src/containers/my-courses/my-courses-container/MyCorsesCardsList.tsx
  tests/unit/containers/cooperation-details/AddCourseTemplateModal.spec.jsx
  tests/unit/containers/find-course/courses-filter-bar/CoursesFilterBar.spec.jsx
Labels: Frontend part, feature

#1548 Created cooperation from scratch option
  src/constants/translations/en/cooperation-details.json
  src/constants/translations/en/course.json
  src/constants/translations/ua/cooperation-details.json
  src/constants/translations/ua/course.json
  src/containers/cooperation-details/cooperation-from-scratch/CooperationFromScratch.constans.tsx
  src/containers/cooperation-details/cooperation-from-scratch/CooperationFromScratch.styles.ts
  src/containers/cooperation-details/cooperation-from-scratch/CooperationFromScratch.tsx
  src/containers/course-section/CourseSectionContainer.tsx
  src/containers/course-sections-list/CourseSectionsList.tsx
  src/containers/my-cooperations/cooperation-activities-list/CooperationActivitiesList.tsx
  src/containers/my-cooperations/cooperation-activities/CooperationActivities.tsx
  src/containers/my-cooperations/cooperation-details/CooperationDetails.tsx
  src/context/modal-context.tsx
  src/pages/create-course/CreateCourse.tsx
  src/types/cooperation/interfaces/cooperation.interface.ts
  tests/unit/containers/cooperation-details/CooperationFromScratch.spec.jsx
Labels: Frontend part, feature

#1550 Added filters to add courses modal
  src/constants/translations/en/common.json
  src/constants/translations/ua/common.json
  src/containers/cooperation-details/add-course-modal-modal/AddCourseTemplateModal.constants.tsx
  src/containers/cooperation-details/add-course-modal-modal/AddCourseTemplateModal.styles.ts
  src/containers/cooperation-details/add-course-modal-modal/AddCourseTemplateModal.tsx
  src/containers/find-course/courses-filters/CourseFilters.styles.tsx
  src/containers/find-course/courses-filters/CoursesFilters.tsx
  tests/unit/containers/cooperation-details/AddCourseTemplateModal.spec.jsx
  tests/unit/containers/find-course/courses-filters/CoursesFilters.spec.jsx
Labels: Frontend part, feature

#1524 Created validation fields for courses
  src/constants/translations/en/common.json
  src/constants/translations/en/lesson.json
  src/constants/translations/en/offer-page.json
  src/constants/translations/ua/lesson.json
  src/constants/translations/ua/my-courses-page.json
  src/constants/translations/ua/offer-page.json
  src/containers/find-offer/create-new-subject/CreateNewSubject.constants.ts
  src/containers/my-courses/course-toolbar/CourseToolbar.style.ts
  src/containers/my-courses/course-toolbar/CourseToolbar.tsx
  src/containers/offer-page/create-or-edit-offer/CreateOrEditOffer.constants.ts
  src/pages/create-course/CreateCourse.constants.tsx
  src/pages/create-course/CreateCourse.tsx
  src/pages/create-or-edit-lesson/CreateOrEditLesson.constants.tsx
  tests/unit/pages/create-course/CreateCourse.spec.jsx
Labels: Frontend part, feature

#1527 Make courses bar and filter drawer responsive
  src/components/app-select/AppSelect.styles.ts
  src/components/filters-toggle/FiltersToggle.styles.ts
  src/constants/translations/en/my-courses-page.json
  src/constants/translations/ua/my-courses-page.json
  src/containers/find-course/courses-filter-bar/CoursesFilterBar.styles.ts
  src/containers/find-course/courses-filter-bar/CoursesFilterBar.tsx
  src/containers/my-courses/add-course-with-input/AddCourseWithInput.styles.ts
  src/containers/my-courses/add-course-with-input/AddCourseWithInput.tsx
  src/containers/my-courses/courses-filters-drawer/CoursesFiltersDrawer.styles.ts
  src/containers/my-courses/courses-filters-drawer/CoursesFiltersDrawer.tsx
  src/pages/my-courses/MyCourses.constants.tsx
  src/types/course/interfaces/course.interface.ts
Labels: bug, Frontend part

#1547 implemented changing quiz settings view
  src/components/tab-navigation/TabNavigation.tsx
  src/constants/translations/en/my-resources-page.json
  src/constants/translations/ua/my-resources-page.json
  src/containers/my-quizzes/create-or-edit-quiz-container/CreateOrEditQuizContainer.constants.ts
  src/containers/my-quizzes/create-or-edit-quiz-container/CreateOrEditQuizContainer.tsx
  src/containers/my-quizzes/quiz-settings-container/QuizSettingsContainer.constants.ts
  src/containers/my-quizzes/quiz-settings-container/QuizSettingsContainer.tsx
  src/containers/my-quizzes/view-quiz-container/ViewQuizContainer.tsx
  src/pages/new-quiz/NewQuiz.constants.tsx
  src/pages/new-quiz/NewQuiz.tsx
  src/types/my-resources/enum/myResources.enum.ts
  src/types/quizzes/interfaces/quizzes.interface.ts
  tests/unit/containers/my-quizzes/QuizSettingsContainer.spec.jsx
  tests/unit/containers/my-quizzes/ViewQuizContainer.spec.jsx
Labels: Frontend part, feature

#1566 Created cooperation notes container
  src/containers/my-cooperations/cooperation-details/CooperationDetails.styles.ts
  src/containers/my-cooperations/cooperation-details/CooperationDetails.tsx
  src/containers/my-cooperations/cooperation-notes/CooperationNotes.styles.ts
  src/containers/my-cooperations/cooperation-notes/CooperationNotes.tsx
  src/types/common/enums/common.enums.ts
  tests/unit/containers/my-cooperations/cooperation-details/CooperationDetails.spec.jsx
  tests/unit/containers/my-cooperations/cooperation-notes/CooperationNotes.spec.jsx
Labels: Frontend part, feature

#1575 Create notes card and add note
  src/constants/request.ts
  src/constants/translations/en/cooperations-page.json
  src/constants/translations/ua/cooperations-page.json
  src/containers/my-cooperations/cooperation-details/CooperationDetails.styles.ts
  src/containers/my-cooperations/cooperation-notes/CooperationNotes.tsx
  src/containers/my-cooperations/cooperation-notes/create-or-edit-note/CreateOrEditNote.styles.ts
  src/containers/my-cooperations/cooperation-notes/create-or-edit-note/CreateOrEditNote.tsx
  src/containers/my-cooperations/cooperation-notes/note-view/NoteView.styles.tsx
  src/containers/my-cooperations/cooperation-notes/note-view/NoteView.tsx
  src/services/cooperation-service.ts
  src/styles/app-theme/app.pallete.ts
  src/types/index.ts
  src/types/notes/interfaces/notes.interfaces.ts
  src/types/notes/notes.index.ts
  tests/unit/containers/my-cooperations/cooperation-notes/CooperationNotes.spec.jsx
  tests/unit/containers/my-cooperations/cooperation-notes/create-or-edit-note/CreateOrEditNote.spec.jsx
  tests/unit/containers/my-cooperations/cooperation-notes/note-view/NoteView.spec.jsx
Labels: Frontend part, feature

#1523 Added drawer filter for my resources toolbar on mobile and tablet
  src/components/app-drawer/AppDrawer.tsx
  src/components/filter-selector/FilterSelector.tsx
  src/components/filters-toggle/FiltersToggle.styles.ts
  src/components/filters-toggle/FiltersToggle.tsx
  src/constants/translations/en/my-courses-page.json
  src/constants/translations/ua/my-courses-page.json
  src/containers/my-courses/courses-filters-drawer/CoursesFiltersDrawer.tsx
  src/containers/my-quizzes/QuizzesContainer.tsx
  src/containers/my-resources/add-resource-with-input/AddResourceWithInput.tsx
  src/containers/my-resources/attachments-container/AttachmentsContainer.styles.ts
  src/containers/my-resources/attachments-container/AttachmentsContainer.tsx
  src/containers/my-resources/lessons-container/LessonsContainer.tsx
  src/containers/my-resources/questions-container/QuestionsContainer.tsx
  src/containers/my-resources/resources-toolbar-drawer/ResourceToolbarDrawer.styles.ts
  src/containers/my-resources/resources-toolbar-drawer/ResourcesToolbarDrawer.tsx
  src/plugins/axiosClient.ts
  src/types/my-resources/interfaces/myResources.interface.ts
  tests/unit/containers/my-resources/AddResourceWithInput.spec.jsx
  tests/unit/containers/my-resources/ResourceToolbarDrawer.spec.jsx
Labels: Frontend part, feature

#1568 Feature/1553/implement custom dropdown for categories
  src/components/async-autocomlete/AsyncAutocomplete.tsx
  src/components/divider-dropdown-autocomplete/DividerDropdownAutocomplete.tsx
  src/constants/translations/en/course.json
  src/constants/translations/ua/course.json
  src/containers/cooperation-details/add-course-modal-modal/AddCourseTemplateModal.tsx
  src/containers/find-course/courses-filters/CoursesFilters.tsx
  src/containers/my-courses/course-toolbar/CourseToolbar.style.ts
  src/containers/my-courses/course-toolbar/CourseToolbar.tsx
  src/hooks/use-user-categories-and-subjects.tsx
  src/pages/create-course/CreateCourse.tsx
  src/types/common/interfaces/common.interfaces.ts
  src/types/course/course.index.ts
  src/types/course/enums/course.enum.ts
  src/types/course/interfaces/course.interface.ts
  src/types/user/user-interfaces/user.interfaces.ts
  src/utils/course-custom-options.tsx
  tests/unit/utils/course-custom-options.spec.jsx
Labels: Frontend part, feature

#1576 Implemented resource availability
  src/assets/img/cooperation-details/resource-availability/closed-icon.svg
  src/assets/img/cooperation-details/resource-availability/open-from.svg
  src/assets/img/cooperation-details/resource-availability/open-icon.svg
  src/constants/translations/en/cooperation-details.json
  src/constants/translations/ua/cooperation-details.json
  src/containers/cooperation-details/cooperation-from-scratch/CooperationFromScratch.constans.tsx
  src/containers/cooperation-details/cooperation-from-scratch/CooperationFromScratch.constants.tsx
  src/containers/cooperation-details/cooperation-from-scratch/CooperationFromScratch.styles.ts
  src/containers/cooperation-details/cooperation-from-scratch/CooperationFromScratch.tsx
  src/containers/course-section/resource-item/ResourceItem.constants.ts
  src/containers/course-section/resource-item/ResourceItem.styles.ts
  src/containers/course-section/resource-item/ResourceItem.tsx
  src/containers/course-section/resources-list/ResourcesList.tsx
  src/containers/my-cooperations/cooperation-details/CooperationDetails.tsx
  src/context/resources-availability-context.tsx
  src/styles/app-theme/custom-animations.ts
  src/types/course/types/course.types.ts
  src/types/my-cooperations/enums/myCooperations.enums.ts
  src/types/my-cooperations/myCooperations.index.ts
  tests/unit/containers/cooperation-details/CooperationFromScratch.spec.jsx
  tests/unit/containers/course-section/resource-item/ResourceItem.spec.jsx
Labels: Frontend part, feature, Tutor

#1567 Implemented activity addition for cooperation details
  src/constants/translations/en/cooperations-page.json
  src/constants/translations/ua/cooperations-page.json
  src/containers/cooperation-details/cooperation-from-scratch/CooperationFromScratch.styles.ts
  src/containers/course-sections-list/CourseSectionsList.constants.tsx
  src/containers/course-sections-list/CourseSectionsList.styles.ts
  src/containers/course-sections-list/CourseSectionsList.tsx
  src/containers/my-cooperations/cooperation-activities-list/CooperationActivitiesList.tsx
  src/containers/my-cooperations/cooperation-activities/CooperationActivities.tsx
  tests/unit/containers/my-cooperations/cooperation-activities-list/CooperationActivitiesList.spec.jsx
Labels: Frontend part, feature, Tutor

#1563 Added title and status to current cooperation
  src/containers/cooperation-details/add-course-modal-modal/AddCourseTemplateModal.styles.ts
  src/containers/my-cooperations/cooperation-details/CooperationDetails.constans.tsx
  src/containers/my-cooperations/cooperation-details/CooperationDetails.styles.ts
  src/containers/my-cooperations/cooperation-details/CooperationDetails.tsx
  src/containers/offer-details/enroll-offer/EnrollOffer.tsx
  src/services/cooperation-service.ts
  src/types/cooperation/interfaces/cooperation.interface.ts
  src/types/offer-details/interfaces/offerDetails.interfaces.ts
  tests/unit/containers/my-cooperations/cooperation-details/CooperationDetails.spec.jsx
Labels: Frontend part, feature

#1571 Added cooperation completion to details
  src/constants/translations/en/cooperations-page.json
  src/constants/translations/ua/cooperations-page.json
  src/containers/my-cooperations/cooperation-completion/CooperationCompletion.constants.tsx
  src/containers/my-cooperations/cooperation-completion/CooperationCompletion.styles.ts
  src/containers/my-cooperations/cooperation-completion/CooperationCompletion.tsx
  src/containers/my-cooperations/cooperation-details/CooperationDetails.constans.tsx
  src/types/my-cooperations/enums/materialsAccess.enums.ts
  src/types/my-cooperations/myCooperations.index.ts
  tests/unit/pages/my-cooperations/CooperationCompletion.spec.jsx
Labels: Frontend part, feature

#1521 Save order of resources in course section
  src/containers/course-section/CourseSectionContainer.tsx
  src/containers/course-sections-list/CourseSectionsList.tsx
  src/pages/create-course/CreateCourse.constants.tsx
  src/pages/create-course/CreateCourse.tsx
  src/types/course/interfaces/course.interface.ts
  tests/unit/containers/course-section/CourseSectionContainer.spec.jsx
Labels: Frontend part, feature

#1546 Fixed input behavior
  src/containers/offer-page/create-or-edit-offer/CreateOrEditOffer.constants.ts
  src/containers/offer-page/faq-block/FaqBlock.tsx
Labels: bug, Frontend part

#1564 Implemented buttons with cancel logic
  src/containers/cooperation-details/cooperation-from-scratch/CooperationFromScratch.constans.tsx
  src/containers/cooperation-details/cooperation-from-scratch/CooperationFromScratch.styles.ts
  src/containers/cooperation-details/cooperation-from-scratch/CooperationFromScratch.tsx
Labels: Frontend part, feature

#1585 [HOTFIX] Fixed incorrect import, deleted redundand file
  src/containers/cooperation-details/cooperation-from-scratch/CooperationFromScratch.constans.tsx
  src/containers/cooperation-details/cooperation-from-scratch/CooperationFromScratch.tsx
Labels: bug, Frontend part, hotfix

#1583 Created cooperation options
  src/constants/request.ts
  src/constants/translations/en/cooperations-page.json
  src/constants/translations/ua/cooperations-page.json
  src/containers/my-cooperations/cooperation-notes/CooperationNotes.tsx
  src/containers/my-cooperations/cooperation-notes/note-view/NoteView.styles.tsx
  src/containers/my-cooperations/cooperation-notes/note-view/NoteView.tsx
  src/services/cooperation-service.ts
  tests/unit/containers/my-cooperations/cooperation-notes/CooperationNotes.spec.jsx
  tests/unit/containers/my-cooperations/cooperation-notes/note-view/NoteView.spec.jsx
Labels: Frontend part, feature

#1522 implemented sort for courses
  src/containers/cooperation-details/add-course-modal-modal/AddCourseTemplateModal.tsx
  src/containers/find-course/courses-filter-bar/CorseFilterBar.constants.ts
  src/containers/find-course/courses-filter-bar/CoursesFilterBar.tsx
  src/containers/my-courses/add-course-with-input/AddCourseWithInput.tsx
  src/pages/my-courses/MyCourses.tsx
  tests/unit/containers/find-course/courses-filter-bar/CoursesFilterBar.spec.jsx
Labels: Frontend part, feature
