Repository ita-social-projects/SpaceToStudy-Client, pull requests merged in 2024-03, with the labels that each got.

#1651 Fixed overlap
  src/containers/my-cooperations/cooperation-details/CooperationDetails.styles.ts
Labels: bug, Frontend part, feature, Tutor

#1653 Fixed ResourceItem warning
  src/containers/course-section/resource-item/ResourceItem.tsx
  src/containers/course-section/resources-list/ResourcesList.tsx
Labels: bug, Frontend part

#1582 Fixed resources order
  src/containers/course-section/CourseSectionContainer.tsx
Labels: bug, Frontend part

#1631 Changed max upload file size
  src/components/file-uploader/FileUploader.tsx
  src/constants/translations/en/become-tutor.json
  src/constants/translations/en/common.json
  src/constants/translations/ua/become-tutor.json
  src/constants/translations/ua/common.json
  src/containers/add-documents/AddDocuments.constants.ts
  src/containers/tutor-home-page/add-photo-step/constants.js
  tests/unit/components/file-uploader/FileUploader.spec.jsx
  tests/unit/components/user-steps-wrapper/UserStepsWrapper.spec.jsx
  tests/unit/hooks/use-upload.spec.js
Labels: bug, Frontend part

#1579 Implemented cooperations details with buttons
  src/components/show-more-collapse/ShowMoreCollapse.tsx
  src/constants/request.ts
  src/constants/translations/en/cooperation-details.json
  src/constants/translations/ua/cooperation-details.json
  src/containers/my-cooperations/cooperation-details/CooperationDetails.constans.tsx
  src/containers/my-cooperations/my-cooperations-details/MyCooperationsDetails.styles.ts
  src/containers/my-cooperations/my-cooperations-details/MyCooperationsDetails.tsx
  src/services/cooperation-service.ts
  src/types/cooperation/interfaces/cooperation.interface.ts
  src/types/my-cooperations/interfaces/myCooperations.interfaces.ts
  tests/unit/containers/my-cooperations/cooperation-details/CooperationDetails.spec.jsx
  tests/unit/containers/my-cooperations/my-cooperations-details/MyCooperationsDetails.spec.jsx
Labels: Frontend part, feature

#1627 fixed stepper bugs
  src/constants/translations/en/become-tutor.json
  src/constants/translations/ua/become-tutor.json
Labels: bug, Frontend part

#1660 Update Nginx and Docker configuration to proxy requests from /api to deployed backend
  .dockerignore
  .github/workflows/main.yaml
  azure-pipeline.yaml
  compose.yaml
  docker-compose.yaml
  docker/Dockerfile.build
  docker/Dockerfile.stage
  docker/files/default.conf.template
  docker/files/ssh_setup.sh
  docker/files/sshd_config
Labels: Frontend part, devOps

#1664 add implementation module creation from course template
  src/containers/cooperation-details/add-course-modal-modal/AddCourseTemplateModal.tsx
  src/containers/course-sections-list/CourseSectionsList.constants.tsx
  src/containers/course-sections-list/CourseSectionsList.tsx
  src/containers/my-cooperations/cooperation-activities-list/CooperationActivitiesList.tsx
  src/context/cooperation-context.tsx
  tests/unit/pages/create-course/CreateCourse.spec.jsx
Labels: Frontend part, Tutor

#1661 implemented account menu with header
  src/components/sidebar-menu/SidebarMenu.tsx
  src/constants/translations/en/edit-tutor-profile.json
  src/constants/translations/en/index.ts
  src/constants/translations/ua/edit-tutor-profile.json
  src/constants/translations/ua/index.ts
  src/pages/edit-profile/EditProfile.constants.tsx
  src/pages/edit-profile/EditProfile.styles.ts
  src/pages/edit-profile/EditProfile.tsx
  src/types/editTutorProfile/editTutorProfile.index.ts
  src/types/editTutorProfile/interfaces/editTutorProfile.enums.ts
  src/types/index.ts
Labels: Frontend part, feature

#1666 Feature/863/implement general edit profile block
  src/components/location-selection-inputs/LocationSelectionInputs.tsx
  src/constants/translations/en/become-tutor.json
  src/constants/translations/en/common.json
  src/constants/translations/en/edit-profile.json
  src/constants/translations/en/index.ts
  src/constants/translations/ua/common.json
  src/constants/translations/ua/edit-profile.json
  src/constants/translations/ua/index.ts
  src/containers/edit-profile/profile-general-tab/ProfileGeneralTab.constants.ts
  src/containers/edit-profile/profile-general-tab/ProfileGeneralTab.styles.ts
  src/containers/edit-profile/profile-general-tab/ProfileGeneralTab.tsx
  src/hooks/use-axios.tsx
  src/pages/edit-profile/EditProfile.tsx
  src/services/location-service.ts
  src/types/common/enums/common.enums.ts
  src/types/common/types/common.types.ts
  src/types/edit-profile/editProfile.index.ts
  src/types/edit-profile/interfaces/editProfile.interfaces.ts
  src/types/index.ts
Labels: Frontend part, feature
