Repository ita-social-projects/SpaceToStudy-Client, pull requests merged in 2024-05, with the labels that each got.

#1837 Add user photo instead of user menu icon/1823
  package-lock.json
  src/containers/navigation-icons/AccountIcon.tsx
  src/containers/navigation-icons/NavigationIcons.constants.tsx
  src/containers/navigation-icons/NavigationIcons.styles.ts
  src/containers/navigation-icons/user-icons/UserIcons.tsx
  src/hooks/use-update-user.tsx
  tests/unit/containers/navbar/NavBar.spec.jsx
  tests/unit/containers/navigation-icons/AccountIcon.spec.jsx
  tests/unit/containers/navigation-icons/user-icons/UserIcons.spec.jsx
Labels: Frontend part, feature, Tutor, Student

#1847 Create question button in quiz - Tooltip
  src/constants/translations/en/my-resources-page.json
  src/constants/translations/ua/my-resources-page.json
  src/containers/my-quizzes/create-or-edit-quiz-container/CreateOrEditQuizContainer.styles.ts
  src/containers/my-quizzes/create-or-edit-quiz-container/CreateOrEditQuizContainer.tsx
Labels: Frontend part, feature

#1852 do not display video previews if the tutor has not added
  src/pages/tutor-profile/TutorProfile.jsx
  tests/unit/pages/tutor-profile/TutorProfile.spec.jsx
Labels: Frontend part, feature, Tutor

#1855 Fixed bug when login input error label jumped while validation
  src/containers/guest-home-page/login-dialog/LoginDialog.styles.js
Labels: bug, enhancement, Frontend part

#1856 Replaced react-beatiful-dnd with react-dnd-kit
  package-lock.json
  package.json
  src/components/drag-handle/DragHandle.styles.ts
  src/components/drag-handle/DragHandle.tsx
  src/components/question/Question.styles.ts
  src/components/question/Question.tsx
  src/containers/course-section/resources-list/ResourcesList.styles.ts
  src/containers/course-section/resources-list/ResourcesList.tsx
  src/containers/course-sections-list/CourseSectionsList.styles.ts
  src/containers/course-sections-list/CourseSectionsList.tsx
  src/containers/questions-list/QuestionsList.tsx
  src/containers/sortable-wrapper/SortableWrapper.tsx
  src/context/sortable-context.tsx
  src/hooks/use-dnd-sensor.tsx
  tests/unit/containers/course-section/CourseSectionContainer.spec.jsx
Labels: enhancement, Frontend part

#1854 Сreate new offer checkboxes - make them more understandable
  src/components/checkbox-list/CheckboxList.tsx
  src/constants/translations/en/offer-page.json
  src/constants/translations/ua/offer-page.json
  src/containers/offer-page/specialization-block/SpecializationBlock.tsx
  src/utils/checkbox-list.tsx
  tests/unit/utils/checkbox-list.spec.jsx
Labels: enhancement, Frontend part

#1857 Hotfix/tooltip for disable button_create or edit quiz container_fix bug
  src/containers/my-quizzes/create-or-edit-quiz-container/CreateOrEditQuizContainer.styles.ts
  src/containers/my-quizzes/create-or-edit-quiz-container/CreateOrEditQuizContainer.tsx
  src/containers/navigation-icons/NavigationIcons.styles.ts
Labels: bug, hotfix

#1875 Add Language menu when user isn't authorized or logout
  src/containers/navigation-icons/guest-icons/GuestIcons.tsx
  tests/unit/containers/navigation-icons/guest-icons/GuestIcons.spec.jsx
Labels: bug, Frontend part

#1873 Removed cooperation context and used redux toolkit instead
  src/App.tsx
  src/constants/index.ts
  src/containers/cooperation-details/add-course-modal-modal/AddCourseTemplateModal.tsx
  src/containers/course-sections-list/CourseSectionsList.tsx
  src/containers/my-cooperations/cooperation-activities-list/CooperationActivitiesList.tsx
  src/containers/my-cooperations/cooperation-details/CooperationDetails.tsx
  src/containers/my-cooperations/empty-cooperation-activities/EmptyCooperationTutorControls.tsx
  src/context/cooperation-context.tsx
  src/redux/features/cooperationsSlice.ts
  src/redux/redux.constants.ts
  src/redux/store.ts
  tests/test-utils.jsx
  tests/unit/containers/my-cooperations/cooperation-activities-list/CooperationActivitiesList.spec.jsx
Labels: enhancement, Frontend part

#1851 Added Professional tab UI and prepared to backend integration
  src/components/confirm-dialog/ConfirmDialog.styles.ts
  src/constants/translations/en/edit-profile.json
  src/constants/translations/en/edit-tutor-profile.json
  src/constants/translations/ua/edit-profile.json
  src/constants/translations/ua/edit-tutor-profile.json
  src/containers/edit-profile/common.style.ts
  src/containers/edit-profile/notification-tab/NotificationContainer.constans.tsx
  src/containers/edit-profile/notification-tab/NotificationTab.constants.tsx
  src/containers/edit-profile/notification-tab/NotificationTab.styles.ts
  src/containers/edit-profile/notification-tab/NotificationTab.tsx
  src/containers/edit-profile/password-security-tab/PasswordSecurityTab.styles.ts
  src/containers/edit-profile/password-security-tab/PasswordSecurityTab.tsx
  src/containers/edit-profile/professional-info-tab/ProfessionalInfoTab.styles.ts
  src/containers/edit-profile/professional-info-tab/ProfessionalInfoTab.tsx
  src/containers/edit-profile/professional-info-tab/about-tutor-accordion/AboutTutorAccordion.constants.tsx
  src/containers/edit-profile/professional-info-tab/about-tutor-accordion/AboutTutorAccordion.styles.ts
  src/containers/edit-profile/professional-info-tab/about-tutor-accordion/AboutTutorAccordion.tsx
  src/containers/edit-profile/professional-info-tab/add-professional-category-modal/AddProfessionalCategoryModal.constants.ts
  src/containers/edit-profile/professional-info-tab/add-professional-category-modal/AddProfessionalCategoryModal.styles.ts
  src/containers/edit-profile/professional-info-tab/add-professional-category-modal/AddProfessionalCategoryModal.tsx
  src/containers/edit-profile/professional-info-tab/professional-category-list/ProfessionalCategoryList.styles.ts
  src/containers/edit-profile/professional-info-tab/professional-category-list/ProfessionalCategoryList.tsx
  src/containers/edit-profile/professional-info-tab/professional-category/ProfessionalCategory.styles.ts
  src/containers/edit-profile/professional-info-tab/professional-category/ProfessionalCategory.tsx
  src/containers/my-courses/course-toolbar/CourseToolbar.style.ts
  src/containers/my-courses/course-toolbar/CourseToolbar.tsx
  src/containers/proficiency-level-select/ProficiencyLevelSelect.styles.ts
  src/containers/proficiency-level-select/ProficiencyLevelSelect.tsx
  src/pages/edit-profile/EditProfile.constants.tsx
  src/types/common/enums/common.enums.ts
  src/types/edit-profile/editProfile.index.ts
  src/types/edit-profile/interfaces/editProfile.interfaces.ts
  src/types/edit-profile/types/editProfile.types.ts
  src/types/editTutorProfile/enums/editTutorProfile.enums.ts
  tests/unit/containers/edit-profile/notification-tab/NotificationTab.jsx
  tests/unit/containers/edit-profile/password-security-tab/PasswordSecurityTab.jsx
  tests/unit/containers/edit-profile/professional-tab/.gitkeep
  tests/unit/pages/edit-profile/EditProfile.spec.jsx
Labels: enhancement, Frontend part

#1877 Add drag-n-drop to edit profile
  src/containers/edit-profile/profile-tab/profile-tabs/profile-general-tab/ProfileGeneralTab.tsx
Labels: enhancement, Frontend part, Tutor, Student

#1845 Implemented pop-up on edit profile page
  src/constants/translations/en/questions.json
  src/constants/translations/en/titles.json
  src/constants/translations/ua/questions.json
  src/constants/translations/ua/titles.json
  src/containers/edit-profile/profile-tab/ProfileTab.styles.ts
  src/containers/edit-profile/profile-tab/ProfileTab.tsx
  src/containers/edit-profile/profile-tab/profile-tab-form/ProfileTabForm.styles.ts
  src/containers/edit-profile/profile-tab/profile-tab-form/ProfileTabForm.tsx
  src/containers/edit-profile/profile-tab/profile-tab-inner-container/ProfileTabInnerContainer.tsx
  src/context/profile-context.tsx
  src/pages/edit-profile/EditProfile.tsx
  src/types/edit-profile/interfaces/editProfile.interfaces.ts
  src/types/user/user-interfaces/user.interfaces.ts
  src/utils/get-profile-context-initial-values.ts
  src/utils/get-profile-values.ts
  tests/unit/containers/edit-profile/ProfileTab.spec.jsx
  tests/unit/containers/edit-profile/profile-tab/profile-tab-form/ProfileTabForm.spec.constants.js
  tests/unit/containers/edit-profile/profile-tab/profile-tab-form/ProfileTabForm.spec.jsx
Labels: Frontend part, feature

#1883 Style for how it works
  src/containers/student-home-page/faq/Faq.styles.ts
  src/containers/student-home-page/student-how-it-works/student-how-it-works.styles.js
Labels: Frontend part, Student

#1886 Add the asterisk to required fields in an activity section
  src/constants/translations/en/course.json
  src/constants/translations/ua/course.json
Labels: Frontend part

#1889 fix title width in My Cooperations
  src/containers/my-cooperations/cooperation-card/CooperationCard.styles.ts
  src/containers/my-cooperations/cooperations-container/CooperationContainer.styles.ts
Labels: bug, Frontend part

#1882 Fix view with notes in cooperation details
  src/containers/my-cooperations/cooperation-details/CooperationDetails.styles.ts
  src/containers/my-cooperations/my-cooperations-details/MyCooperationsDetails.styles.ts
Labels: bug, Frontend part

#1897 fix display the Add Activities button if the activities section is not created
  src/constants/translations/en/cooperations-page.json
  src/constants/translations/ua/cooperations-page.json
  src/containers/course-section/CourseSectionContainer.tsx
  src/containers/course-sections-list/CourseSectionsList.styles.ts
  src/containers/course-sections-list/CourseSectionsList.tsx
  src/containers/my-cooperations/cooperation-activities-list/CooperationActivitiesList.tsx
  src/containers/my-cooperations/empty-cooperation-activities/EmptyCooperationTutorControls.tsx
  src/redux/features/cooperationsSlice.ts
  src/types/common/enums/common.enums.ts
  tests/unit/containers/my-cooperations/cooperation-activities-list/CooperationActivitiesList.spec.jsx
Labels: bug, Frontend part

#1895 Check the logic of checkboxes in project
  src/containers/edit-profile/professional-info-tab/add-professional-category-modal/AddProfessionalCategoryModal.tsx
  src/containers/find-offer/offer-filter-block/offer-filter-list/OfferFilterList.tsx
  src/containers/my-courses/course-toolbar/CourseToolbar.tsx
  src/containers/my-courses/courses-filters-drawer/CoursesFiltersDrawer.tsx
  src/containers/proficiency-level-select/ProficiencyLevelSelect.tsx
  tests/unit/containers/find-offer/offer-filter-block/OfferFilterBlock.spec.jsx
  tests/unit/containers/tutor-profile/ProfileInfo.spec.jsx
  tests/unit/pages/offer-details/OfferDetails.spec.jsx
Labels: enhancement, Frontend part

#1885 Feature/1841/remove button from mui
  src/components/enhanced-table/enhanced-table-pagination/EnhancedTablePagination.jsx
  src/components/file-uploader/FileUploader.tsx
  src/components/search-autocomplete/SearchAutocomplete.tsx
  src/containers/edit-profile/password-security-tab/PasswordSecurityTab.tsx
  src/containers/edit-profile/profile-tab/profile-tab-form/ProfileTabForm.styles.ts
  src/containers/edit-profile/profile-tab/profile-tab-form/ProfileTabForm.tsx
  src/containers/email-confirm-modal/EmailConfirmModal.jsx
  src/containers/guest-home-page/forgot-password/ForgotPassword.jsx
  src/containers/guest-home-page/reset-password/ResetPassword.jsx
  src/containers/guest-home-page/reset-password/ResetPassword.styles.ts
  src/containers/layout/navbar/NavBar.tsx
  src/containers/my-cooperations/cooperation-details/CooperationDetails.constants.tsx
  src/containers/my-cooperations/cooperation-details/CooperationDetails.styles.ts
  src/containers/my-cooperations/cooperation-details/CooperationDetails.tsx
  src/containers/my-cooperations/empty-cooperation-activities/EmptyCooperationActivities.tsx
  src/containers/my-courses/courses-filters-drawer/CoursesFiltersDrawer.tsx
  src/containers/student-home-page/student-how-it-works/StudentHowItWorks.jsx
  src/containers/tutor-home-page/subjects-step/SubjectsStep.jsx
  src/containers/tutor-profile/profile-info/ProfileInfo.jsx
  src/pages/error/AuthPolicy.jsx
  src/pages/error/BadRequest.jsx
  src/pages/error/InternalServerError.jsx
  src/pages/error/NotFound.jsx
  src/scss/src/atoms/Button.scss
  src/styles/app-theme/app.button.ts
  src/styles/app-theme/custom-mui.styles.ts
  src/types/common/enums/common.enums.ts
Labels: enhancement, Frontend part, design system

#1893 Added tests for professional tab after ui changes
  src/containers/edit-profile/professional-info-tab/add-professional-category-modal/AddProfessionalCategoryModal.tsx
  src/containers/edit-profile/professional-info-tab/professional-category/ProfessionalCategory.tsx
  src/containers/proficiency-level-select/ProficiencyLevelSelect.tsx
  tests/test-utils.jsx
  tests/unit/components/location-selection-inputs/LocationSelectionInputs.spec.jsx
  tests/unit/containers/edit-profile/professional-info-tab/ProfessionalInfoTab.spec.jsx
  tests/unit/containers/edit-profile/professional-info-tab/about-tutor-accordion/AboutTutorAccordion.spec.jsx
  tests/unit/containers/edit-profile/professional-info-tab/add-professional-category-modal/AddProfessionalCategoryModal.spec.jsx
  tests/unit/containers/edit-profile/professional-info-tab/professional-category/ProfessionalCategory.spec.jsx
  tests/unit/containers/edit-profile/professional-tab/.gitkeep
Labels: enhancement, Frontend part, test

#1874 Implemented view for cooperation
  src/components/cooperation-section-view/CooperationSectionView.styles.ts
  src/components/cooperation-section-view/CooperationSectionView.tsx
  src/components/header-text-with-dropdown/HeaderTextWithDropdown.styles.ts
  src/components/header-text-with-dropdown/HeaderTextWithDropdown.tsx
  src/containers/cooperation-details/cooperation-activities/CooperationActivities.tsx
  src/containers/cooperation-details/cooperetion-activities-view/CooperationActivitiesView.style.ts
  src/containers/cooperation-details/cooperetion-activities-view/CooperationActivitiesView.tsx
  src/containers/course-section/CourseSectionContainer.tsx
  src/containers/course-section/resource-item/ResourceItem.styles.ts
  src/containers/course-section/resource-item/ResourceItem.tsx
  src/containers/course-section/resources-list/ResourcesList.tsx
  src/containers/course-sections-list/CourseSectionsList.tsx
  src/containers/edit-profile/profile-tab/profile-tab-form/ProfileTabForm.tsx
  src/containers/my-cooperations/cooperation-details/CooperationDetails.tsx
  src/containers/tutor-profile/profile-info/ProfileInfo.jsx
  src/pages/create-course/CreateCourse.tsx
  src/types/common/interfaces/common.interfaces.ts
  src/types/course/interfaces/course.interface.ts
  src/types/course/types/course.types.ts
  src/types/my-resources/enum/myResources.enum.ts
  tests/unit/components/cooperation-section-view/CooperationSectionView.spec.jsx
  tests/unit/pages/create-course/CreateCourse.spec.jsx
Labels: Frontend part, feature

#1890 Add button to save changes on every tab in edit profile
  src/constants/translations/en/edit-profile.json
  src/constants/translations/ua/edit-profile.json
  src/containers/edit-profile/common.styles.ts
  src/containers/edit-profile/notification-tab/NotificationTab.constants.tsx
  src/containers/edit-profile/notification-tab/NotificationTab.styles.ts
  src/containers/edit-profile/notification-tab/NotificationTab.tsx
  src/containers/edit-profile/password-security-tab/PasswordSecurityTab.styles.ts
  src/containers/edit-profile/professional-info-tab/ProfessionalInfoTab.styles.ts
  src/containers/edit-profile/professional-info-tab/ProfessionalInfoTab.tsx
  src/containers/edit-profile/profile-tab/ProfileTab.styles.ts
  tests/unit/containers/edit-profile/notification-tab/NotificationTab.spec.jsx
  tests/unit/containers/edit-profile/password-security-tab/PasswordSecurityTab.spec.jsx
Labels: enhancement, Frontend part

#1896 Feature/1830/professional block logic
  src/constants/translations/en/edit-profile.json
  src/constants/translations/ua/edit-profile.json
  src/containers/edit-profile/professional-info-tab/ProfessionalInfoTab.styles.ts
  src/containers/edit-profile/professional-info-tab/ProfessionalInfoTab.tsx
  src/containers/edit-profile/professional-info-tab/about-tutor-accordion/AboutTutorAccordion.tsx
  src/containers/edit-profile/profile-tab/ProfileTab.tsx
  src/containers/tutor-profile/about-tutor-block/AboutTutorBlock.constans.ts
  src/containers/tutor-profile/about-tutor-block/AboutTutorBlock.tsx
  src/containers/tutor-profile/profile-info/ProfileInfo.jsx
  src/hooks/use-update-user.tsx
  src/pages/edit-profile/EditProfile.constants.tsx
  src/pages/edit-profile/EditProfile.tsx
  src/pages/tutor-profile/TutorProfile.jsx
  src/types/user/user-interfaces/user.interfaces.ts
  src/types/user/user-types/user.types.ts
  tests/unit/containers/edit-profile/professional-info-tab/ProfessionalInfoTab.spec.jsx
  tests/unit/containers/edit-profile/professional-info-tab/about-tutor-accordion/AboutTutorAccordion.spec.jsx
  tests/unit/pages/edit-profile/EditProfile.spec.jsx
  tests/unit/pages/tutor-profile/TutorProfile.spec.jsx
Labels: Frontend part, feature, Tutor

#1909 Made placeholder of offer search input aware of authorRole
  src/constants/translations/en/find-offer-page.json
  src/constants/translations/ua/find-offer-page.json
  src/containers/find-offer/offer-search-toolbar/OfferSearchToolbar.tsx
Labels: bug, enhancement, Frontend part

#1911 deleted redundant param from setup-interceptors
  src/index.tsx
Labels: bug, Frontend part

#1912 Fixed bug when course could not be created
  src/hooks/use-user-categories-and-subjects.tsx
Labels: bug, Frontend part, Functional

#1918 Synchronized structure of availability object in cooperations and fixed small bugs
  src/components/cooperation-section-view/CooperationSectionView.tsx
  src/components/icon-extension-with-title/IconExtensionWithTitle.tsx
  src/containers/add-resources/AddResources.tsx
  src/containers/course-section/CourseSectionContainer.tsx
  src/containers/course-section/resource-item/ResourceItem.constants.ts
  src/containers/course-section/resource-item/ResourceItem.tsx
  src/containers/course-section/resources-list/ResourcesList.tsx
  src/containers/course-sections-list/CourseSectionsList.tsx
  src/containers/my-cooperations/cooperation-activities-list/CooperationActivitiesList.tsx
  src/pages/create-course/CreateCourse.constants.tsx
  src/pages/create-course/CreateCourse.tsx
  src/pages/lesson-details/LessonDetails.constants.tsx
  src/types/attachment/interfaces/attachment.interface.ts
  src/types/common/interfaces/common.interfaces.ts
  src/types/course/interfaces/course.interface.ts
  src/types/course/types/course.types.ts
  src/types/my-resources/interfaces/myResources.interface.ts
  src/types/quizzes/interfaces/quizzes.interface.ts
Labels: enhancement, Frontend part, Functional

#1920 Added highlight for active tab in edit profile page
  src/components/sidebar-menu/SidebarMenu.styles.ts
  src/components/sidebar-menu/SidebarMenu.tsx
  src/constants/translations/en/edit-tutor-profile.json
  src/constants/translations/ua/edit-tutor-profile.json
  src/pages/edit-profile/EditProfile.constants.tsx
  src/pages/edit-profile/EditProfile.styles.ts
  src/pages/edit-profile/EditProfile.tsx
  src/types/editTutorProfile/enums/editTutorProfile.enums.ts
  tests/unit/pages/edit-profile/EditProfile.spec.jsx
Labels: enhancement, Frontend part

#1929 Added tests for CourseToolbar
  tests/unit/containers/my-courses/course-toolbar/CourseToolbar.spec.jsx
Labels: enhancement, Frontend part
