Repository ita-social-projects/SpaceToStudy-Client, pull requests merged in 2025-01, with the labels that each got.

#3004 Added a type to value in order to fix the error
  src/components/input-with-icon/InputWithIcon.tsx
Labels: bug, Frontend part

#3008 Modified the ResourceBase in order to resolve the issue
  src/pages/create-or-edit-lesson/CreateOrEditLesson.constants.tsx
  src/types/my-resources/interfaces/myResources.interface.ts
Labels: bug, Frontend part

#3037 Added tests for Deactivate account
  tests/unit/containers/edit-profile/password-security-tab/PasswordSecurityTab.spec.jsx
Labels: test, Tutor, Functional, test case, Edit

#3035 Fixed types mismatch in ProfileInfo
  src/components/app-icon-button/AppIconButton.tsx
  src/containers/user-profile/profile-info/ProfileContainerDesktop.tsx
  src/containers/user-profile/profile-info/ProfileContainerMobile.tsx
  src/containers/user-profile/profile-info/ProfileInfo.constants.ts
  src/containers/user-profile/profile-info/ProfileInfo.tsx
Labels: bug, Frontend part, component, design system

#2990 Create Menu component
  src/design-system/components/menu-item/MenuItem.constants.ts
  src/design-system/components/menu-item/MenuItem.scss
  src/design-system/components/menu-item/MenuItem.tsx
  src/design-system/components/menu-item/MenuItem.types.ts
  src/design-system/components/menu/Menu.scss
  src/design-system/components/menu/Menu.tsx
  src/design-system/stories/Menu.stories.tsx
  src/design-system/stories/MenuItem.stories.tsx
  tests/unit/design-system/components/menu-item/MenuItem.spec.jsx
  tests/unit/design-system/components/menu/Menu.spec.jsx
Labels: feature, component, design system

#3017 Fix type error caused by spliceSx helper function
  src/utils/helper-functions.tsx
Labels: bug, Frontend part, TypeScript

#3054 Update getFullUrl helper function
  src/utils/helper-functions.tsx
  tests/unit/utils/get-full-url.spec.js
Labels: Frontend part, hotfix

#3010 Refactor LocationSelectionInputs component
  src/components/location-selection-inputs/LocationSelectionInputs.tsx
  src/services/location-service.ts
Labels: bug, Frontend part, component, TypeScript

#3001 Verified ability to search for a city by re-entering letters in the 'City' field
  tests/unit/components/app-auto-complete/AppAutoComplete.spec.jsx
  tests/unit/components/location-selection-inputs/LocationSelectionInputs.spec.jsx
Labels: Tutor, Student, Functional, priority: low, test case, my-profile, Edit

#3018 Replaced `useAxios` with `useQuery` on the My Cooperations page
  src/components/active-students/ActiveStudentsBlock.tsx
  src/containers/my-cooperations/accept-cooperation-modal/AcceptCooperationModal.tsx
  src/containers/my-cooperations/cooperations-container/CooperationContainer.tsx
  src/pages/my-cooperations/MyCooperations.tsx
  src/services/cooperation-service.ts
  src/types/my-cooperations/interfaces/myCooperations.interfaces.ts
  src/types/services/types/services.types.ts
  tests/unit/components/active-students/ActiveStudentsBlock.spec.jsx
Labels: enhancement, Frontend part, feature, useQuery

#3056 Fixed TypeScript error in ActiveStudentsBlock component
  src/components/active-students/ActiveStudentsBlock.styles.ts
  src/components/active-students/ActiveStudentsBlock.tsx
  src/components/app-icon-button/AppIconButton.tsx
Labels: bug, Frontend part, Tutor, TypeScript, design system

#3058 Added test for deactivation account
  tests/unit/containers/edit-profile/password-security-tab/PasswordSecurityTab.spec.jsx
Labels: Frontend part, test case

#3057 Verified ability to search for a country by re-entering letters in the 'Country' field
  tests/unit/components/app-auto-complete/AppAutoComplete.spec.jsx
Labels: Frontend part, test case

#3045 Replace useAxios with useQuery on AddResources
  src/containers/add-resources/AddResources.tsx
  src/containers/course-section/CourseSectionContainer.tsx
  src/containers/my-quizzes/create-or-edit-quiz-container/CreateOrEditQuizContainer.tsx
  src/pages/create-or-edit-lesson/CreateOrEditLesson.tsx
  src/services/resource-service.ts
  src/types/my-resources/interfaces/myResources.interface.ts
  src/types/services/types/services.types.ts
  src/utils/get-error-key.ts
  tests/unit/containers/add-resources/add-attachments/AddAttachments.spec.jsx
  tests/unit/containers/add-resources/add-lessons/AddLessons.spec.jsx
  tests/unit/containers/add-resources/add-questions/AddQuestions.spec.jsx
  tests/unit/containers/add-resources/add-quizzes/AddQuizzes.spec.jsx
  tests/unit/pages/create-or-edit-lesson/CreateOrEditLesson.spec.jsx
Labels: Frontend part, useQuery

#3027 Fixed drag-and-drop in cooperation activities modules in statuses of resources
  src/components/drag-handle/DragHandle.tsx
  src/containers/course-section/CourseSectionContainer.tsx
  src/containers/course-section/resource-item/ResourceItem.tsx
  src/containers/course-section/resources-list/ResourcesList.tsx
  src/redux/features/cooperationsSlice.ts
  src/types/course/types/course.types.ts
  tests/unit/containers/course-section/resources-list/ResourcesList.spec.jsx
Labels: bug, Frontend part, Tutor

#3033 Replaced useAxios hook with useQuery on CompleteProfileBlock
  src/components/complete-profile/CompleteProfileBlock.tsx
  src/constants/request.ts
  src/pages/my-offers/MyOffers.tsx
  src/services/offer-service.ts
  src/types/my-offers/interfaces/myOffers.interfaces.ts
  tests/unit/components/complete-profile/CompleteProfileBlock.spec.jsx
Labels: Frontend part, useQuery

#2968 Fix sonar issues in pages, containers, components folders
  src/components/accordion-with-image/AccordionWithImage.tsx
  src/components/async-autocomlete/AsyncAutocomplete.tsx
  src/components/message/Message.styles.ts
  src/containers/chat/chat-item/ChatItem.tsx
  src/containers/find-offer/offer-filter-block/offer-filter-list/OfferFilterList.tsx
  src/containers/my-cooperations/my-cooperations-details/MyCooperationsDetails.tsx
  src/containers/my-resources/add-categories-modal/AddCategoriesModal.constants.ts
  src/containers/my-resources/categories-container/CategoriesContainer.constansts.tsx
  src/containers/my-resources/lessons-container/LessonsContainer.tsx
  src/containers/quiz/question-answer/Answer.tsx
  src/containers/student-home-page/student-how-it-works/HowItWorksCards.js
  src/containers/student-home-page/student-how-it-works/StudentHowItWorks.jsx
  src/pages/cookie-policy/CookiePolicy.jsx
  src/pages/cookie-policy/cookie-policy.constants.js
  src/pages/find-offers/FindOffers.tsx
Labels: sonarFix

#3063 Replaced uuid with the native browser method
  package-lock.json
  package.json
  src/containers/course-section/CourseSectionContainer.tsx
  src/containers/edit-profile/professional-info-tab/add-professional-category-modal/AddProfessionalCategoryModal.tsx
  src/pages/create-course/CreateCourse.handlers.ts
  src/pages/create-course/CreateCourse.tsx
  src/redux/features/cooperationsSlice.ts
  src/utils/validations/isValidUUID.js
  tests/test-utils.jsx
  tests/unit/pages/create-course/CreateCourse.handlers.spec.jsx
  tests/unit/redux/cooperationsSlice.spec.js
  tests/unit/utils/validations/isValidUUID.spec.js
Labels: bug, enhancement, Frontend part

#3069 Enhance getFullUrl helper function
  src/constants/request.ts
  src/services/category-service.ts
  src/services/cooperation-service.ts
  src/services/offer-service.ts
  src/services/resource-service.ts
  src/utils/get-full-url.ts
  src/utils/helper-functions.tsx
  tests/unit/utils/get-full-url.spec.js
Labels: enhancement, Frontend part

#3082 [Edit Profile. Profile] Fixed the ability for the user to enter all allowed values ​​in the 'First name' and 'Last name' fields
  src/hooks/use-form.tsx
Labels: bug, Frontend part, Tutor, Student, Functional, my-profile

#3061 Replace useAxios with useQuery in LocationSelectionInputs and GeneralInfoStep components
  src/components/location-selection-inputs/LocationSelectionInputs.tsx
  src/constants/request.ts
  src/containers/edit-profile/profile-tab/profile-tab-form/ProfileTabForm.styles.ts
  src/containers/edit-profile/profile-tab/profile-tab-form/ProfileTabForm.tsx
  src/containers/tutor-home-page/general-info-step/GeneralInfoStep.tsx
  src/services/location-service.ts
  tests/unit/components/location-selection-inputs/LocationSelectionInputs.spec.jsx
  tests/unit/containers/tutor-home-page/general-info-step/GeneralInfoStep.spec.jsx
  tests/unit/pages/edit-profile/EditProfile.spec.jsx
  tests/unit/services/location-service.spec.js
Labels: enhancement, Frontend part, feature, useQuery

#3091 Fix getFullUrl import in the location-service
  src/services/location-service.ts
Labels: Frontend part, hotfix

#3055 Replaced `useAxios` with `useQuery` and `useMutation` hooks on the Create Or Edit Lesson page
  src/constants/request.ts
  src/containers/course-section/CourseSectionContainer.tsx
  src/pages/create-or-edit-lesson/CreateOrEditLesson.tsx
  src/pages/lesson-details/LessonDetails.tsx
  src/services/resource-service.ts
  src/types/lesson/interfaces/lesson.interfaces.ts
  src/types/my-resources/interfaces/myResources.interface.ts
  tests/unit/pages/create-or-edit-lesson/CreateOrEditLessonWithId.spec.jsx
  tests/unit/pages/lesson-details/LessonDetails.spec.jsx
  tests/unit/services/resource-service.spec.jsx
Labels: enhancement, Frontend part, feature, useQuery

#3096 Fix margin in add categories modal
  src/containers/my-resources/add-categories-modal/AddCategories.styles.ts
Labels: bug, Frontend part, component

#3089 Multiple query key invalidation inside useMutation hook
  src/hooks/use-mutation.tsx
  tests/unit/hooks/use-mutation.spec.js
Labels: enhancement, Frontend part, useQuery

#3109 Update workflow actions from `v3` to `v4`
  .github/workflows/main.yaml
Labels: Frontend part, devOps

#3118 Renamed async-autocomlete folder
  src/components/async-autocomplete/AsyncAutocomplete.tsx
  src/components/divider-dropdown-autocomplete/DividerDropdownAutocomplete.tsx
  src/containers/edit-profile/professional-info-tab/add-professional-category-modal/AddProfessionalCategoryModal.tsx
  src/containers/find-offer/create-new-subject/CreateNewSubject.tsx
  src/containers/find-offer/offer-search-toolbar/OfferSearchToolbar.tsx
  src/containers/my-courses/courses-filters-drawer/CoursesFiltersDrawer.tsx
  src/containers/my-resources/add-attachment-category-modal/AddAttachmentCategoryModal.tsx
  src/containers/my-resources/create-or-edit-question-modal/CreateOrEditQuestionModal.tsx
  src/containers/my-resources/edit-attachment-modal/EditAttachmentModal.tsx
  src/containers/offer-page/specialization-block/SpecializationBlock.tsx
  src/containers/tutor-home-page/subjects-step/SubjectsStep.tsx
  src/pages/subjects/Subjects.tsx
  tests/unit/containers/offer-page/specialization-block/SpecializationBlock.spec.jsx
Labels: bug, Frontend part

#3044 Replaced the chip component through out the whole project
  src/components/status-chip/StatusChip.styles.ts
  src/components/status-chip/StatusChip.tsx
  src/components/subject-level-chips/SubjectLevelChips.tsx
  src/design-system/components/chip/Chip.tsx
  src/design-system/components/chip/types.ts
Labels: Frontend part, design system

#3060 Replaced useAxios with useQuery on the FindOffers.tsx
  src/constants/request.ts
  src/containers/offer-details/offer-carousel/OfferCarousel.tsx
  src/pages/find-offers/FindOffers.tsx
  src/services/offer-service.ts
  src/types/findOffers/interfaces/findOffers.interfaces.ts
  tests/unit/containers/offer-details/offer-carousel/OfferCarousel.spec.jsx
  tests/unit/pages/find-offers/FindOffers.spec.jsx
  tests/unit/services/offer-service.spec.jsx
Labels: Frontend part, useQuery

#3129 Created a `QuizHeader` container for the quiz page
  src/constants/translations/en/quiz.json
  src/constants/translations/uk/quiz.json
  src/containers/quiz/points/Points.styles.ts
  src/containers/quiz/points/Points.tsx
  src/containers/quiz/quiz-header/QuizHeader.styles.ts
  src/containers/quiz/quiz-header/QuizHeader.tsx
  src/containers/quiz/quiz-info-section/QuizInfoSection.styles.ts
  src/containers/quiz/quiz-info-section/QuizInfoSection.tsx
  src/containers/quiz/quiz-info/QuizInfo.styles.ts
  src/containers/quiz/quiz-info/QuizInfo.tsx
  src/containers/quiz/timer/Timer.styles.ts
  src/containers/quiz/timer/Timer.tsx
  src/pages/quiz/Quiz.styles.ts
  src/pages/quiz/Quiz.tsx
  tests/unit/containers/quiz/QuizInfo.spec.jsx
  tests/unit/pages/quiz/Quiz.spec.jsx
Labels: Frontend part, feature

#2628 Enhanced chat search
  src/components/search-by-message/SearchByMessage.tsx
  src/containers/chat/chat-header/ChatHeader.tsx
  src/pages/chat/Chat.styles.ts
  src/pages/chat/Chat.tsx
  src/pages/chat/MessagesList.tsx
  tests/unit/components/search-by-message/SearchByMessage.spec.jsx
  tests/unit/pages/chat/messages-list/MessagesList.spec.jsx
Labels: enhancement, Frontend part

#2988 Fixed needAction according to backend changes
  src/containers/my-cooperations/accept-cooperation-modal/AcceptCooperationModal.tsx
  src/containers/my-cooperations/cooperation-card/CooperationCard.tsx
  src/containers/my-cooperations/cooperation-details/CooperationDetails.constants.tsx
  src/containers/my-cooperations/cooperation-details/CooperationDetails.tsx
  src/containers/my-cooperations/cooperations-container/CooperationContainer.constants.tsx
  src/types/cooperation/interfaces/cooperation.interface.ts
  tests/unit/containers/my-cooperations/MyCooperations.spec.constants.js
  tests/unit/containers/my-cooperations/cooperation-details/CooperationDetails.spec.jsx
Labels: enhancement, Frontend part, on Hold

#3128 Updating quiz settings
  src/constants/translations/en/my-resources-page.json
  src/constants/translations/uk/my-resources-page.json
  src/containers/my-quizzes/create-or-edit-quiz-container/CreateOrEditQuizContainer.constants.ts
  src/containers/my-quizzes/quiz-settings-container/QuizSettingsContainer.constants.ts
  src/containers/my-quizzes/quiz-settings-container/QuizSettingsContainer.tsx
  src/pages/new-quiz/NewQuiz.constants.tsx
  src/types/my-resources/enum/myResources.enum.ts
  src/types/quizzes/interfaces/quizzes.interface.ts
  tests/unit/containers/my-quizzes/QuizSettingsContainer.spec.jsx
Labels: Frontend part, feature

#3102 Replaced `useAxios` with `useQuery` and `useMutation` hooks on CategoryDropdown container
  src/components/app-button-menu/AppButtonMenu.tsx
  src/containers/category-dropdown/CategoryDropdown.tsx
  src/containers/my-resources/add-categories-modal/AddCategoriesModal.tsx
  src/containers/my-resources/add-resource-modal/AddResourceModal.tsx
  src/containers/my-resources/add-resource-with-input/AddResourceWithInput.tsx
  src/containers/my-resources/categories-container/CategoriesContainer.tsx
  src/containers/my-resources/resources-toolbar-drawer/ResourcesToolbarDrawer.tsx
  src/services/resource-service.ts
  src/types/services/types/services.types.ts
  tests/unit/components/app-button-menu/AppButtonMenu.spec.jsx
  tests/unit/pages/create-or-edit-lesson/CreateOrEditLessonWithId.spec.jsx
  tests/unit/services/resource-service.spec.jsx
Labels: Frontend part, useQuery

#3143 Changed output of questions on EditQuiz page
  src/components/question/Question.styles.ts
  src/components/question/Question.tsx
  src/containers/questions-list/QuestionsList.tsx
  tests/unit/components/question/Question.spec.jsx
Labels: Frontend part, Tutor, UI/Usability

#3127 Replace useAxios with useMutation in the CourseSectionContainer component
  src/constants/request.ts
  src/constants/translations/en/errors.json
  src/constants/translations/uk/errors.json
  src/containers/course-section/CourseSectionContainer.tsx
  src/containers/my-resources/attachments-container/AttachmentsContainer.tsx
  src/containers/my-resources/edit-attachment-modal/EditAttachmentModal.constants.ts
  src/containers/my-resources/edit-attachment-modal/EditAttachmentModal.tsx
  src/hooks/use-snackbar-alert.tsx
  src/pages/create-or-edit-lesson/CreateOrEditLesson.tsx
  src/redux/features/snackbarSlice.ts
  src/services/resource-service.ts
  src/types/attachment/interfaces/attachment.interface.ts
  src/types/index.ts
  src/types/snackbar/snackbar.index.ts
  src/types/snackbar/types/snackbar.types.ts
  tests/unit/containers/my-resources/EditAttachmentModal.spec.jsx
  tests/unit/pages/create-or-edit-lesson/CreateOrEditLessonWithId.spec.jsx
  tests/unit/services/resource-service.spec.jsx
Labels: Frontend part, useQuery

#3161 Fixed usage of Button color prop
  src/containers/my-cooperations/accept-cooperation-close/AcceptCooperationClosing.tsx
  src/containers/my-cooperations/cooperation-action-input/CooperationActionInput.tsx
  src/containers/my-cooperations/cooperation-closure-declined-banner/CooperationClosureDeclinedBanner.tsx
  src/design-system/stories/Button.stories.tsx
Labels: bug, Frontend part

#3152 Created QuestionComment component for Questions in Quiz container
  src/constants/translations/en/quiz.json
  src/constants/translations/uk/quiz.json
  src/containers/quiz/question-comment/QuestionComment.styles.ts
  src/containers/quiz/question-comment/QuestionComment.tsx
  tests/unit/containers/quiz/QuestionComment.spec.jsx
Labels: Frontend part, feature, component

#3156 Fixed Categories page not found error
  src/constants/request.ts
  src/hooks/use-load-more.tsx
  src/pages/subjects/Subjects.tsx
  src/services/subject-service.ts
  tests/unit/hooks/use-load-more.spec.jsx
  tests/unit/services/subject-service.spec.jsx
Labels: bug, Frontend part

#3147 Implemented finish quiz functionality
  src/constants/request.ts
  src/constants/translations/en/quiz.json
  src/constants/translations/uk/quiz.json
  src/containers/quiz/finish-quiz-modal/FinishQuizModal.styles.ts
  src/containers/quiz/finish-quiz-modal/FinishQuizModal.tsx
  src/containers/quiz/quiz-header/QuizHeader.tsx
  src/containers/quiz/quiz-info/QuizInfo.styles.ts
  src/containers/quiz/quiz-info/QuizInfo.tsx
  src/pages/quiz/Quiz.tsx
  src/services/resource-service.ts
  src/types/finished-quizzes/finishedQuizzes.index.ts
  src/types/finished-quizzes/types/finishedQuizzes.types.ts
  src/types/index.ts
  src/utils/helper-functions.tsx
  tests/unit/pages/quiz/Quiz.spec.jsx
Labels: Frontend part, feature, Student

#3120 Fixed types mismatch
  src/containers/my-quizzes/create-or-edit-quiz-container/CreateOrEditQuizContainer.tsx
  tests/unit/containers/my-quizzes/CreateOrEditQuizContainer.spec.jsx
Labels: bug, Frontend part, TypeScript
