Repository ita-social-projects/SpaceToStudy-Client, pull requests merged in 2025-03, with the labels that each got.

#3242 Replace useAxios with useQuery & useMutatioin in GuestHomePage modals
  src/constants/request.ts
  src/containers/email-confirm-modal/EmailConfirmModal.styles.ts
  src/containers/email-confirm-modal/EmailConfirmModal.tsx
  src/containers/guest-home-page/forgot-password/ForgotPassword.styles.ts
  src/containers/guest-home-page/forgot-password/ForgotPassword.tsx
  src/containers/guest-home-page/reset-password/ResetPassword.tsx
  src/hooks/use-query.tsx
  src/services/auth-service.ts
  src/types/user/user-interfaces/user.interfaces.ts
  tests/unit/containers/email-confirm-modal/EmailConfirmModal.spec.jsx
  tests/unit/containers/guest-home-page/forgot-password/ForgotPassword.spec.jsx
  tests/unit/containers/guest-home-page/reset-password/ResetPassword.spec.jsx
Labels: Frontend part, feature, TypeScript, useQuery

#3189 Replaced useAxios with useQuery on CreateOrEditNote container
  src/containers/my-cooperations/cooperation-notes/create-or-edit-note/CreateOrEditNote.tsx
  tests/unit/containers/my-cooperations/cooperation-notes/CooperationNotes.spec.jsx
  tests/unit/containers/my-cooperations/cooperation-notes/create-or-edit-note/CreateOrEditNote.spec.jsx
Labels: Frontend part, useQuery

#3260 Replaced useAxios with useQuery in AccountIcon component
  src/containers/navigation-icons/AccountIcon.tsx
  tests/unit/containers/navigation-icons/AccountIcon.spec.jsx
Labels: Frontend part, feature, useQuery

#2937 The user can not save the information on 'Edit Profile' page after clicking on the 'Home page'
  src/constants/translations/en/edit-profile.json
  src/pages/edit-profile/EditProfile.tsx
  tests/unit/pages/edit-profile/EditProfile.spec.jsx
Labels: bug, Frontend part, my-profile

#3194 Replaced useAxios with useQuery in AsyncAutocomplete
  src/components/async-autocomplete/AsyncAutocomplete.tsx
  src/components/divider-dropdown-autocomplete/DividerDropdownAutocomplete.tsx
  src/constants/request.ts
  src/containers/category-dropdown/CategoryDropdown.tsx
  src/containers/edit-profile/professional-info-tab/add-professional-category-modal/AddProfessionalCategoryModal.tsx
  src/containers/find-course/courses-filters/CoursesFilters.tsx
  src/containers/find-offer/create-new-subject/CreateNewSubject.tsx
  src/containers/find-offer/offer-search-toolbar/OfferSearchToolbar.tsx
  src/containers/my-courses/course-toolbar/CourseToolbar.tsx
  src/containers/my-courses/courses-filters-drawer/CoursesFiltersDrawer.tsx
  src/containers/my-resources/add-attachment-category-modal/AddAttachmentCategoryModal.tsx
  src/containers/my-resources/add-resource-modal/AddResourceModal.tsx
  src/containers/my-resources/add-resource-with-input/AddResourceWithInput.tsx
  src/containers/my-resources/categories-container/CategoriesContainer.tsx
  src/containers/my-resources/create-or-edit-question-modal/CreateOrEditQuestionModal.tsx
  src/containers/my-resources/edit-attachment-modal/EditAttachmentModal.tsx
  src/containers/my-resources/resources-toolbar-drawer/ResourcesToolbarDrawer.tsx
  src/containers/offer-page/specialization-block/SpecializationBlock.tsx
  src/containers/tutor-home-page/subjects-step/SubjectsStep.tsx
  src/hooks/use-categories-names.tsx
  src/hooks/use-subjects-names.tsx
  src/pages/categories/Categories.tsx
  src/pages/subjects/Subjects.tsx
  src/services/category-service.ts
  src/services/resource-service.ts
  src/services/subject-service.ts
  src/utils/fetch-and-translate-category.tsx
  src/utils/translate-data.tsx
  tests/test-utils.jsx
  tests/unit/containers/edit-profile/professional-info-tab/add-professional-category-modal/AddProfessionalCategoryModal.spec.jsx
  tests/unit/containers/find-offer/create-new-subject/CreateNewSubject.spec.jsx
  tests/unit/containers/find-offer/offer-search-toolbar/offerSearchToolbar.spec.jsx
  tests/unit/containers/my-courses/course-toolbar/CourseToolbar.spec.jsx
  tests/unit/containers/my-courses/courses-filters-drawer/CoursesFiltersDrawer.spec.jsx
  tests/unit/containers/my-resources/ResourceToolbarDrawer.spec.jsx
  tests/unit/containers/offer-page/create-offer/CreateOffer.spec.jsx
  tests/unit/containers/offer-page/create-or-edit-offer/CreateOrEditOffer.spec.jsx
  tests/unit/containers/offer-page/edit-offer/EditOffer.spec.jsx
  tests/unit/containers/tutor-home-page/subjects-step/SubjectsStep.spec.jsx
  tests/unit/hooks/use-categories-names.spec.jsx
  tests/unit/hooks/use-subjects-names.spec.jsx
  tests/unit/pages/subjects/Subjects.spec.jsx
  tests/unit/services/resource-service.spec.jsx
Labels: Frontend part, useQuery

#3134 Replaced use axios with use query on GeneralIntoStep container
  src/components/user-steps-wrapper/UserStepsWrapper.tsx
  src/containers/tutor-home-page/general-info-step/GeneralInfoStep.tsx
  tests/unit/components/user-steps-wrapper/UserStepsWrapper.spec.jsx
  tests/unit/containers/tutor-home-page/general-info-step/GeneralInfoStep.spec.jsx
  tests/unit/pages/student-home/StudentHome.spec.jsx
  tests/unit/pages/tutor-home/TutorHome.spec.jsx
Labels: Frontend part, useQuery

#3276 Replaced useAxios with useQuery and useMutation in CreateCourseContainer
  src/constants/request.ts
  src/containers/course-section/CourseSectionContainer.tsx
  src/pages/create-course/CreateCourse.tsx
  src/services/course-service.ts
  tests/unit/pages/create-course/CreateCourse.spec.constants.js
  tests/unit/pages/create-course/CreateCourse.spec.jsx
Labels: Frontend part, useQuery

#3283 Replaced useAxios with useMutation in AcceptCooperationModal
  src/constants/request.ts
  src/containers/my-cooperations/accept-cooperation-modal/AcceptCooperationModal.tsx
  src/services/offer-service.ts
  tests/unit/containers/my-cooperations/accept-cooperation-modal/AcceptCooperationModal.spec.jsx
Labels: Frontend part, feature, useQuery
