Repository ita-social-projects/SpaceToStudy-Client, pull requests merged in 2025-04, with the labels that each got.

#3271 Replaced useAxios with useMutation in useSteps hook
  src/hooks/use-steps.tsx
  src/redux/features/editProfileSlice.ts
  src/services/user-service.tsx
  tests/unit/redux/editProfileSlice.spec.js
Labels: Frontend part, feature

#3286 Replaced useAxios with useMutation in the CreateOrEditOffer container
  src/containers/offer-page/create-or-edit-offer/CreateOrEditOffer.tsx
  src/containers/offer-page/edit-offer/EditOffer.tsx
  src/hooks/use-snackbar-alert.tsx
  src/services/offer-service.ts
  tests/unit/services/offer-service.spec.jsx
Labels: Frontend part, feature, useQuery

#3299 Remove unused 'data' prop from NotFoundResults
  src/pages/find-offers/FindOffers.tsx
Labels: bug, good first issue, Frontend part

#3301 Add string type to 'radio.title' in RadioButtonInputs component
  src/components/radio-button-inputs/RadioButtonInputs.tsx
  src/types/components/radioButtonInputs/RadioButtonInputs.types.ts
Labels: bug, good first issue, Frontend part, fixed

#3302 Fix props error for first login confirmation steps
  src/containers/tutor-home-page/add-photo-step/AddPhotoStep.tsx
  src/containers/tutor-home-page/general-info-step/GeneralInfoStep.tsx
  src/containers/tutor-home-page/language-step/LanguageStep.tsx
  src/containers/tutor-home-page/subjects-step/SubjectsStep.tsx
Labels: bug, good first issue, Frontend part

#3303 Fixed errors in EnrollOffer container
  src/containers/offer-details/enroll-offer/EnrollOffer.tsx
  src/types/offer-details/interfaces/offerDetails.interfaces.ts
Labels: bug, good first issue, Frontend part

#3311 Replaced useAxios with useQuery and useMutation in MyCourses page
  src/constants/request.ts
  src/containers/cooperation-details/add-course-modal-modal/AddCourseTemplateModal.tsx
  src/containers/find-course/courses-filters/CoursesFilters.tsx
  src/containers/my-courses/add-course-with-input/AddCourseWithInput.tsx
  src/containers/my-courses/course-toolbar/CourseToolbar.tsx
  src/pages/create-course/CreateCourse.tsx
  src/pages/my-courses/MyCourses.tsx
  src/services/course-service.ts
  tests/unit/containers/cooperation-details/add-course-modal-modal/AddCourseTemplateModal.spec.jsx
  tests/unit/containers/my-courses/add-course-with-input/AddCourseWithInput.spec.jsx
  tests/unit/pages/my-courses/MyCourses.spec.jsx
Labels: Frontend part, feature, useQuery

#3315 Added ukrainian translation for confirm profile changes modal window
  src/constants/translations/uk/edit-profile.json
Labels: bug, good first issue, Frontend part

#3320 Fixed login popup width for invalid email #2788
  src/containers/guest-home-page/login-form/LoginForm.styles.js
  src/containers/guest-home-page/login-form/LoginForm.tsx
Labels: bug, good first issue, Frontend part

#3319 Fix ProfileTabForm error
  src/containers/edit-profile/profile-tab/profile-tab-form/ProfileTabForm.tsx
Labels: Frontend part, fixed

#3300 Refactor filter change handler in CoursesFiltersDrawer
  src/components/filter-input/FilterInput.tsx
  src/containers/bookmarked-offers/BookmarksToolbar.tsx
  src/containers/chat/list-of-users-with-search/ListOfUsersWithSearch.tsx
  src/containers/my-courses/courses-filters-drawer/CoursesFiltersDrawer.tsx
  tests/unit/components/filter-input/FilterInput.spec.jsx
Labels: bug, good first issue, Frontend part, fixed

#3317 Fixed error in editProfileSlice
  src/constants/request.ts
  src/redux/features/editProfileSlice.ts
  src/services/user-service.tsx
  tests/unit/redux/editProfileSlice.spec.js
Labels: bug, Frontend part

#3329 Fixed errors in SearchAutocomplete component
  src/components/app-auto-complete/AppAutoComplete.tsx
  src/components/search-autocomplete/SearchAutocomplete.tsx
Labels: bug, good first issue, Frontend part

#3310 Fix error in CategoryDropdown
  src/containers/category-dropdown/CategoryDropdown.tsx
Labels: bug, good first issue, Frontend part

#3316 Fix bug with unreachable radio button
  src/containers/find-offer/offer-filter-block/offer-filter-list/OfferFilterList.tsx
  src/pages/find-offers/FindOffers.tsx
  tests/unit/containers/find-offer/offer-filter-block/offer-filter-list/OfferFilterList.spec.jsx
Labels: bug, good first issue, Frontend part

#3332 replace plain strings with authRoutes in ActiveStudentsBlock component
  src/components/active-students/ActiveStudentsBlock.tsx
  tests/unit/components/active-students/ActiveStudentsBlock.spec.jsx
Labels: Frontend part

#3313 Fixed type errors in AsyncAutocomplete component
  src/components/async-autocomplete/AsyncAutocomplete.tsx
Labels: bug, Frontend part

#3314 Fixed New Quiz bug
  src/containers/my-quizzes/create-or-edit-quiz-container/CreateOrEditQuizContainer.styles.ts
Labels: bug, Frontend part

#3333 Bugfix/3214/fix div inside p warning in cooperationdetails
  src/containers/my-cooperations/accept-cooperation-close/AcceptCooperationClosing.styles.ts
  src/containers/my-cooperations/accept-cooperation-close/AcceptCooperationClosing.tsx
  src/containers/my-cooperations/cooperation-closure-declined-banner/CooperationClosureDeclinedBanner.tsx
Labels: bug, Frontend part

#3339 Implemented tests for too long firstName and lastName in ProfileTab component
  tests/unit/containers/edit-profile/ProfileTab.spec.jsx
Labels: Frontend part, test case

#3322 Fix a bug when selecting a level in offer filtering
  src/containers/find-offer/offer-filter-block/offer-filter-list/OfferFilterList.tsx
  tests/unit/containers/find-offer/offer-filter-block/offer-filter-list/OfferFilterList.spec.jsx
Labels: bug, enhancement, good first issue, Frontend part

#3341 Now button disabled if user write incorrect password form
  src/containers/edit-profile/password-security-tab/change-password-modal/ChangePasswordModal.tsx
  tests/unit/containers/edit-profile/password-security-tab/ChangePasswordModal.spec.jsx
Labels: test case, Fix

#3195 Replaced useAxios with useQuery on the UserProfile page
  src/pages/user-profile/UserProfile.tsx
  tests/unit/pages/tutor-profile/TutorProfile.spec.jsx
Labels: enhancement, Frontend part, useQuery

#3335 fixed issue with props types in DividerDropdonwAutoComplete
  src/components/divider-dropdown-autocomplete/DividerDropdownAutocomplete.tsx
Labels: bug, good first issue, Frontend part, component

#3345 Fixed styles in AddCourseTemplate modal #3312
  src/containers/cooperation-details/add-course-modal-modal/AddCourseTemplateModal.styles.ts
  src/containers/find-course/courses-filters/CourseFilters.styles.tsx
Labels: bug, Frontend part

#3353 [Edit profile. Profile]Verify that the tutor/student couldn't save the last name only with space characters
  tests/unit/containers/edit-profile/ProfileTab.spec.jsx
Labels: Tutor, Student, priority: medium, Functional, test case, my-profile, Edit

#3389 Fixed linter issue in ProfileTab unit tests
  tests/unit/containers/edit-profile/ProfileTab.spec.jsx
Labels: Frontend part, hotfix

#3390 (SP: ) Fix page not found error when trying to edit lesson #3365
  src/router/constants/authRoutes.ts
Labels: bug, Frontend part

#3363 Replaced useAxios with useQuery and useMutation in UserTable component
  src/components/user-table/UserTable.tsx
  src/constants/request.ts
  src/constants/translations/en/user-table.json
  src/constants/translations/uk/user-table.json
  src/services/user-service.tsx
  src/types/user/user-interfaces/user.interfaces.ts
  tests/unit/components/user-table/UserTable.spec.jsx
  tests/unit/services/user-service.spec.jsx
Labels: Frontend part, feature, useQuery

#3370 Test that ensures that user can save last name up to 30 characters included
  tests/unit/pages/edit-profile/EditProfile.spec.jsx
Labels: Frontend part, test case

#3395 (SP: 0.5) Renamed user-service.tsx to .ts
  src/services/user-service.ts
Labels: Frontend part, Edit

#3361 (SP:) [Edit profile.Profile] Verify that the tutor/student can save a First Name containing alphabetic characters from Cyrillic and Latin scripts
  tests/unit/pages/edit-profile/EditProfile.spec.jsx
Labels: Tutor, Student, priority: medium, Functional, test case, my-profile, Edit

#3355 (SP:) [Edit profile. Profile]Verify that the tutor/student couldn't save the last name with non-alphabetic characters (Except special characters).
  tests/unit/containers/edit-profile/ProfileTab.spec.jsx
Labels: Tutor, Student, priority: medium, Functional, test case, my-profile, Edit

#3352 (SP:) [Edit profile. Professional info] Verify that the user can delete a subject in the "Your professional category" pop-up.
  tests/unit/containers/edit-profile/professional-info-tab/add-professional-category-modal/AddProfessionalCategoryModal.spec.jsx
Labels: Tutor, Student, Functional, test case

#3358 Added tests for First name input
  tests/unit/containers/edit-profile/ProfileTab.spec.jsx
Labels: Frontend part, test case

#3393 (SP:) Fix error when getting by resource ID #3392
  src/constants/request.ts
  src/services/course-cooperation-service.ts
Labels: bug, Frontend part

#3347 Added react-query to userProfileLoader
  src/router/constants/crumbs.ts
  src/router/constants/loaders.ts
  tests/unit/router/loaders.spec.jsx
Labels: Frontend part, feature, useQuery

#3381 (SP: ) Remove starting modal when there is no time limit on quiz #3366
  src/pages/quiz-attempts/QuizAttempts.tsx
Labels: bug, Frontend part

#3387 (SP: ) Remove edit action if the offer is closed #3371
  src/components/enhanced-table/EnhancedTable.tsx
  src/containers/my-offers/my-offers-card/MyOffersCard.styles.ts
  src/containers/my-offers/my-offers-container/MyOffersContainer.tsx
  src/types/components/enhanced-table/enhancedTable.interface.ts
  tests/unit/components/enhanced-table/EnhancedTable.spec.jsx
Labels: bug, Frontend part

#3338 (SP:) [Edit profile. Professional info] Verify that the user can't select the subject by typing invalid values in the "Category subject" field. #2825
  tests/unit/containers/edit-profile/professional-info-tab/add-professional-category-modal/AddProfessionalCategoryModal.spec.jsx
Labels: Frontend part, Tutor, Student, test case

#3405 (SP:) [Edit profile. Profile]Verify that Tutor/student can`t add the link with invalid Domen name
  tests/unit/containers/edit-profile/profile-tab/profile-tab-form/ProfileTabForm.spec.jsx
Labels: Frontend part, test case

#3383 (SP: ) Remove study materials access from student's offer #3372
  src/containers/offer-details/offer-general-info/OfferGeneralInfo.tsx
  src/containers/offer-page/teaching-block/TeachingBlock.tsx
Labels: bug, Frontend part

#3359 [Edit profile. Profile]Verify that Tutor/Student can`t add more than 200 characters into Professional headline field. #2736
  tests/unit/containers/edit-profile/profile-tab/profile-tab-form/ProfileTabForm.spec.jsx
Labels: Tutor, Student, Functional, priority: low, test case, my-profile, Edit

#3354 (SP: ) Replace useAxios with useQuery in ProfileInfo Container #3263
  src/containers/offer-page/chat-dialog-window/ChatDialogWindow.tsx
  src/containers/user-profile/profile-info/ProfileInfo.tsx
  src/pages/chat/Chat.tsx
  src/services/chat-service.ts
  tests/unit/containers/tutor-profile/ProfileInfo.spec.jsx
  tests/unit/pages/chat/Chat.spec.jsx
Labels: enhancement, feature, useQuery

#3412 (SP:) [Edit profile. Profile]Verify that tutor/student can search for native language in 'Your native language' field. #2729
  tests/unit/containers/edit-profile/profile-tab/profile-tab-form/ProfileTabForm.spec.jsx
Labels: Tutor, Student, Functional, test case, my-profile, Edit

#3409 Updated README.md file
  README.md
  spacetostudy-thumbnail.jpg
Labels: documentation, feature

#3399 Added user role label on offerDetails page
  src/components/offer-card/OfferCard.tsx
  src/components/user-profile-info/UserProfileInfo.styles.ts
  src/components/user-profile-info/UserProfileInfo.tsx
  src/constants/translations/en/offer-details-page.json
  src/constants/translations/uk/offer-details-page.json
  src/containers/find-offer/offer-card-square/OfferCardSquare.tsx
  src/pages/offer-details/OfferDetails.tsx
Labels: Frontend part, feature
