Repository ita-social-projects/SpaceToStudy-Client, pull requests merged in 2025-02, with the labels that each got.

#2998 Added redirect to chat
  src/containers/user-profile/profile-info/ProfileInfo.tsx
  tests/unit/containers/tutor-profile/ProfileInfo.spec.jsx
Labels: Frontend part, feature, Student

#3180 Add memoization to useForm hook
  src/containers/edit-profile/profile-tab/ProfileTab.tsx
  src/hooks/use-form.tsx
  src/pages/create-or-edit-lesson/CreateOrEditLesson.tsx
  src/pages/create-or-edit-question/CreateOrEditQuestion.tsx
Labels: Frontend part, feature

#3154 Created Quiz Preview for Student
  src/constants/request.ts
  src/constants/translations/en/quiz.json
  src/constants/translations/uk/quiz.json
  src/containers/quiz/quiz-header/QuizHeader.tsx
  src/containers/quiz/quiz-info/QuizInfo.styles.ts
  src/containers/quiz/quiz-info/QuizInfo.tsx
  src/pages/quiz/Quiz.constant.tsx
  src/pages/quiz/Quiz.styles.ts
  src/pages/quiz/Quiz.tsx
  src/services/resource-service.ts
  src/types/quizzes/interfaces/quizzes.interface.ts
  tests/unit/containers/quiz/QuizInfo.spec.jsx
  tests/unit/pages/quiz/Quiz.spec.jsx
Labels: Frontend part, feature, Student, UI/Usability

#3176 Replaced useAxios with useQuery and useMutation in the CreateOrEditQuizContainer and QuizSettingsContainer
  src/constants/request.ts
  src/containers/my-quizzes/create-or-edit-quiz-container/CreateOrEditQuizContainer.tsx
  src/containers/my-quizzes/quiz-settings-container/QuizSettingsContainer.tsx
  src/services/resource-service.ts
  tests/unit/containers/my-quizzes/CreateOrEditQuizContainer.spec.jsx
  tests/unit/services/resource-service.spec.jsx
Labels: Frontend part, feature, useQuery

#3101 Replaced useAxios with useQuery on AddCourseTemplateModal
  src/constants/request.ts
  src/containers/cooperation-details/add-course-modal-modal/AddCourseTemplateModal.tsx
  src/services/course-service.ts
  src/services/user-service.tsx
  src/types/course/interfaces/course.interface.ts
  tests/unit/containers/cooperation-details/add-course-modal-modal/AddCourseTemplateModal.spec.jsx
Labels: Frontend part, useQuery

#3162 Fix validation error in GeneralInfoSteps
  src/hooks/use-steps.tsx
Labels: Frontend part, Fix

#3193 Replace useAxios with useQuery on the QuizzesContainer
  src/containers/my-quizzes/QuizzesContainer.tsx
  src/containers/my-quizzes/create-or-edit-quiz-container/CreateOrEditQuizContainer.tsx
  src/containers/my-resources/add-resource-with-input/AddResourceWithInput.tsx
  src/pages/quiz/Quiz.tsx
  src/router/constants/authRoutes.ts
  src/services/resource-service.ts
  src/types/my-resources/types/myResources.types.ts
  tests/unit/containers/my-quizzes/CreateOrEditQuizContainer.spec.jsx
  tests/unit/containers/my-quizzes/QuizzesContainer.spec.jsx
  tests/unit/services/resource-service.spec.jsx
Labels: Frontend part, feature, useQuery

#3207 Replace useAxios with useQuery in the QuestionContainer
  src/containers/my-resources/questions-container/QuestionsContainer.constants.tsx
  src/containers/my-resources/questions-container/QuestionsContainer.tsx
  src/router/constants/authRoutes.ts
  src/services/resource-service.ts
  tests/unit/containers/my-resources/QuestionsContainer.spec.jsx
  tests/unit/services/resource-service.spec.jsx
Labels: Frontend part, feature, useQuery

#3167 Enhance Cooperation Closure: Modal Logic & needAction.messages Updates
  src/components/status-chip/StatusChip.styles.ts
  src/constants/translations/en/cooperation-details.json
  src/constants/translations/uk/cooperation-details.json
  src/containers/my-cooperations/accept-cooperation-close/AcceptCooperationClosing.styles.ts
  src/containers/my-cooperations/accept-cooperation-close/AcceptCooperationClosing.tsx
  src/containers/my-cooperations/cooperation-action-banner/CooperationActionBanner.tsx
  src/containers/my-cooperations/cooperation-action-input/CooperationActionInput.tsx
  src/containers/my-cooperations/cooperation-card/CooperationCard.tsx
  src/containers/my-cooperations/cooperation-closure-declined-banner/CooperationClosureDeclinedBanner.tsx
  src/containers/my-cooperations/cooperation-details/CooperationDetails.tsx
  src/containers/my-cooperations/cooperations-container/CooperationContainer.tsx
  src/containers/my-cooperations/my-cooperations-details/MyCooperationsDetails.tsx
  src/redux/features/cooperationsSlice.ts
  src/services/cooperation-service.ts
  src/types/cooperation/types/cooperation.types.ts
  tests/unit/containers/my-cooperations/accept-cooperation-close/AcceptCooperationClosing.spec.jsx
  tests/unit/containers/my-cooperations/cooperation-details/CooperationDetails.spec.jsx
  tests/unit/pages/my-cooperations/MyCooperations.spec.jsx
Labels: Frontend part, feature

#3148 Fixed the ability to save answer of question when type is Open Answer
  src/components/question-editor/QuestionEditor.constants.tsx
  src/components/question-editor/QuestionEditor.styles.ts
  src/components/question-editor/QuestionEditor.tsx
  src/containers/my-quizzes/create-or-edit-quiz-question/CreateOrEditQuizQuestion.tsx
  src/containers/quiz/question-answer/Answer.styles.ts
  src/containers/quiz/quiz-question/Question.tsx
  src/pages/create-or-edit-question/CreateOrEditQuestion.tsx
  src/types/questions/interfaces/questions.interface.ts
  src/utils/count-quiz-points.ts
  src/utils/is-correct-answer.ts
  tests/unit/components/question-editor/QuestionEditor.spec.jsx
  tests/unit/containers/my-quizzes/CreateOrEditQuizQuestion.spec.jsx
  tests/unit/containers/quiz/QuizQuestion.spec.jsx
Labels: bug, Frontend part, Functional

#3186 Replace useAxios with useQuery in the AttachmentsContainer
  src/constants/request.ts
  src/containers/add-documents/AddDocuments.tsx
  src/containers/course-section/CourseSectionContainer.tsx
  src/containers/my-resources/add-attachment-category-modal/AddAttachmentCategoryModal.tsx
  src/containers/my-resources/add-resource-modal/AddResourceModal.tsx
  src/containers/my-resources/attachments-container/AttachmentsContainer.tsx
  src/pages/create-or-edit-lesson/CreateOrEditLesson.tsx
  src/services/resource-service.ts
  src/types/my-resources/interfaces/myResources.interface.ts
  tests/unit/containers/AttachmentsContainer/AttachmentsContainer.spec.jsx
  tests/unit/containers/my-resources/AddAttachmentCategoryModal.spec.jsx
  tests/unit/services/resource-service.spec.jsx
Labels: useQuery

#3188 Replaced useQuery hook on categories container
  src/containers/my-resources/categories-container/CategoriesContainer.tsx
  src/services/resource-service.ts
  src/types/my-resources/interfaces/myResources.interface.ts
  tests/unit/containers/my-resources/CategoriesContainer.spec.jsx
Labels: enhancement, Frontend part

#3220 Created review attempt page and replaced fixed a bug in activeQuiz
  src/constants/request.ts
  src/constants/translations/en/breadcrumbs.json
  src/constants/translations/uk/breadcrumbs.json
  src/pages/quiz-attempts/QuizAttempts.styles.ts
  src/pages/quiz-attempts/QuizAttempts.tsx
  src/pages/quiz-review/QuizReview.styles.ts
  src/pages/quiz-review/QuizReview.tsx
  src/pages/quiz/Quiz.tsx
  src/pages/quiz/QuizVariants.tsx
  src/router/constants/authRoutes.ts
  src/router/constants/crumbs.ts
  src/router/routes/authRouter.tsx
  tests/unit/pages/quiz-attempt/QuizAttempts.spec.jsx
  tests/unit/pages/quiz/Quiz.spec.jsx
Labels: enhancement, Frontend part, feature

#3232 Fixed spacing in `CreateOrEditOffer` Container
  src/containers/offer-page/OfferPage.styles.ts
  src/containers/offer-page/specialization-block/SpecializationBlock.tsx
  src/containers/offer-page/teaching-block/TeachingBlock.tsx
Labels: Frontend part, design system

#3230 Replaced useAxios with useMutation in useToggleBookmark hook
  src/constants/request.ts
  src/services/user-service.tsx
  src/utils/toggle-bookmark.ts
  tests/unit/containers/offer-details/offer-carousel/OfferCarousel.spec.jsx
Labels: Frontend part, feature, useQuery

#3218 Update Cooperation Closing Banners Design
  src/containers/my-cooperations/accept-cooperation-close/AcceptCooperationClosing.styles.ts
  src/containers/my-cooperations/accept-cooperation-close/AcceptCooperationClosing.tsx
  src/containers/my-cooperations/cooperation-action-banner/CooperationActionBanner.styles.ts
  src/containers/my-cooperations/cooperation-action-banner/CooperationActionBanner.tsx
  src/containers/my-cooperations/cooperation-action-input/CooperationActionInput.styles.ts
  src/containers/my-cooperations/cooperation-action-input/CooperationActionInput.tsx
  src/containers/my-cooperations/cooperation-closure-declined-banner/CooperationClosureDeclinedBanner.styles.ts
  src/containers/my-cooperations/cooperation-closure-declined-banner/CooperationClosureDeclinedBanner.tsx
  src/styles/app-theme/app.pallete.ts
Labels: Frontend part

#3192 Replaced useAxios with useQuery in LessonsContainer
  src/containers/my-resources/lessons-container/LessonsContainer.tsx
  src/pages/create-or-edit-lesson/CreateOrEditLesson.tsx
  tests/unit/containers/my-resources/LessonsContainer.spec.jsx
Labels: Frontend part, feature, useQuery

#3229 Refactor CreateOrEditQuestion and CreateOrEditQuizQuestion: Replace useAxios with useQuery & useMutation
  src/components/question-editor/QuestionEditor.tsx
  src/constants/request.ts
  src/containers/my-quizzes/create-or-edit-quiz-container/CreateOrEditQuizContainer.tsx
  src/containers/my-quizzes/create-or-edit-quiz-question/CreateOrEditQuizQuestion.tsx
  src/containers/my-resources/questions-container/QuestionsContainer.tsx
  src/pages/create-or-edit-question/CreateOrEditQuestion.tsx
  src/services/resource-service.ts
  src/types/my-resources/interfaces/myResources.interface.ts
  tests/unit/containers/my-quizzes/CreateOrEditQuizContainer.spec.jsx
  tests/unit/containers/my-quizzes/CreateOrEditQuizQuestion.spec.jsx
  tests/unit/pages/create-or-edit-question/CreateOrEditQuestion.spec.jsx
  tests/unit/services/resource-service.spec.jsx
Labels: Frontend part, feature, useQuery

#3235 Replaced `useAxios` with `useMutation` in the `useChangeUserStatus` hook
  src/hooks/use-change-user-status.tsx
  src/services/user-service.tsx
  tests/unit/hooks/use-change-user-status.spec.jsx
Labels: enhancement, Frontend part, feature

#3233 Fixed button's loader in `CreateOrEditOffer` container
  src/containers/offer-page/create-or-edit-offer/CreateOrEditOffer.tsx
Labels: bug, Frontend part

#3160 Fixed profile editing
  src/pages/edit-profile/EditProfile.tsx
  src/types/user/user-interfaces/user.interfaces.ts
  src/utils/get-changed-fields.ts
  src/utils/replace-empty-strings-with-null.ts
Labels: Frontend part, my-profile, Fix
